### ISSUE TITLE
Certificate name checking does not honor the Host header

### ISSUE THREAD

**Issue by rshipp** [kennethreitz/requests#1671]
When verifying SSL certificates, requests only uses information from the URL string passed to `get()`, and ignores the HTTP Host header (passed in with the optional `headers` argument). This causes a failure in my case because the URL I am using is actually a local IP address. (If I use the domain name, it resolves to the server's public IP, but I need to work with the local one.)

In other words, I expect

    requests.get('https://192.168.X.X/' headers={'Host': 'example.com'})

to work as long as the certificate for 192.168.X.X matches example.com (or *.example.com). Instead, it throws an exception. Is this a bug that could be fixed, or is there some other way to accomplish this task that I am missing?

**Comment by Lukasa** [comment]
@sigmavirus24 Should we be filing this under our long list of "Do we trust the Host: header" bugs?

**Comment by sigmavirus24** [comment]
@Lukasa I think so. My concern is that we keep special-casing areas of the library around this and I really really hate that.

**Comment by Lukasa** [comment]
Agreed. We need a better way of getting host information. Perhaps a property on the `Request` object?

**Comment by sigmavirus24** [comment]
I can't envision anything off the top of my head. What do you have in mind?

**Comment by Lukasa** [comment]
Something like

``` python
class PreparedRequest(object):
    @property
    def host(self):
        if 'host' in self.headers.keys():
            return self.headers['host']
        else:
            return urlparse(self.url).host
```

I think there are a few other places where we consult the URL for this information, so this might work a bit better. Maybe worth renaming, because sometimes we _do_ want the URL host.

Quick, tell me why it won't work. =)

**Comment by sigmavirus24** [comment]
This works fine for me. For the times we do want the URL host, we should have a property that is the parsed url, e.g., 

``` python
@property
def parsed_url(self):
    return urlparse(self.url)
```

**Comment by Lukasa** [comment]
Also a good idea. This would be a useful pair of fixes.

Can you thin of a better name for that `host` property though? The best I have is `asserted_host`, which frankly sucks pretty hard.

**Comment by sigmavirus24** [comment]
@Lukasa do we still want to do this?

I can't think of a better name for the attribute frankly, but a better implementation might be:

``` python
class PreparedRequest(object):
    @property
    def parsed_url(self):
        return urlparse(self.url)

    @property
    def host(self):
        return self.headers.get('host', self.prepared_url.host)
```

That should be slightly faster than checking if the header is in the dictionary and then retrieving it. 

I don't like `asserted_host` at all.

I continue to be :-1: on changes like this though. Further, do we even do any of the certificate name checking or is that entirely in urllib3?

**Comment by Lukasa** [comment]
Mm, urllib3 seems to do it. Maybe that's the place to look.

**Comment by t-8ch** [comment]
It should be possible to create a TransportAdapter for `https://192.168.X.X/` which passes the `assert_hostname` parameter to urllib3, which tell urllib3 to use another hostname.
