### ISSUE TITLE
Why don't we send `strict` to urllib3?

### ISSUE THREAD

**Issue by Lukasa** [kennethreitz/requests#1869]
I was trawling the Python core bugtracker when I spotted [this](http://bugs.python.org/issue17849) beauty. It looks like it should be impossible to hit this if `strict` is set to `True`, but we don't pass that parameter to `urllib3`. Is there a good design reason we don't do this? If there isn't, are we open to a PR that does set that argument?

**Comment by sigmavirus24** [comment]
If it doesn't cause issues, I don't see why not.

**Comment by jschneier** [comment]
`strict` was deprecated in Python3. With that the `LineAndFileWrapper` was removed because HTTP/1.x is assumed. The fact that the `LineAndFileWrapper` is created means that the proxy must be returning some malformed status line or is using HTTP/0.9. Or at least that sounds correct to me.

I might be a bit thick but what are people using to easily setup a proxy? I'd like to take a look at the raw response.

**Comment by Lukasa** [comment]
@jschneier I'm not so worried about that particular issue: we've never hit it in Requests. I'm just wondering whether there's a good technical reason we shouldn't just limit ourselves to well-formed HTTP/1.1.

**Comment by jschneier** [comment]
I think printing an annoying deprecation warning on python3 is the only drawback if you only want to deal with HTTP/1.x

**Comment by Lukasa** [comment]
Deprecation warnings don't print by default on 3.x I don't think. So it's not even that bad.

**Comment by sigmavirus24** [comment]
Let's do it unless @kennethreitz has an object to restricting the library to HTTP/1.1

**Comment by kennethreitz** [comment]
I don't see how this is useful.

**Comment by kennethreitz** [comment]
I don't see how this is unuseful.

**Comment by sigmavirus24** [comment]
You baffle me

**Comment by kennethreitz** [comment]
I suppose I'm now +0 (while before I was -0) :)

**Comment by Lukasa** [comment]
Doing this would solve #2322.

**Comment by Lukasa** [comment]
Alrighty, patch in #2323.
