### ISSUE TITLE
Optionally depend on certifi

### ISSUE THREAD

**Issue by dstufft** [kennethreitz/requests#1947]
Right now requests (afaik) doesn't issue security releases for old versions or have any sort of support period for any versions of requests other than the latest. This is problematic because requests bundles the CA bundle as part of the code base. This means that people *must* upgrade requests in order to get access to the latest certificates. This becomes even more problematic when people are on older requests that cross a major version boundary.

I know requests used to depend on certifi and I assume it stopped doing so for some reason, likely ease of vendoring, so what I would like to suggest is for requests to know what version of certifi it's internal certificates corresponds to, and if there is a higher version certifi available requests will use that instead.

This will allow people to easily update the certificates of requests without having to upgrade requests, which might require coding to cross a compatibility breakage.

**Comment by Lukasa** [comment]
@kennethreitz I'm open to doing the work here if this is something you think you'd like.

**Comment by Lukasa** [comment]
Requests now automatically picks up certifi if present.
