### ISSUE TITLE
In `stream=True` mode, redirect-following crashes when body already consumed

### ISSUE THREAD

**Issue by zackw** [kennethreitz/requests#1952]
`Session.resolve_redirects` unconditionally accesses `Response.content`, to make sure that all of the content *has* been consumed, so the socket can be reused.  If you are manually following redirects, and you have set `stream=True`, and you use `Response.iter_content` to consume the entire body of a redirect before cycling to the next one, this access of `.content` will throw a `RuntimeError`.

This appears to be fixed by pull request #1944; I'm filing this bug anyway to record that it *is* a bug (and to make clear why "`except RuntimeError: pass`" is needed).

**Comment by Lukasa** [comment]
Thanks for this, I'm marking this issue as fixed. =)

**Comment by schlamar** [comment]
@zackw can you please give more detailed steps to reproduce (code example or test case).
