### ISSUE TITLE
MIME type no longer set on file upload

### ISSUE THREAD

**Issue by wtip** [kennethreitz/requests#1996]
I have the following code that was working fine with requests 1.2.0 but is not working with 2.2.1
```python
while True:
	try: # Try to upload the image
		f = open (img_name,'rb')
		r =  requests.post(url='http://myurl.com/post', data = {'Upload':'upload'}, files = {'userfile':f}, timeout=30)
		print r.status_code
		r.raise_for_status()
		break # If the upload completes without errors break out of the loop
	except requests.exceptions.RequestException:
		print "Something went wrong, waiting and then trying again"
		time.sleep(30)
```
The code runs without errors but the image is not uploaded. The upload page rejects the post due to unsupported file type. I did a tcpdump capture while running the code with both versions of requests. The main difference I saw was that requests 1.2.0 properly sets Content-Type: image/jpeg while with requests 2.2.1 I did not see Content-Type header.

Am I doing something wrong or is this a bug?

**Comment by Lukasa** [comment]
Are you expecting the `Content-Type` header on the request or on one of the parts of the multipart upload?

**Comment by wtip** [comment]
I am expecting Content-Type on the second part of the multipart upload. This is properly done with requests 1.2.0

**Comment by Lukasa** [comment]
Hmm, yup, from looking at the code it's clear that we no longer guess the MIME type of the uploaded file. I wonder if that was deliberate.

Looks like it went away in af4fb8cedca7c331b8c914a40c477a2cb02055e1 (part of #1640) when we switched to explicitly using `RequestField` objects. Assuming we're happy to guess MIME types I'm happy to put it back. @kennethreitz, should we be guessing MIME types on multipart upload parts?

**Comment by wtip** [comment]
If it was intentional it would be nice if this would be put in the migration guide.

In trying to figure this out I saw that the mime type guessing code moved over to https://github.com/kennethreitz/requests/blob/master/requests/packages/urllib3/fields.py with `def guess_content_type` but doesn't seem to be working?

**Comment by Lukasa** [comment]
It's not that it's not working, it's that it's not hit. We explicitly create `RequestField` objects, which don't do any content-type guessing.

**Comment by sigmavirus24** [comment]
Hey @kennethreitz I was rummaging through issues and we never did get an answer from you. Was it intentional that content type guessing was removed? There's an API for the user to specify it now explicitly so we just might want to document this.
