### ISSUE TITLE
Invocation of `SSLContext.load_verify_locations` causes intermittent hanging

### ISSUE THREAD

**Issue by scoarescoare** [kennethreitz/requests#2146]
I have a background worker that makes many http requests to various APIs. I've found that every time my job runs, a few requests appear to just "hang" for quite a long time.
I've investigated further and it appears the requests are not actually hanging, but my python code "hangs" when it invokes `OpenSSL's` `SSL_CTX_load_verify_locations` function.

I forked `requests` and added some more logging. The last entry to be logged in my code is `begin: ssl_wrap_socket: load verify locations` and that corresponds to [this line](https://github.com/WiFL-co/requests/blob/master/requests/packages/urllib3/util/ssl_.py#L118).

One possible conclusion is that SSL_CTX_load_verify_locations is hanging because of parallel file access or the version of OpenSSL on my Heroku dyno has a bug. FYI the `requests` library is calling python's `load_verify_locations` which is what then calls `OpenSSL`. I am not invoking these functions manually.

[I've created a question on StackOverflow](http://stackoverflow.com/questions/24628866/why-does-my-program-hang-after-urllib3-logs-starting-new-https-connection) that provides extensive information. I am using the following dependencies:

    python 3.4
    requests==2.3.0.  
    Rabbit 3.1.3 celery:3.1.11 (Cipater w/ Prefork) kombu:3.0.16
    billiard:3.3.0.17 py-amqp:1.4.5

@Lukasa has been really helpful thus far, and I've been able to narrow it down. I figured i'd throw this issue up and see if anyone else has some insight.

**Comment by Lukasa** [comment]
I'm really interested to see what people can come up with here. I cannot see any good reason for `SSL_CTX_load_verify_locations` to hang.

**Comment by Lukasa** [comment]
Closed for inactivity.
