### ISSUE TITLE
Revisit concerns in #2244

### ISSUE THREAD

**Issue by sigmavirus24** [kennethreitz/requests#2287]
See https://github.com/kennethreitz/requests/pull/2244 for more context:

Specific concerns are:

- Should redirects handled by the cache count against the max number of redirects? (e.g., if we set a max of 30 and find 2 redirects in the cache, the max number of redirects a user could encounter after that would be 28)
- Should history be some-how generated by the redirect cache? (i.e., should we be making responses and adding them to the final  response's history?)
- Should a separate error be raised for the case where there's a loop in the cache? (When documented this would help the user realize they're stuck in a cached loop and that they may want to clear it to retry using the live site. Note: this also affects the API of `Session#resolve_redirects`.)

**Comment by sigmavirus24** [comment]
@Lukasa is it still worth keeping this open?

**Comment by Lukasa** [comment]
I still hate the redirect cache, but I think we should talk about it at PyCon. In particular, we should talk about whether we should yank it out and instruct people to use CacheControl instead.
