### ISSUE TITLE
Add custom line delimiter to iter_lines()

### ISSUE THREAD

**Issue by 2deviant** [kennethreitz/requests#2292]
I saw a couple of requests that touched on this issue but, none that have hit it on the nose.  Has adding  a custom line delimiter functionality to `iter_lines()` been considered before? If so, what are the reasons for not including it?  If the feature has not yet been considered, I would not mind submitting a pull request for comment.

This feature would be useful in cases when, for example, newlines are a part of data and the stream is delimited with, say `<>`.

**Comment by Lukasa** [comment]
I don't believe it has. It's a pretty niche feature, but I'd be open to considering a PR with it.

**Comment by sigmavirus24** [comment]
Fixed #2295
