### ISSUE TITLE
Vendored version of chardet is buggy, can't detect utf-8 with bom

### ISSUE THREAD

**Issue by tgs** [kennethreitz/requests#2296]
[Here's the commit](https://github.com/chardet/chardet/commit/0f9030139ceeaa4c3bf590de299fe84a5895c218) that fixed it in upstream.

Because of the bug, if I fetch a UTF-8 file that starts with a BOM, I get (e.g.):

```
ï»¿<?xml version="1.0" encoding="utf-8"?>
...
```

and `response.encoding` is `ISO-8859-1` or `-2`.

I think you should be able to just pull the newest version, and it will be fixed.

**Comment by sigmavirus24** [comment]
@tgs thanks. We haven't had the reason to do a new release yet. When we do, we'll pull this in.

Until we do, if you know the encoding you can simply do `response.encoding = 'utf8'`

**Comment by tgs** [comment]
Sounds good, thank you!

For anyone else finding this, one workaround is to set response.encoding yourself:

``` python
response = requests.get(...)
response.encoding = 'utf-8-sig' # trims off the BOM, or you could say 'utf-8' to leave it
response.text
```
