### ISSUE TITLE
SSL verification fails with proxy

### ISSUE THREAD

**Issue by looperhacks** [kennethreitz/requests#2386]
Using this code:

    import requests
    requests.get('https://github.com')

Throws the following exception:

    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/lib/python2.7/site-packages/requests/api.py", line 55, in get
        return request('get', url, **kwargs)
      File "/usr/lib/python2.7/site-packages/requests/api.py", line 44, in request
        return session.request(method=method, url=url, **kwargs)
      File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 456, in request
        resp = self.send(prep, **send_kwargs)
      File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 559, in send
        r = adapter.send(request, **kwargs)
      File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 382, in send
        raise SSLError(e, request=request)
    requests.exceptions.SSLError: hostname '<Proxy>' doesn't match either of 'github.com', 'www.github.com'

where <Proxy> is the URL of the http(s)-proxy I'm using. I have set the environment-variables HTTP_PROXY and HTTPS_PROXY (lowercase, too) to that URL. Is it possible to avoid that error without appending verify=False so I don't have to mess with other projects?

**Comment by Lukasa** [comment]
Does the URL to your proxy begin with `https://`? That will cause us to try a TLS handshake with that proxy, which obviously fails as that proxy isn't authoritative for that domain. If this is the case, try setting the protocol to `http://`.

**Comment by peterjeschke** [comment]
It does start with https://, but setting it to http:// doesn't help.

**Comment by sigmavirus24** [comment]
@looperhacks can you tell us what kind of proxy this is? Also, I doubt it will help, but have you attempted to use the `proxies` argument to `get`?

**Comment by peterjeschke** [comment]
I don't know the software used, but using a squid-proxy causes the same problem. `proxies` doesn't help either.

**Comment by Lukasa** [comment]
When you say switching to `http://` doesn't help, do you mean you're getting the exact same error?

**Comment by peterjeschke** [comment]
Yes.

**Comment by remram44** [comment]
`curl` doesn't seem to accept `http_proxy=https://...`. I can't make Chrome use an HTTPS proxy either. Is this something people use?

**Comment by Lukasa** [comment]
It is extremely uncommon, but it does exist and we do technically support it.

**Comment by schlamar** [comment]
Duplicate: https://github.com/shazow/urllib3/issues/531

BTW, there is no support for HTTPS proxies in requests/urllib3, see https://github.com/kennethreitz/requests/issues/1622

**Comment by Lukasa** [comment]
Ah, thanks for the reminder @schlamar, I had forgotten that we regressed/removed this.

**Comment by schlamar** [comment]
Not quite, the current behavior is that HTTPS via HTTPS proxy silently degrades to HTTPS via HTTP proxy... ;)
