### ISSUE TITLE
how  can I get the "exception code"

### ISSUE THREAD

**Issue by tdyhacker** [kennethreitz/requests#2397]
I am using "requests (2.5.1)" .now  I want to catch the exception and return an dict with some exception message,the dict I will return is as following:
```
{
   "status_code":   61, # exception code,
   "msg": "error msg",
}
```
but now I can't get the error status_code and error message,I try to use 
```
except requests.exceptions.ConnectionError as e:
response={
            u'status_code':4040,
            u'errno': e.errno,
            u'message': (e.message.reason),
            u'strerror': e.strerror,
            u'response':e.response,
        }
```
but it's too redundancy,how can I get the error message simplicity?anyone can give some idea?

**Comment by sigmavirus24** [comment]
Questions belong on [StackOverflow](https://stackoverflow.com/questions/tagged/python-requests).
