### ISSUE TITLE
Clarify InsecureRequestWarning and verify=True in docs

### ISSUE THREAD

**Issue by rsyring** [kennethreitz/requests#2398]
The docs:

http://docs.python-requests.org/en/latest/user/advanced/#ssl-cert-verification

say:

> By default, verify is set to True. Option verify only applies to host certs.

If my HTTPS connection is being verified by default, why am I also seeing a InsecureRequestWarning?  Clarifying this situation and updating the docs with more info would be helpful IMO.

**Comment by sigmavirus24** [comment]
> If my HTTPS connection is being verified by default, why am I also seeing a InsecureRequestWarning? Clarifying this situation and updating the docs with more info would be helpful IMO.

I don't know why. Can you give us any details to help you?

**Comment by rsyring** [comment]
> I don't know why. Can you give us any details to help you?

Thank you for the prompt response.  Actually, this was my fault.  I didn't realize I was using a session that had verify=False.  The warning did exactly what it was supposed to, I just thought it was someone elses's fault!  :o/

Thanks again.

**Comment by sigmavirus24** [comment]
Hah. No worries.
