### ISSUE TITLE
x509 Certificate 

### ISSUE THREAD

**Issue by kvarga** [kennethreitz/requests#2405]
Is there any support for x509 certificate authentication with requests? I can't seem to find any examples and would much prefer to use requests.

**Comment by Lukasa** [comment]
By which you mean TLS authentication? Yes, it's enabled by default.

**Comment by Lukasa** [comment]
I apologise, I may have misread. Do you mean TLS _client_ certificates?

**Comment by kvarga** [comment]
Yeah, sorry. I'm piecing together some horrible documentation from our vendor. The example app they gave is corrupted so awaiting that back. The language from documentation that I do have is

> In addition to using the certificate to establish the SSL connection, your system will need to use a client key and secret to authenticate to the APIs.

**Comment by Lukasa** [comment]
Ok, so we can use client certificates. You use the `cert` keyword as documented [here](http://docs.python-requests.org/en/latest/api/#requests.request).

**Comment by kvarga** [comment]
Awesome. Thanks!
