### ISSUE TITLE
Wrong digest header creation when server has qop="auth,auth-int"

### ISSUE THREAD

**Issue by berndschultze** [kennethreitz/requests#2408]
I always get "401 unauthorized" when trying to log in to a server which writes qop="auth,auth-int" in its answer. The problem doesn't exist with Curl.
I debugged the requests code and probably found the problem in auth.py. The function build_digest_header in class HTTPDigestAuth calculates
    noncebit = "%s:%s:%s:%s:%s" % (nonce, ncvalue, cnonce, qop, HA2)
and gives back
    base += ', qop="auth", nc=%s, cnonce="%s"' % (ncvalue, cnonce)
to the server.

So in our client digest calculation we use qop="auth,auth-int", which we take from the server response, and make the server use qop="auth" in its calculation by giving back this header.

While debugging I can log in correctly if I change noncebit on the fly to
    noncebit = "%s:%s:%s:%s:%s" % (nonce, ncvalue, cnonce, "auth", HA2)
This would be my suggestion for the solution. Theqop for the calculation should be the same as we give back in our header.

**Comment by Lukasa** [comment]
We do not use `qop=auth-int`, we don't support it. When given multiple `qop` values like that in an auth challenge we're allowed to select one, and we have: `auth`.

You're right, however, about the fix. If we've chosen `auth` that's what we should use in our calculation. The simplest fix should be to pull the calculation of `noncebit` down into the only place it's used.

That said, can RFCreader @sigmavirus24 confirm that this is correct WRT the specs?

**Comment by sigmavirus24** [comment]
> That said, can RFCreader @sigmavirus24 confirm that this is correct WRT the specs?

Is this the new requests/urllib3 thing? If so, I thoroughly approve.

**Comment by berndschultze** [comment]
Thank you for your quick responses.
Would pulling down noncebit also fit for qop="auth,auth-int"? Wouldn't we still calculate with the wrong qop in case we match the condition "'auth' in qop.split(',')" as we would do with qop="auth,auth-int"?
I think we should not calculate with the qop we read from the response and instead with the one we write into the header (the constant "auth").

**Comment by Lukasa** [comment]
@berndschultze Sorry, I was insufficiently clear. I agree. What I meant was pulling that line into the `auth` block _and_ changing it to always specifically use `auth`.

**Comment by berndschultze** [comment]
@Lukasa You are right, I misunderstood. Thanks again.

**Comment by sigmavirus24** [comment]
I went back through [RFC 2617](https://tools.ietf.org/html/rfc2617#page-8) (which is still the definition of Digest Access Authentication, although parts were _updated_ (not obsoleted) by 7235). tl;dr the ABNF says unambiguously:

```
      qop-value         = "auth" | "auth-int" | token
```

Where `token` is one or more letters (`a-zA-Z`), digits (`0-9`), and US-ASCII visible characters (excluding `(),/:;<=>?@[\]{}` and `"`). In otherwords, _technically_ the server is doing the wrong thing but we can handle it because a `,` should never be part of the `qop-value` so it should be safe to approach this by following roughly this logic:

``` py
if 'auth' in set(qop_value.split(',')):
   qop = 'auth'
else:
   return None  # or whatever we return when we're not doing 'auth'
```

**Comment by sigmavirus24** [comment]
@berndschultze if you want to test out #2415 and let us know how that goes, that'd be awesome.
