### ISSUE TITLE
Data argument introduced too early in Quickstart guide

### ISSUE THREAD

**Issue by alfonsomhc** [kennethreitz/requests#2418]
I'm following the quick start guide in:
http://docs.python-requests.org/en/latest/user/quickstart/
I got confused when reading the section "Custom Headers" because the example code features the data argument, which hasn't been introduced in the guide yet (it is the next section "More complicated POST requests" that describes the data argument).
My suggestion is to swap the order of those two sections, i.e. have "More complicated POST requests" before "Custom Headers", or modify the example code in "Custom Headers" (remove data argument).

**Comment by Lukasa** [comment]
Agreed, this should be reworked. Marking as contributor friendly.

**Comment by yasoob** [comment]
Why not just leave out the data argument in the Custom Headers section? That section is clearly not meant to explain the usage of data argument. It is being discussed later on in the "More complicated POST requests" section. What do you guys say?

**Comment by Lukasa** [comment]
The only reason to worry about it is that the header we're sending is a `Content-Type` one, which does rather require a body.

**Comment by yasoob** [comment]
Let's just set it to a useragent string then?

**Comment by Lukasa** [comment]
Totally reasonable. =)

**Comment by yasoob** [comment]
Should I go ahead and submit a patch?

## Outline:
- Omit the data attribute.
- Replace the headers with a user-agent string

**Comment by Lukasa** [comment]
Make sure you change the verb, but sure. =)

**Comment by yasoob** [comment]
The full user-agent string is too long:
`Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.115 Safari/537.36`. Can I just write `Mozilla/5.0` or is it necessary to write the complete user-agent string?
