### ISSUE TITLE
Quoted newlines not handled properly

### ISSUE THREAD

**Issue by jrootham** [kennethreitz/requests#2421]
When trying to use iter_lines() reader for csv to read an parse a csv file it failed.  It turns out that if there is a quoted newline in the file it removes the comma quote delimiter for the quoted newline and the following line.

This makes it impossible to use iter_lines for csv.

**Comment by sigmavirus24** [comment]
## Can you use a paste servIce to give a concrete example of this? I'm not sure I follow your description 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by jrootham** [comment]
Input file:
    "a","
    ","b"
    "c","
    ","d"

Output stings
    "a"
    "c"

**Comment by Lukasa** [comment]
I don't see how this is iter_lines' fault. It doesn't understand file formats, so it can't possibly know that it's in a CSV file and so that newlines can be quoted. It's not "iter_semantic_lines", and nor should it be. In this situation, you want to use iter_content.

**Comment by jrootham** [comment]
Sorry, it looks like my fault.  I was faked out by my data source providing 2 different files with identical identifying headers.
