### ISSUE TITLE
Bug: field "uri" in header["Proxy-Authorization"] should not be empty

### ISSUE THREAD

**Issue by luozhaoyu** [kennethreitz/requests#2426]
#### Issue
When I am handling [toolbelt's digest proxy issue] (https://github.com/sigmavirus24/requests-toolbelt/issues/53), I find the proxy server rejects my request header:

Connection: keep-alive\r\n
Proxy-Authorization: Digest username="luozhaoyu", realm="balabalba@host.com", nonce="o3jFVAAAAADwDnHL3X8AABqmXw4AAAAA", uri="", 
response="9a5d356b4a5bac5473864896bcfdcc69", qop="auth", nc=00000001, cnonce="a681e67b2a3bb034"\r\n
Accept-Encoding: gzip, deflate\r\n

The problem is because field uri should be "/" rather than "". ([request-uri's definition is in RFC 2616] (http://tools.ietf.org/html/rfc2616#section-5.1.2))

#### Bug reproduce
It is funny to find the bug. Set up a digest auth proxy, 
`r = requests.get(url, proxies=proxies, auth=auth, allow_redirects=True)`
url is http://bing.cn/ (this is a typo), there will be a HTTP 301 to http://www.rz.com/, client would try to access http://www.rz.com directly, but the proxy would reject and ask for user/password.
However, the automatic redirect's url parse result will be
`ParseResult(scheme='http', netloc='www.rz.com', path='', params='', query='', fragment='')` 
The path is empty, and will result in authentication failure.

#### Solution is one line:
add a line in `auth.py` line 110: `path = "/" if not path else path`
I will create a pull request later.

**Comment by sigmavirus24** [comment]
Closed by #2427.
