### ISSUE TITLE
Upgrade/install of 2.5.0 fails on Fedora via yum

### ISSUE THREAD

**Issue by constantine1** [kennethreitz/requests#2430]
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction (shutdown inhibited)
  Updating   : python-requests-2.5.0-3.fc21.noarch                                                                                                                                                             1/2 
Error unpacking rpm package python-requests-2.5.0-3.fc21.noarch
*error: unpacking of archive failed on file /usr/lib/python2.7/site-packages/requests/packages/urllib3: cpio: rename*
  Verifying  : python-requests-2.5.0-3.fc21.noarch                                                                                                                                                             1/2 
python-requests-2.3.0-3.fc21.noarch was supposed to be removed but is not!
  Verifying  : python-requests-2.3.0-3.fc21.noarch                                                                                                                                                             2/2 

Failed:
  python-requests.noarch 0:2.3.0-3.fc21                                                                    python-requests.noarch 0:2.5.0-3.fc21

**Comment by ghost** [comment]
v 2.3 can be installed/uninstalled
v2.5 cann't be installed/upgraded-to
Works fine from pip

**Comment by Lukasa** [comment]
We do not package or build the Red Hat packages. Please take this up with downstream.

**Comment by joaocosta** [comment]
This seems to be caused by a conflict when the package is already installed via pip.
See https://bugzilla.redhat.com/show_bug.cgi?id=1177479#c4

One solution is to "pip uninstall requests". Or upgrade via pip instead of installing via rpm.
