### ISSUE TITLE
Implement limits for requests

### ISSUE THREAD

**Issue by skorokithakis** [kennethreitz/requests#2432]
Would anyone be interested in a `limit` parameter that timed out after X seconds or Y bytes received, as a DoS countermeasure? I want to implement one, but I'm not sure if you would accept the PR here or whether I should make it a third party library. It feels like it would be more fitting in requests itself, though.

**Comment by sigmavirus24** [comment]
We've been in a perpetual feature freeze for some time now (see https://github.com/kennethreitz/requests/issues/1165) meaning that this would not be accepted as yet another keyword parameter. Additions like this are being added to the [requests-toolbelt](/sigmavirus24/requests-toolbelt).

**Comment by sigmavirus24** [comment]
I'm proposing we close this since there's been no response in over 2 months and there seems to be no one else interested in this. Further, there's an appropriate place for a feature like this (the toolbelt).

**Comment by skorokithakis** [comment]
Sorry, yes, do close it. I already made it into a library:

https://pypi.python.org/pypi/requests-guard
