### ISSUE TITLE
Scaffold an API console sample from a model

### ISSUE THREAD

**Issue by scls19fr** [kennethreitz/requests#2443]
Hello,

I wonder if RAML 
http://www.sitepoint.com/raml-restful-api-modeling-language/
http://raml.org/
couldn't be use to create (scaffold) an API console sample.

This idea is probably out of the scope of requests but we could talk about such idea here.

Same idea for server:
https://github.com/flask-restful/flask-restful/issues/394

Kind regards

PS: I'm writing this about RAML but maybe API Blueprint https://apiblueprint.org/ or Swagger http://swagger.io/ are also good candidates

**Comment by sigmavirus24** [comment]
> This idea is probably out of the scope of requests but we could talk about such idea here.

It is definitely out of the scope of requests. Since it is out of scope this is not the place to discuss it.
