### ISSUE TITLE
[rfe] requests should process chunked responses transparently

### ISSUE THREAD

**Issue by TomasTomecek** [kennethreitz/requests#2449]
When server responds with `Transfer-Encoding: chunked`, it would be nice if `requests` would process the chunked response. Right now if I do `response.iter_lines()` I get access to chunks part where length of the chunk is encoded with optional chunk extension. It would be awesome if `requests` would provide something like `iter_chunks` where I would get access to the chunk data only.

More info:
http://en.wikipedia.org/wiki/Chunked_transfer_encoding
http://mihai.ibanescu.net/chunked-encoding-and-python-requests

**Comment by Lukasa** [comment]
As mentioned in the blog post you link to, `httplib` does not provide us with access to those chunks. To get them we'd have to go around `httplib` and read directly from the socket itself. That's do-able, but it's a pretty aggressive layering violation. The first place to ask for that would be in our underlying layer, urllib3. I suggest opening an issue there. =)

**Comment by TomasTomecek** [comment]
Oh, should have read the blog most carefully.

Okay, will migrate this issue.

**Comment by Lukasa** [comment]
That's ok, it's an easy mistake to make. =)

**Comment by TomasTomecek** [comment]
@Lukasa Since it's in urllib3 now, how we can take advantage of it?

**Comment by Lukasa** [comment]
That's actually an interesting point.

By default, `iter_content` will automatically use `stream`, as you can see [here](https://github.com/kennethreitz/requests/blob/master/requests/models.py#L656-L657). This _should_ mean that `iter_content` will now transparently work with chunked transfer encoding (interestingly, so will `iter_lines`).

However, it might be a good idea to document how best to handle chunked transfer encoding (namely, calling `iter_content` with a chunk size of `None`).

**Comment by TomasTomecek** [comment]
I probably won't have time to write that docs. But am really looking forward to try the new stuff in docker-py once urllib3 is rebased in requests and released.

**Comment by Lukasa** [comment]
See #2506 for those docs.
