### ISSUE TITLE
multiple cookie headers should be joined with semicolons

### ISSUE THREAD

**Issue by requiredfield** [kennethreitz/requests#2452]
please see https://github.com/kennethreitz/requests/issues/1155#issuecomment-55176733

**Comment by sigmavirus24** [comment]
This should be fixed by https://github.com/shazow/urllib3/pull/534 after we cut a new release of requests.

**Comment by Lukasa** [comment]
I apologise, my original statement in #1155 is wrong. Multiple cookie headers shouldn't be joined at all: there is simply no safe way to do that.
