### ISSUE TITLE
Multiple requests suggested way

### ISSUE THREAD

**Issue by nsorros** [kennethreitz/requests#2464]
Hi,

I am trying to do multiple requests without having to wait for each one to finish. I was using grequests but i am wondering if there is a better way to handle it.

**Comment by Lukasa** [comment]
grequests is the best way to handle it at the moment if you like using gevent. Your other options are [trequests](https://github.com/1stvamp/trequests), [treq](https://github.com/dreid/treq), [async-requests](https://github.com/inglesp/async-requests), and there are likely some others floating around that I don't know about.
