### ISSUE TITLE
requests 2.5.4 mishandles WWW-Authenticate headers

### ISSUE THREAD

**Issue by dieterv** [kennethreitz/requests#2474]
Executing a get() with requests 2.5.4 I now stumble over an unexpected 401 error.
Looking into it I see that response.headers contains:
{'server': 'Microsoft-IIS/7.5', 'content-type': 'text/html', 'date': 'Thu, 05 Mar 2015 11:56:25 GMT', 'content-length': '1293', 'x-powered-by': 'ASP.NET', 'www-authenticate': 'Negotiate'}
and the HttpNtlmAuth handler installed onto my session object has not kicked in.
I have a feeling the "WWW-Authenticate: NTLM" header which is also in the response disappeared somewhere:
![headers](https://cloud.githubusercontent.com/assets/220082/6504440/b22c5680-c337-11e4-89bb-6f2da348c9fd.png)

**Comment by dieterv** [comment]
Note the above works as expected after downgrading to requests 2.5.1.

**Comment by Lukasa** [comment]
Thanks @dieterv, this is a known issue, see shazow/urllib3#561. We aim to push out a fix for this very shortly.
