### ISSUE TITLE
iter_lines: Skipping first line using next(..)

### ISSUE THREAD

**Issue by plaes** [kennethreitz/requests#2476]
When trying to skip first line of  `response.iter_lines()` using `next()`, some extra data from following lines is also consumed.

Test script:
```python
import requests
from contextlib import closing

with closing(requests.get('http://httpbin.org/stream/5', stream=True)) as r:
    skip = next(r.iter_lines())
    print 'SKIP: ', skip
    for n, l in enumerate(r.iter_lines(), start=1):
        print 'PROCESS: {}'.format(n), l
```

With following output (line 1 totally missing, and line 2 being partial):
```
SKIP:  {"url": "http://httpbin.org/stream/5", "headers": {"Host": "httpbin.org", "Accept-Encoding": "gzip, deflate", "Accept": "*/*", "User-Agent": "python-requests/2.4.3 CPython/2.7.9 Linux/4.0.0-rc2+"}, "args": {}, "id": 0, "origin": "xxx"}
PROCESS: 1 n.org/stream/5", "headers": {"Host": "httpbin.org", "Accept-Encoding": "gzip, deflate", "Accept": "*/*", "User-Agent": "python-requests/2.4.3 CPython/2.7.9 Linux/4.0.0-rc2+"}, "args": {}, "id": 2, "origin": "xxx"}
PROCESS: 2 {"url": "http://httpbin.org/stream/5", "headers": {"Host": "httpbin.org", "Accept-Encoding": "gzip, deflate", "Accept": "*/*", "User-Agent": "python-requests/2.4.3 CPython/2.7.9 Linux/4.0.0-rc2+"}, "args": {}, "id": 3, "origin": "xxx"}
PROCESS: 3 {"url": "http://httpbin.org/stream/5", "headers": {"Host": "httpbin.org", "Accept-Encoding": "gzip, deflate", "Accept": "*/*", "User-Agent": "python-requests/2.4.3 CPython/2.7.9 Linux/4.0.0-rc2+"}, "args": {}, "id": 4, "origin": "xxx"}
```

**Comment by sigmavirus24** [comment]
This is a tricky interaction with iterators. Most iterators don't quite behave the same way. What you need to do is the following

``` py
with closing(requests.get('https://httpbin.org/stream/5', stream=True)) as r:
    iterator = r.iter_lines()
    print 'SKIP: ', next(iterator)
    for n, l in enumerate(iterator, start=1):
        print 'PROCESS: {}'.format(n), l
```

That works fine for me. I'm not confident this is a bug because `iter_lines` is allowed to make some assumptions about how it's used. I'll wait to see if @Lukasa agrees with me.

**Comment by plaes** [comment]
Thanks, this was unexpected :)

**Comment by Lukasa** [comment]
Agreed.

`iter_lines` and `iter_content` should _really_ only be used in a single place, or they risk having unexpected effects. It might be worth adding a `..warning` or `..admonition` block to the docstrings for those methods to reinforce that message.

**Comment by sigmavirus24** [comment]
So I took a quick look at the implementation of [`Response.iter_lines`](https://github.com/kennethreitz/requests/blob/master/requests/models.py#L693)

We read a chunk from the response, and then find the line within that chunk and return it. We store the remainder locally in the function and not on a the response object itself. I think an update to the docs like @Lukasa described is warranted.

**Comment by plaes** [comment]
Would it make sense to actually store the pending data as `self._pending`?
