### ISSUE TITLE
Returning json from SocketServer: ConnectionError BadStatusLine

### ISSUE THREAD

**Issue by manojgudi** [kennethreitz/requests#2479]
This worked in requests version 2.2.1, but breaks in 2.5.3
Environment:
Ubuntu 12.04/x86
Python 2.7.3

**Comment by sigmavirus24** [comment]
@manojgudi can you give us more information. We have absolutely nothing to debug this with otherwise and will be forced to close the issue.

**Comment by manojgudi** [comment]
@sigmavirus24 Thanks for prompt reply! Lemme write a script to reproduce this issue.. Gimme a day or so..

Thanks

**Comment by manojgudi** [comment]
Turns out I didnt attach http headers when returning a json response from my custom SocketServer(which was causing this issue) 
sorry for the noise..
