### ISSUE TITLE
Radio streaming download: ICY causes BadStatusLine

### ISSUE THREAD

**Issue by rubentorresbonet** [kennethreitz/requests#2480]
Hello,

Even if the icy's protocol is broken, I would still need to download the streaming data of a shoutcast server.
When attempting to, I get this issue:

  File "/usr/lib/python3/dist-packages/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 558, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 378, in send
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='streaming3.radiocat.net', port=80): Max retries exceeded with url: /;listen.mp3 (Caused by ProtocolError('Connection aborted.', BadStatusLine('ICY 200 OK\r\n',)))

Any workaround or something I could do?

Thanks.

**Comment by Lukasa** [comment]
Yes. =) Don't use a HTTP library.

That answer was a bit glib, but it's pretty accurate. Let me show you what RFC 7230 says a HTTP status line should look like:

`status-line = HTTP-version SP status-code SP reason-phrase CRLF`

That first set of characters needs to be a HTTP version. If it doesn't specify a HTTP version, a HTTP library cannot assume it has the faintest idea what's going on. For that reason, `httplib` sees a HTTP version called 'ICY', doesn't recognise it, and bails out (quite rightly).

Unfortunately for you, `httplib` then closes the socket connection and loses its reference to the socket object.

What you really need is something that can fake out a HTTP request using a socket. This shouldn't be very hard: create a socket connection directly to your target and then just write some basic HTTP headers to it.

If you find that helpful, you could write an ICY transport adapter for requests and use it.

Sadly, however, this is outside the scope of requests to help you. =)

**Comment by rubentorresbonet** [comment]
Lukasa, thank you for your answer.

How bad would it be to modify the original library like this?
https://mail.python.org/pipermail/web-sig/2005-August/001641.html

It sounds like I'd save a lot of work just by adding two lines. Still, I know it's not a great solution. What do you personally think about it?

Doing everything with sockets will be a lot of pain.

**Comment by sigmavirus24** [comment]
@rubentorresbonet if you choose to modify httplib like that, that's your decision. It's not up to our discretion nor is it our place to recommend it.

I think modifying a standard library is a poor way of handling this, but if that's what you choose to do, there's nothing for anyone to do about it.

Also @Lukasa didn't tell you to do _everything_ with sockets, only portions dealing with ICY.
