### ISSUE TITLE
Consider adding return type documentation in docstrings

### ISSUE THREAD

**Issue by ulope** [kennethreitz/requests#2483]
It would be great if the docstrings of (at least) the top level entry points (`request`, `get`, `post`, etc.) could define the return type in a sphinx compatible way (`:rtype:` http://sphinx-doc.org/domains.html#info-field-lists). This would make it easier to work with requests in various IDEs and code inspection tools.

**Comment by Lukasa** [comment]
Sounds good to me!

Do you want to open a pull request containing this change?

**Comment by ulope** [comment]
Sure. I'll try to fit it in later in the day.

**Comment by sigmavirus24** [comment]
:+1:

**Comment by sigmavirus24** [comment]
Looks like this was fixed by #2487. Closing as fixed.
