### ISSUE TITLE
Need documentation about "Cookies set on individual Requests through a `Session` are not persisted to the session"

### ISSUE THREAD

**Issue by colinfang** [kennethreitz/requests#2488]
It took me a while to figure it out. Thought it might be a bug initially, I then came across #1791 & #1728.

Since this feature by design is quite confusing. I feel it deserves some more attention apart from simply mention it in the changelog (0b68037).

Can we have it as a tip/hint some where in the documentation (or quick start)? And suggest the proper way to prepare the persistent cookies.

**Comment by sigmavirus24** [comment]
Sorry, it's late here and I'm tired. Could you give an example of what you mean?

**Comment by Lukasa** [comment]
So I think this is a good idea. It's not entirely clear that we don't send the custom cookies in the second request here:

``` python
s = Session()
s.get('http://myhost.com/page1', cookies={'from-my': 'browser'})
s.get('http://myhost.com/page2')
```

I'll happily merge any pull request that adds documentation for this. =)
