### ISSUE TITLE
Request works from command line, but not from within script.

### ISSUE THREAD

**Issue by egmhansen** [kennethreitz/requests#2507]
If I run the following from the command line, it works fine.  If I try to run it from a script I get the AttributeError.  Why is those things I said?

import requests
r = requests.head('https://api.github.com/user')

AttributeError: 'module' object has no attribute 'head'

**Comment by kevinburke** [comment]
Is there a file named 'requests.py'? Python would try to import that file, not the module, in that case.

**Comment by egmhansen** [comment]
Nailed it!  thanks Kevin!
