### ISSUE TITLE
Session timeout doesn't accept tuple?

### ISSUE THREAD

**Issue by mdalpi** [kennethreitz/requests#2508]
Hi.
Following the [documentation](http://docs.python-requests.org/en/latest/user/advanced/#timeouts), I've set a tuple with connect and read timeouts:

    data = self.session.post('https://...', 
               data=params, 
               headers=headers, 
               timeout=(4.5, 10),
               verify=False).json()

But what I've got is this:

    Timeout value connect was (4.5, 10), but it must be an int or float.

As stated in the [developer API](http://docs.python-requests.org/en/latest/api/#request-sessions) under request method, timeout should accept float or tuple, right?
Thanks

**Comment by kevinburke** [comment]
Taking a look now

On Friday, March 20, 2015, Mateus Dalto Piveta notifications@github.com
wrote:

> Hi.
> Following the documentation
> http://docs.python-requests.org/en/latest/user/advanced/#timeouts, I've
> set a tuple with connect and read timeouts:
> 
> data = self.session.post('https://...,
>            data=params,
>            headers=headers,
>            timeout=(4.5, 10),
>            verify=False).json()
> 
> But what I've got is this:
> 
> Timeout value connect was (4.5, 10), but it must be an int or float.
> 
> As stated in the developer API
> http://docs.python-requests.org/en/latest/api/#request-sessions under
> request method, timeout should accept float or tuple, right?
> Thanks
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kennethreitz/requests/issues/2508.

## 

## 

Kevin Burke
phone: 925.271.7005 | twentymilliseconds.com

**Comment by Lukasa** [comment]
What version of requests are you using?

**Comment by Lukasa** [comment]
The reason I ask is that with 2.6.0, I cannot reproduce this bug.

**Comment by ghost** [comment]
Requests 2.6.0
Python 3.4.0

Also, same error without using session

**Comment by Lukasa** [comment]
Once again, I do not reproduce this on requests 2.6.0 on Python 3.4.3 on OS X.

**Comment by ghost** [comment]
![screen shot 2015-03-20 at 20 20 19](https://cloud.githubusercontent.com/assets/6289699/6762468/92405c54-cf3f-11e4-9ce9-66b619e9c49c.png)

Ubuntu 14.04.2
=/

**Comment by kevinburke** [comment]
what is the urllib3 version? a single `util.py` file is fairly old..

## 

Kevin Burke
phone: 925.271.7005 | twentymilliseconds.com

**Comment by kevinburke** [comment]
sorry - what I am trying to suggest is that your requests version is 2.6.0,
but the attached urllib3 version is part of your system packages and may be
earlier, in a compatibility-breaking way.

## 

Kevin Burke
phone: 925.271.7005 | twentymilliseconds.com

**Comment by ghost** [comment]
I've uninstalled the python3-urllib3 that comes with default installation (v1.7.1) and installed via pip v1.10.2, and now everything works :grin:
Thank you guys
