### ISSUE TITLE
Can't copy-paste international URL

### ISSUE THREAD

**Issue by cool-RR** [kennethreitz/requests#2515]
Observe this link to an article: http://alaxon.co.il/article/%D7%9C%D7%95-%D7%99%D7%9B%D7%9C%D7%95-%D7%97%D7%AA%D7%95%D7%9C%D7%99%D7%9D-%D7%9C%D7%93%D7%91%D7%A8/

If you click it, you'll see Hebrew letters in your address bar. (At least in Chrome.) The article works.

Now, try accessing it in requests:

    >>> import requests
    >>> requests.get('http://alaxon.co.il/article/%D7%9C%D7%95-%D7%99%D7%9B%D7%9C%D7%95-%D7%97%D7%AA%D7%95%D7%9C%D7%99%D7%9D-%D7%9C%D7%93%D7%91%D7%A8/')
    Starting new HTTP connection (1): alaxon.co.il
    <Response [403]>

Why is that?

**Comment by cool-RR** [comment]
Note that I get the same 403 error response when I put the Hebrew URL in `requests.get` without the percentage escape sequences. If I put this Hebrew URL in the browser, it works fine.

**Comment by cool-RR** [comment]
My mistake, this was a completely unrelated problem with the site.

**Comment by Lukasa** [comment]
Heh, I was just diving in. Thanks for solving it yourself!
