### ISSUE TITLE
AttributeError- LWPCookieJar instance has no attribute 'copy'

### ISSUE THREAD

**Issue by zhaoguixu** [kennethreitz/requests#2527]
Hi,
In version 2.x:
<b>[test-case]</b>
```python
import requests
from cookielib import LWPCookieJar
cookiejar = LWPCookieJar()
req = requests.Request('GET', 'http://httpbin.org/get', cookies=cookiejar)
r = req.prepare()
r.copy()
```
<b>[traceback]</b>
...
AttributeError: LWPCookieJar instance has no attribute 'copy'

<b>[comments]</b>
It seems that not all instances of cookiejar have the copy method, but in the copy method of PreparedRequest, it call the copy method of cookies without any checks.

**Comment by sigmavirus24** [comment]
What is your proposed solution?

**Comment by zhaoguixu** [comment]
Hi @sigmavirus24,
Thanks for quick response.  This situation is a little tricky that the base CookieJar class does not supply the 'copy' method but the RequestsCookieJar does. However, in the method 'prepare_cookies' of PreparedRequests, you permit all the instances of the subclass of CookieJar preserved as its original form(which may not contain 'copy' method). As I suppose, one uniformed way is to remove the copy method of  RequestsCookieJar and use the python copy function when copy is needed(This may need changes of other places). The other is more conservative, that is, restrict the self._cookies of PreparedRequest to be only the instance of RequestsCookieJar or else check whether having copy method before calling this method of a CookieJar instance.

``` python
def prepare_cookies(self, cookies):
    """Prepares the given HTTP cookie data."""

    if isinstance(cookies, cookielib.CookieJar):   #<=====
        self._cookies = cookies
    else:
        self._cookies = cookiejar_from_dict(cookies)
    ...
```

**Comment by sigmavirus24** [comment]
@zhaoguixu check out #2534

**Comment by zhaoguixu** [comment]
As mentioned in #2077, self._cookies may be None

``` python
p._cookies = _copy_cookie_jar(self._cookies)   # need check whether it is None
```

**Comment by sigmavirus24** [comment]
Thanks for catching that @zhaoguixu. I updated the PR to account for that.
