### ISSUE TITLE
2.5.1 labeled latest release at GitHub (rather than 2.6.0)?

### ISSUE THREAD

**Issue by hartwork** [kennethreitz/requests#2528]
Hi!

Looking at
https://github.com/kennethreitz/requests/releases
I need to click on "Show 3 newer tags" to see 2.6.0 uncovered.
2.5.1 is marked the latest release. Is that intended?
It's 2.6.0 on PyPI https://pypi.python.org/pypi/requests/ .

Best, Sebastian

**Comment by Lukasa** [comment]
We don't really have a consistent policy of updating GitHub's releases. For our release notes we strongly recommend looking at PyPI or our documentation.

**Comment by hartwork** [comment]
So... no fix? 2.5.1 remains the latest on GitHub?

**Comment by sigmavirus24** [comment]
@hartwork as @Lukasa has already kindly explained, PyPI is the source of truth. Not GitHub. You might notice that there are _several_ releases missing notes on GitHub.

**Comment by hartwork** [comment]
My point are not the releases notes. My point is the fix potential user confusion. The release page up here raises more questions than it answers. If it's trouble to keep in sync, okay. If not, my vote to keep it synced, even just versions without release notes. That's all.

**Comment by sigmavirus24** [comment]
@hartwork it is not trivial.

**Comment by hartwork** [comment]
Okay :)
