### ISSUE TITLE
__build__ out of sync? Still at 0x020503, looks like 2.5.3 rather than 2.6.0

### ISSUE THREAD

**Issue by hartwork** [kennethreitz/requests#2530]
Could it be that
```
__build__ = 0x020503
```
at https://github.com/kennethreitz/requests/blob/master/requests/__init__.py#L46
went out of sync? It looks like 2.5.3 rather than 2.6.0.

Best, Sebastian

**Comment by Lukasa** [comment]
Yup, this looks wrong.
