### ISSUE TITLE
Dependency is not satisfiable: python (>= 2.7.5-5~)

### ISSUE THREAD

**Issue by francesco1119** [kennethreitz/requests#2538]
hello,

I'm trying to install python-requests on my Debian Wheezy from the .deb:

# gdebi python-requests_2.4.3-6_all.deb 
Reading package lists... Done
Building dependency tree        
Reading state information... Done
Building data structures... Done 
Building data structures... Done 
This package is uninstallable
Dependency is not satisfiable: python (>= 2.7.5-5~)

Well, is quite strange as with a "python -V" the output is: Python 2.7.7.
And I have already tried all of those chances: http://docs.python-requests.org/en/latest/user/install/#install

Any idea?

**Comment by Lukasa** [comment]
I'm afraid we can't support you with the `.deb`, because we don't build or maintain that package, @ralphbean does. I recommend raising a bug with debian if you're having trouble.

When you say you've tried the install methods on our website, which methods have you actually tried and how did they fail?

**Comment by francesco1119** [comment]
Thank you, I will contact Debian for that. 
I've trued to download the tar.gz from GitHub: nothing
Then:

# pip install requests

Requirement already satisfied (use --upgrade to upgrade): requests in /usr/local/lib/python2.7/dist-packages

# easy_install requests

Searching for requests
Best match: requests 2.6.0
Adding requests 2.6.0 to easy-install.pth file

Using /usr/local/lib/python2.7/dist-packages
Processing dependencies for requests
Finished processing dependencies for requests

With git clone and the tar.gz there is apparently no problem, but then it doesn't work:

python setup.py install
/root/.pythonbrew/pythons/Python-2.7.7/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'extras_require'
  warnings.warn(msg)
/root/.pythonbrew/pythons/Python-2.7.7/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'zip_safe'
  warnings.warn(msg)
/root/.pythonbrew/pythons/Python-2.7.7/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'include_package_data'
  warnings.warn(msg)
/root/.pythonbrew/pythons/Python-2.7.7/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
running install
running build
running build_py
creating build
creating build/lib
creating build/lib/requests
copying requests/sessions.py -> build/lib/requests
copying requests/certs.py -> build/lib/requests
copying requests/api.py -> build/lib/requests
copying requests/structures.py -> build/lib/requests
copying requests/cookies.py -> build/lib/requests
copying requests/utils.py -> build/lib/requests
copying requests/status_codes.py -> build/lib/requests
copying requests/**init**.py -> build/lib/requests
copying requests/hooks.py -> build/lib/requests
copying requests/models.py -> build/lib/requests
copying requests/adapters.py -> build/lib/requests
copying requests/compat.py -> build/lib/requests
copying requests/exceptions.py -> build/lib/requests
copying requests/auth.py -> build/lib/requests
creating build/lib/requests/packages
copying requests/packages/**init**.py -> build/lib/requests/packages
creating build/lib/requests/packages/chardet
copying requests/packages/chardet/universaldetector.py -> build/lib/requests/packages/chardet
copying requests/packages/chardet/mbcharsetprober.py -> build/lib/requests/packages/chardet
copying requests/packages/chardet/langthaimodel.py -> build/lib/requests/packages/chardet
copying requests/packages/chardet/sjisprober.py -> build/lib/requests/packages/chardet
copying requests/packages/chardet/constants.py -> build/lib/requests/packages/chardet
copying requests/packages/chardet/gb2312prober.py -> build/lib/requests/packages/chardet
copying requests/packages/chardet/latin1prober.py -> build/lib/requests/packages/chardet
copying requests/packages/chardet/charsetgroupprober.py -> build/lib/requests/packages/chardet
copying requests/packages/chardet/mbcssm.py -> build/lib/requests/packages/chardet
copying requests/packages/chardet/**init**.py -> build/lib/requests/packages/chardet
copying requests/packages/chardet/euckrfreq.py -> build/lib/requests/packages/chardet
copying requests/packages/chardet/euctwprober.py -> build/lib/requests/packages/chardet
copying requests/packages/chardet/big5prober.py -> build/lib/requests/packages/chardet
copying requests/packages/chardet/sbcharsetprober.py -> build/lib/requests/packages/chardet
copying requests/packages/chardet/langbulgarianmodel.py -> build/lib/requests/packages/chardet
copying requests/packages/chardet/escprober.py -> build/lib/requests/packages/chardet
copying requests/packages/chardet/jisfreq.py -> build/lib/requests/packages/chardet
copying requests/packages/chardet/eucjpprober.py -> build/lib/requests/packages/chardet
copying requests/packages/chardet/mbcsgroupprober.py -> build/lib/requests/packages/chardet
copying requests/packages/chardet/sbcsgroupprober.py -> build/lib/requests/packages/chardet
copying requests/packages/chardet/chardistribution.py -> build/lib/requests/packages/chardet
copying requests/packages/chardet/codingstatemachine.py -> build/lib/requests/packages/chardet
copying requests/packages/chardet/langhungarianmodel.py -> build/lib/requests/packages/chardet
copying requests/packages/chardet/gb2312freq.py -> build/lib/requests/packages/chardet
copying requests/packages/chardet/big5freq.py -> build/lib/requests/packages/chardet
copying requests/packages/chardet/euctwfreq.py -> build/lib/requests/packages/chardet
copying requests/packages/chardet/hebrewprober.py -> build/lib/requests/packages/chardet
copying requests/packages/chardet/jpcntx.py -> build/lib/requests/packages/chardet
copying requests/packages/chardet/compat.py -> build/lib/requests/packages/chardet
copying requests/packages/chardet/charsetprober.py -> build/lib/requests/packages/chardet
copying requests/packages/chardet/euckrprober.py -> build/lib/requests/packages/chardet
copying requests/packages/chardet/escsm.py -> build/lib/requests/packages/chardet
copying requests/packages/chardet/langgreekmodel.py -> build/lib/requests/packages/chardet
copying requests/packages/chardet/chardetect.py -> build/lib/requests/packages/chardet
copying requests/packages/chardet/langcyrillicmodel.py -> build/lib/requests/packages/chardet
copying requests/packages/chardet/utf8prober.py -> build/lib/requests/packages/chardet
copying requests/packages/chardet/cp949prober.py -> build/lib/requests/packages/chardet
copying requests/packages/chardet/langhebrewmodel.py -> build/lib/requests/packages/chardet
creating build/lib/requests/packages/urllib3
copying requests/packages/urllib3/request.py -> build/lib/requests/packages/urllib3
copying requests/packages/urllib3/**init**.py -> build/lib/requests/packages/urllib3
copying requests/packages/urllib3/_collections.py -> build/lib/requests/packages/urllib3
copying requests/packages/urllib3/filepost.py -> build/lib/requests/packages/urllib3
copying requests/packages/urllib3/poolmanager.py -> build/lib/requests/packages/urllib3
copying requests/packages/urllib3/connectionpool.py -> build/lib/requests/packages/urllib3
copying requests/packages/urllib3/response.py -> build/lib/requests/packages/urllib3
copying requests/packages/urllib3/fields.py -> build/lib/requests/packages/urllib3
copying requests/packages/urllib3/exceptions.py -> build/lib/requests/packages/urllib3
copying requests/packages/urllib3/connection.py -> build/lib/requests/packages/urllib3
creating build/lib/requests/packages/urllib3/packages
copying requests/packages/urllib3/packages/six.py -> build/lib/requests/packages/urllib3/packages
copying requests/packages/urllib3/packages/__init__.py -> build/lib/requests/packages/urllib3/packages
copying requests/packages/urllib3/packages/ordered_dict.py -> build/lib/requests/packages/urllib3/packages
creating build/lib/requests/packages/urllib3/contrib
copying requests/packages/urllib3/contrib/**init**.py -> build/lib/requests/packages/urllib3/contrib
copying requests/packages/urllib3/contrib/pyopenssl.py -> build/lib/requests/packages/urllib3/contrib
copying requests/packages/urllib3/contrib/ntlmpool.py -> build/lib/requests/packages/urllib3/contrib
creating build/lib/requests/packages/urllib3/util
copying requests/packages/urllib3/util/ssl_.py -> build/lib/requests/packages/urllib3/util
copying requests/packages/urllib3/util/request.py -> build/lib/requests/packages/urllib3/util
copying requests/packages/urllib3/util/**init**.py -> build/lib/requests/packages/urllib3/util
copying requests/packages/urllib3/util/timeout.py -> build/lib/requests/packages/urllib3/util
copying requests/packages/urllib3/util/response.py -> build/lib/requests/packages/urllib3/util
copying requests/packages/urllib3/util/retry.py -> build/lib/requests/packages/urllib3/util
copying requests/packages/urllib3/util/url.py -> build/lib/requests/packages/urllib3/util
copying requests/packages/urllib3/util/connection.py -> build/lib/requests/packages/urllib3/util
creating build/lib/requests/packages/urllib3/packages/ssl_match_hostname
copying requests/packages/urllib3/packages/ssl_match_hostname/**init**.py -> build/lib/requests/packages/urllib3/packages/ssl_match_hostname
copying requests/packages/urllib3/packages/ssl_match_hostname/_implementation.py -> build/lib/requests/packages/urllib3/packages/ssl_match_hostname
copying requests/cacert.pem -> build/lib/requests
running install_lib
running install_egg_info
Removing /root/.pythonbrew/pythons/Python-2.7.7/lib/python2.7/site-packages/requests-2.6.0-py2.7.egg-info
Writing /root/.pythonbrew/pythons/Python-2.7.7/lib/python2.7/site-packages/requests-2.6.0-py2.7.egg-info

Thank you

**Comment by ralphbean** [comment]
> I'm afraid we can't support you with the .deb, because we don't build or maintain that package, @ralphbean does.

Just a correction:  I do not support the debian redistribution, @eriol does.  I work on the `.rpm` packaging for Fedora and EPEL.  Regardless, thanks for the ping!

**Comment by sigmavirus24** [comment]
I think @lukasa meant to ping @eriol

**Comment by Lukasa** [comment]
Additionally, it's worth noting that the install appears to have gone just fine.

**Comment by sigmavirus24** [comment]
So actually this looks like @francesco1119 is using python brew to install things, which does not work (I would guess) with aptitude/dpkg. That would be your problem @francesco1119. You can't mix python brew with system packages. You should look for `/usr/bin/python` (or something like that) to determine:
1. If you have Python installed
2. What version of Python _is_ installed.

**Comment by francesco1119** [comment]
Python is at the version 2.7.7. 
So let's say I don't want to use .deb but "pip install requests". I launch the command the the terminal replay:

Requirement already satisfied (use --upgrade to upgrade): requests in /usr/local/lib/python2.7/dist-packages

Apparently looks ok, so I try to install pulseaudio-dlna_0.3.4_all.deb (that needs python-request) and the terminal says:

Reading package lists... Done
Building dependency tree  
Reading state information... Done
Building data structures... Done 
Building data structures... Done 
This package is uninstallable
Dependency is not satisfiable: python-requests (>= 2.2.1)

So it means that python-requests is installed but not the version I need. How to upgrade it?

**Comment by Lukasa** [comment]
@francesco1119 You're clearly in a whole world of dependency pain.

The reason pulseaudio can't satisfy its requests requirement is because there is no requests package installed, because apt-get ignores anything installed by pip. Your inability to install requests is a much bigger problem, and clearly your system requires real work to get into a good state again.

**Comment by eriol** [comment]
Hello, thanks for the ping for the Debian related stuff!

@francesco1119 I don't know python brew but it does not create a _Debian package_ (for this you can use [stdeb](https://github.com/astraw/stdeb)) so this is why when installing pulseaudio-dlna_0.3.4_all.deb you get that dependency is not satisfiable.
If you want to use pulseaudio-dlna_0.3.4_all.deb (it's not an official Debian package, did you package it by yourself?) the best thing to do is to backport requests from Jessie. Keep in mind that you have to backport python-urllib3 before backporting requests since, in Debian, requests uses the system-wide urllib3.
To backporting a package you can follow https://wiki.debian.org/SimpleBackportCreation

Otherwise you can use stdeb and package requests from PyPI (you don't need to follow Debian Policy for a package builded by yourself), and then install pulseaudio-dlna_0.3.4_all.deb. Or since you seems at ease with python brew, you can see if you can install pulseaudio-dlna using it.

HTH
