### ISSUE TITLE
Noisy SSL warnings

### ISSUE THREAD

**Issue by tonyennis** [kennethreitz/requests#2539]
Is there a way to suppress these noisy SSL warnings? I got them by specifying requests.get(..., verify=False) when I was trying to use some self-signed web services.

/usr/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:79: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
/usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:769: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)

**Comment by Lukasa** [comment]
`requests.packages.urllib3.disable_warnings()`.

**Comment by tonyennis** [comment]
Thank you!
