### ISSUE TITLE
Fully disable cookie handling in Sessions

### ISSUE THREAD

**Issue by logc** [kennethreitz/requests#2544]
This is a feature request, not a bug.

When creating a new `Session` in order to issue multiple requests, one can specify a `CookiePolicy` to reject all cookies (e.g. [this way](http://stackoverflow.com/a/21714597/2250036)). But for each new request, a new `RequestsCookieJar` is created, with a `DefaultCookiePolicy`, where previous cookies are merged.

Since there are no previous cookies, the behaviour is correct (no cookies are accepted), but the creation of those objects is costly and leads to a decreased performance. Working around this issue, with a subclass of Session that does not perform any cookie handling, gives a speedup of 1.32x or more, in our measurements.

Furthermore, it is a bit surprising that `Session` imposes this object creation to users, even if the user has specified that no cookie handling is needed (by setting the custom `CookiePolicy` after initialization), and even for a single request that does not create a `Session` (since a `Session` is created under the hood by all convenience methods like `requests.get`, `requests.post`).

Why is this behaviour so?  Are there plans to create a variant of `Session` where cookies can be fully disabled?  May we contribute our own workaround, if there is interest from other users?

**Comment by Lukasa** [comment]
Thanks for this feature request!

The reality is that you haven't told the `Session` no cookie handling is needed, you've only told the cookiejar it owns. The `Session` has no way to be told that you don't want cookie handling, and it's simply not a feature requests possesses.

The reality is, vastly more users want cookie handling on and functioning than want to turn it off. For that reason we really have no plans to make it possible to fully disable cookie handling. If you're sufficiently worried about performance that you want to turn off one of requests' most important high-level features, I recommend investigating whether you can use `urllib3` just as easily. =)

**Comment by logc** [comment]
Thanks to you for your swift answer!  We will look into using directly `urllib3`…
