### ISSUE TITLE
Document filtering of 'None' values for url-encoded parameters

### ISSUE THREAD

**Issue by Varriount** [kennethreitz/requests#2545]
Currently, when passing a dictionary/list of pairs to the request constructor's `params` parameter, any 'None' values are filtered when encoding the request url. If this is intended behavior or not something that will change, then this should be documented (actually, even if it is subject to change, it should probably by documented anyway so that people don't rely on it)

**Comment by Lukasa** [comment]
It already is documented. =) See [this block](http://docs.python-requests.org/en/latest/user/quickstart/#passing-parameters-in-urls).
