### ISSUE TITLE
Cookies issue causing segfault still in 2.6?

### ISSUE THREAD

**Issue by 11phc** [kennethreitz/requests#2549]
FYI I think there might still be a cookies related issue... I was having issues two weeks ago with cookies.py in 2.5.3 i think, but I have downloaded the new requests 2.6 running on raspberry pi for a datalogger every minute, and it's much better but now it segfaults every 24 hours or so in a slightly different place.  (FYI I'm not very competent on python debugging yet)  

Traceback show's it segfaulting on line 241 in python2.7/rfc822.py (it shows as line 243 in my screenshot but I had already added a couple of lines above for debugging - it is whatever line "for line in self.headers" is on in getAllMatchingHeaders), invoked ultimately from requests/cookies.py.

The process is just repeatedly loading a webserver.html page on a PLC we have on our intranet, to read it's variables, so it's not going over the internet.

When running, normally the 'lst' variable is always returned as [] so I dont even need this procedure and for now I've bypassed the "for line in self.headers" bit to keep it from segfaulting once a day.

If you want more info do please let me know what you need.

And of course, thanks for the great work.

![screen shot 2015-04-12 at 08 17 02](https://cloud.githubusercontent.com/assets/10351369/7104822/fce30c78-e0f1-11e4-8d40-ea12fb032df0.png)

**Comment by 11phc** [comment]
Or is this just a python2.7 bug?

**Comment by sigmavirus24** [comment]
@11phc it is just a python2.7 bug. I would check bugs.python.org to figure out which version number has the fix. If you can, I would update your version of python to 2.7.9 on your Pi.

Cheers,
Ian

**Comment by 11phc** [comment]
ok thanks very much Ian.  I was on version 2.7.3, but unfortunately going to Python 2.7.9 still doesn’t seem to fix it.  I might have to go to Python 3.x I fear.

piers

**Comment by 11phc** [comment]
Sorry…. I’ve got another segfault now in requests/api.py which I think probably is in requests, right? 

python 2.7.9
requests 2.6.0

its a data logger program, so it just happens once every 24 hours or so, after doing a requests call every minute.

anything useful I can do to isolate it?
Shall I open another issue in github?

thanks

**Comment by sigmavirus24** [comment]
Can you provide any extra information here first? A traceback? More details about how you're using requests? Anything that we could possibly use to help you.
