### ISSUE TITLE
Why does the PreparedRequest.prepare method provide None as the default parameter value for those who cannot be None? 

### ISSUE THREAD

**Issue by zhaoguixu** [kennethreitz/requests#2552]
Hi,
I just inspect some test cases of your project, and find some test cases like
```python
def test_prepare_unicode_url():
    p = PreparedRequest()
    p.prepare(
        method='GET',
        url=u('http://www.example.com/üniçø∂é'),
        hooks=[]
    )
    assert_copy(p, p.copy())
```
When I remove some parameters for calling the prepare method, it will raise exceptions(with url being missed) or traceback(with hooks being missed). 
Is it unreasonable to provide None default parameter for some arguments cannot be None? 
(A related PR is #2301).

Thanks.

**Comment by Lukasa** [comment]
I see no good reason to leave those as `None`-able defaults. I think we could get away with patching this in a minor release, because while it's _technically_ backward-incompatible, in practice I don't think anyone can be correctly relying on this behaviour. @sigmavirus24?

**Comment by sigmavirus24** [comment]
Personally, I like the idea of more or less _suggesting_ that users specify the arguments by keyword. If anything we should be documenting the fact that some of these parameters need to be provided. That said, I don't like that we have to pass hooks as an empty list so I'm sending a patch with a fix for that.
