### ISSUE TITLE
Make an official logo and stickers for it

### ISSUE THREAD

**Issue by sigmavirus24** [kennethreitz/requests#2559]
Proposed logo:

:sparkles: :cake: :sparkles:

**Comment by Lukasa** [comment]
If we could get a designer to render it in a way that wasn't just emoji, this'd be perfect.

**Comment by alex** [comment]
This would be the second emoji logo stick I have!

:muscle: :computer: :us:

**Comment by kennethreitz** [comment]
YES!

**Comment by kennethreitz** [comment]
`>>> import requests`
:sparkles: :cake: :sparkles:

**Comment by kennethreitz** [comment]
the github3.py stickers are some of my favorites.

**Comment by sigmavirus24** [comment]
Yeah the Digital Services stickers are the reason why I thought of :sparkles: :cake: :sparkles: stickers as a real good idea. I still know the designer who did the github3.py stickers. I can see if she's available for hire to do this. I'll happily handle paying for the logo.

**Comment by missingdink** [comment]
When are you looking for this to be done?

**Comment by sigmavirus24** [comment]
`¯\_(ツ)_/¯`

**Comment by kennethreitz** [comment]
@missingdink whenevs :)

**Comment by missingdink** [comment]
:+1: :hankey: :muscle:

**Comment by sigmavirus24** [comment]
@missingdink :cake:

**Comment by hickford** [comment]
Does James Halliday take commissions? I adore his readmes http://substack.net/art

**Comment by sigmavirus24** [comment]
@missingdink actually came through @hickford. We just need to revamp our stuff with the new logo.
