### ISSUE TITLE
Add contribution guidelines

### ISSUE THREAD

**Issue by kennethreitz** [kennethreitz/requests#2560]
https://github.com/benoitc/gunicorn/blob/master/CONTRIBUTING.md

**Comment by Lukasa** [comment]
Presumably this document will be pretty similar to the content of [these](http://docs.python-requests.org/en/latest/dev/philosophy/) [two](http://docs.python-requests.org/en/latest/dev/todo/) pages.

**Comment by sigmavirus24** [comment]
Thoughts on adding something akin to [this](https://github.com/sigmavirus24/requests-toolbelt/blob/master/CODE_OF_CONDUCT.rst) as well?

**Comment by sigmavirus24** [comment]
Also the bit in the [Standard Library](http://docs.python-requests.org/en/latest/dev/philosophy/#standard-library) section about having just reached v1.0.0 is a bit ... dated.

**Comment by sigmavirus24** [comment]
Oh also our [Runtime Environments](http://docs.python-requests.org/en/latest/dev/todo/#runtime-environments) list is very wrong. PyPy 1.9 is very old and dated. We don't actually test against it either and I don't think we support 3.1 or 3.2 either. =(

**Comment by kennethreitz** [comment]
simpler than pledging, i think

"be cordial, or be on your way", "adhere to our philosophy", etc.

**Comment by Lukasa** [comment]
@kennethreitz In that case, what do you think of [this doc](https://hyper.readthedocs.org/en/latest/contributing.html).

**Comment by kennethreitz** [comment]
@Lukasa wonderful!

**Comment by Lukasa** [comment]
Alright, basic proposal is in #2572.

**Comment by sigmavirus24** [comment]
With #2572 merged, I'm closing this. :cake:
