### ISSUE TITLE
Content-Encoding: Gzip not automatically decoded in 2.6.1

### ISSUE THREAD

**Issue by elsimir** [kennethreitz/requests#2561]
When using requests on python 2.7.8 ubuntu 14.10 from pypi, the current version 2.6.1 exhibits different behaviour from 2.6.0. Response.content is a gzipped binary string, instead of a decoded unicode string in 2.6.0. Is this change in behaviour intended? Running this script in both 2.6.0 and 2.6.1 shows the difference.

    import requests
    import gzip
    import json
    from StringIO import StringIO

    resp = requests.get('https://liquidstate.atlassian.net/rest/api/2/serverInfo')
    try:
        print 'Reading as JSON'
        print resp.json()
    except Exception:
        print 'Failed to load JSON, reading as Gzip'
        print 'Reading as Gzip'
        content = StringIO()
        content.write(resp.content)
        content.seek(0)
        gz = gzip.GzipFile(fileobj=content)
        print json.loads(gz.read())

Under version 2.6.0:
Reading as JSON
{u'versionNumbers': [6, 5, 0], u'serverTitle': u'JIRA', u'buildDate': u'2015-04-08T00:00:00.000+1000',        u'scmInfo': u'0dc1796b325ae7e85b1dca228885a3417f39097a', u'baseUrl': u'https://liquidstate.atlassian.net', u'buildNumber': 65000, u'version': u'6.5-OD-01-120'}

And under version 2.6.1:
Reading as JSON
Failed to load JSON, reading as Gzip
Reading as Gzip
{u'versionNumbers': [6, 5, 0], u'serverTitle': u'JIRA', u'buildDate': u'2015-04-08T00:00:00.000+1000', u'scmInfo': u'0dc1796b325ae7e85b1dca228885a3417f39097a', u'baseUrl': u'https://liquidstate.atlassian.net', u'buildNumber': 65000, u'version': u'6.5-OD-01-120'}

**Comment by Lukasa** [comment]
Thanks for this!

This is actually a regression in urllib3, so I've raised an issue there (shazow/urllib3#593). We'll fix it up and release a fix shortly. =)

**Comment by emil79** [comment]
This is likely to be an issue for many people. Thanks for fixing!

**Comment by tombech** [comment]
Was broken for us as well this morning (used by our product's CI tests), workaround was to revert to 2.6.0. Thanks for prompt fixing!

**Comment by JonathonReinhart** [comment]
:+1: GitHub really needs a silent +1 button, so people can acknowledge that we've seen a bug, without polluting the comment space.

**Comment by sigmavirus24** [comment]
@JonathonReinhart no joke. Feel free to [Contact](https://github.com/contact) them though and tell them that. I know I have in the past and the more people who ask for it, the better our chances of getting it (I would hope).

**Comment by sigmavirus24** [comment]
I just released 2.6.2 to PyPI with the fix for this issue. Please upgrade as appropriate.

**Comment by elsimir** [comment]
Thanks for the quick fix!
