### ISSUE TITLE
Merge with requesocks

### ISSUE THREAD

**Issue by ikus060** [kennethreitz/requests#2562]
Any plan to merge modification made to requests to support SOCKS proxy ?

See https://github.com/dvska/requesocks

**Comment by sigmavirus24** [comment]
It doesn't seem likely that we'll merge with requesocks as that hasn't been updated in over 2 years. Also that author never propsed a merge on their own.

**Comment by ikus060** [comment]
May I propose to add this feature to requests ?

**Comment by Lukasa** [comment]
@ikus060 Many people have proposed it and even begun work: see #2425, #2156, #1982, shazow/urllib3#486, shazow/urllib3#284, shazow/urllib3#68, and shazow/urllib3#44.

You are welcome to attempt to do the work. The initial implementation should be over in urllib3: I recommend that you start work there.

If you were simply _requesting_ the feature, the core team does not believe it's an important enough priority to justify our development time. In practice, the absence of SOCKS support does not appear to be limiting the success of the library. For that reason, unless someone does the work for the implementation themselves, I do not believe we'll be implementing it ourselves.
