### ISSUE TITLE
Specify local port

### ISSUE THREAD

**Issue by vishalwy** [kennethreitz/requests#2563]
How do I specify the local port for the socket rather than picking up a random free port?

**Comment by Lukasa** [comment]
You can do this using the [requests toolbelt](https://toolbelt.readthedocs.org/en/latest/). Get it by running `pip install requests-toolbelt`.

``` python
>>> import requests
>>> from requests_toolbelt.adapters.source import SourceAddressAdapter
>>> s = requests.Session()
>>> s.mount('https://google.com', SourceAddressAdapter(('', 6666)))
```
