### ISSUE TITLE
Keep-alive broken in 2.6.1 and 2.6.2 with chunked transfer-encoding

### ISSUE THREAD

**Issue by lmikkelsen** [kennethreitz/requests#2568]
Starting in 2.6.1 an exception is thrown if a connection with chunked transfer-encoding is reused. I suspect that the bug is in the bundled urllib3 which was upgraded from 1.10.2 to 1.10.3.

```python
#!/usr/bin/env python
import requests
s = requests.Session()
r = s.get('http://httpbin.org/stream/1')
r.json()
r = s.get('http://httpbin.org/stream/1')
r.json()
```

```
$ ./test.py
Traceback (most recent call last):
  File "./test.py", line 10, in <module>
    r = s.get('http://httpbin.org/stream/1')
  File "[...]/requests/requests/sessions.py", line 477, in get
    return self.request('GET', url, **kwargs)
  File "[...]/requests/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "[...]/requests/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "[...]/requests/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ResponseNotReady())
```

**Comment by Lukasa** [comment]
> I suspect that the bug is in the bundled urllib3 which was upgraded from 1.10.2 to 1.10.3.

As do I: can you open this bug over there, please? We'll fix it in that repository.

**Comment by sigmavirus24** [comment]
We should start preparing requests 2.7.0 with the fix for shazow/urllib3#598

**Comment by rfortress** [comment]
Is there any workaround for this? I've gone back to 2.6.0 for now.

**Comment by Lukasa** [comment]
@rfortress I'm afraid not. We're working on this, there are a number of other problems with the chunked change and we'd like to land them at all once if we possibly can.

I'm genuinely sorry for how long this is taking. =(

**Comment by ne0ark** [comment]
Version 2.5.1 is latest version now? Isn't this version affected by: http://www.cve.mitre.org/cgi-bin/cvename.cgi?name=2015-2296

**Comment by EugeneDae** [comment]
The latest and affected by the bug in question, is 2.6.2. The latest that is **not** affected by the bug in question, seems to be 2.6.0 -- and it works well for me.

**Comment by Lukasa** [comment]
Correct, 2.6.0 is the version to use to avoid this bug.

**Comment by Lukasa** [comment]
I have just cut requests 2.7.0, which I believe resolves this problem (and several related ones). Thank you all for your patience!
