### ISSUE TITLE
[Proposal] New Release Management Process

### ISSUE THREAD

**Issue by sigmavirus24** [kennethreitz/requests#2569]
In v2.6.1 we pulled in a new copy of urllib3. Typically this doesn't negatively affect us but in this case we've seen a bunch of new issues from the chunked encoding refactor in urllib3. Because that kind of stuff *should* not break in a `.x` release I'm proposing we follow this process when preparing releases (and that we document it for the future):

For an `v*.*.x` release, e.g., `v2.6.1`, `v2.6.2`, `v2.6.3`, etc. we *only* include changes to requests itself. This means anything that does not live in `requests/packages/{urllib3,chardet}/*`.

For a `v*.x.0` release, e.g., `v2.6.0`, `v2.7.0`, etc. we include changes to requests *and* update the vendored libraries. The same goes for a `vx.0.0` release, but of course those have other implications as well.

**Comment by Lukasa** [comment]
+1. Write it down in the docs, let's make it so.

**Comment by sigmavirus24** [comment]
:cake: Will do tonight or tomorrow morning
