### ISSUE TITLE
Custom auth handler not called on redirect

### ISSUE THREAD

**Issue by cefolger** [kennethreitz/requests#2577]
Hi, 

I have a custom auth handler, and my problem is that if the service returns a 302 the handler needs to be re-run to generate auth headers for the request to the new url.

Right now I'm setting allow_redirects=False and handling this manually, but can this be done by requests instead?

**Comment by sigmavirus24** [comment]
So auth handlers tend to register themselves as `response` hooks which are called every time [`send`](https://github.com/kennethreitz/requests/blob/master/requests/sessions.py#L579) is called. And that's also called when [requests handles redirects](https://github.com/kennethreitz/requests/blob/master/requests/sessions.py#L188).

That said, without more details about your auth handler, I have no clue how to help you.
