### ISSUE TITLE
Can't post BytesIO file-like object

### ISSUE THREAD

**Issue by JetForMe** [kennethreitz/requests#2589]
Hi. I'm trying to zip a directory in memory and then POST that to a server. Unfortunately, I don't seem to be able to use the BytesIO object to which the zip data is written. Instead, I have to get the bytes from it. But the docs seem to indicate I can provide either bytes or a file-like object in the tuple.

Here's a condensed version of the code:

```
zipData = io.BytesIO();
with zipfile.ZipFile(zipData, mode="w") as zf:
	zf.write(<some content>)

url = "https://some.host/api/upload"

files = { "ipa" : open(ipaPath, "rb") }
#files["dsym"] = (zipName, zipData)				# file-like object doesn't work?
files["dsym"] = (zipName, zipData.getvalue())	# works
r = requests.post(url, files=files)
```

It may well be user error; if so, sorry for the noise.

**Comment by sigmavirus24** [comment]
So try this on for size:

``` py
zipData = io.BytesIO();
with zipfile.ZipFile(zipData, mode="w") as zf:
    zf.write(<some content>)

zipData.seek(0, 0)
url = "https://some.host/api/upload"

files = { "ipa" : open(ipaPath, "rb") }
#files["dsym"] = (zipName, zipData)             # file-like object doesn't work?
files["dsym"] = (zipName, zipData.getvalue())   # works
r = requests.post(url, files=files)
```

The problem is that the `BytesIO` object moves the position when you write to it. If you do

``` py
fp = io.BytesIO()
fp.write(b'some data')
assert fp.read() == b''
fp.seek(0, 0)
assert fp.read() == fp.getvalue()
```

Cheers!

**Comment by JetForMe** [comment]
Yep! That was it! Totally explains what I was seeing, too (empty content). Thank you.

**Comment by sigmavirus24** [comment]
Happy to help!

**Comment by doogle-oss** [comment]
Perfect Answer. Always worked with files when we open default point is at start in case of write to streams we have to explicitly put the pointer back at start of the object. Saved my day thanks for the explanation.
