### ISSUE TITLE
Redundancy when requesting URLs

### ISSUE THREAD

**Issue by cornelinux** [kennethreitz/requests#2592]
This is just a question I'd like to mark as feature request.

Is it ever planned to provide some kind of redundancy - i.e. add a list or URLs to the Request Object and the Request Object would try to fetch the next URL, if the first one timed out.
This might be interesting if requesting web APIs, where redundancy is not provided by the service.

Just tell if this is a bad idea.

**Comment by Lukasa** [comment]
Thanks for the feature request @cornelinux!

This seems like the kind of thing that could easily be built on top of requests. =) If a `Session` object is used, it shouldn't be hard to write a little wrapper around it that does exactly that.

However, I don't think we'll be adding this feature to requests core, as we're in an indefinitely feature freeze. Sorry!
