### ISSUE TITLE
colon in get params is double encoded

### ISSUE THREAD

**Issue by makoshark** [kennethreitz/requests#2596]
Thanks for maintaining requests! I love it!

If a parameters in <code>params</code> passed to <code>get()</code> includes a colon (as is required for categories in the MediaWiki AP, for exampleI) requests double encodes it. Here's some example code:

    import requests    
    parameters = {'action' : 'query',
                  'list' : 'categorymembers',
                  'format' : 'json',
                  'cmtitle' : 'Category:London'}
    r = requests.get('http://wikivoyage.org/w/api.php', params=parameters)
    print(r.url)

This returns a double escaped colon as <code>http://en.wikivoyage.org/w/api.php?action=query&cmtitle=Category%253ALondon&list=categorymembers&format=json</code>.

A working URL would be: <code>http://en.wikivoyage.org/w/api.php?action=query&cmtitle=Category%3ALondon&list=categorymembers&format=json</code> or even the unescaped <code>http://en.wikivoyage.org/w/api.php?action=query&cmtitle=Category:London&list=categorymembers&format=json</code>, both of which work fine.

Shouldn't a colon in a parameter only be escaped once as "<code>%3A</code>"? Composing the URL and passing it directly in seems to work just fine.

**Comment by Lukasa** [comment]
Requests does not double encode the colon. =)

What you don't see in that code is that you've been redirected. That URL is actually where you ended up after a chain of redirects. If you look for the _first_ request in the chain, you'll see the correct URL:

``` python
>>> r.history[0].url
u'http://wikivoyage.org/w/api.php?action=query&cmtitle=Category%3ALondon&list=categorymembers&format=json'
```

**Comment by makoshark** [comment]
Got it! Thanks for the incredibly quick response and resolution! The URL seems to also be correct in the second step in the chain.

Is this a bug in the redirect code that WikiVoyage is using or is this an unavoidable side effect of relying on the 301s? This is simple enough to fix on my end but I'm wondering if I should file a ticket with the Wikimedia Foundation.

**Comment by Lukasa** [comment]
I think the bug is with WikiVoyage, it seems to be incorrectly parsing the URLs. The bug is not in the first redirect (from wikivoyage.org to www.wikivoyage.org), but in the second redirect (from www.wikivoyage.org to en.wikivoyage.org). You can therefore probably avoid the bug in your own code by going straight there, and then file a bug with whomever is managing that code to check why it mishandles URL escaping.

**Comment by makoshark** [comment]
Thanks! I had already fixed the bug by avoiding the redirects but I wanted to let Wikimedia (who run WikiVoyage) about the issue so that others who make the same mistake don't run into the issue.

Thanks again for your help!
