### ISSUE TITLE
Auth handler should be calling close, not release_conn

### ISSUE THREAD

**Issue by sigmavirus24** [kennethreitz/requests#2599]
On [this line](https://github.com/kennethreitz/requests/blob/956ec8321a76f0b5a9f5bcb591cf6e77d773f819/requests/auth.py#L182) we should be using the response's "close" method. We shouldn't be explicitly calling a method on the "raw" attribute.

**Comment by Lukasa** [comment]
Resolved in #2601.

**Comment by sahutd** [comment]
Should I add a test to ensure close gets called?
Would using a mock object be the right way?
