### ISSUE TITLE
[Bug?]  json.dumps(json)?

### ISSUE THREAD

**Issue by maxdandan** [kennethreitz/requests#2611]
download from https://pypi.python.org/pypi/requests/2.7.0
models.py
line 418
bug?

**Comment by sigmavirus24** [comment]
Do you mean https://github.com/kennethreitz/requests/blob/b7bd29734022e634634d908e10bbf7a5ac15e76b/requests/models.py#L428 ? If so, no.

**Comment by maxdandan** [comment]
Yes,“json_dump” is True
But in  kennethreitz-requests-v2.7.0-8-g4505f71.zip   there is   “json.dumps”
Fixed right now
Tks :)

**Comment by sigmavirus24** [comment]
There is no such file on PyPI. If you're downloading files from GitHub, I'd advise you not to.
