### ISSUE TITLE
get url redirect hangs in requests

### ISSUE THREAD

**Issue by gengjiawen** [kennethreitz/requests#2618]
I am trying to handle url redirect using requests,but it hangs.The original python lib works as expected.Below is the code(**Python 3**).
```python
import urllib.request
import requests

url = "http://go.microsoft.com/fwlink/p/?LinkId=522148"
final_url = urllib.request.urlopen(url)
print(final_url.geturl())

r = requests.get(url)
print(r.url)
```

**Comment by gengjiawen** [comment]
The code below also works fine:

``` python
r = requests.head('http://github.com', allow_redirects=True)
print(r.url)
```

should I use **requests.head** over **requests.get** when handling url redirect?

**Comment by t-8ch** [comment]
@gengjiawen This URL redirects to a 4GB big ISO image. So the download takes a little bit.
You probably don't want to read this into memory anyways.
Try `requests.get(url, stream=True)` and then iterate over the content.

**Comment by gengjiawen** [comment]
@t-8ch Thanks, your solution also works.
