### ISSUE TITLE
Connect Error or Timeout Error

### ISSUE THREAD

**Issue by jongiddy** [kennethreitz/requests#2620]
At https://github.com/kennethreitz/requests/blob/8b5e457b756b2ab4c02473f7a42c2e0201ecc7e9/requests/models.py#L664 the urllib3 `ReadTimeoutError` gets mapped to a `requests.exceptions.ConnectionError`. It seems like the `requests.exceptions.ReadTimeout` would be a more obvious exception.

Is this just an oversight, or is there a reason for keeping it as `ConnectionError`?

**Comment by Lukasa** [comment]
Good spot! I think this is an oversight.

Unfortunately, changing the exception type is a backward incompatible change, because `ReadTimeoutError` does not inherit from `ConnectionError`. I think we should do it, but we can't do it until 3.0.0.

**Comment by jongiddy** [comment]
Sorry, just noticed this is a duplicate of https://github.com/kennethreitz/requests/issues/2392

**Comment by sigmavirus24** [comment]
Ah thanks @jongiddy. It's been long enough (over a year, wow) that I completely forgot that was open. Would you mind if we closed this since it's a duplicate?

**Comment by jongiddy** [comment]
No problem. I would have closed it myself, but wasn't sure how that affects the labels and milestone info.

**Comment by sigmavirus24** [comment]
It doesn't affect it. You're still welcome to do so yourself. I'll make a reminder to close it next week if it's still open

**Comment by jongiddy** [comment]
Closing as duplicate.
