### ISSUE TITLE
why implement requests.util.timeout.Timeout() instead of bsd socket options?

### ISSUE THREAD

**Issue by est** [kennethreitz/requests#2623]
In python's socket module, `socket.timeout` could be used as connect timeout, also `setsockopt` can be used with `SO_RCVTIMEO` and `SO_SNDTIMEO`. It there a reason to implement our own  `requests.util.timeout.Timeout` class instead?

**Comment by sigmavirus24** [comment]
Are you looking at the right project? https://github.com/kennethreitz/requests/blob/master/requests/utils.py

**Comment by Lukasa** [comment]
More generally, the answer is yes. `Timeout` is not special: it's just a wrapper over the timeout functions available in the socket module. The reason it was written into urllib3 (which is where I think you meant to say) is that it is useful to have an abstraction that is at the same layer as urllib3. Generally, passing things from the `socket` module into `urllib3` should be considered an expert-level action and only taken rarely: timing out requests is good practice, and should be done often.

**Comment by est** [comment]
Ah yes, I meant this file

https://github.com/kennethreitz/requests/blob/master/requests/packages/urllib3/util/timeout.py

Thanks for the explaination!
