### ISSUE TITLE
Use keep-alive / streaming while processing

### ISSUE THREAD

**Issue by kvarga** [kennethreitz/requests#2624]
Is there a way to send intermittent responses to client to avoid timeout for long-running tasks (~2minutes) ? 

If not, I guess I will have to do the following flow: 

1. User requests a webpage
2. Check if that webpage is available in cache
3. If not, redirect them to a holding page that checks ~15 seconds if that request is ready
4. Load the response

Seems less than ideal, but gets the added benefit of showing some sort of progress indicator to the user.

**Comment by sigmavirus24** [comment]
@kvarga sorry, are you using the requests library? You seem to not be using it at all unless I'm misunderstanding your bug.

**Comment by kvarga** [comment]
Oops. I meant to post this to flask.

**Comment by sigmavirus24** [comment]
No worries! :8ball: says the flask maintainers will be more helpful.
