### ISSUE TITLE
Connection pool not recycling connections on timeout or connection exceptions

### ISSUE THREAD

**Issue by jlatherfold** [kennethreitz/requests#2629]
If preload_content is not specified on a request, connections are implicitly returned to the pool after the request is read. However, when a timeout error occurs or the connection is dropped the connection is closed but not returned in to the pool (since the response is None). This problem is compounded when retries are turned on since the next attempt will grab a new connection from the pool thus depleting it further. With non-blocking pools this is not a problem since we will create a new connection if the pool is empty but when the pool is blocking we have found that eventually the pool size becomes zero (after no.of connections timeout errors) which causes the calling application to hang on it's next request.
This can be fixed in connectionpool.urlopen in the exception handlers by explicitly returning the closed connection to the pool via _put_conn (if release_conn is false), since subsequent calls to _get_conn will check if the connection has been dropped and return a new one.

**Comment by Lukasa** [comment]
This is a bug in [urllib3](https://github.com/shazow/urllib3): can you please open it there?

**Comment by jlatherfold** [comment]
Thanks for the response. Yes I will do that.
