### ISSUE TITLE
Partial content and compression : decoding error

### ISSUE THREAD

**Issue by netheosgithub** [kennethreitz/requests#2632]
Be default requests generate http requests with 'Accept-Encoding: gzip, deflate' header.
If one want to GET only the last 5 bytes of a file, adding a Range: -5 header should do the trick. However, remote server may honor the Accept-Encoding and return the last 5 bytes of gzipped content (instead of the gzip of last 5 bytes as one may think).
This is the difference between Accept-Encoding and transfer encoding 'TE' headers. 'Accept-Encoding: gzip' is for fetching the compressed entity, TE: gzip is for indicating to next proxy that we support a response with header 'Transfer-Encoding: gzip'. In both cases response body is compressed data ; however if Range header specifies partial content, the difference is *when* compression is achieved :
- before slicing for Accept-Encoding
- after slicing for TE
[however this is theoric, and not really supported by web servers and proxys]

In my case, the bytes received can not be decoded and urllib3 raises with error :
File ".../site-packages/requests/models.py", line 678, in generate
    raise ContentDecodingError(e)
requests.exceptions.ContentDecodingError: ('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing: incorrect header check',))

Error is probably in urllib3.

Some requests questions :
Is it possible to disable compression ?
Is it possible to get the raw gzipped response (without other decoding than chunked) ?

**Comment by Lukasa** [comment]
> Is it possible to disable compression ?

Yes. Set `headers={'Accept-Encoding': None}`.

> Is it possible to get the raw gzipped response (without other decoding than chunked) ?

Yes. If you set `stream=True`, you can then call `response.raw.read(decode_content=False)`

**Comment by sigmavirus24** [comment]
In the future, please ask questions on [StackOverflow](https://stackoverflow.com/questions/tagged/python-requests).
