### ISSUE TITLE
Does requests support url anchor

### ISSUE THREAD

**Issue by kaizengliu** [kennethreitz/requests#2633]
Can the url  containing both parameters and anchor, like http://xx.com?a=1&&b=2#here

**Comment by Lukasa** [comment]
It absolutely can, but you have to build the URL yourself. If you ask requests to encode the parameters for you (using params) then we'll throw the anchor away.

It seems like a reasonable request to keep hold of that anchor: @sigmavirus24?

**Comment by sigmavirus24** [comment]
I'm confused about what's being discussed:

``` py
>>> req = requests.Request(method='GET', url='http://xx.com?a=1&&b=2#here')
>>> p = req.prepare()
>>> p.url
'http://xx.com/?a=1&&b=2#here'
```

Indicates that the URL is not affected. Are we talking about something like:

``` py
requests.get('http://xx.com', params='a=1&&b=2#here')
```

That shouldn't work because we expect params to be a dictionary

``` py
requests.get('http://xx.com', params={'a': '1', 'b': '2#here'})
```

In this case, we'd have to do a lot of pre-processing on the params to make sure the value with `#here` is at the end and not encoded... which may not be what people want.

But I'm probably completely missing the point.

**Comment by Lukasa** [comment]
The thing you _might_ expect to work is this:

``` python
requests.get('http://hostname/path#fragment', params={'param': 'value'})
```

That does not work.

All the other things function correctly.

**Comment by sigmavirus24** [comment]
Yeah, I'm confused:

``` py
>>> import requests
>>> r = requests.Request(method='GET', url='http://example.com/foo#bar', params={'a': 'b'})
>>> p = r.prepare()
>>> p
<PreparedRequest [GET]>
>>> p.url
'http://example.com/foo?a=b#bar'
>>> r = requests.get('https://httpbin.org/get#fragment', params={'a': 'b'})
>>> r.json()
{u'origin': u'127.0.0.1', u'headers': {u'Host': u'httpbin.org', u'Accept-Encoding': u'gzip, deflate', u'Accept': u'*/*', u'User-Agent': u'python-requests/2.7.0 CPython/2.7.9 Darwin/14.1.0'}, u'args': {u'a': u'b'}, u'url': u'https://httpbin.org/get?a=b'}
>>> r.url
u'https://httpbin.org/get?a=b#fragment'
```

**Comment by Lukasa** [comment]
Ah crap, I'm an idiot. I looked at the JSON response, forgetting that the fragment doesn't get transmitted to the server. Duh.

This all works totally fine!

**Comment by sigmavirus24** [comment]
@kaizengliu Please do not use the _bug_ tracker to ask questions. Our question forum is located [here](https://stackoverflow.com/questions/tagged/python-requests).

**Comment by kaizengliu** [comment]
I got it.  It can work in the way like this

```
requests.Request(method='GET', url='http://example.com/foo#bar', params={'a': 'b'})
```

Thank you very much. And I am sorry,  I will ask question in [here](https://stackoverflow.com/questions/tagged/python-requests)
