### ISSUE TITLE
Handle upgrade to WebSocket (Feature Request)

### ISSUE THREAD

**Issue by marians** [kennethreitz/requests#2634]
it would be awesome if there was a way to handle the response for a request that upgrades to a websocket connection, for example:

```python
url = "https://host.domain.com/mypath"
headers = {
    "Authorization": "myrealm <my-auth-token>",
    "Connection": "upgrade",
    "Upgrade": "websocket",
    "Sec-Websocket-version": "13",
    "Sec-Websocket-key": "<some-challenge-key>",
}
payload = {
    "some_key": ['some', 'values']
}
def handler(message):
    print(message)
response = requests.post(url, headers=headers, json=payload, websocket_callback=handler)
```

**Comment by Lukasa** [comment]
I'm afraid that we're extremely unlikely to add support for this at the requests level in this form. What you'd have to do is use `stream=True` and then grab the socket out of the response object at a very low level.

**Comment by sigmavirus24** [comment]
I have to agree with @Lukasa. This is not on the roadmap for future versions of requests at this point.

**Comment by marians** [comment]
All right, fair enough.
