### ISSUE TITLE
Same HTTPConnection object returned to pool twice

### ISSUE THREAD

**Issue by gilesbrown** [kennethreitz/requests#2636]
Not totally sure how to reproduce this yet but I am definitely getting a case where I am getting the "Connection pool is full" message because the same connection object is being returned to the pool twice  (and not surprisingly the second time the pool says that it is full).

I am using gevent (yes I realize that is probably crucial), but even so ...

The first time the connection gets returned is in requests.adapters:

410                 else:
411                     # All is well, return the connection to the pool.
412                     conn._put_conn(low_conn)

The second time the connection gets returned is in requests.packages.urllib3.response:

285         finally:
286             if self._original_response and self._original_response.isclosed():
287                 self.release_conn()

I'd love to  be able to supply a simple example, but the code path is a little to convoluted for me to work out quickly so I'm looking for hints/tips here if you have any.

Thanks,
Giles

**Comment by sigmavirus24** [comment]
I've seen this and wasn't able to come up with a simple case to reproduce it. /cc @shazow since we discussed it

**Comment by shazow** [comment]
Maybe we need a mutex around our release_conn() innards.

**Comment by gilesbrown** [comment]
Actually it turns out that the bug is super easy to reproduce.

https://gist.github.com/gilesbrown/3832fc29100213171968

It doesn't require gevent, all it requires is doing a chunked PUT (or POST etc).

**Comment by Lukasa** [comment]
Interesting. This line of code looks fishy to me:

``` python
# All is well, return the connection to the pool.
conn._put_conn(low_conn)
```

We do that internally, despite having set `preload_content=False`. We may well then consume the content elsewhere.

I think that's just wrong, really, and it opens us up to bugs.

**Comment by Lukasa** [comment]
And, quite expectedly, commenting out that block causes everything to function properly. I just think that's wrong.

**Comment by Lukasa** [comment]
It should be noted that [I was the idiot](https://github.com/kennethreitz/requests/commit/31c0962e83c8f3b043b3faceff880f69a9a4dbdc) who put that release in the code in the first place, nearly two years ago. Past me is a jerk. =P

**Comment by shazow** [comment]
@Lukasa I did always like future-you better than past-you.

**Comment by gilesbrown** [comment]
Well it's good that you're able to fix your fishy past so easily.
