### ISSUE TITLE
deflate failure on google appengine above requests 2.3.0

### ISSUE THREAD

**Issue by tarvitz** [kennethreitz/requests#2643]
if response was given with deflate,gzip or just deflate (Content-Encoding: "gzip, deflate") then requests on google appengine would failure this line
packages/urllib3/response.py:440
```python
if self._original_response and self._original_response._method.upper() == 'HEAD':
```

It happens because self._original_response is replaced by google sdk and has different format from inner Response class objects.
gae:

```python
<google.appengine.dist27.gae_override.httplib.HTTPResponse instance at 0x7f66f51cbf80>
```
origin:

```python
<httplib.HTTPResponse instance at 0x7f59742b0638>
```
Though original_response._method is not str (it's actually int).

This breaks content deflating e.g. requests will process request normally but response.content would contain binary (compressed) data.

Tested on 2.7.0 branch. 2.3.0 works well.

**Comment by Lukasa** [comment]
Sorry, this is a bug in [urllib3](https://github.com/shazow/urllib3), do you mind opening an issue for it on that repository?

**Comment by sigmavirus24** [comment]
This should be fixed when https://github.com/shazow/urllib3/pull/620 is merged and we pull it in for a new release.

**Comment by tarvitz** [comment]
np, thanks for advance :)
