### ISSUE TITLE
incorrect status_code

### ISSUE THREAD

**Issue by jincept** [kennethreitz/requests#2644]
import requests
import time
import random

url = 'http://myserver.com'

n = 0

while(True):
    resp = requests.get(url)
    now=time.time()
    n += 1
    print(n, resp, resp.status_code, time.ctime(now))
    print(resp.headers)
    r=random.randint(1,5)
    time.sleep(r)
    print('\t\t\t slept',r, 'seconds')

===========

Output:

1 <Response [200]> 200 Thu Jun 18 23:15:57 2015
{'pragma': 'no-cache', 'set-cookie': 'OutlookSession=d2b7de620d414931b8100369275493d4; path=/; secure; HttpOnly', 'expires': '-1', 'x-owa-version': '14.3.181.6', 'x-powered-by': 'ASP.NET', 'date': 'Fri, 19 Jun 2015 06:15:56 GMT', 'content-type': 'text/html; charset=utf-8', 'vary': 'Accept-Encoding', 'content-encoding': 'gzip', 'content-length': '3251', 'cache-control': 'no-cache, no-store'}
			 slept 5 seconds
2 <Response [200]> 200 Thu Jun 18 23:16:02 2015
{'pragma': 'no-cache', 'set-cookie': 'OutlookSession=9093d72589364d9894173a5ed0475a45; path=/; secure; HttpOnly', 'expires': '-1', 'x-owa-version': '14.3.181.6', 'x-powered-by': 'ASP.NET', 'date': 'Fri, 19 Jun 2015 06:16:01 GMT', 'content-type': 'text/html; charset=utf-8', 'vary': 'Accept-Encoding', 'content-encoding': 'gzip', 'content-length': '3251', 'cache-control': 'no-cache, no-store'}
.....

============
While actual response code is 300 as seen in wireshark capture:
HTTP/1.1 302 Object Moved\r\n

**Comment by jincept** [comment]
￼
![screen shot 2015-06-18 at 11 21 48 pm](https://cloud.githubusercontent.com/assets/10746779/8248193/d4ae4228-1610-11e5-9b63-f84c66b703bb.png)

**Comment by Lukasa** [comment]
This is not a bug.

Requests will follow all redirects until the chain is complete. What has happened here is that you've been redirected from HTTP to HTTPS by the second 302, which means your wireshark filter does not show the next transaction. =)

If you print `resp.history` you'll see the full redirect chain we followed.
