### ISSUE TITLE
Documentation of verify parameter inconsistent with examples on stackoverflow

### ISSUE THREAD

**Issue by nmgeek** [kennethreitz/requests#2652]
requests is a very nice replacement for ugly code you would write using urllib and urllib2.  After converting my code to requests and testing extensively I found a glitch when packaging my code with pyinstaller (I guess the same thing happens with py2exe).  When connecting to https sites requests apparently depends upon a certificate file which is hard to find in the release tree.  (When you package python code with pyinstaller you must also package any required data files.)

Posted solutions to this problem show setting the 'verify' parameter for the post and get methods to the path to a cacert.pem file grabbed from the certifi python package.  I tried this solution and it works.  (I also tried the documented cert parameter pointing to a cert and key file pair used by my django server but that did not work.)  One such answer is at http://stackoverflow.com/questions/10667960/python-requests-throwing-up-sslerror

This demonstrates that the verify parameter has undocumented functionality:  it accepts more than the True and False values shown in the documentation.

Could you correct the documentation to document this functionality.  And hopefully you could explain the difference between setting a pem file with the verity parameter vs the cert parameter.

**Comment by t-8ch** [comment]
@nmgeek You may want to take a look at http://docs.python-requests.org/en/latest/user/advanced/#ssl-cert-verification where it is documented: 'You can pass verify the path to a CA_BUNDLE file with certificates of trusted CAs.'

This really could use an example though.

**Comment by Lukasa** [comment]
@t-8ch is right, this _is_ documented, just not very well. As to your point of `verify` vs `cert`, that's covered in the same section of the prose documentation that @t-8ch linked to.
