### ISSUE TITLE
utils.get_netrc_auth silently fails when netrc exists but fails to parse

### ISSUE THREAD

**Issue by dpursehouse** [kennethreitz/requests#2654]
My .netrc contains a line for the github auth, [like this](https://gist.github.com/wikimatze/9790374).

It turns out that `netrc.netrc()` doesn't like that:

```
>>> from netrc import netrc
>>> netrc()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/netrc.py", line 35, in __init__
    self._parse(file, fp, default_netrc)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/netrc.py", line 117, in _parse
    file, lexer.lineno)
netrc.NetrcParseError: bad follower token 'protocol' (/Users/david/.netrc, line 9)
```

`get_netrc_auth` catches the `NetrcParseError` [but just ignores it](https://github.com/kennethreitz/requests/blob/master/requests/utils.py#L106).

At least having it emit a warning would have saved some hair-pulling.

**Comment by Lukasa** [comment]
Yeah, this is tricky. You can see the reason we added this logic in #449.

Given that you're using the function explicitly, maybe the best option is to add a kwarg to `get_netrc_auth` that allows it to be used in an explodey way (when users like yourself want to be explicit), but that allows us to continue to use it in a not-explodey way.

**Comment by sigmavirus24** [comment]
Because this can be done in a backwards compatible way, I've tagged this optimistically for 2.8.0
