### ISSUE TITLE
HTTPAdapter timeout type error

### ISSUE THREAD

**Issue by gbishop** [kennethreitz/requests#2660]
At https://github.com/kennethreitz/requests/blob/master/requests/adapters.py#L378 you call

conn._get_conn(timeout=timeout)

The timeout object you pass is a Timeout but that internal method in urllib3 expects a float. This results in a type error about float + Timeout. 

A float works there but I wasn't sure which to use.

**Comment by Lukasa** [comment]
Yeah, I think I spotted this before. I have no idea why we never fixed it, but it's definitely a bug.

**Comment by gbishop** [comment]
I found it while chasing the Connection pool is full warning on chunked
posts. No parameter settings to HTTPAdaptor seem to help.

**Comment by Lukasa** [comment]
See #2661 for what I think is a fix for this.

**Comment by gbishop** [comment]
Yes, that is equivalent to my hacked test.

**Comment by Lukasa** [comment]
Fixed. =) Thanks @gbishop!
