### ISSUE TITLE
cookiejar_from_dict support SimpleCookie

### ISSUE THREAD

**Issue by spumer** [kennethreitz/requests#2665]
Hi there! :)

I have a suggestion about support `http.cookies.SimpleCookie` by `requests.cookies.cookiejar_from_dict`.

Example:
```python
import http.cookies

import requests
import requests.cookies

cookie_str = 'Key1=Value1;Key2=Value2'  # e.g can be obtain from cfg
cookie = http.cookies.SimpleCookie(cookie_str)

sess = requests.session()
sess.cookies = requests.cookies.cookiejar_from_dict(cookie)

```

`SimpleCookie` have mapping interface and `RequestsCookieJar` can assign cookie with `Morsel` value, but `cookiejar_from_dict` don't do this right now.

I thinking about that fixup, because `RequestsCookieJar` just extension of common `CookieJar`:
```python
cookiejar.set_cookie(create_cookie(name, cookie_dict[name]))
->
RequestsCookieJar.set(cookiejar, name, cookie_dict[name])
```

But method name is strongly say us `from_dict`, SimpleCookie not a dict, just mapping. May be we need new method. I don't know. What do you think?

**Comment by Lukasa** [comment]
Have you tested your example code? It works fine for me...

**Comment by spumer** [comment]
Yes, of course! Code works fine before you send first request. See the picture.
If you need I can send full report (.html doc) (rendered by mako lib).

On the screen you see Python\lib\http\cookiejar.py : 1289
![report_part](https://cloud.githubusercontent.com/assets/735150/8637499/2700ca06-28ad-11e5-8317-812696ffcfdd.PNG)

**Comment by Lukasa** [comment]
In which case, it's not clear to me what the bug is. Given that `cookiejar_from_dict` works fine with `SimpleCookie`, what problem do we have?

**Comment by spumer** [comment]
`SimpleCookie` handle thier values as `Morsel` object, and when we pass `SimpleCookie` object to cookiejar_from_dict, value write without "unpacking".

**Comment by spumer** [comment]
I think this is not a bug, i just want to do a enchancment request. I suggest my solution, but i think this is not clear enough.

**Comment by Lukasa** [comment]
Aha, ok, good. =) Now we have a problem.

However, I think this is a sufficiently simple problem that it doesn't warrant a helper method in requests. It's two lines of code to get the behaviour you want:

``` python
for item in cookie.items():
    sess.cookies.set(*item)
```

**Comment by spumer** [comment]
Ou! You are right :+1: Thanks

**Comment by Lukasa** [comment]
Glad I could help! :cake: :sparkles:
