### ISSUE TITLE
Low-level exceptions leaking from Response.iter_content()

### ISSUE THREAD

**Issue by jmoldow** [kennethreitz/requests#2673]
Up through v2.6.0, ``Response.iter_content()``would catch all expected exceptions coming from ``self.raw.stream()``, and wrap them in instances of various subclasses of ``RequestException``.

In v2.6.1, urllib3 was updated to 1.10.3, which has issue https://github.com/shazow/urllib3/issues/673 that causes ``self.raw.stream()`` to raise low-level ``httplib.HTTPException``s, particularly ``httplib.IncompleteRead``. Because of this, as of v2.6.1 of requests, ``Response.iter_content()`` leaks these low-level of exceptions, instead of catching them and wrapping them in ``RequestException`` instances.

Issue https://github.com/shazow/urllib3/issues/673 has been fixed in master, but hasn't been released yet.

To fix this, requests could catch ``httplib.HTTPException`` along with ``urllib3.exceptions.ProtocolError``, converting both into ``ChunkedEncodingError``. Or requests can upgrade to the newest version of urllib3 when it is released.

**Comment by Lukasa** [comment]
Requests will upgrade to the newest version of urllib3 when it is released. =)

Thanks for the report!
