### ISSUE TITLE
can't use proxy-authorization in header 

### ISSUE THREAD

**Issue by matthew-summers** [kennethreitz/requests#2677]
hi, i try to use Proxy-Authorization header with my request, but it doesn't appear in request headers. If i change header name to 'Proxy-Authorization1', for example, everything is ok, i can see it in output. 

```python
proxy = {'http': 'http://ip:port/'}
token = base64.encodestring('user:pass').strip()
headers = {'Proxy-Authorization': 'Basic ' + token, 'Proxy-Connection': 'Keep-Alive', 'Accept': '*/*'}

r = requests.get('http://url', headers=headers, proxies=proxy) 
```

the reason why i'm trying to do this - with authentication like 'http://user:pass@ip.port' or via HTTPBasicAuth request fails with 407 Authentication Required

so, is there a way to explicitly define Proxy-Authorization header ?

**Comment by Lukasa** [comment]
Well, in the sample code above you aren't actually telling requests which proxy to talk to. =)

This is easiest to do by using the username and password in the proxy URL, and then not providing the header at all:

``` python
proxy = {'http': 'http://user:pass@ip:port/'}
r = requests.get('http://url', proxies=proxy) 
```

**Comment by matthew-summers** [comment]
yep, tried this way, but proxies were still returning 407. however, now everything is ok again, i begin to suspect this is proxy's issue.
