### ISSUE TITLE
implement delayed retry support to failed requests

### ISSUE THREAD

**Issue by ssbarnea** [kennethreitz/requests#2682]
Currently requests library supports a retry mechanism where you can specify how many retries to make untill it will fail, which is great unless you have a downtime of the service of only few seconds.

In order to make usage of requests more resilient to temporary errors we need an option to delay further retries, preferably using a fibonacci-like increase delay on sequential  retries.

Example, `start_delay=5` seconds and `max_retries=10`, would use these delays: 5, 10, 15, 25, 40, 65, 105, ...

I observed that lots of people are encountering the same issue and I do think that is much better to have this as part of requests and not having to hack our own httpadaptor to implement it. 

I would go so far to say that I would even argue for having it enabled by default, when max_retries is specified.

**Comment by Lukasa** [comment]
Thanks for the suggestion!

The supported way to do this in requests is to use a HTTP adapter. I notice you've spotted this but consider it to be a 'hack'. It's not: the requests project considers the HTTP adapter a first-class part of our interface.

The change is very simple:

``` python
from requests.adapters import HTTPAdapter
from requests.packages.urllib3.util.retry import Retry

class RetryAdapter(HTTPAdapter):
    def __init__(self, *args, **kwargs):
        super(RetryAdapter, self).__init__(*args, **kwargs)
        self.max_retries = Retry(total=self.max_retries, backoff_factor=5)

s = requests.Session()
s.mount('http://', RetryAdapter())
s.mount('https://', RetryAdapter())
```

This is a very simple adapter and could easily be dropped in. We may even want to add it to the requests-toolbelt: a pull request there would be very welcome. (/cc @sigmavirus24)

Thanks for the suggestion!
