### ISSUE TITLE
[Request] Simple argument to set an overall timeout for the request

### ISSUE THREAD

**Issue by SpokeNode** [kennethreitz/requests#2685]
The `timeout` parameter is useful but does not provide a way to set an overall timeout for the request.

But in keeping with *simple is beautiful*, it would be terrific if we could do:
`requests.get(url, overall_timeout=10)`

Thanks in advance for considering it. :)

**Comment by boolbag** [comment]
As a workaround, the `@stopit.threading_timeoutable` seems to work.
