### ISSUE TITLE
convert requests command

### ISSUE THREAD

**Issue by a4fr** [kennethreitz/requests#2689]
I'm using `requests` module in my app but when i run it in google app engine, raise **SSL Connection** exception:
```
File "/base/data/home/apps/s~myapp/1.385939809966824449/lib/requests/adapters.py", line 429, in send
    raise SSLError(e, request=request)
SSLError: Can't connect to HTTPS URL because the SSL module is not available.
```

I google this problem and read some answers that said SSL module is not in *GAE while list*.
I can send a simple GET request with `urllib`. It was ok.
What is equivalent of `requests.request('GET', request_url, params=params, files=files)` in `urllib`?

**Comment by Lukasa** [comment]
Requests does not consider Google App Engine a supported platform at this time, so I'm afraid we can't help you here. I recommend asking your question on StackOverflow. =) Sorry!
