### ISSUE TITLE
how to prepare response object 

### ISSUE THREAD

**Issue by aliraza0337** [kennethreitz/requests#2695]
Hi, I am requesting the http object using some other methode and want to cache them. The problem is the caching library uses the response object from request, is there any way that I can construct the reponse object if I have all the headers and response body of an http object?

**Comment by sigmavirus24** [comment]
The defect tracker is not the place to ask questions. Please use [StackOverflow](https://stackoverflow.com/questions/tagged/python-requests) for questions.
