### ISSUE TITLE
404 for timeouts advanced documentation links

### ISSUE THREAD

**Issue by nilya** [kennethreitz/requests#2698]
Three files [in this search](https://github.com/kennethreitz/requests/search?l=python&q=<user/advanced.html#timeouts>&type=Code&utf8=✓) has links to `<user/advanced.html#timeouts>` which works good for documentation generated on the local machine.
But on the http://docs.python-requests.org/ there is no ".html" in pages urls so 404 Page not found is returned.

I think docs.python-requests.org will be ok if you change links to `<user/advanced/#timeouts>` but local machine documentation will be broken.

**Comment by sigmavirus24** [comment]
We should be using `:ref:` in our docs, so sphinx will handle this for us. Thanks for catching this @nilya
