### ISSUE TITLE
Option to disable percent encoding disabled?

### ISSUE THREAD

**Issue by danhong** [kennethreitz/requests#2701]
Hi,

I know it's not good practice to disable percent encoding, but the server I'm connecting to doesn't support it. There seemed to be an option using requests.defaults in an earlier version, but it seems to be gone now. Is there any way to disable percent encoding? Thanks.

**Comment by sigmavirus24** [comment]
This has been discussed before in:
- https://github.com/kennethreitz/requests/pull/757
- https://github.com/kennethreitz/requests/issues/1454

And I'm sure other issues (but those are just the first two that a search of the issues found). Our current behaviour suits easily more than 95% of our users and thus it will stay. If you need to bypass (or change) how we encode the URL, the [PreparedRequest flow](http://docs.python-requests.org/en/latest/user/advanced/#prepared-requests) is what you need. For questions about that, please use [StackOverflow](https://stackoverflow.com/questions/tagged/python-requests).
