### ISSUE TITLE
Capitalize response reasons.

### ISSUE THREAD

**Issue by betolink** [kennethreitz/requests#2715]
This is a somewhat trivial thing, I ran into a "bug" while grouping responses by reason instead of status codes. This is of course a very particular case but just to be consistent it may be a good idea to have response.reason always be "NOT FOUND" instead of "Not Found", "Not found", "not found" etc.

**Comment by Lukasa** [comment]
Generally speaking, reason phrases are not to be trusted when provided by the server. There is no requirement that they be the same as the status code: nothing's really wrong with sending `200 NO PROBLEM BOSS`, for example, aside from the fact that the spec says you shouldn't.

For that reason, you should not rely on the reason phrase when making decisions unless the exact binary form of that phrase is something you care about. I don't think requests should canonicalise in any way here.

Thanks for the suggestion though!

**Comment by sigmavirus24** [comment]
+100 to what @Lukasa said. If you want normalized responses, you can use a mapping of status codes to whatever you'd like them to represent.

**Comment by betolink** [comment]
Note that I did not mention let's change `200 NO PROBLEM BOSS` to `200 OK` or vice-versa, the only proposed change is to capitalize whatever the reason coming from the server is just to avoid having to do it in an extra map().
