### ISSUE TITLE
Passing a list with size one to request.get transforms list into single element

### ISSUE THREAD

**Issue by bwdrop** [kennethreitz/requests#2718]
Hello,

I'm using Python 2.7.6 and requests (2.6.2).
When I try to send a GET request with this payload :
```python
{
  'event_parameter_2': datetime(2014, 3, 9, 6, 11, 35), 
  'event_parameter_3': [u'eligendi'], 
  'event_parameter_4': u'sc', 
}
```

The `event_parameter_3` field isn't a List type anymore, but a String type when my API gets the request.
This is how I send the GET request :
```python
r = requests.get('http://' + host + ':' + port + '/event/log', params=generate_event())
print r.url
```

Which gets me the following output :
```
http://127.0.0.1:3000?event_parameter_2=2014-03-09+06%3A11%3A35&event_parameter_3=eligendi&event_parameter_4=sc
```

However, when having a list with multiple elements, I have no problem and get the following output :
```
http://127.0.0.1:3000?event_parameter_2=2012-10-12+01%3A29%3A37&event_parameter_3=occaecati&event_parameter_3=possimus&event_parameter_4=gy
```

I think that maybe when sending lists in url requests, formatting the url as such might be better ?
```
http://127.0.0.1:3000?event_parameter_3[0]=occaecati&event_parameter_3[1]=possimus
```

Thank you :smile:

**Comment by Lukasa** [comment]
Thanks for this report!

Your summary is not quite accurate. The output that you are unhappy with in the first case is strictly formatted exactly the same as the output you _are_ happy with in the second case. The second case has multiple entries with the same name: the same number of entries as elements in the list. The first case also does: it just happens that there's only one element in the list.

You can see that if I break the sections out. Here is the two element case:

```
event_parameter_3=occaecati
&
event_parameter_3=possimus
```

Here's the one element case:

```
event_parameter_3=eligendi
```

This is exactly the same representation. =) We're being very consistent.

When sending lists in the URL there is no standard representation. The _most common_ representation is to have empty square brackets (`[]`), which you can do by doing `'event_parameter_3[]': [u'eligendi']`, but the reality is that there is no one right way to do this. Therefore, in the face of this ambiguity, we refuse to guess. You'll need to make sure the data is correct for whatever format your web service would like to receive.

Sorry we can't be more helpful!

**Comment by hlnlwj** [comment]
Thank you for your answer ! :)

What I actually meant was that when passing a single sized list:

```
event_parameter_3=eligendi
```

There is no way to know whether it was an list or any other type when receiving the request, a string being represented the same way:

```
event_parameter_4=sc
```

**Comment by Lukasa** [comment]
Indeed. This is the problem with query strings: they aren't really fully-structured data. They're just a list of key-value pairs. There are some _conventions_ around representing 'lists' and other kinds of data structures in query strings, but they are only conventions, there are no rules.

As I said, the closest there is to a 'standard' convention is to use square brackets after the key name: `event_parameter_3[]`.

**Comment by hlnlwj** [comment]
Oh, I didn't understand it this way !
Thank you very much ! :blush:
