### ISSUE TITLE
Connection reset by peer on get requests

### ISSUE THREAD

**Issue by mkates** [kennethreitz/requests#2726]
In making a request to a third party resource, https://www.henryscheinvet.com, I am getting the following traceback:

```python
import requests; requests.get('http://www.henryscheinvet.com')

Traceback (most recent call last):
 (......traceback.....)
  File "/Users/python3.4/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
```

For reference, I am on python 3.4.3, using requests 2.7.0, and running on Mac 10.9. What is very strange about this issue in particular is that the same call works if i run 'curl -i https://www.henryscheinvet.com' or if I access the URL using a browser. I believe it has something to do with the SSL handshake

**Comment by Lukasa** [comment]
Yeah, connection reset by peer means the remote peer doesn't like the TLS handshake much. It's difficult to know without tcpdumping what the problem is here. I don't see the problem on my end though: do you have PyOpenSSL installed?

**Comment by mkates** [comment]
It was an issue with the SSL certificate on their site, which has since been resolved. Thanks!
