### ISSUE TITLE
Add bitcoin donation info to README.rst

### ISSUE THREAD

**Issue by DoWhileGeek** [kennethreitz/requests#2727]
I would like to donate on a monthly basis, and I'm sure others do too. I'm not a particular fan of one time donations which you've recently added to the docs landing page.

I would however love to make small, monthly, bitcoin donations.

**Comment by smiley** [comment]
Looks like Requests already accepts (micro)donations [through Flattr](https://flattr.com/thing/442264/Requests), so you could use that for monthly donations. (But I'm not sure if you can manually set the amount you donate _specifically to requests_...)

**Comment by Lukasa** [comment]
This is a structural problem we need to work out in a way that is going to be most fair. I think the team need to sit down and discuss this a little bit at some point.

**Comment by kennethreitz** [comment]
`1Fov3RQFSDTxxGApR19g1GgQazzoutiGCC`
