### ISSUE TITLE
file:// protocol not available

### ISSUE THREAD

**Issue by Moliholy** [kennethreitz/requests#2732]
Hello all, and first of all thanks for this awesome library.

While working with requests I was surprised to find out that it doesn't handle the file:// protocol. Even though I understand it's maybe not a key feature of this library it would come in handy for compatibility reasons.

Concretely I have sort of a 'Fetcher' class that servers files from a 'Repository', but this repository can be local or remote. In case of being local I tried (unsuccessfully, of course) to use the file:// protocol. Finally it forced me to considerably increase the number of lines of code I needed to handle the issue.

For example, something like this would be fine:
```
response = requests.get('file:///Users/User/my_file.txt')
```

So far it raises this exception:
```
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 649, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
requests.exceptions.InvalidSchema: No connection adapters were found for 'file:///Users/User/my_file.txt'
```

My questions are: 
1) Would there be a reason to not to implement this feature?
2) In case there isn't, shall I submit a a pull request, or it is already planned to add this functionality soon?

**Comment by Lukasa** [comment]
Thanks for this issue!

The reason we don't support the `file://` protocol is because requests is a HTTP library. Our core purpose is to do HTTP: anything else is outside the scope of the core library.

I believe there is a pluggable Transport Adapter for the file protocol floating around. You can also consider adapting one from [this answer](http://stackoverflow.com/a/22989322).

**Comment by sigmavirus24** [comment]
Before opening issues, please search all issues (not just open ones) for similar issues. [This](https://github.com/kennethreitz/requests/issues/847) is just the earliest issue I could find and there are several others (including pull requests).
