### ISSUE TITLE
PyOpenSSL support doesn't work with TLSv1.1 and TLSv1.2

### ISSUE THREAD

**Issue by itamarst** [kennethreitz/requests#2734]
`docker-py` tries to use latest protocol version in the `ssl` module, so use `ssl.PROTOCOL_TLSv1_2`. Unfortunately the version of urllib3 included with requests (and likely upstream?) only has older versions:

https://github.com/kennethreitz/requests/blob/master/requests/packages/urllib3/contrib/pyopenssl.py#L71

**Comment by sigmavirus24** [comment]
So raise this issue against urllib3?
