### ISSUE TITLE
 params of  proxy_headers are  inconsistent with its docstrings

### ISSUE THREAD

**Issue by qingyunha** [kennethreitz/requests#2739]
requests/adapters.py

    def proxy_headers(self, proxy):
            """Returns a dictionary of the headers to add to any request sent
            through a proxy. This works with urllib3 magic to ensure that they are
            correctly sent to the proxy, rather than in a tunnelled request if
            CONNECT is being used.  

            This should not be called from user code, and is only exposed for use
            when subclassing the
            :class:`HTTPAdapter <requests.adapters.HTTPAdapter>`.

            :param proxies: The url of the proxy being used for this request.
            :param kwargs: Optional additional keyword arguments.
            """

**Comment by Lukasa** [comment]
Yup, that does look wrong. Are you interested in providing a pull request to make this fix?

**Comment by qingyunha** [comment]
Yes, I'm grad to.
