### ISSUE TITLE
Session connection with stream=True unusable after response.close()

### ISSUE THREAD

**Issue by mherrmann** [kennethreitz/requests#2747]
Please consider the following code:

```
import requests
session = requests.Session()
resp = session.get('http://www.w3schools.com/html/demo_sse.php', stream=True)
resp.close()
session.get('http://www.w3schools.com')
```

It results in the following exception:
```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File ".../venv/lib/python3.4/site-packages/requests/sessions.py", line 477, in get
    return self.request('GET', url, **kwargs)
  File ".../venv/lib/python3.4/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File ".../venv/lib/python3.4/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File ".../venv/lib/python3.4/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ResponseNotReady('Request-sent',))
```

Unless I am doing something wrong, It appears to me that `resp.close()` returns the connection to the pool in an inconsistent state. What's interesting is that the exception does not occur when the last line in the example above connects to a different server (eg. `session.get('http://www.google.com')` instead of `http://www.w3schools.com`). What's also interesting is that the problem only occurs when working with a `requests.Session`. That is, the following code does not raise an exception:

```
import requests
resp = requests.get('http://www.w3schools.com/html/demo_sse.php', stream=True)
resp.close()
requests.get('http://www.w3schools.com')
```

I am using requests version `2.7.0`. The problem occurs on both Windows 7 with Python 2.7.10 and on OS X with Python 3.4.3.

**Comment by Lukasa** [comment]
This is a known issue (#2593), and was fixed in #2610. =) The next release of requests should contain the fix.

**Comment by mherrmann** [comment]
Awesome, thanks :-) Is there an ETA for the next release?

**Comment by Lukasa** [comment]
Nothing beyond "soon" I'm afraid. Hopefully our release process will get a bit more concrete over the next few weeks.

**Comment by mherrmann** [comment]
Ok, thanks for letting me know!
