### ISSUE TITLE
during redirecting the host adress in header did not update correctly

### ISSUE THREAD

**Issue by HeartUnchange** [kennethreitz/requests#2748]
Situation:POST or GET a adress which will redirect an adress which the host adress in header is different with the last request.

I write a small script to simulate login my school account.But the exception,
> requests.exceptions.ConnectionError: ('Connection aborted.', error(10054, ''))
is always happening.

I try to print the information of every request.So in [session.py](https://github.com/kennethreitz/requests/blob/master/requests/sessions.py) class SessionRedirectMixin function resolve_redirects ,I print the header information before a real request.

I find during redirecting,the header information is just copied  from its last request.So if a request is redirected to an adress which the host adress in header is different with the last request,it will failed.

I try to solve this problem.
I add these lines in function resolve_redirects at 172th line in [session.py](https://github.com/kennethreitz/requests/blob/master/requests/sessions.py) before send the request.

    if headers.get("Host"):
        headers["Host"] = urlparse(url).hostname
And it worked for me.

more information:
 
    import requests
    print request.__version__
    '2.7.0'

**Comment by sigmavirus24** [comment]
@HeartUnchange are you specifying your own `Host` header? If so, why?

**Comment by hxzhao527** [comment]
~(≧▽≦)/~I got it.I delete the Host ,and it works.I see browser send this field ,so I add this(I am a beginer).Thanks for your help.
