### ISSUE TITLE
form data encoding can't be modifid

### ISSUE THREAD

**Issue by pynixwang** [kennethreitz/requests#2749]
these days, I 'm doing a poster to an old system,it only accepts gbk encoding,but form data is utf8, python 3 can pass a encoding parameter to urlencode then pass to post method,but python 2 urlencode does'nt support this parameter.

any opinion about this?

**Comment by sigmavirus24** [comment]
This isn't something requests would do for you anyway, so what you should do is urlencode the data, and then pass it to the `data=` parameter, e.g., 

``` py
postdata = urlencode(...)
postdata = postdata.encode(...)
requests.post(url, data=postdata, headers={'Content-Type': 'application/x-www-form-urlencoded'})
```

It isn't pretty but requests clearly meets the 95% use case here. The remaining 5% is something we won't add support for to the API.

Alternatively, you could use the PreparedRequest flow and encode the body before sending the request, but that (I think) might end up being more work than what I've sketched out above.

**Comment by sigmavirus24** [comment]
Also in the future, if you're looking for help, please ask questions on [StackOverflow](https://stackoverflow.com/questions/tagged/python-requests).

**Comment by pynixwang** [comment]
@sigmavirus24 sorry.

urlencode in python 2 encode unicode to ?

this is a problem
