### ISSUE TITLE
Json supersedes data in prepare_body

### ISSUE THREAD

**Issue by xEtherealx** [kennethreitz/requests#2756]
When not a stream, json supersedes data in prepare_body:
https://github.com/kennethreitz/requests/blob/f5dacf84468ab7e0631cc61a3f1431a32e3e143c/requests/models.py#L446

This conflicts with the docstring, which indicates that json is only used when data is not specified:
https://github.com/kennethreitz/requests/blob/f5dacf84468ab7e0631cc61a3f1431a32e3e143c/requests/models.py#L195

**Comment by Lukasa** [comment]
Thanks for this! Yes, that's well spotted: we're definitely in conflict with the documented behaviour.

**Comment by Lukasa** [comment]
I may try to find someone who wants to get started in requests to see if they want to fix this: it's a perfect fix for someone relatively new to OSS.

**Comment by taion** [comment]
BTW, `files` also supersedes `json` - the docs could use a small update there.

**Comment by Lukasa** [comment]
This is resolved in 2.8.0. Thanks all!
