### ISSUE TITLE
python3: does not un-gzip replies

### ISSUE THREAD

**Issue by smurfix** [kennethreitz/requests#2759]
It seems that (at least) a 403 response with gzipped body is expanded when running Python2, but not so with Py3.

```
desk ~/src/librssreader$ python run.py 
AppId required! Contact app developer. See http://www.inoreader.com/developers
[ traceback because of unrelated missing error check ]
desk ~/src/librssreader$ python3 run.py 
[[[ binary gibberish ]]]
[ same traceback ]
desk ~/src/librssreader$ 
```

run.py is simply:
```
#!/usr/bin/python3

from librssreader.inoreader import RssReader, ClientAuthMethod
auth = ClientAuthMethod('USERNAME','CENSORED')
reader = RssReader(auth)
print(reader.getUserInfo())
```

You need to register with inoreader.com (or find another web server) before testing this.

**Comment by Lukasa** [comment]
Requests has no logic relating to response code that should affect whether or not the body of the request is expanded. If you read the content, you should get the gzip expanded. My money is that the 403 response does not include a Content-Encoding header. Can you show me the request/response please (sanitising secure headers if needed)?

**Comment by smurfix** [comment]
Found it. The reply header looks like this:

```
HTTP/1.1 403 Forbidden
Server: nginx/1.7.9
Date: Mon, 07 Sep 2015 17:20:42 GMT
Content-Type: text/html; charset=UTF-8
Content-Length: 90
Connection: keep-alive
X-Powered-By: PHP/5.4.41
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Reader-Google-Version: 555-000
X-XSS-Protection: 1; mode=block
AppId required! Contact app developer. See http: //www.inoreader.com/developers
Vary: Accept-Encoding,User-Agent
Content-Encoding: gzip

[gzipped content]
```

Obviously the problem here is that Requests, on Python2, manages to ignore the inserted line of nonsense (note how the sender's server cleverly inserted a space after the colon), while on Python3 it does not.
I'll send them a bug report.

Still, there should not be inconsistent behavior between Py2 and Py3 versions.

**Comment by sigmavirus24** [comment]
So the header parsing is done by httplib (on Python 2, renamed to http.client on Python 3). This is a bug in the standard library, not in requests.

We cannot control the dependencies that are far beneath us (like the standard library).

**Comment by Lukasa** [comment]
Yup, unfortunately there's nothing we can really do about this at the moment, until such time as we stop using `httplib` to do the low-lying HTTP stuff for us.

I am extremely sorry about this. In the short term, I recommend you contact the server provider if possible and tell them to stop sending that nonsense in the HTTP headers (or at least to give the HTTP header a proper key).
