### ISSUE TITLE
Redundant creation of list?

### ISSUE THREAD

**Issue by ueg1990** [kennethreitz/requests#2765]
Hello, I came across this code under status_codes.py:

for (code, titles) in list(_codes.items()):
    for title in titles:
        setattr(codes, title, code)
        if not title.startswith('\\'):
            setattr(codes, title.upper(), code)

in the first line (the outermost loop), i think the list(_codes.items()) step is redundant. it should just be iterating over _codes.items(). what i am not sure is if the items method here returns a list (python 2) or an iterator/generator (python 3). if its the former, maybe its better to loop over _codes.iteritems(). In either case, you do not really need to convert it to a list.

Though this is a very small issue, if its worth doing a PR, I can do it. (in that way, i can contribute my first PR to the requests library :) )

**Comment by Lukasa** [comment]
Thanks @ueg1990! I think you're right: feel free to provide a pull request. =)

**Comment by sigmavirus24** [comment]
## To be clear: please do not use iteritems. Just remove the use of list()

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ueg1990** [comment]
I will send the pull request today. But i am curious, why should we not use iteritems?

**Comment by Lukasa** [comment]
@ueg1990 It doesn't exist in Python 3. =) Given that this is a one-time operation, we don't care too much about the one-off memory allocation for the temporary list on Python 2.

**Comment by ueg1990** [comment]
oh yeah make sense.
