### ISSUE TITLE
switch to alabaster theme

### ISSUE THREAD

**Issue by kennethreitz** [kennethreitz/requests#2779]
this may prove difficult, due to some ad tracking codes we have enabled

**Comment by ArcTanSusan** [comment]
@kennethreitz: Is this what you have in mind? https://github.com/kennethreitz/requests/pull/2915 How do I confirm that ad tracking codes are still enabled and nothing broke?

**Comment by jonathan-s** [comment]
The PR for this issue is merged, so the issue could be perhaps be closed.
