### ISSUE TITLE
ImportError: cannot import name certs

### ISSUE THREAD

**Issue by Boshomi** [kennethreitz/requests#2788]
opensuse 13.1 / python-requests = 2.7.0-63.1 / 

In [8]: import requests;
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-8-eedc5c747136> in <module>()
----> 1 import requests;

/usr/lib/python2.7/site-packages/requests/__init__.py in <module>()
     56     pass
     57 
---> 58 from . import utils
     59 from .models import Request, Response, PreparedRequest
     60 from .api import request, get, head, post, patch, put, delete, options

/usr/lib/python2.7/site-packages/requests/utils.py in <module>()
     23 
     24 from . import __version__
---> 25 from . import certs
     26 from .compat import parse_http_list as _parse_list_header
     27 from .compat import (quote, urlparse, bytes, str, OrderedDict, unquote, is_py2,

ImportError: cannot import name certs

**Comment by Boshomi** [comment]
this issue is fixed with version -requests = opensuse 13.1 / 2.7.0-66.1 /

**Comment by SlavePaul** [comment]
![401kmay2015](https://cloud.githubusercontent.com/assets/9671338/10117811/f376ce18-6418-11e5-86fb-58c0608e7f9a.jpeg)

**Comment by SlavePaul** [comment]
![forced intox](https://cloud.githubusercontent.com/assets/9671338/10118177/2046545a-6427-11e5-8705-0b7f2d90b125.jpg)
