### ISSUE TITLE
Quickstart note about json rendering is misleading

### ISSUE THREAD

**Issue by hosamaly** [kennethreitz/requests#2799]
In the Quickstart document, the [JSON Response Content](http://docs.python-requests.org/en/v2.0-0/user/quickstart/#json-response-content) section says:

> In case the JSON decoding fails, `r.json` raises an exception. For example, if the response gets a 401 (Unauthorized), attempting `r.json` raises `ValueError: No JSON object could be decoded`

This is a bit misleading, especially that the [`json()`](https://github.com/kennethreitz/requests/blob/v2.7.0/requests/models.py#L798) method makes no attempt to validate that. It is accurate to say that failure to decode JSON will result in an error being raised. However, receiving 401 does not necessarily mean that JSON decoding will fail. Some APIs might return a JSON object in the response body (e.g. `{ 'error': 'Unauthorized' }`), in which case `r.json()` will work fine.

**Comment by Lukasa** [comment]
That's a fair observation. Got a suggestion for clearer language?
