### ISSUE TITLE
IP Address of target host in Response

### ISSUE THREAD

**Issue by sezginriggs** [kennethreitz/requests#2802]
Hello,

Is there any way to get IP address of target host of a request? Looks like it's possible to get it from urllib3's HTTPResponse object with <Object>._fp.fp._sock.getpeername() but I couldn't find how to get it working with requests.

Is there any easy way or work around for it? Or can you please add it to feature requests and to Response object as an attribute? It would be good to use it like
r = requests.get("http://blabla.com")
print r.ip_addr

Best Regards,
Sezgin

**Comment by sigmavirus24** [comment]
Hi @sezginriggs thanks for taking the time to open this. We've discussed this previously on https://github.com/kennethreitz/requests/issues/2158 and decided against this. We're currently in a feature freeze (and will be for the rest of the project's life time in all likelihood) so we're not adding new features.

In the future, please search all issues using GitHub before opening new feature requests.

Cheers,
Ian

**Comment by est** [comment]
@sezginriggs use `stream=True`, grab the IP before you read the response body.

More here https://github.com/kennethreitz/requests/issues/2158
