### ISSUE TITLE
Cert present in certifi but not in requests

### ISSUE THREAD

**Issue by hombremuchacho** [kennethreitz/requests#2809]
https://github.com/certifi/python-certifi/blob/master/certifi/cacert.pem#L5026

Can the Entrust G2 certificate be added to the requests certificate store?

**Comment by Lukasa** [comment]
I think the core issue here is that requests' certificate store is somewhat out of date. I propose we ship a 2.8.1 containing a cert store update, specifically the `weak.pem` bundle that ships with certifi.

@hombremuchacho Someone I presume was your colleague or another team member (@aehlke) suggested that certifi was missing a certificate you needed, so you couldn't use it as a drop-in replacement. Did you try using `certifi.old_where()`?

**Comment by Lukasa** [comment]
(To be clear, the bundle pointed at by `certifi.old_where()` is exactly the same as the bundle I'm proposing in #2810, so if that works for you I'll know it's a good choice to move forward with.)

**Comment by hombremuchacho** [comment]
@Lukasa Thanks, I'll test this now.
