### ISSUE TITLE
Requests json argument is ignored in 2.8.0

### ISSUE THREAD

**Issue by vasiliy-bout** [kennethreitz/requests#2813]
In version `2.7.0` I was using `Requests` constructor with `json` parameter specified, like:
```
json_data = [ ... ];
r = requests.Request('POST', url, json=json_data)
```

And in the `2.8.0` version this code does not work, because I do not specify `data` parameter. Inside constructor we get `self.data` assigned as `[] if data is None else data`, so we finally get `self.data` equal to `[]`.

And because of this commit: 7a0cd16c1a5be16f3df395ee12ed11d0ddde7837 we get `json` parameter ignored, because now we have to explicitly specify `data={}` when calling constructor, like:
```
json_data = [ ... ];
r = requests.Request('POST', url, json=json_data, data={})
```

I think that this issue definitely breaks documented API.

**Comment by Lukasa** [comment]
Ah, yeah, that definitely happened. Sorry. =(

This was introduced in #2763. Looks like we need a slightly more subtle check than the one we introduced.

**Comment by Lukasa** [comment]
See #2814 for a proposed fix.
