### ISSUE TITLE
Bad examples of PUSH and PUT in Quickstart

### ISSUE THREAD

**Issue by TorKlingberg** [kennethreitz/requests#2826]
The quickstart guide had these examples:

    >>> r = requests.post("http://httpbin.org/post")
    >>> r = requests.put("http://httpbin.org/put")

With PUSH and PUT you almost always want to include some data. Without it they become fairly meaningless.

**Comment by Lukasa** [comment]
That's certainly true, though with the quickstart guide we're generally trying to err on the side of not providing _too_ much extraneous information. Nevertheless, if you'd like to open a pull request giving both of those some data (a simple bytestring will do), I'd be happy to merge that. =)

**Comment by shagunsodhani** [comment]
@Lukasa I have opened a pull request for this.

**Comment by TorKlingberg** [comment]
Thanks @shagunsodhani. I got busy and didn't notice this.
