### ISSUE TITLE
PUT send is doing Quotation on json payload

### ISSUE THREAD

**Issue by czerwe** [kennethreitz/requests#2828]
Hi,
i need to send via PUT an octetstream/json element via put. requests is quoting the full string. Example:

        testdata = '[{"cid": "1","uuid": "sdasd"}]'        
        response = requests.put(requestUrl, auth=self.auth, json=testdata)

can be seen in Wireshare like this:
        "[{\"cid\": \"1\",\"uuid\": \"sdasd\"}]"

if i use POST it is unquoted.
My remote REST Interface is not able to handle the quoted strings. I wasn't able to find any option where i can turn of the quotation.

**Comment by sigmavirus24** [comment]
If you read the [documentation](http://docs.python-requests.org/en/latest/user/quickstart/?highlight=json#more-complicated-post-requests) closely, you'll see your code should look like:

``` py
    testdata = [{"cid": "1","uuid": "sdasd"}]
    response = requests.put(requestUrl, auth=self.auth, json=testdata)
```

**Comment by czerwe** [comment]
the response is within a class which contains the auth definitin like:

self.auth = HTTPBasicAuth(username, password)

and i use this later on.
And how does the auth content influence the payload?

**Comment by sigmavirus24** [comment]
@czerwe 
1. I don't understand your question
2. The issue tracker is not a support forum. Please use [StackOverflow](https://stackoverflow.com/questions/tagged/python-requests)

**Comment by czerwe** [comment]
I am sorry about missleaded:
if found out that this seems to work:
        testdata = [{"cid": 1, "uuid":2}]
        response = requests.put(requestUrl, auth=self.auth, headers={"Content-Type": 'application/json'}, data=json.dumps(testdata))

using jsons doing quotation. From my point it's a missbehavior of the json handler in the session. 
Nevertheless sorry.

**Comment by Lukasa** [comment]
It is not an error in the Json handler. The json handler does not accept a _string_, it accepts the Python object directly. The difference between what you provided and what @sigmavirus24 gave is this:

``` python
testdata = '[{"cid": "1","uuid": "sdasd"}]'
testdata = [{"cid": "1","uuid": "sdasd"}]
```

**Comment by czerwe** [comment]
I was already wondering.
Your right. I tried so many things that some error output from the response miss leaded me. 

Thank you both. Next time i will ask in StackOverflow first.
Sorry.
