### ISSUE TITLE
Not marked as python3.4 compatible in PyPi

### ISSUE THREAD

**Issue by jra3** [kennethreitz/requests#2832]
Hi there,
 http://docs.python-requests.org/en/latest/ says there is support for python 2.6-3.4, but PyPi lists only 2.7.  I discovered this when i used the tool `caniusepython3` and saw requests on the list of packages holding me back.

**Comment by Lukasa** [comment]
Yeah, all our trove classifiers seem to be missing on PyPI. Looks like it was a while since it was registered. Resolved now. =)

Thanks for the report!
