### ISSUE TITLE
Response.text as byte string

### ISSUE THREAD

**Issue by rschwarz1711** [kennethreitz/requests#2834]
Hey,

we are missing informations how to stop the requests library from guessing the content type of response.text.

http://docs.python-requests.org/en/latest/api/?highlight=text#requests.Response.text

For our use case we need the original byte string. The current docs don't explain how to get it.
Please improve the docs.

Best regards
René

**Comment by Lukasa** [comment]
The docs absolutely do say how to get the original byte string, just a few lines up from where you linked: http://docs.python-requests.org/en/latest/api/?highlight=text#requests.Response.content

It's `response.content`.
