### ISSUE TITLE
Insecure Platform Warning

### ISSUE THREAD

**Issue by ueg1990** [kennethreitz/requests#2837]
I am contributing to a project that uses requests library (version 2.7.0) and even though the requests return outputs without any issue, I see the following warnings being printed:
/Users/ue/.virtualenvs/imgurpython/lib/python2.7/site-packages/requests-2.7.0-py2.7.egg/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail.

Any help on how to fix this?

**Comment by Lukasa** [comment]
@ueg1990 This is occurring because you're using this on an old version of Python which does not have a fully-featured `ssl` module. You can fix it either by upgrading to 2.7.9 or later, or by installing `pyopenssl`, `ndg-httpsclient`, and `pyasn1`.
