### ISSUE TITLE
PEP8 compliance

### ISSUE THREAD

**Issue by pathcl** [kennethreitz/requests#2842]
Hello,

I've just forked requests and tried flake8 on it.

1       E122 continuation line missing indentation or outdented
1       E127 continuation line over-indented for visual indent
1       E129 visually indented line with same indent as next logical line
1       E401 multiple imports on one line
1       E713 test for membership should be 'not in'
1       E714 test for object identity should be 'is not'
1       F402 import '_' from line 13 shadowed by loop variable
1       W391 blank line at end of file
2       E121 continuation line under-indented for hanging indent
2       E225 missing whitespace around operator
2       F841 local variable 'url' is assigned to but never used
3       E125 continuation line with same indent as next logical line
3       E221 multiple spaces before operator
3       E301 expected 1 blank line, found 0
4       E126 continuation line over-indented for hanging indent
10      E303 too many blank lines (3)
10      W291 trailing whitespace
11      E131 continuation line unaligned for hanging indent
16      F821 undefined name 'unicode'
20      E251 unexpected spaces around keyword / parameter equals
20      E302 expected 2 blank lines, found 1
39      E128 continuation line under-indented for visual indent
65      E262 inline comment should start with '# '
84      F401 'urllib3' imported but unused
85      E261 at least two spaces before inline comment
111     E265 block comment should start with '# '
257     E501 line too long (80 > 79 characters)
2651    E231 missing whitespace after ','

Is this relevant? I think it should be available some linting check before doing setup.py install

**Comment by sigmavirus24** [comment]
Please check old issues before opening new ones.
- https://github.com/kennethreitz/requests/issues/1899
- https://github.com/kennethreitz/requests/pull/2298
- https://github.com/kennethreitz/requests/pull/1964

This project does not follow PEP-0008.
