### ISSUE TITLE
_encode_params return bytes that break urlencode

### ISSUE THREAD

**Issue by gagoman** [kennethreitz/requests#2844]
Simple example:

```
import requests


r = requests.get('http://python.org', params=b'test=foo')


print(r.status_code)
```

Trace:

```
Traceback (most recent call last):
... skip ...
    url = requote_uri(urlunparse([scheme, netloc, path, None, query, fragment]))
  File "C:\Python35\lib\urllib\parse.py", line 383, in urlunparse
    _coerce_args(*components))
  File "C:\Python35\lib\urllib\parse.py", line 111, in _coerce_args
    raise TypeError("Cannot mix str and non-str arguments")
TypeError: Cannot mix str and non-str arguments
```

I know, that this one is a bad use case, but API allows us to do so.

Should we do something?

P.S. Python 3.4/3.5 on win 8.1 x64

**Comment by Lukasa** [comment]
I think what we need to do here is to change `encode_params` to make sure that it calls `to_native_string` on its argument before returning it. This seems like a bug we can fix pretty swiftly, and is well suited to a new contributor, so I'll mark this as `Contributor Friendly`.

**Comment by untitaker** [comment]
This fix seems completely broken. It prevents me from uploading binary data through PUT.

**Comment by sigmavirus24** [comment]
@untitaker please open a new issue.

**Comment by untitaker** [comment]
See #2030

**Comment by touilleMan** [comment]
Could you release a quick 2.9.1 with this fix plz ?

I was waiting the 2.9.0 for the REQUEST_CA_BUNDLE env var but cannot use it for the moment due to this bug ;-(

**Comment by Lukasa** [comment]
@touilleMan We're planning to release 2.9.1 on Monday.

**Comment by touilleMan** [comment]
Awesome, you guys rock ! ^^

**Comment by yami** [comment]
Looking forward to the new release. This bug breaks everything, since we use Chinese...
