### ISSUE TITLE
urllib3 SSL errors in 2.8.x

### ISSUE THREAD

**Issue by flupke** [kennethreitz/requests#2848]
We recently tried to upgrade to requests 2.8.1 and have been touched by this urllib3 issue: https://github.com/shazow/urllib3/issues/717

Downgrading to 2.7.0 resolves it.

**Comment by Lukasa** [comment]
@flupke The urllib3 and requests projects work together closely: we're entirely aware of the bug that you're encountering, but we won't be able to fix it until a new urllib3 release comes out.
