### ISSUE TITLE
Documentation Problem?

### ISSUE THREAD

**Issue by djchou** [kennethreitz/requests#2851]
When I run the following code from requests documentation, I get a 401 response.

import requests
r = requests.get('https://api.github.com', auth=('user', 'pass'))

Given that this is the quick start code for requests, is there something that needs to be updated?

**Comment by Lukasa** [comment]
@djchou In this context, `user` and `pass` are placeholder strings to be replaced by your own Github username and password.

**Comment by djchou** [comment]
Yes, I replaced them with my user pass and still had the same result.

**Comment by Lukasa** [comment]
@djchou What is the result of:

``` python
import requests
r = requests.get('https://api.github.com', auth=('user', 'pass'))
print(r.content)
```

**Comment by djchou** [comment]
ah, its the two factor auth that is causing it to fail.

'{"message":"Must specify two-factor authentication OTP
code.","documentation_url":"https://developer.github.com/v3/auth#working-with-two-factor-authentication"}'

**Comment by Lukasa** [comment]
Yeah, that's what I thought too.

I don't think it's worth gumming up the docs with this: it's extraneous detail that won't help much.
