### ISSUE TITLE
Problem with verbose logging

### ISSUE THREAD

**Issue by cousintroy** [kennethreitz/requests#2853]
I am trying to enable verbose logging with my request string and I am getting the following error:
"request() got an unexpected keyword argument config"

I have tried searching but have not found a fix for this and I followed the following directions:

>>> my_config = {'verbose': sys.stderr}
>>> requests.get('http://httpbin.org/headers', config=my_config)
2011-08-17T03:04:23.380175   GET   http://httpbin.org/headers
<Response [200]>

Thanks

**Comment by sigmavirus24** [comment]
Please consult our documentation: The section immediately above [the Licensing section](http://docs.python-requests.org/en/latest/api/?highlight=log#licensing) explains how to enable verbose logging in versions of requests 1.0.0 and greater.

**Comment by sigmavirus24** [comment]
Also in the future, please ask all questions on [StackOverflow](https://stackoverflow.com/questions/tagged/python-requests). This is a defect tracker, not a support forum.

**Comment by troy-perkins** [comment]
Thanks and noted for future questions!
