### ISSUE TITLE
Expose expires attribute of cookie in class RequestsCookieJar

### ISSUE THREAD

**Issue by AmmsA** [kennethreitz/requests#2857]
Right now, the class `RequestsCookieJar` class methods only expose `name` and `value` attributes of its cookies. It will be useful to have a method that checks if any of the cookies in `RequestsCookieJar` are expired. 
Like `is_expired()` would return True if any cookies are expired otherwise false

**Comment by Lukasa** [comment]
The `RequestsCookieJar` is a subclass of the standard library's [`cookiejar`](https://docs.python.org/2/library/cookielib.html#cookiejar-and-filecookiejar-objects), which means that it behaves exactly like that class. In particular, you can get the actual cookies themselves by iterating over it. This means the method you want is one line of code:

``` python
any_expired = any(cookie.is_expired() for cookie in session.cookies)
```

We're generally reluctant to add methods that are as simple as that one, given that there are a number of other constructions users might want (a method to say whether _all_ the cookies have expired, for example). Restricting the surface area of our APIs is extremely important to us.

One final thing: what's your use case? From where I'm sat it's hard to see why this would be useful: the cookie jar will remove expired cookies when they would have gotten used anyway, so I'm not entirely sure what advantage you receive by making this change.
