### ISSUE TITLE
GitHub release page lists the "latest release" as v2.5.1

### ISSUE THREAD

**Issue by edmorley** [kennethreitz/requests#2871]
On https://github.com/kennethreitz/requests/releases , the "latest release" label is next to v2.5.1, whereas the newest release is v2.8.1, which is hidden under the "Show 8 newer tags" link.

If newer release entries are missing because it's a hassle to transpose the release notes into each, perhaps just linking to the relevant entry on http://docs.python-requests.org/en/latest/community/updates/ would be sufficient? (Though it seems the permalinks on that page are just generic, eg `#id1` and not `#v2-8-1` etc). Or even leaving the notes section blank would be fine.

**Comment by Lukasa** [comment]
Yeah, it's mostly annoying to transpose the notes. I'll do it now anyway. =)

**Comment by sigmavirus24** [comment]
@Lukasa let's just remove them. This is a hassle and we've had .... 4 bugs about this? It's worthless and it doesn't provide real value.

**Comment by edmorley** [comment]
Removing them works for me; at least GitHub then defaults to just showing the tags, which will always be up to date :-)

**Comment by sigmavirus24** [comment]
Releases deleted.

**Comment by Lukasa** [comment]
:heart: @sigmavirus24 

Thanks for the report @edmorley!

**Comment by edmorley** [comment]
Many thanks :-)
