### ISSUE TITLE
Redundant import in docs?

### ISSUE THREAD

**Issue by kiddick** [kennethreitz/requests#2877]
I am talking about this doc.
https://github.com/kennethreitz/requests/blob/master/docs/user/quickstart.rst

Here:

```python
>>> import json
>>> url = 'https://api.github.com/some/endpoint'
>>> payload = {'some': 'data'}

>>> r = requests.post(url, json=payload)
```

json parameter is optional.
Is there any reason to import json module?
Thank you.

**Comment by Lukasa** [comment]
@kiddick You're entirely right: that import of the `json` module is from an old version of the documentation. Would you like to open a pull request to remove it?

**Comment by kiddten** [comment]
@Lukasa Thanks for reply. Yep I'll open pull request!

**Comment by sigmavirus24** [comment]
Thanks for fixing this @kiddick
