### ISSUE TITLE
Posting files with unicode file names

### ISSUE THREAD

**Issue by DeepSpace2** [kennethreitz/requests#2883]
Hi all. I'm having issues with posting files with UTF-8 file names. 
I've thoroughly read these 2 issues: 
https://github.com/kennethreitz/requests/issues/2505
https://github.com/mitsuhiko/flask/issues/1384

Please also refer to my question on SO:
http://stackoverflow.com/questions/33717690/python-requests-post-with-unicode-filenames

Unlike the first issue I linked to, my filename doesn't end with '\n'.

I noticed that the file ends up in request.form and not in request.files (just like described in the issues I linked to), must be because of the '*'  in 'Content-Disposition: form-data; name="file0"; filename*=utf-8''%D7%90.txt'  just after 'filename'.

**Comment by Lukasa** [comment]
Sorry, you've said you're "having trouble", but haven't actually specified what's happening that you aren't expecting. Could you elaborate?

**Comment by DeepSpace2** [comment]
I'm sorry it was not clear but the problem is that the server doesn't
receive the file (request.files is empty).

**Comment by Lukasa** [comment]
So, I believe this is fundamentally the same problem as shown as #2313. We're encoding the file using RFC 2231, which is a more-than-10-year-old specification, and your server appears not to be following it. To resolve this problem, either set the filename to a bytestring (or one that does not contain unicode data) or get the server fixed. =)
