### ISSUE TITLE
SSLError: [Errno 185090050] _ssl.c:336: error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib

### ISSUE THREAD

**Issue by AraHaan** [kennethreitz/requests#2884]
I am seeing this when compiling with requests in Python 2.7.10 with py2exe.

Everything goes just fine till I test the exe it generates.

My setup.py I used to create it is this.
```Python
from distutils.core import setup
import py2exe


setup(console=['Decorater.py'])

**Comment by Lukasa** [comment]
This is almost certainly a py2exe problem. It seems like py2exe is not handling the ssl module correctly.

**Comment by AraHaan** [comment]
I think that missing 3 dependencies could cause this as well although it still happens even when I just solved the "Insecure Platform Warning".

**Comment by AraHaan** [comment]
looking closer it seems to be similar to the one like this that is closed.

here is some Code that I do not know would work in the module that I make executable.
[personal login data to the account the bot uses stripped from code.]

https://i.gyazo.com/20b51bd6ac81a8f613f047146b910287.png
seems like the below does not work fully atm. But that is when I do not run it with py2exe. Testign it with now.

``` Python
import sys
from requests.certs import where

where()
os.environ['REQUESTS_CA_BUNDLE'] = os.path.join(os.path.dirname(sys.executable), "cacert.pem")
```

**Comment by AraHaan** [comment]
Fixed it with the code above but only works in py2exe. Closing this.

**Comment by AraHaan** [comment]
The only issues in py2exe are the Platform ones which I have not found out a fix on.
Although I tried the deps on the other issue that was closed.

https://github.com/kennethreitz/requests/issues/2837

**Comment by sigmavirus24** [comment]
@AraHaan this is absolutely not a bug in requests. Please look into using [data files](http://www.py2exe.org/index.cgi/data_files) with py2exe and [StackOverflow](https://stackoverflow.com) for further help with py2exe.

**Comment by AraHaan** [comment]
I noticed that when I find the warnings in the files it says from that other issue when I comment them out I do not see them anymore. Now it works just fine.
