### ISSUE TITLE
capath support in requests

### ISSUE THREAD

**Issue by mariayh1** [kennethreitz/requests#2892]
We are currently using pycurl, but we would like to migrate to requests in order to independent of NSS.
However, we could see that we can only provide a ca_bundle instead of a capath. In urllib2.urlopen you can provide cafile and capath options, however that is not the case in the requests module. 

Also we tried to use urllib2, but this only supports GET and POST requests, we are also interested in HEAD, PUT and DELETE. That is why we would like to use requests.

 Could you let me know if there are plans to support capath in the requests module? 

Thanks a lot,
Maria

**Comment by Lukasa** [comment]
Support for directories of CAs is in the current master, and will be released as part of the 2.9.0 release. See also #2858 and #2659.
