### ISSUE TITLE
Ability to use requests as a web server

### ISSUE THREAD

**Issue by cyberval** [kennethreitz/requests#2893]
Hi, I was wondering if a wrapper was existing around requests so that it could be used as a web server ?

**Comment by Lukasa** [comment]
@cyberval When you say "used as a web server", what does that mean exactly? What would requests do?

**Comment by valerianrossigneux** [comment]
Sorry it's not very clear. I want to access requests through a web server rather than the CLI, something like:
http://mydomain/requests?get=http://foo.com&authuser=a&authpass=b

Because of thrid party tool limitation that can only perform a GET or POST request and can't execute a script...

**Comment by Lukasa** [comment]
I'm afraid I'm not aware of any such project, however it should be an easy enough thing to write.
