### ISSUE TITLE
How can I detect encoding after I streamed only few pieces of response?

### ISSUE THREAD

**Issue by adibalcan** [kennethreitz/requests#2894]
size = 0
        start = time.time()
        for chunk in r.iter_content(1024):
            if time.time() - start > max_time:
                r.reason = 'timeout riched'
                raise ValueError(r.reason)
            size += len(chunk)
            if size > max_size:
                r.reason = 'response too large'
                raise ValueError(r.reason)

**Comment by Lukasa** [comment]
When you say "encoding", what kind of encoding do you mean?

**Comment by adibalcan** [comment]
After stream ends (finish, or I interrupt), I want to use r.content (decoded response). Who can I do this?

**Comment by Lukasa** [comment]
If you use `iter_content` manually, it does not save into `r.content`. You should simply save off the data directly yourself.

**Comment by adibalcan** [comment]
Okay but I want to use request decode system for my saved data to obtain a result similar to r.text

**Comment by Lukasa** [comment]
The easiest way to emulate it is to add `chardet` to your list of dependencies, and then do:

``` python
r = requests.get(url)
if r.encoding:
    text = content.decode(r.encoding)
else:
    encoding = chardet.detect(content)['encoding']
    text = content.decode(encoding)
```

That'll get you text decoded exactly as requests does it.
