### ISSUE TITLE
Does iter_content sometimes emit empty chunks

### ISSUE THREAD

**Issue by LinusU** [kennethreitz/requests#2901]
I've seen a lot of code on stackoverflow that guards the loop-body with an `if chunk:` when using `iter_content`. Is this really necessary, I don't see it anywhere in the documentation.

If it is, could we fix it? Or if not, document it.

```python
for chunk in r.iter_content():
  if chunk: # <- why this?
    output.write(chunk)
```

**Comment by Lukasa** [comment]
`iter_content` should not emit empty chunks. Historically it _could_, however with the current logic that should not be possible. If anyone encounters this problem I'd consider it a bug.

**Comment by LinusU** [comment]
Perfect, that's what I'd hoped for! Thanks
