### ISSUE TITLE
Feature Request: Format reponse as HTTP Response Message Format

### ISSUE THREAD

**Issue by CrazyPython** [kennethreitz/requests#2904]
http://www.tcpipguide.com/free/t_HTTPResponseMessageFormat.htm

A helper method to format a response as shown in the URL above would be useful.

**Comment by sigmavirus24** [comment]
Requests is currently in a feature freeze. As such we aren't going to be implementing this. That said, if you wanted to implement this yourself, you would probably get 90% of the way there with [dump_response](https://toolbelt.readthedocs.org/en/latest/dumputils.html#requests_toolbelt.utils.dump.dump_response) from the [toolbelt](/sigmavirus24/requests-toolbelt).
