### ISSUE TITLE
requests.packages.urllib3.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:646)

### ISSUE THREAD

**Issue by caizixian** [kennethreitz/requests#2906]
Mac OS X 10.11.1
Python 3.5.0 from https://www.python.org/downloads/
requests (2.8.1)

```python
>>> import ssl
>>> ssl.OPENSSL_VERSION
'OpenSSL 0.9.8zg 14 July 2015'
```

URL https://api.telegram.org/

**Comment by Lukasa** [comment]
That version of OpenSSL is absolutely _ancient_. I suspect it's the cause of your problem.

I have OS X 10.11.2 Beta, Python 3.5.0 linked against a newer version of OpenSSL (1.0.2d), and the same version of requests, and I can reach that URL fine. I highly encourage you to use a newer version of OpenSSL.

You can get this by running `pip install -U requests[security]`.

**Comment by caizixian** [comment]
@Lukasa So maybe I need to install a newer version of OpenSSL using homebrew and use it to replace the old OpenSSL shipped with OS.

**Comment by Lukasa** [comment]
@caizixian It's an option, but if you `pip install -U requests[security]` that will grab PyOpenSSL, which includes its own copy of OpenSSL on OS X.

**Comment by caizixian** [comment]
@Lukasa I had following errors when installing requests[security], both related to cffi.
1. `c/_cffi_backend.c:14:10: fatal error: 'ffi.h' file not found`
   
   so I `brew install pkg-config libffi`, which solved this problem.
2. After that, I tried to install requests[security] again, and I got `Failed building wheel for cffi` . 
   
   Despite this error, pip said that all things were installed. So I checked `ssl.OPENSSL_VERSION` again, still the same.

FYI, my Xcode is 7.1.1

**Comment by Lukasa** [comment]
`Failed building wheel for cffi` is fine, you don't mind. You shouldn't check `ssl.OPENSSL_VERSION` because that's the standard library and doesn't get changed by the packages you just installed. Instead, you should try running `python -c "from cryptography.hazmat.backends.openssl.backend import backend;print(backend.openssl_version_text())"`. That should print the newer OpenSSL version, and that's the one that will be used by requests.

**Comment by caizixian** [comment]
```
pip install cryptography
pip install pyopenssl
pip install requests[security]
```

Problem solved.

```
Python 3.5.1 (v3.5.1:37a07cee5969, Dec  5 2015, 21:12:44) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from cryptography.hazmat.backends.openssl.backend import backend
>>> print(backend.openssl_version_text())
OpenSSL 1.0.2e 3 Dec 2015
```

**Comment by ghost** [comment]
caizixian, you saved my life!!!!!
Thank you so much
