### ISSUE TITLE
Wrong content type on request.head() only

### ISSUE THREAD

**Issue by bestofothers** [kennethreitz/requests#2918]
Using request.head()  I want to get the content-type of a page before proceeding. Unfortunately for me, the request header content-type returns text/html. But if after completing the requests using request.get()
the content type is application/octet-stream.

I have suspected the web server but using urllib2 with a head request it return application/octet-stream

Here is my code and the exact url to reproduce the same error:

```py
>>> import requests
>>> u = "http://holo-pack.com.tw/download.phpx?soft=ea70"
>>> r = requests.head(u)
>>> r.headers['content-type']
'text/html'
```

With request.get() the header is "application/octet-stream" so with urllib2 as seen here: pect https://filippo.io/send-a-head-request-in-python/

**Comment by sigmavirus24** [comment]
Please review the [CONTRIBUTING](https://github.com/kennethreitz/requests/blob/master/CONTRIBUTING.md#good-bug-reports) file that GitHub prompted you to review prior to filing this bug.

You've not told us what version of requests you're using or how you've installed it.

**Comment by sigmavirus24** [comment]
So in spite of not having the information here, I noticed that the blog post registers a redirect handler. It looks like your head request gets redirected. As such you need to pass `allow_redirects=True` to a `HEAD` request to make sure you follow them too with requests. When you follow it all the way to the bottom you get the content-type you expect.
