### ISSUE TITLE
Uploading packages via twine fails

### ISSUE THREAD

**Issue by nicorevin** [kennethreitz/requests#2929]
Using latest 2.9.0
```
$ twine upload dist/*.whl
Uploading somepkg-15.12.16-py3-none-any.whl
ConnectionError: ('Connection aborted.', BadStatusLine("''",))
$
```
rollback to 2.8.1 solves the issue.

**Comment by Lukasa** [comment]
@sigmavirus24 You're probably best placed to look at this, but my suspicion is that there's an unexpected interaction between the toolbelt's MultipartEncoder and the fix we put in for calculating the actual length of file-like objects that are not seeked to the beginning. That said, I can't find anything in that.

**Comment by sigmavirus24** [comment]
Yeah, so this is a bug in requests-toolbelt and requests interaction.

**Comment by sigmavirus24** [comment]
Closing as the bug is actually over at https://github.com/sigmavirus24/requests-toolbelt/issues/117. Thanks for bringing this to our attention @nicorevin ! :cake:
