### ISSUE TITLE
PyPI doesn't know about python 3 support

### ISSUE THREAD

**Issue by mrterry** [kennethreitz/requests#2932]
PyPI doesn't seem to know that requests supports Python 3 (3.3, 3.4, & 3.5!).  As a result, [caniusepython3](https://caniusepython3.com/) thinks `requests` is a Python 3 blocker and `requests` is in red on the [Python 3 Wall of Superpowers](https://python3wos.appspot.com/).

Requests is awesome and it should get the credit it deserves.

**Comment by Lukasa** [comment]
Annoyingly, our trove classifiers appear to have disappeared again. I've re-uploaded them. Thanks!
