### ISSUE TITLE
COC?

### ISSUE THREAD

**Issue by alison985** [kennethreitz/requests#2941]
Hi,

I'm just wondering what your code of conduct is for this project?

Thanks,
Alison

**Comment by Lukasa** [comment]
Hi @alison985!

Currently our relatively minor code of conduct is [defined here](http://docs.python-requests.org/en/latest/dev/contributing/). There is interest amongst some of the maintainers in moving to something based on the [Contributor Covenant](http://contributor-covenant.org/), given that both myself and @sigmavirus24 maintain personal projects that use it, but I'm unwilling to change that by fiat: I'd want consensus from the whole team.

Regardless, I believe that the Contributor Covenant _implicitly_ applies to this project, and certainly that's the standard to which the maintainers hold themselves.
