### ISSUE TITLE
How to POST a very Big file with 'chunk' mode?

### ISSUE THREAD

**Issue by jchluo** [kennethreitz/requests#2942]
I want to Post to a very big file to the server,  will requests use the "chunk" mode ?
if
\>\>\> f = open("very big file")
\>\>\> requests.post(url, data=f)
From the `PreparedRequest.prepare_body` method, file length can get from `util.super_len`, 
then the `'Content-Length'` will be a number, which make chunk  mode False.
Is these any way to use the chunk mode when post a big file ?
Thank you!

**Comment by Lukasa** [comment]
Requests will not chunk the file, but neither will it read it all into memory. Instead, it will "stream" it: that is, send it from the file directly to the network. Do you really specifically need chunked-transfer-encoding here? What does chunked transfer encoding get you that the streaming method does not?

**Comment by jchluo** [comment]
Thank you @Lukasa . My mistake, I thought requests has to read it all into memory before send to network.In fact requests just "stream" it, which is cool.Thank you!

**Comment by sigmavirus24** [comment]
@jchluo in the future, please do **not** use the **issue** tracker for **questions**. Use [StackOverflow](https://stackoverflow.com/questions/tagged/python-requests).
