### ISSUE TITLE
Add json parameter to put methods

### ISSUE THREAD

**Issue by ibuchanan** [kennethreitz/requests#2943]
I enjoy both `requests.post(json=payload)` and `session.post(json=payload)`. I would like to have the same for both `requests.put()` and `session.put()`.

In a cursory examination of the code, it looks like a simple change. I would be happy to create a pull request for it. Is there a reason the convenience wasn't already propagated to PUTs?

**Comment by Lukasa** [comment]
> Is there a reason the convenience wasn't already propagated to PUTs?

It was. =) All our keyword arguments work on _all_ verbs, which means `json=` works on PUT as well as POST. The only thing we didn't do was add it as an explicit keyword argument so that it appears in the documentation. Would you like to make that change?

**Comment by ibuchanan** [comment]
Sure enough! I had tried it but when my tests failed, I thought that was the cause. But, as is usually the case, it was my code. :)

The lack of an explicit parameter doesn't bother me, so I'll pass for now.

Thanks for the quick response!
