### ISSUE TITLE
getting unexpected output

### ISSUE THREAD

**Issue by L1ghtn1ng** [kennethreitz/requests#2946]
So I am creating a script to interact with an API for https://haveibeenpwned.com/API/v2 (link to the API docs) so when I run this from the example on the site in python3 this works as expected.

```#!/usr/bin/python3

import requests
import pprint

headers = {'User-agent': 'Have I been pwn module'}

API = 'https://haveibeenpwned.com/api/v2/breachedaccount/foo@bar.com'

request = requests.get(API, headers=headers)
res = request.json()
pprint.pprint(res)
```

but when changing out the foo@bar.com email address to my personal email, I should get ```404 	Not found — the account could not be found and has therefore not been pwned``` status code but get this instead

```
  Traceback (most recent call last):
  File "/home/jay/.PyCharm50/config/scratches/scratch_4", line 11, in <module>
    res = request.json()
  File "/usr/lib/python3.5/site-packages/requests/models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.5/site-packages/simplejson/__init__.py", line 505, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3.5/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.scanner.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Process finished with exit code 1
```

Hope its not me being silly?

**Comment by Lukasa** [comment]
Can you let us know what your email address is? Do you feel comfortable with that?

**Comment by L1ghtn1ng** [comment]
@Lukasa I would prefer not to but if you under the API var put your email address you should hit the same issue I am having as long as you are not in any of the breach lists

**Comment by Lukasa** [comment]
@L1ghtn1ng So in both Python 3 and Python 2 I find that the response has no body if there have been no breaches. As a result the JSON decoders fail to decode correctly. You should check the status code (`res.status_code`) before using `r.json()`.
