### ISSUE TITLE
Persistent Connection suffer from delay of Nagle

### ISSUE THREAD

**Issue by zhangi** [kennethreitz/requests#2957]
Not sure if this is a bug from urllib3 or Requests, the problem is that there is an extra delay introduced for all subsequent requests other than the first one when reusing a session object.
The test are performed in Ubuntu 14 to a http server running on the localhost
```python
with requests.Session() as session:
    session.get(url) # this takes <1ms
    session.get(url) # this takes around 40ms
    session.get(url) # this takes around 40ms
```
Similar case was observed in httplib2 with Python 2.6(https://code.google.com/p/httplib2/issues/detail?id=91), and was fixed in Python 2.7.

**Comment by Lukasa** [comment]
There should not be a Nagle's algorithm delay, because by default we disable Nagle's algorithm. Can you please answer the questions from our [CONTRIBUTING.md](https://github.com/kennethreitz/requests/blob/master/CONTRIBUTING.md), specifically:

> Tell us **what version of Requests you're using**, and **how you installed it**.

**Comment by zhangi** [comment]
version: 2.9.1
installed by: sudo pip install requests --upgrade
python version: 2.7.3
os: Ubuntu 14

**Comment by Lukasa** [comment]
So [we disable Nagle's algorithm by default](https://github.com/kennethreitz/requests/blob/master/requests/packages/urllib3/connection.py#L97), which means that your diagnosis of this cannot be right.

Are you familiar with wireshark or tcpdump?

**Comment by zhangi** [comment]
Let me investigate more, maybe it has something to do with server side. I will close it first.

**Comment by Lukasa** [comment]
To be clear, if the server-side has delayed ACKs turned on it may cause this problem.
