### ISSUE TITLE
HTTPAdapter ignored

### ISSUE THREAD

**Issue by swmerko** [kennethreitz/requests#2965]
Hi,
i'm trying to force ssl.PROTOCOL_TLSv1 as written in documentation:
http://docs.python-requests.org/en/latest/user/advanced/#example-specific-ssl-version
```
from requests.adapters import HTTPAdapter
from requests.packages.urllib3.poolmanager import PoolManager
import ssl

class MyAdapter(HTTPAdapter):
    def init_poolmanager(self, connections, maxsize, block=False):
        self.poolmanager = PoolManager(num_pools=connections,
                                       maxsize=maxsize,
                                       block=block,
                                       ssl_version=ssl.PROTOCOL_TLSv1)

import requests
s = requests.Session()
s.mount('https://', MyAdapter())

requests.get('https://services.mailup.com/')
```
but this gives me 
```
requests.exceptions.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:600)
```

so i tried to patch requests/packages/urllib3/poolmanager.py with:
```
class PoolManager(RequestMethods):
    proxy = None

    def __init__(self, num_pools=10, headers=None, **connection_pool_kw):
        RequestMethods.__init__(self, headers)
        connection_pool_kw['ssl_version'] = ssl.PROTOCOL_TLSv1
        self.connection_pool_kw = connection_pool_kw
        self.pools = RecentlyUsedContainer(num_pools,
                                           dispose_func=lambda p: p.close())
```

and i get:
```
>>> import requests
>>> requests.get('https://services.mailup.com/')
<Response [403]>
```
Any ideas?

Thanks,
Matteo

**Comment by Lukasa** [comment]
@swmerko You have to route your request through the Session object. In your code example you create a Session object `s`, but then call `requests.get`. That's not how Session objects work. Change your last line to `s.get()` instead of `requests.get()` and your problem should be solved.

**Comment by swmerko** [comment]
Is there a way to define globally requests with my Adapter?

**Comment by Lukasa** [comment]
No, requests deliberately maintains very little global state. Under the covers, each requests.\* call creates a new Session to execute the request. If you really wanted to do this (and I strongly do not recommend this approach), you could monkeypatch `Session.__init__()` to mount your adapters over the default ones.

**Comment by swmerko** [comment]
Thank you very much!
