### ISSUE TITLE
SSL-Client-Certificate and Subject Alternative Names

### ISSUE THREAD

**Issue by felskrone** [kennethreitz/requests#2967]
I have a (Puppet-)generated SSL-certificate with a CN and several SANs. A stripped output of openssl-output looks like this:

```bash
# openssl x509 -in cert.crt -text
Certificate:
    ...
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: CN=Puppet CA: puppet.domain.com
        ...
        X509v3 extensions:
            ...
            X509v3 Subject Alternative Name:
                DNS:srv01.domain.com, DNS:srv02.domain.com, DNS:srv03.domain.com
        ...
```

Now when i use this certificate with requests, it always picks the CN to do the actual request. Meaning my remote always receives "puppet.domain.com" to verify the client-certificate against. Since the remote IS puppet.domain.com, and the client is srv01.domain.com, the verification always fails.

Is there any way, to have requests use any of the SANs to do its request?

Or is it my remote the actually only uses the CN to do verification?

**Comment by Lukasa** [comment]
Sorry...I'm confused. When you say "to do the actual request", what do you mean?

**Comment by felskrone** [comment]
I meant when i do request.post(url, cert()..) that requests always picks the CN.

But i think thats not the problem here. Im quite certain that the remote (apache) or maybe even the application (foreman) has to look at the SANs to actually do the verification since the client-certificate is sent as is, isnt it?

**Comment by Lukasa** [comment]
Correct: requests doesn't touch or extract any information at all from the client certificate. If the remote peer is failing to validate it, that's a configuration error with the remote peer.

**Comment by felskrone** [comment]
Great, thx :-)
