### ISSUE TITLE
Cut a release to match urllib3-1.14?

### ISSUE THREAD

**Issue by ralphbean** [kennethreitz/requests#2969]
Hi, we noticed that urllib3-1.14 was released right at the end of 2015.  Are there plans to release a new version of requests bundling that?

Downstream in Fedora we had a bug filed requesting urllib3-1.14, but with the way things stand now, we can't update to that until we have a matching requests release.  https://bugzilla.redhat.com/show_bug.cgi?id=1295402

**Comment by Lukasa** [comment]
@ralphbean At some point, sure. We weren't generally planning on racing to new urllib3 versions, especially as really the only change in that urllib3 release is the SOCKS proxy support.

Is there a particular rush to get urllib3 1.14 into Fedora?

**Comment by ralphbean** [comment]
I think Nir Magnezi in that ticket was having issues setting up an OpenStack dep that may have pinned version 1.14 of urllib3.  I'll ask for more details.

**Comment by jonathan-s** [comment]
:+1: for this. 
There was another release in 1.14 as well: "Fixed AppEngine handling of transfer-encoding header and bug in Timeout defaults checking." Together with this patch: https://github.com/sigmavirus24/requests-toolbelt/pull/119 and the use of requests_toolbelt, requests will actually work on appengine. 

So it would be much appreciated if requests got updated to urllib3 1.14.

**Comment by Lukasa** [comment]
So to be clear, we _will_ cut such a release. I'm just trying to work out how time-sensitive this release is.

**Comment by jonathan-s** [comment]
Thank you :). Looking forward to when it will be.

**Comment by mikelambert** [comment]
As the one doing the changes to get urllib3/requests working on appengine, I would say "not high priority" on that count, as it's not blocked on this urllib3 import yet. Once we get https://github.com/sigmavirus24/requests-toolbelt/pull/119 submitted, and that branch integrated into master, then I'll come pushing on this thread again to get appengine functionality unblocked.

**Comment by mikelambert** [comment]
Okay that went quicker than expected, based on extrapolation of past activity on my pull request. :) My changes are now integrated into a requests-toolbelt branch, conditioned against a hypothetical 2.10 version of requests containing the latest urllib3 functionality. I assume once requests cuts this release, @sigmavirus24 can then integrate the branch into mainline requests-toolbelt.

I'll leave it to you guys to determine the time-sensitivity of appengine functionality.

**Comment by timc13** [comment]
+1 - looking forward to the appengine fix

**Comment by deweydb** [comment]
+1 for SOCKS support. [requesocks](https://github.com/dvska/requesocks) is horribly out of date.

**Comment by mtakacs** [comment]
+1 for SOCKS support as well.

**Comment by tarhan** [comment]
+1 for SOCKS support especially for using with tor directly without tsocks/proxychains in middle.

**Comment by brettdh** [comment]
+1 for SOCKS support, especially with the recent release of Docker 1.11.0 with SOCKS support, and the fact that docker-py can't support SOCKS until requests does.
