### ISSUE TITLE
Response encoding defaulting to ISO-8859-1

### ISSUE THREAD

**Issue by eskerda** [kennethreitz/requests#2974]
Hello,

For the last month I've been getting reported issues on badly encoded data (ie: https://github.com/eskerda/pybikes/issues/109)

I've searched through the issues and also tried to pinpoint it to a particular change, but only one if found is from 2014.

Has something changed recently?

Can be reproduced as:

```python
import requests
import re

rgx = r'setEstacao\((.+)\)'
resp = requests.get('http://www.ciclosampa.com.br/estacoes.php')

print "Uses default encoding %r" % resp.encoding
print re.findall(rgx, resp.text)[0]
print ""
resp.encoding = 'UTF-8'
print "Uses set encoding %r" % resp.encoding
print re.findall(rgx, resp.text)[0]
```

```
Uses default encoding 'ISO-8859-1'
-23.572208,-46.644283,"1","EstaÃ§Ã£o Hcor","Rua Desembargador Eliseu Guilherme 14","5","11"

Uses set encoding 'UTF-8'
-23.572208,-46.644283,"1","Estação Hcor","Rua Desembargador Eliseu Guilherme 14","5","11"
```

Sorry if this has already been reported or resolved. Looked for issues but most changes on this are too old to be relevant.

**Comment by Lukasa** [comment]
This has not changed: requests has behaved like this for an extremely long time. See #2086 for a discussion about it.

If this used to work but has now stopped working, it's likely that the server used to send a `charset` field in the Content-Type header but no longer does.

If you know you're going to be handling HTML, you should look to extract the encoding from the HTML body. You can handle that automatically by using [this utility function from the requests toolbelt](https://toolbelt.readthedocs.org/en/latest/deprecated.html#requests_toolbelt.utils.deprecated.get_encodings_from_content).
