### ISSUE TITLE
Why retry doesn't work on sesson.post method

### ISSUE THREAD

**Issue by demonguy** [kennethreitz/requests#2975]
I've pasted requests.packages.urllib3.util.Retry object to max_retries argument of HTTPAdapter
But i found, it only works on session.get. How could i make it work on session.post ?

**Comment by Lukasa** [comment]
When you say it doesn't work on post, what does that mean? What are you expecting to see and what actually happens?

**Comment by demonguy** [comment]
it means. when i use session.post to access url = 'https://httpbin.org/status/500', it doesn't retry and just return an 500 error, not maxretry error.

**Comment by Lukasa** [comment]
@demonguy That's not how retries work by default. Generally speaking, retries only affect actual connection issues that prevent us from sending the request or retrieving the response altogether. Normally, we do not issue retries on 500 errors. You can change that behaviour by initializing your `Retry` object with `status_forcelist=range(500, 600)`, as documented on the [Retry object API document](https://urllib3.readthedocs.org/en/latest/helpers.html#urllib3.util.retry.Retry).

**Comment by demonguy** [comment]
I am doing what you said.

**Comment by demonguy** [comment]
I am doing what you said, did you read my original post? i past "requests.packages.urllib3.util.Retry" object.

And of course i passed status_forcelist, but it only works on get, not on post

**Comment by Lukasa** [comment]
If you look at the API documentation, you'll notice that it says this:

> method_whitelist (iterable) –
> Set of uppercased HTTP method verbs that we should retry on.
> By default, we only retry on methods which are considered to be indempotent (multiple requests with the same parameters end with the same state).

POST is not considered IDEMPOTENT. You'll need to extend the method whitelist with POST to allow max_retries to function there.

**Comment by sigmavirus24** [comment]
@demonguy in the future **questions** are to be asked on [StackOverflow](https://stackoverflow.com/questions/tagged/python-requests). Please do not ask a question in an issue again.

**Comment by demonguy** [comment]
Sorry. I search for the whole Request document, i should expect it's in urllib3 documents.
Really sorry. 
And i did search Google and stackoverflow, maybe i use wrong keyword so i didn't get answer from that.
Sorry
