### ISSUE TITLE
JSON-ROA data ignored

### ISSUE THREAD

**Issue by birk** [kennethreitz/requests#2977]
Hi,
I'm trying to read JSON-ROA responses from an API that look like this:
```json
{
	"_json-roa": {
		"filled_with": "lots of data"
	},
	"created_at": "2015-11-05T10:33:37.249Z",
	"creator_id": "a41b963a-e50e-40ad-9c37-dc5dfcc9a1de",
	"id": "c97e9d4c-aaff-415a-a996-4a7e79ce0c81",
}
```
A call to ``r.json()`` recognizes ``created_at``, ``creator_id``, and ``id`` correctly but ignores ``_json-roa``.
``r.text`` shows likewise only the last three nodes.

If I open and read the same JSON not as a server response but as a static file, parsing it is not problem.

Any ideas?

Best,
birk

**Comment by Lukasa** [comment]
If `r.text` only shows the last three nodes, that means that only the last three nodes are present. This means that for some reason the server is choosing not to send you that data.

You'll need to consult with your API documentation or server operator to determine why that data is absent.

**Comment by birk** [comment]
Thanks for the quit response. If I do the same request in the shell via curl I do get all the data from the server.

**Comment by Lukasa** [comment]
So in this case the problem is likely to be one of user-agent filtering. Try using `curl -v` to see what headers curl sends, and then set the user-agent header to the same thing using requests.

**Comment by birk** [comment]
The header it was … I used `'accept': 'application/json'` but it has to be either `'accept': '*/*'` or correctly `'accept': 'application/json-roa+json'`.
