### ISSUE TITLE
JSON content type for PUT method

### ISSUE THREAD

**Issue by Neraste** [kennethreitz/requests#2979]
According to the [doc](http://docs.python-requests.org/en/latest/api/), you can specify to send a request with JSON content type for POST method. But there is nothing like this for PUT or PATCH methods.

Is there a reason? Can this be implemented?

**Comment by sigmavirus24** [comment]
If you look at the documentation for [`requests.put`](http://docs.python-requests.org/en/latest/api/#requests.put) and [`requests.patch`](http://docs.python-requests.org/en/latest/api/#requests.patch) they take `**kwargs` that are passed to [`requests.request`](http://docs.python-requests.org/en/latest/api/#requests.request).

This means that `json=` is already a valid parameter for those methods.
