### ISSUE TITLE
First line of uploading files disappears.

### ISSUE THREAD

**Issue by amdei** [kennethreitz/requests#2983]
requests 2.9.1 
Executing of this code (from samples in documentation):

`import requests

url = 'http://192.168.88.164:8000/'
files = {'file': ('conf.txt', 'some, data,to send\r\nnanother,row,to,send\r\nyet another,row,to,send\r\n')}

r = requests.post(url, files=files)
print r.text`

Results in correctly uploaded file, but without first line.
I.e. part 'some, data,to send\r\n' is missed.

Same with actoual file upload:
`import requests

url = 'http://192.168.88.164:8000/'
files = {'file': ('conf.txt', open('conf.txt', 'rb'))}

r = requests.post(url, files=files)
print r.text`

First line disappears from uploaded content.
The same file uploaded to the same server with curl:
`curl -v -X POST -F file=@conf.txt http://192.168.88.164:8000`
do not such an issue.

Issue seems to be in incorrect encoding - extra \r\n where missed somewhere.

**Comment by Lukasa** [comment]
Sorry, but I can't reproduce this using a publicly available website. If I run this code:

``` python
import requests
url = 'http://http2bin.org/post'
files = {'file': ('conf.txt', 'some, data,to send\r\nnanother,row,to,send\r\nyet another,row,to,send\r\n')}
r = requests.post(url, files=files)
print r.content
```

then the terminal prints:

```
{
  "args": {}, 
  "data": "", 
  "files": {
    "file": "some, data,to send\r\nnanother,row,to,send\r\nyet another,row,to,send\r\n"
  }, 
  "form": {}, 
  "headers": {
    "Accept": "*/*", 
    "Accept-Encoding": "gzip, deflate", 
    "Connection": "keep-alive", 
    "Content-Length": "211", 
    "Content-Type": "multipart/form-data; boundary=83f1175700aa4a2b8a49111a87fce425", 
    "Host": "http2bin.org", 
    "User-Agent": "python-requests/2.9.1", 
    "Via": "1.1 http2bin.org"
  }, 
  "json": null, 
  "origin": "87.115.225.178", 
  "url": "http://http2bin.org/post"
}
```

As you can see, all the data is present. The actual HTTP request on the wire looked like this:

```
POST /post HTTP/1.1
Host: http2bin.org
Content-Length: 211
Accept-Encoding: gzip, deflate
Accept: */*
User-Agent: python-requests/2.9.1
Connection: keep-alive
Content-Type: multipart/form-data; boundary=83f1175700aa4a2b8a49111a87fce425

--83f1175700aa4a2b8a49111a87fce425
Content-Disposition: form-data; name="file"; filename="conf.txt"

some, data,to send
nanother,row,to,send
yet another,row,to,send

--83f1175700aa4a2b8a49111a87fce425--
```

This all seems correct to me. Are you sure your server is handling this appropriately?

**Comment by amdei** [comment]
Indeed, issue was on server-side.
When requests send string, there is no 'Content-Type' field, and it confused server so it ate first line of uploaded file.

Thanks for great library!
Sorry for hesitate.

**Comment by sigmavirus24** [comment]
No worries @amdei
