### ISSUE TITLE
Any idea if it would be possible to use something like oscrypto instead of the bundled SSL lib for HTTPS?

### ISSUE THREAD

**Issue by danechitoaie** [kennethreitz/requests#2989]
Any idea if it would be possible to use something like [oscrypto](https://github.com/wbond/oscrypto) instead of the bundled SSL lib for HTTPS?

I need to use this in a Sublime Text 3 plugin where the bundled version of SSL is pretty old and I can't connect to some hosts supporting only TLS1.2. Using the above should fix this issue.

Any idea how this can be used for SSL?

**Comment by Lukasa** [comment]
@danechitoaie Let's split this into two questions.

First, the problem with OpenSSL. If you can use a third-party library, you should be able to install `PyOpenSSL`, `ndg-httpsclient`, and `pyasn1`. If the `cryptography` library that backs PyOpenSSL is linked against a newer version of OpenSSL than the bundled one (or if you're on Windows or OS X, where `cryptography` is statically linked against a modern OpenSSL).

Using oscrypto instead is extremely tricky. Requests cannot add support for this in the mainline. You could in principle add support for this in urllib3, but that won't happen quickly. PyOpenSSL is probably your best bet here.

**Comment by danechitoaie** [comment]
I can't use PyOpenSSL as that requires compilation and it would not work as a SublimeText3 plugin as they have their own version of python bundled that executes the plugins code. So you can't use pip, easy_install, etc... you can only use "pure" python code that doesn't have external dependencies.
Oscrypto would work as it's just Python code (nothing to compile) that uses the native OS SSL lib trough CFFI. 

I understand that it can't be added to requests, I'm looking at maybe some pointers or ideas on how/if this could be implemented, even if it means I have to change some code in requests or urllib3 (private fork). I know it doesn't sound good but it's kind of the only option.

**Comment by Lukasa** [comment]
@danechitoaie PyOpenSSL and oscrypto both use the exact same backing library. PyOpenSSL has not required compilation for more than a year now.

**Comment by danechitoaie** [comment]
Hmm, then I need to look more into PyOpenSSL then. Maybe I can just use that. Thanks for the input.
