### ISSUE TITLE
Consider simplifying Session.resolve_redirects

### ISSUE THREAD

**Issue by kennethreitz** [kennethreitz/requests#2990]
Currently, the `Session.resolve_redirects` method requires a `Response` to be passed in, as well as a `Request` (the response's originating request). When using this method directly, this is a bit confusing, especially considering that the desired/required `Request` is an attribute of the obviously required `Response`.

There must have been some reason behind why I made this design decision, but I'm not seeing it currently.

**Comment by sigmavirus24** [comment]
Adding this to 3.0.0 because it would be a fairly significant breaking change. I was also never quite certain why that was required, but I'm not certain it is actively harmful either :/

**Comment by kennethreitz** [comment]
Yeah, this would be a 3.0.0 change. 

@sigmavirus24 I was just trying to use it directly while debugging an infinitely redirecting URL, and I had to look at the source code to figure out how to do so. I just really need to spend some time figuring out why I wrote it that way, there must have been a reason.

**Comment by kennethreitz** [comment]
Done! https://github.com/kennethreitz/requests/blob/proposed/3.0.0/requests/sessions.py#L88
