### ISSUE TITLE
Requests default to environment CA even when there's a session-set CA

### ISSUE THREAD

**Issue by jcmcken** [kennethreitz/requests#2998]
If I set a CA via an environment variable, such as:

```console
$ export REQUESTS_CA_BUNDLE=/etc/pki/tls/certs/ca-bundle.crt
```

(Where the CA bundle actually does exist)

And then I prepare a session like this:

```python
import requests

session = requests.Session()
session.verify = '/path/to/custom/ca.pem'
```

(Again, assume this 2nd CA path exists)

Executing a ``session.get`` against an HTTPS endpoint signed by the 2nd CA but not the first will result in an SSL verification error. This is because the request is defaulting to using the environment CA rather than the session CA. This sort of contradicts my expectations, where the session is much closer to the request in the stack than the process's environment.

The source of this issue is the merging happening here:

https://github.com/kennethreitz/requests/blob/3a77b59df222920391359f052cab9319dda31ac7/requests/sessions.py#L625

...where the conditional validates whether the verification is set at the request level (either ``True`` or ``None``) before choosing to set the env CA, but doesn't look at the session (``self.verify``) (which likely has, and in my case does have, a more accurate CA setting).

**Comment by sigmavirus24** [comment]
I believe this is related to https://github.com/kennethreitz/requests/issues/2018 which is scheduled for 3.0.0

**Comment by sigmavirus24** [comment]
As an aside, you can disable using the environment by setting `trust_env=False`.

**Comment by Lukasa** [comment]
Closing to centralise on #2018.

**Comment by jcmcken** [comment]
@sigmavirus24 That's the workaround I intend to use, although it's a little troublesome since I'm using a library which is itself using `requests`, and it doesn't expose `trust_env`, so I'm having to patch it in. It's also troublesome because it disables proxy configuration via the environment.

Thanks though, I didn't see the other issue!
