### ISSUE TITLE
Problem with Content-Lenght is missing

### ISSUE THREAD

**Issue by victor1969** [kennethreitz/requests#3000]
I'm playing clonk rage but i can't play online because this happend 
Content-Lenght is missing pls help me
PS: i don't speak english so well

**Comment by kennethreitz** [comment]
@victor1969 can you please share the code you are using so we can understand what you're asking?

**Comment by victor1969** [comment]
where i get the code?

**Comment by kennethreitz** [comment]
@victor1969 is this an error you saw while playing a game? Why did you decide to post about it here?

**Comment by victor1969** [comment]
i'm just trying to play online Clonk rage but says on the server list
Internet server on league.clonkspot.org
Invalid server response: Content-Length is missing!

**Comment by kennethreitz** [comment]
@victor1969 unfortunately, that has nothing to do with project. There's probably somewhere else online for you to report this, though!

**Comment by victor1969** [comment]
ok 
:(
