### ISSUE TITLE
Add ability to pass CA certificates by fileobj

### ISSUE THREAD

**Issue by Kentzo** [kennethreitz/requests#3007]
Sometimes requests has no ability to open file with CA because is no such file, e.g. when CA is embedded in the app.

requests should allow to specify fileobj (which can be a file or io wrapper on top of string and bytes) for that.

**Comment by Lukasa** [comment]
Unfortunately that's extremely difficult for requests to do. 

The 'path to a file' approach is actually the API used by OpenSSL. It's also possible to pass an in-memory serialized representation (as read from a file object), but that API is not exposed by the standard library so we can't rely on that being present.

**Comment by kennethreitz** [comment]
We could create a tmpfile automatically when passed a file-like-object, but we would likely want to ensure its deletion after execution is complete.

So, definitely possible, but probably not the best idea.

**Comment by Kentzo** [comment]
Creating intermediate file can be handled by user of requests.

After checking Python's code I agree that it's, at least, a limitation in Python.
Sad that OpenSSL relies on file being present in FS.

**Comment by Kentzo** [comment]
@Lukasa is there a way to query presense of this API in runtime? Could you give me some links to read more about it?

**Comment by Kentzo** [comment]
Is it possible to verify by using system's CA without shipping cacert.pem nor certifi?

**Comment by Lukasa** [comment]
@Kentzo: for a discussion about the system cert bundle, see #2966. It is possible to query for this API at runtime because it's only exposed by PyOpenSSL.

**Comment by dsully** [comment]
Python 2.7.9+ and 3.5's implementation of `load_verify_locations()` in `Modules/_ssl.c` support passing of a `cadata` argument, which contains the serialized trust store. This is also exposed in the `ssl.create_default_context()` function.

**Comment by Kentzo** [comment]
@Lukasa I think the original issue is orthogonal to #2966 and this issue should be re-opened because of the discovery made by @dsully.
