### ISSUE TITLE
exceptions missing from __init__.py

### ISSUE THREAD

**Issue by jtpereyda** [kennethreitz/requests#3022]
It is traditional to include the public API in `__init__.py`.

Consider this test code:
```python
import requests
import requests.exceptions

a = requests.exceptions.ConnectTimeout
```

This will run properly, but PyCharm raises a warning, saying, "Cannot find reference 'exceptions' in `__init__.py`".

This could be fixed by changing an `__init__.py` line from:

    from . import utils

to

    from . import requests, utils

While this is technically a [bug ](https://youtrack.jetbrains.com/issue/PY-18550) in PyCharm, requests' __init__.py already imports utils, apparently for this very purpose. So it would be consistent to import exceptions as well.

**Comment by sigmavirus24** [comment]
This isn't _technically_ a bug in PyCharm. It is a bug that they should be fixing. If we did something like this for each editor that does nonsensical things like this, I'm not sure we'd have a very coherent project.

**Comment by jtpereyda** [comment]
@kennethreitz Resolved this by changing the docs (see PR #3023).

Looks like http://docs.python-requests.org/en/master/api/#exceptions is still missing ConnectTimeout and ReadTimeout. Should they be added to `__init__.py`?

**Comment by kennethreitz** [comment]
@jtpereyda oddly, those two exceptions are being _raised_ during the sphinx build. I haven't dug into it yet. 

But.... anyone can investigate! ;)

**Comment by kmad1729** [comment]
Is this still a reproducible bug? Both (python2 and python3) sphinx builds are clean:

```
(p2_venv) requests $ make docs
cd docs && make html
make[1]: Entering directory '/home/kmaduri/Documents/programming/python/requests/docs'
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.3.5
loading pickled environment... failed: unsupported pickle protocol: 4
loading intersphinx inventory from http://urllib3.readthedocs.org/en/latest/objects.inv...
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 18 source files that are out of date
updating environment: 18 added, 0 changed, 0 removed
reading sources... [100%] user/quickstart                                     
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] user/quickstart                                      
generating indices... genindex py-modindex
highlighting module code... [100%] requests.auth                              
writing additional pages... search
copying static files... done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded.

Build finished. The HTML pages are in _build/html.
make[1]: Leaving directory '/home/kmaduri/Documents/programming/python/requests/docs'
\033[95m\n\nBuild successful! View the docs homepage at docs/_build/html/index.html.\n\033[0m
```

**Comment by kennethreitz** [comment]
This may have been fixed now; there was a change made around this recently.
