### ISSUE TITLE
Proxies not working

### ISSUE THREAD

**Issue by Pr0xy671** [kennethreitz/requests#3025]
My script shows that proxies aren't working. Am I doing something wrong? 
Here's the code if you need:
[Script.zip](https://github.com/kennethreitz/requests/files/149201/Script.zip)

**Comment by kennethreitz** [comment]
Code here:

``` python
# Important stuff here
from json import load
import requests
from random import choice, randint, shuffle
from urllib2 import urlopen

url = 'http://epiccodes.com' 

# Random proxies from - http://proxygaz.com
proxies = {'https': 'https:131.96.228.236:9064',
           'https': 'https:54.85.61.208:80',
           'https': 'https:54.209.36.19:80',}

# Retrieves IP Address
def IPAddress():
    IP = load(urlopen('http://httpbin.org/ip'))['origin']
    return(IP)

# Retrieves Cookie
def CookieIP():
    r = requests.get(url,
                     # Using proxy
                     proxies=proxies)
    try:
        Cookie = r.headers['Set-Cookie']
        return(Cookie)
    except KeyError as e:
        return("Website might be down")

# This prints your IP
print("IP Address: " + IPAddress())

# The website's cookie has your IP in it. If proxy works, then the IP on the
# cookie should be different from the other IP.
print("\nProxy's IP: " + CookieIP())

```

**Comment by sigmavirus24** [comment]
A few things:
1. If you look at [the proxy documentation](http://docs.python-requests.org/en/master/user/advanced/?highlight=proxies#proxies) you'll see that your proxy dictionary should look like this:
   
   ``` py
   proxies = {'https': 'https://131.96.228.236:9064'}
   ```
   
   Note the `//`.
2. You haven't described what kind of proxies these are. (Hint: If they're SOCKS proxies, those will not work with requests... yet.)
3. You haven't described what you're seeing versus what you're expecting.
4. Questions belong on [StackOverflow](https://stackoverflow.com/questions/tagged/python-requests). Please ask future questions there.

**Comment by Tosible** [comment]
1. If you look at my script (the one @kennethreitz  posted), that's what I did. 
   proxies = {'https': 'https:131.96.228.236:9064',
          'https': 'https:54.85.61.208:80',
          'https': 'https:54.209.36.19:80',}
2. The proxies I tried to use are HTTPS
3. If you look at the cookies for http://epiccodes.com, you'll see your IP in the cookies, I was expecting to see the proxy's IP in the cookie when I use proxies=proxies in the get request, instead of my actual IP.
4. My bad, I didn't know. Will do in the future if I have any questions.

**Comment by sigmavirus24** [comment]
> If you look at my script (the one @kennethreitz posted), that's what I did. 

It isn't. Please look closely at what you wrote and what I wrote. Further, which proxy do you expect to be used? Creating a dictionary with a repeated key is undefined behaviour (as to which value is kept) in Python.

**Comment by kennethreitz** [comment]
@Pr0xy671 you are specifying 3 proxies. Try only doing one. Also, add a `//` to your proxy URL.

p.s. you can use `http://httpbin.org/ip` to get ip address easily.

**Comment by Tosible** [comment]
Ok, I tried doing this way and still nothing.

r = requests.get('http://httpbin.org/ip', proxies={'https': 'https://89.163.131.168:3128'})
print(r.json()['origin'])

It then prints out my real IP and not 89.163.131.168

**Comment by jkbrzt** [comment]
@Pr0xy671 it's because you specified a proxy only for HTTPS (`{'https': …}`) but requested a HTTP page.
