### ISSUE TITLE
option to enable TCP level keepalive

### ISSUE THREAD

**Issue by woosley** [kennethreitz/requests#3026]
When there is firewall between client and server, http session will be killed even with keepalive enabled because no TCP level keepalive probe is sent. 

according to [here](http://tldp.org/HOWTO/TCP-Keepalive-HOWTO/usingkeepalive.html)
> Remember that keepalive support, even if configured in the kernel, is not the default behavior in Linux. Programs must request keepalive control for their sockets using the setsockopt interface. There are relatively few programs implementing keepalive

that said, is it possible to enable this behavior as an option in the library?

**Comment by Lukasa** [comment]
It is already possible: the requests tool belt provides a [Socket Options transport adapter](http://toolbelt.readthedocs.org/en/latest/adapters.html#socketoptionsadapter) that allows you to turn on TCP_KEEPALIVE.

**Comment by sigmavirus24** [comment]
There's also a separate keep alive adapter which subclasses the socket options adapter. That will ideally make things simpler for your usage

**Comment by kennethreitz** [comment]
If we're going to be responding to tickets like this, then we need to make Requests-Toolbelt more prominent in the documentation.
