### ISSUE TITLE
Strange behaviour in class dict

### ISSUE THREAD

**Issue by coveritytest** [kennethreitz/requests#3030]
Apparently the class does not like hyphens or percent sign.

cookies = dict(hottest-count='working')
SyntaxError: keyword can't be an expression

Same problem with cookies like %FOO%='bar'.

**Comment by Lukasa** [comment]
@coveritytest That has nothing to do with requests, and everything to do with Python: as the error reports to you, your _syntax_ is wrong.

Try: `cookies = {"hottest-count": "working"}`.
