### ISSUE TITLE
using ipv6 with requests 

### ISSUE THREAD

**Issue by 1a1a11a** [kennethreitz/requests#3037]
Hi I read previous issue on using requests on ipv6, but I don't quite understand how to update the HOST header, could someone point out? (suppose I already have ipv6 address of a website, how do request it?)
Or is there any better solution available now? 

Thank you!

**Comment by Lukasa** [comment]
It's not clear what you mean when you say "the previous issue", but I assume it is #3002, which is a bug. You can work around it by doing `requests.get('https://[fe80::00]', headers={'Host': 'fe80::00'})`. Alternatively, wait for the next release, which should contain a fix.
