### ISSUE TITLE
Proxy settings not working

### ISSUE THREAD

**Issue by janscas** [kennethreitz/requests#3039]
HI, using urllib2, I can connect through a proxy without problems. But, using requests it's not working:

http://stackoverflow.com/questions/35851227/python-requests-behind-proxy

Can anyone help?

**Comment by Lukasa** [comment]
Don't use `https` schemes. Your proxy dict should be:

``` python
proxy_dict = {
    'http': 'http://10.20.23.5:8080',
    'https': 'http://10.20.23.5:8080',
}
```

**Comment by alejcas** [comment]
It is not working...

Why urllib2 is doing it correctly and requests is unable to handle this?

**Comment by Lukasa** [comment]
I notice in your urllib2 code you aren't actually providing a list of proxies. That means it is reading the proxy information from the environment. Requests does that automatically, with no need to provide the proxies dictionary. Try removing it entirely and see if requests sorts the problem out for you.

**Comment by alejcas** [comment]
Same result with status code 407.

page = requests.get('http://www.google.com')

This returns:
'407 Proxy Authentication Required'

**Comment by Lukasa** [comment]
@janscas What operating system are you using?

**Comment by alejcas** [comment]
It's windows 8.1.
I'm behind a corporate proxy (Isa Server Forefront TMG)

It seams the urllib2 can take the proxy settings from the envirenment.

After doing this: 

proxy = urllib2.ProxyHandler({})
opener = urllib2.build_opener(proxy)
urllib2.install_opener(opener)

urllib2.getproxies() returns a dictionary with the correct proxies.

**Comment by Lukasa** [comment]
What's the result of `urllib.getproxies()`, please?

**Comment by alejcas** [comment]
it s python dict containing the proxies used by the system:

proxy_dict = urllib2.getproxies()
print proxy_dict
{'ftp': 'ftp://10.20.23.5:8080', 'http': 'http://10.20.23.5:8080', 'https': 'https://10.20.23.5:8080'}

**Comment by Lukasa** [comment]
Ok, can you print the headers from the 407 please?

**Comment by alejcas** [comment]
{'Content-Length': '4128', 'Via': '1.1 SRVMADISA08', 'Proxy-Connection': 'Keep-Alive', 'Proxy-Authenticate': 'Negotiate, Kerberos, NTLM', 'Connection': 'Keep-Alive', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache', 'Content-Type': 'text/html'}

**Comment by Lukasa** [comment]
Ok, so the problem here is that Requests does not out of the box support any of those authorization schemes for proxies. [Requests-NTLM](https://github.com/requests/requests-ntlm) does provide support for authenticating to a proxy, but it will require that you pass your domain credentials to requests NTLM.

**Comment by alejcas** [comment]
But... why urllib2 does this out of the box?

**Comment by Lukasa** [comment]
@janscas I have no idea. If you want to try to dive deeper into what urllib2 is doing that we're not, you could use Wireshark to check the differences between the request that requests sends and the one that urllib2 sends.

**Comment by alejcas** [comment]
ok, I'll check this and report back.

Thanks a lot
