### ISSUE TITLE
got response with 'Connection: close', instead of closing connection but still send message body

### ISSUE THREAD

**Issue by zjulmh** [kennethreitz/requests#3040]
When I post a big file to a server with invalid authorization, the server response with a `400` error response and with `"Connection: close"` header before read all the request body  and then close the connection, requests still send message body and get `connection aborted` exception, but according to [RFC7230](https://tools.ietf.org/html/rfc7230#section-6.5), the client `SHOULD` monitor the network connection for an error response and immediately cease transmitting the body and close its side of the connection.

**Comment by Lukasa** [comment]
@zjulmh This is a known problem. Unfortunately, the underlying HTTP library we're using makes it essentially impossible to actually do this: we only find out about the error response when the connection gets closed.

We'd need to replace httplib to avoid this problem, which is a substantial amount of work.
