### ISSUE TITLE
Suggest to user to install 'certifi' Python module if CA bundle is not found and 'certifi' is not loaded

### ISSUE THREAD

**Issue by aahancoc** [kennethreitz/requests#3044]
Requests grabs its CA bundle by either using the 'certifi' library, or if it's not installed, looking at the hard-coded filename 'cacert.pem'. The problem is that if you're on a Linux distro (ex: OpenSUSE) that doesn't have 'certifi' installed by default and doesn't have the CA bundle named 'cacert.pem', all you get is an unhelpful error telling you it could not find a suitable SSL CA certificate bundle.

What I'm suggesting is that, if the filename look fails and 'certifi' is not loaded, Requests adds a message in the "could not find a suitable SSL CA certificate bundle" error message that suggests that the user install 'certifi' to resolve the problem. It would save a lot of headache for people who aren't savvy enough to search the source code and figure out what they need to install in the first place.

**Comment by Lukasa** [comment]
@aahancoc Requests ships the `cacert.pem` bundle by default, which means that if you're on a Linux distribution and it cannot be found your distribution removed that file themselves. This means your distribution broke your install.

I recommend you take it up with the people breaking our software downstream. =)

**Comment by kennethreitz** [comment]
We may not want to encourage the distros to modify thecodebase even further.

Ugh.
