### ISSUE TITLE
python 3.5 requests 2.9.1 can not upload Chinese filename

### ISSUE THREAD

**Issue by pc10201** [kennethreitz/requests#3046]
source code

`import requests

headers = {
    'Origin': 'http://home.ctfile.com',
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.75 Safari/537.36',
    'Accept': '*/*',
    'Referer': 'http://home.ctfile.com/',
    'Accept-Encoding': 'gzip, deflate',
    'Accept-Language': 'zh-CN,zh;q=0.8',
}

files = {'file': open('中文.txt', 'rb')}
values = {'name': r'中文.txt', 'filesize': '101'}

url = 'xxxx'
r = requests.post(url, files=files, data=values, headers=headers)

print(r.content)`

I use fiddler to capture browser data.

The right data is:
Content-Disposition: form-data; name="file"; filename="中文.txt"

The python script data is 
Content-Disposition: form-data; name="file"; filename*=中文.txt

so I change 

Python35\Lib\site-packages\requests\packages\urllib3\fields.py

line 46-47 to

`    # value = email.utils.encode_rfc2231(value, 'utf-8')
    value = '%s="%s"' % (name, value)`

It is OK now.

**Comment by Lukasa** [comment]
> The right data is:
> Content-Disposition: form-data; name="file"; filename="中文.txt"

That is not the right data. This is:

```
Content-Disposition: form-data; name="file"; filename*=utf-8''%E4%B8%AD%E6%96%87.txt
```

This uses RFC 2231 already. To achieve it, change your code to this:

``` python
files = {'file': open(u'中文.txt', 'rb')}
values = {'name': r'中文.txt', 'filesize': '101'}

url = 'xxxx'
r = requests.post(url, files=files, data=values, headers=headers)
```

**Comment by pc10201** [comment]
The fiddler right data screenshot

![img1](https://cloud.githubusercontent.com/assets/8475089/13702662/36592330-e7cb-11e5-8d99-7ddb6d0739e8.jpg)

![img2](https://cloud.githubusercontent.com/assets/8475089/13702668/3ed008f8-e7cb-11e5-8fad-80bd2bbf3ad6.jpg)

not like
 filename*=utf-8''%E4%B8%AD%E6%96%87.txt

**Comment by Lukasa** [comment]
@pc10201 Did you change your code to match mine, _including_ the unicode string for opening the file?

**Comment by pc10201** [comment]
I will try tomorrow.I will tell you result.

**Comment by pc10201** [comment]
I tried your code.
It do not work
![img3](https://cloud.githubusercontent.com/assets/8475089/13703163/d4c33026-e7ce-11e5-9db1-efa3ec9ece0c.jpg)
![img4](https://cloud.githubusercontent.com/assets/8475089/13703164/d51a0ebe-e7ce-11e5-8c39-74adbd66d6b7.jpg)

If you use windows,you can use fiddler to capture http data.
if you use linux or mac os,you can use wireshark.

**Comment by Lukasa** [comment]
@pc10201 In what sense is that not working? I see the filename field formatted correctly.

**Comment by pc10201** [comment]
The server response is not right.
The right data

![img1](https://cloud.githubusercontent.com/assets/8475089/13703995/74192cf2-e7d4-11e5-88a0-e9bebf7755b4.jpg)

The bad data
![img3](https://cloud.githubusercontent.com/assets/8475089/13704002/7b5e663a-e7d4-11e5-9d25-a4fb06d627e2.jpg)

Please check the third line with each image.

**Comment by Lukasa** [comment]
Assuming for a moment that the different filenames are unrelated to this problem, the issue here is that the "right" case is not using RFC 2231 encoding. This is common, but _wrong_: the server needs to be able to handle the RFC 2231-encoded filename, which is what we're providing.

**Comment by pc10201** [comment]
You are right.The server may cause this problem.Please close this issue.
