### ISSUE TITLE
Set a default timeout on a Session instance

### ISSUE THREAD

**Issue by rgov** [kennethreitz/requests#3054]
It would be useful to be able to set a default timeout on a Session instance, which would get used for any requests initiated from that Session in lieu of an explicitly supplied timeout.

**Comment by Lukasa** [comment]
Please search the issue repository before you open new issues. If you had done so you'd have seen #2856 and #2011 which both cover this issue.

**Comment by sigmavirus24** [comment]
In the future please search the closed issues for similar ideas. This is one we have rejected numerous times. Further it is trivial to subclass the session class to provide this.
