### ISSUE TITLE
Honor HTTP public key pinning headers for server certificate validation

### ISSUE THREAD

**Issue by asieira** [kennethreitz/requests#3063]
An interesting protection against MITM attacks could be provided by default if requests looked for and honored [Public-Key-Pins](https://en.wikipedia.org/wiki/HTTP_Public_Key_Pinning) headers in the server response for additional validation of the certificate presented.

**Comment by Lukasa** [comment]
@asieira This is an idea we've been interested in for a long time: see shazow/urllib3#607.

Unfortunately, any support we're likely to have will be of minimal use in practice unless deliberate effort is taken to harden your application. We'd need a cache in non-ephemeral storage (or the exit of your app cleans the in-memory cache), and PKP headers are extremely uncommon.

Regardless, the issue to track is the one linked above.

**Comment by asieira** [comment]
Perfect, thank you! :bow:
