### ISSUE TITLE
Honor HTTP strict transport security headers

### ISSUE THREAD

**Issue by asieira** [kennethreitz/requests#3064]
[HTTP strict transport security header](https://scotthelme.co.uk/hsts-the-missing-link-in-tls/) helps protect web applications against communications interception and MITM attacks. I would recommend that requests look for and honor the header by default.

**Comment by Lukasa** [comment]
See shazow/urllib3#608, and the comment I just made on #3063: the same limitations that apply there apply here.

**Comment by asieira** [comment]
Perfect, thank you! :bow:
