### ISSUE TITLE
No way to make requests redirect POST/PUT/DELETE requests

### ISSUE THREAD

**Issue by vmalloc** [kennethreitz/requests#3067]
In the documentation (see http://docs.python-requests.org/en/latest/api/#requests.request) it says that specifying *allow_redirects* to `True` means that redirecting POST/PUT/DELETE is allowed.

Quick attempts show that the reality is that those requests *ALWAYS* get redirected as `GET`s, even when this parameter is True (which it is by default). It seems like the tests [here](https://github.com/kennethreitz/requests/blame/3acf3a723892550719ca23bfe1be07549a8ad201/tests/test_requests.py#L165) support this claim.

The one commented out test [here](https://github.com/kennethreitz/requests/blame/3acf3a723892550719ca23bfe1be07549a8ad201/tests/test_requests.py#L208) supports the statement from the documentation, but is commented out (the reason seems to be a bug in httpbin, but no further explanation is supplied)

**Comment by Lukasa** [comment]
Requests will change the verb used for a redirect in the following cases:
- On a 303 See Other response, HEAD and GET are left alone: all other verbs get changed to GET, as per [RFC 7231 Section 6.4.4](https://tools.ietf.org/html/rfc7231#section-6.4.4).
- On a 302 Found response, HEAD and GET are left alone: all other verbs get changed to GET. This is allowed by the note in [RFC 7231 Section 6.4.3](https://tools.ietf.org/html/rfc7231#section-6.4.3), and is extremely common behaviour with all browsers.
- On a 301 Moved Permanently response, POST is changed to GET. All other verbs are left alone. Again, this is allowed by the note in [RFC 7231 Section 6.4.2](https://tools.ietf.org/html/rfc7231#section-6.4.2) and is extremely common behaviour with browsers.

While requests allows redirects, it uses the semantic meaning in the status code to potentially adjust the redirect verb. If a server explicitly wants the redirected user agent to keep the verb the same in all circumstances, servers should use 307 Temporary Redirect and 308 Permanent Redirect.

**Comment by vmalloc** [comment]
:+1: thanks. You learn something new every day...

**Comment by kennethreitz** [comment]
@lukasa we should add your snippet of text there to the docs. Doubt it'll reduce incoming issues (questions) around this, but it'd be great for the docs.
