### ISSUE TITLE
find_no_duplicates raise KeyError

### ISSUE THREAD

**Issue by jackyliang** [kennethreitz/requests#3072]
Hi there!

I am currently on `requests version: 2.9.1` I have getting the following error in my code:

```
Traceback (most recent call last):
  File "./add.py", line 98, in <module>
    'SESSID':term.cookies['SESSID'],
  File "/usr/local/lib/python2.7/site-packages/requests/cookies.py", line 276, in __getitem__
    return self._find_no_duplicates(name)
  File "/usr/local/lib/python2.7/site-packages/requests/cookies.py", line 331, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='SESSID', domain=None, path=None"
```

Line 98 in `add.py` refers to the following:

    # Grab the Add/Drop Class page cookies                                
    ad_cookie = {                                                         
        'SESSID':term.cookies['SESSID'],                                  
        'IDMSESSID':username                                              
    } 

Just to make sure that the particular cookie in that page was not removed or missing, I checked the cURL for when I hit that page, and surely enough, both `SESSID` and `IDMSESSID` were in that cURL request.

Wondering what the issue is?

**Comment by Lukasa** [comment]
Don't check curl, check requests. =) Can you print out:

```
for resp in response.history:
    print resp.headers
print response.headers
```

That should provide information about what cookies got set.

**Comment by jackyliang** [comment]
@Lukasa I feel dumb! Turns out my `username` and `password` were incorrect, and thus I was not authenticated, and thus no cookie. My bad. Thanks for the super quick reply though, Lukasa!

**Comment by Lukasa** [comment]
No problem, glad you got it sorted out!
