### ISSUE TITLE
The request module redirects to a wrong URL if the 'Location' field of the response header contains utf-8 characters.

### ISSUE THREAD

**Issue by odlbo** [kennethreitz/requests#3078]
Hello!

The requests module redirects to a wrong URL if the 'Location' field of the response header contains UTF-8 characters (for example,  https://picsrch.me/wCtd3uQF). The server typically does not return a response containing UTF-8 characters in the 'Location' field, but many HTTP clients (Firefox, Chrome, Wget, etc.) react correctly. As I can see, this module tries to solve this problem as well.

The main problem is that http.client module (which is used by requests module) decodes all fields in latin1, but requests module uses utf-8 encoding to prepare URL from 'Location' field (we can see this behavior in urllib.parse.quote function).

P.S.:
Python    - 3.4.0
requests - 2.8.1

**Comment by Lukasa** [comment]
Hi there!

This is a known issue that has a fix prepared for the 3.0.0 release: see #2754. Unfortunately, this change will subtly change the logic of the code for a lot of people, which is why it's scheduled for 3.0.0. However, we're aiming to have the 3.0.0 release out in the first half of this year.

**Comment by odlbo** [comment]
Ok. Thanks! :)

**Comment by 1600** [comment]
when will the 3.0 release be out? from the situation I have this issue persists and looks like its not just for utf-8 Location header.

**Comment by nateprewitt** [comment]
@1600 we don't have a hard date for 3.0 at this time as we're waiting for some work on urllib3 to be completed before we can look at creating a release.
