### ISSUE TITLE
Missing double quotation marks at "requests/packages/urllib3/fields.py" Line 46

### ISSUE THREAD

**Issue by imnisen** [kennethreitz/requests#3081]
value = '%s*=%s' % (name, value)
should not be
value = '%s*="%s"' % (name, value)
:)

**Comment by imnisen** [comment]
Oh sorry, i miss the "*", so the question is:


value = '%s*=%s' % (name, value)
should not be
value = '%s*="%s"' % (name, value)

thanks

**Comment by Lukasa** [comment]
Thanks for this report!

No double quotation mark is required here. All the characters that would require a quotation mark (e.g. spaces) are percent-encoded by `encode_rfc2231`. This means that, per that RFC, no quotation mark is required. =)
