### ISSUE TITLE
requests attempts to use IPv6 even when IPv6 is disabled

### ISSUE THREAD

**Issue by kz26** [kennethreitz/requests#3084]
This is an issue when running on a server without IPv6 (must be disabled because the network does not support it). Example when connecting to https://graph.facebook.com and IPv4 happens to fail:

Python 3.4.3, requests 2.9.1, `ipv6.disabled=1` in kernel, `gai.conf` set to prefer IPv4

```python
HTTPSConnectionPool(host='graph.facebook.com', port=443): Max retries exceeded with url: /v2.5/me/feed (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f4dbd158518>: Failed to establish a new connection: [Errno 97] Address family not supported by protocol',))
Traceback (most recent call last):
  File "/home/lib/python3.4/site-packages/requests/packages/urllib3/connection.py", line 137, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/home/lib/python3.4/site-packages/requests/packages/urllib3/util/connection.py", line 91, in create_connection
    raise err
  File "/home/lib/python3.4/site-packages/requests/packages/urllib3/util/connection.py", line 71, in create_connection
    sock = socket.socket(af, socktype, proto)
  File "/usr/lib/python3.4/socket.py", line 126, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 97] Address family not supported by protocol
```

**Comment by Lukasa** [comment]
Requests doesn't do much special here. Requests calls `getaddrinfo` and then iterates through the entries in the order returned from `getaddrinfo` attempting to connect to each one in turn.

That exception only gets raised if we've attempted all our connections and they all fail. We then raise the final exception we saw. The bigger problem here seems to be that we're swallowing perfectly reasonable exceptions earlier in the chain that reveal the underlying problem in situations when IPv6 or IPv4 are enabled.

That code all lives in [urllib3](https://github.com/shazow/urllib3), would you like to open this issue over there so we can track it appropriately?

**Comment by kz26** [comment]
That's fair. I'll open a ticket on urllib3.
