### ISSUE TITLE
Is there a way to specify filename in the post data?

### ISSUE THREAD

**Issue by imnisen** [kennethreitz/requests#3085]
Hi, 
For example, I want to upload a video called "测试中文视频.mp4", which will be converted to`filename*=utf-8''%E6%B5%8B%E......`, the problem is that my working server does not recognize this format, so, is there a method to tell requests to convert the request message to like this: `filename=测试中文视频.mp4` or like this: `filename=u'\u6d4b\u8bd5\u4e2d\u6587\u89c6\u9891.mp4'`.

Thanks very much!

**Comment by StewPoll** [comment]
I haven't worked on this, but a PreparedRequest I believe is what you want.

**Comment by Lukasa** [comment]
There is no builtin method to make requests do this, nor will there be: servers that don't understand the format requests uses are old an non-standards-compliant. However, as @TetraEtc points out, you can use the [PreparedRequest flow](http://docs.python-requests.org/en/master/user/advanced/#prepared-requests) to mutate the body as you wish to, which would allow you to change the multipart-encoded body to whatever form you like.

You can also manually set the filename yourself by using longer tuples in the [files parameter](http://docs.python-requests.org/en/master/api/#requests.request): in particular, if you use a _bytestring_ in the filename portion then requests will leave it alone.

**Comment by imnisen** [comment]
@TetraEtc thanks, I have succeed using  urllib2 to send the data which encoded manually, although it is a boring work. I will also try the PreparedRequest method.

@Lukasa  do you mean use  something like `"测试中文视频.mp4".encode('utf-8')` in the filename portion?
 when I try this, because of `result.encode('ascii')` (at requests/packages/urllib3/fields line38) fail, the post content is also  changed to something like this `filename*='%E6%B5%8B%E8%AF%95%E4%B8%AD%E6%96%87%E...`, which is not I want

Thank you.

**Comment by Lukasa** [comment]
Ah, yup, that'll do it. So yes, in that case I'm afraid you will have to use the prepared request flow to tweak the body.
