### ISSUE TITLE
Is there a mistake on requests/docs/user/quickstart.rst

### ISSUE THREAD

**Issue by gaoxinge** [kennethreitz/requests#3087]
I am reading the official document of requests. There is one code in quickstart.rst

```python
>>> payload = {'key1': 'value1', 'key2': ['value2', 'value3']}
>>> r = requests.get('http://httpbin.org/get', params=payload)
>>> print(r.url)
```

However, the output is

```python
http://httpbin.org/get?key2=value2&key2=value3&key1=value1
```

instead of what is in rst?

Is this a small mistake?

**Comment by Lukasa** [comment]
No. =)

Python dictionaries are _unordered_: that is, when iterated over the order in which elements are returned is not well defined. That means that iterating over the dictionary above can give you two possible options: first `'key1'` then `'key2'`, or first `'key2'` then `'key1'`. The first case gives you the code from the documentation, the second one gives you the code you saw.

If you repeatedly re-run the same code, you should see both URLs. This is not a bug in requests or in Python, it's just an expected side effect of the way Python works.
