### ISSUE TITLE
badTimezone: cannot clone with git 2.8.1

### ISSUE THREAD

**Issue by rillian** [kennethreitz/requests#3088]
I can't clone this repo. It complains:

```
$ git clone https://github.com/kennethreitz/requests
Cloning into 'requests'...
remote: Counting objects: 17048, done.
remote: Compressing objects: 100% (39/39), done.
error: object 5e6ecdad9f69b1ff789a17733b8edc6fd7091bd8: badTimezone: invalid author/committer line - bad time zone
fatal: Error in object
fatal: index-pack failed
```

**Comment by Lukasa** [comment]
This is a known problem: see #3008 and #2690 for previous discussions. The problem can be easily resolved on your end either by performing a shallow clone (if you don't need the history) or turning off the fsck timestamp check.

**Comment by rillian** [comment]
Thanks for the quick response.

**Comment by kennethreitz** [comment]
@rillian did you enable verification yourself or did another tool do that?

**Comment by rillian** [comment]
You're right, I have those options set in my ~/.gitconfig; it's nothing to do with the git version. I don't know if I did it manually or if one of our audit tools added it, because how is that not the default? :/

``` ini
[transfer]
          fsckobjects = true
[fetch]
          fsckobjects = true
[receive]
          fsckObjects = true 
```

I've been trying to figure out how to get YCM to work around this, but it's tricky with submodules because an initial shallow clone generally fails. There doesn't seem to be a `fetch.fsckBadTimezone`. I couldn't get your `$ git config fsck.badTimezone ignore` suggestion to work, just disabling `fetch.fsckObjects` entirely.

**Comment by rogueresistor** [comment]
```git config --global fetch.fsck.badTimezone ignore```

Works for me when cloning submodules, this just disables it for fetch.
