### ISSUE TITLE
Token string add error

### ISSUE THREAD

**Issue by Nuruddinjr** [kennethreitz/requests#3093]
```python
url = "https://graph.facebook.com/v2.6/me/subscribed_apps?access_token="+self.token
        data = {}
        if url:
            data['url'] = url
        result = requests.post(url, data)
```
Above code generating following error, even though schema is defined as in url. how to fix?
```
requests.exceptions.MissingSchema: Invalid URL '%sreally long string , facebook token':
No schema supplied. Perhaps you meant http://%sreally long string , facebook token?
```

**Comment by Nuruddinjr** [comment]
EAAHEisMO9u8BABL41ZCoUFeXRWzhhjxDb0jDNzyH7YdJeFVpUoYpRrqhp96YKkDrfzqFJfclbqhOZB4MMvihAOS2XBJLYpLDGLIyZAuXBuo8gpddNICEgc7Xo8mRGBH6F9q38ZALItZCaGfytrs59dPLRhi9ibEYeC2Pi0AbXXXXXXXX my token is as following

**Comment by Lukasa** [comment]
@Nuruddinjr Can you print the actual error message? It seems like the URL you've built is invalid, which suggests that the code you're using right now isn't correct in some way.

**Comment by sigmavirus24** [comment]
@Nuruddinjr please answer @Lukasa soon. Otherwise, I'm going to close this issue as it does not appear to be a bug.
