### ISSUE TITLE
How to find what proxies Requests is using?

### ISSUE THREAD

**Issue by thuzhf** [kennethreitz/requests#3101]
I set no proxies in environment variables, but I set proxies in system configuration on my MacOS. And I find that Requests use it automatically (by checking what responses I get), but it seems this feature is not pointed out in your documentation. So is there any way to see what proxies are Requests is using? Will it automatically use what urllib.request.getproxies() return?

**Comment by Lukasa** [comment]
You can call `requests.utils.get_environ_proxies(url)`, where the URL is the URL you're accessing. That will show you what proxies we found.
