### ISSUE TITLE
Sticker Design [Kenneth]

### ISSUE THREAD

**Issue by kennethreitz** [kennethreitz/requests#3105]
Using this as a place to throw things i find that I like. 

Going to use StickerMule, not StickerRobot. Undecided on size or design, yet. 

I like the idea of using 99designs to come up with the sticker. Would be far more expensive than doing it myself, but I'd rather be handing out *amazing* stickers at a conference than mediocre ones (for an amazing project).

**Comment by kennethreitz** [comment]
http://99designs.com

**Comment by kennethreitz** [comment]
Turtles (evolutions of Rezzy the sea turtle, possibly):
- http://graphicriver.net/item/turtle/10194964?s_rank=6 (cute, but not a sea turtle)
- http://graphicriver.net/item/cartoon-turtle/12865148?s_rank=38 (running, meh)
- http://graphicriver.net/item/cartoon-turtle/9991241?s_rank=49 (i really like this one, very similar to current Rezzy)
- http://graphicriver.net/item/vector-turtle-tattoo/8725608?s_rank=157 (super dope, very different)

Undecided if "sea turtle" is important. I feel like it is.

**Comment by kennethreitz** [comment]
Experimented with using the current Rezzy, of course. This could work, but I think the stickers are an opportunity to play with Rezzy as a concept, not as that specific image.

**Comment by Lukasa** [comment]
> Would be far more expensive than doing it myself, but I'd rather be handing out amazing stickers at a conference than mediocre ones (for an amazing project).

I'll be handing out mediocre ones. =D

**Comment by kennethreitz** [comment]
99design's prices have gone up, won't be using them.

**Comment by kennethreitz** [comment]
$ pip install requests

**Comment by kennethreitz** [comment]
Shipped!
