### ISSUE TITLE
utils.select_proxy raises an exception when URL has no hostname

### ISSUE THREAD

**Issue by chipaca** [kennethreitz/requests#3131]
URLs sometimes have no hostname (e.g. file URLs, or unix socket URLs). The parsed URL `hostname` attribute returns `None` in this case, making `utils.select_proxy` complain about concat'ing a `str` with `None`.

**Comment by sigmavirus24** [comment]
@chipaca keep in mind that whatever adapter you're using will have to deal with older versions of requests and if it's not meant to touch the network should not be inheriting from the HTTPAdapter.

**Comment by chipaca** [comment]
@sigmavirus24 I'm using https://github.com/msabramo/requests-unixsocket/ which does inherit from `HTTPAdapter`. I'm not sure what you mean, though; where does "touching the network" become a factor?

**Comment by sigmavirus24** [comment]
If you're using a `file://` URI, you're never going to talk to something over the network using HTTP (for example). I'll talk to @msabramo about fixing unixsocket as this problem will persist otherwise for several people who will not get this fix.

**Comment by sigmavirus24** [comment]
I'm curious how you saw this exception while using that library. Looking at unixsocket's code, it overrides the method which is the one place where [`select_proxy` is used in requests](https://github.com/kennethreitz/requests/blob/60aee145b96a4cf13a7daefd8578d538fe8459a8/requests/adapters.py#L250).

**Comment by chipaca** [comment]
it's used in one more place: `HTTPAdapter.request_url`.

On Tue, Apr 26, 2016 at 3:56 PM, Ian Cordasco notifications@github.com
wrote:

> I'm curious how you saw this exception there. Looking at unixsocket's
> code, it overrides the method which is the one place where select_proxy
> is used in requests
> https://github.com/kennethreitz/requests/blob/60aee145b96a4cf13a7daefd8578d538fe8459a8/requests/adapters.py#L250
> .
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/kennethreitz/requests/issues/3131#issuecomment-214772376

## 

John Lenton (jlenton@gmail.com) ::: http://chipaca.com

**Comment by chipaca** [comment]
As to where I'm using it, I'm using it to connect to a unix socket :-)
I packaged httpie as a snap (originally for snappy ubuntu core systems, now on ubuntu classic itself), and added support for unix sockets so that it could talk to the snappy daemon. That's on https://github.com/chipaca/httpie-snap fwiw.

**Comment by sigmavirus24** [comment]
Ah so @msabramo should be overriding that too if he continues to subclass the adapter. (I missed the usage in the `request_url` method because GitHub search hasn't indexed that yet apparently.)

**Comment by kennethreitz** [comment]
I didn't know about requests-unixsocket! We must catalogue these extensions somewhere.

**Comment by msabramo** [comment]
Hmmm, but don't unixsocket URLs always have a "hostname" Because the "hostname" is a URL-encoded path to the socket on the filesystem. E.g.:

```
[38] > /Users/marca/dev/git-repos/requests/requests/utils.py(592)select_proxy()
-> proxy = proxies.get(urlparts.scheme+'://'+urlparts.hostname)
(Pdb++) urlparts
ParseResult(scheme='http+unix', netloc='%2Ftmp%2Ftest_requests.132820227_21127_b4f4da9f', path='/path/to/page', params='', query='', fragment='')
(Pdb++) urlparts.scheme
'http+unix'
(Pdb++) urlparts.hostname
'%2ftmp%2ftest_requests.132820227_21127_b4f4da9f'
```
