### ISSUE TITLE
requests.cookies hardcodes a root path attribute

### ISSUE THREAD

**Issue by evnm** [kennethreitz/requests#3135]
While trying to figure out how to set specific [path attributes](https://en.wikipedia.org/wiki/HTTP_cookie#Domain_and_Path) in cookies when using requests, I noticed that `RequestsCookieJar` [hardcodes the root path](https://github.com/kennethreitz/requests/blob/bbeb0001cdc657ac8c7fef98e154229bc392db0e/requests/cookies.py#L400) when cookies are created and doesn't seem to allow this default to be overridden.

Is there a reason for this? If not, would the maintainers be open to a PR modifying `create_cookie` to heed a `path` specified in `kwargs`?

**Comment by Lukasa** [comment]
@evnm That reading of the code is not right. =)

You'll notice [here](https://github.com/kennethreitz/requests/blob/bbeb0001cdc657ac8c7fef98e154229bc392db0e/requests/cookies.py#L414) that we call `update` with the kwargs. That will override the path if you provide it. Try it: `create_cookie('key', 'value', path='/some/path')` should work just fine.

**Comment by evnm** [comment]
Ah, cool. An object lesson on careful code-reading. Thanks for taking the time to point that out!

**Comment by Lukasa** [comment]
No problem, thanks for checking with us! :sparkles:
