### ISSUE TITLE
Possible NameError if unexpected encryption algorithm encountered.

### ISSUE THREAD

**Issue by markshannon** [kennethreitz/requests#3138]
`HTTPDigestAuth.build_digest_header` may fail with a NameError if encryption algorithm is not one of
 'MD5', 'MD5-SESS' or 'SHA.
https://github.com/kennethreitz/requests/blob/master/requests/auth.py#L117

**Comment by Lukasa** [comment]
Yup, that looks wrong. Looks like that name needs to be initialised to `None`. Want to provide a patch?

**Comment by markshannon** [comment]
I thought I'd leave that to those of you who know the code base, in case there was something more subtle going on. I'm happy to make a PR if you want.

**Comment by Lukasa** [comment]
PRs always appreciated!
