### ISSUE TITLE
how to use socks proxy ?

### ISSUE THREAD

**Issue by iliul** [kennethreitz/requests#3172]
The new feature socks proxy is supported，but how to use it ?

 no example In [http://www.python-requests.org/en/master/user/advanced/#proxies](http://www.python-requests.org/en/master/user/advanced/#proxies) .

**Comment by Lukasa** [comment]
Yup, that's a good spot.

To do it, you need to `pip install requests[socks]`, and then you can set the proxy as normal: `proxies={'http': 'socks5://host:port', 'https': 'socks5://host:port'}`.

**Comment by iliul** [comment]
Thanks and  I got it @Lukasa

**Comment by Lukasa** [comment]
The pull request #3173 should add the needed section. Thanks for the report @iliul! :sparkles:

**Comment by ljdawn** [comment]
Hi. When I'm using proxy = {'http': 'socks5://IP:PORT', 'https': 'socks5:///IP:PORT'}, I got "AssertionError: Not supported proxy scheme socks5". I had upgraded my requests and env is mac osx.
