### ISSUE TITLE
Gzipping requests

### ISSUE THREAD

**Issue by kuraga** [kennethreitz/requests#3175]
Good day!

Does `requests` functionality of encoding POST requests with `gzip`?

If no, will you accept a pull request? Some notes, maybe?

Thanks!

**Comment by Lukasa** [comment]
@kuraga Requests does not currently support doing this automatically. =) However, doing so is fairly simple. I don't think we'd accept a pull request adding this functionality (it's not likely to be generally useful), but we'd certainly be happy to add an example to our documentation.

**Comment by kuraga** [comment]
Ok, thanks!

P.S.

> it's not likely to be generally useful

Disagree =) But yes, one more dependency...
