### ISSUE TITLE
OSError: [Errno 22] in self.sock.sendall(data)

### ISSUE THREAD

**Issue by AstinCHOI** [kennethreitz/requests#3180]
env: Mac OS X El Capitan / python 3.5.1 / requests 2.10.0  

I want to upload file which is about 3GB size.

```py
    def read_in_chunks(file_object, chunk_size=4096):
        while True:
            data = file_object.read(chunk_size)
            if not data:
                break
            yield data

    with open('3GB.mov', 'br') as f:
        data = b''.join([chunk for chunk in read_in_chunks(f)])

    requests.put(url, headers=headers, data=data)
```

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 1240, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1083, in request
    self._send_request(method, url, body, headers)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1128, in _send_request
    self.endheaders(body)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1079, in endheaders
    self._send_output(message_body)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 913, in _send_output
    self.send(message_body)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 885, in send
    self.sock.sendall(data)
OSError: [Errno 22] Invalid argument
```

Could you give me some advice?

**Comment by sigmavirus24** [comment]
Hi @AstinCHOI,

This is a defect tracker, not a question and answer portion of the requests project. If you're looking for help (which it appears you are) please pose questions on [StackOverflow](https://stackoverflow.com/questions/tagged/python-requests). When posting there, please be prepared to answer questions such as:
- Why are you using a generator and then joining it into a single byte string in memory?
- Why does your traceback not include any code from the requests library?

**Comment by AstinCHOI** [comment]
Hi, @sigmavirus24 
1) http://stackoverflow.com/questions/11662960/ioerror-errno-22-invalid-argument-when-reading-writing-large-bytestring and it's my fault to use like that.
2) Sorry, I couldn't include the traceback with requests due to some logic.. but there is problem when you use data=data which is above 2GB size binary in OS X. If you use OSX, you can test it.

Naver mind. I will post in StackOverflow.

Thanks.

**Comment by AstinCHOI** [comment]
In OS X, alternative way (for some versions): http://stackoverflow.com/questions/2502596/python-http-post-a-large-file-with-streaming and it can post/put with big files.

It was not requests module fault.

Thanks.
