### ISSUE TITLE
Sending too much personal information in User-Anget. Risky

### ISSUE THREAD

**Issue by Logmytech** [kennethreitz/requests#3182]
```
>>> r.request.headers["User-Agent"]
'python-requests/2.x.x CPython/x.x.x Linux/3.xx.xx-generic'
```

I think requests is sending too much info.
The bot name `"python-requests" would be okay.

But my **Python version which may be vulnerable** ?

My Linux **kernel version which may be vulnerable**?

I consider this a big problem. Many people using requests may not be aware of this and inadvertently sending this info.

Please just change the the `User-Agent` to something like
`"python-requests"` or `"Requests"`

**Comment by Lukasa** [comment]
@Logmytech We did. Note our [changelog](http://docs.python-requests.org/en/master/community/updates/#id6), which says that we updated in 2.8.0, released 7 months ago. =)
