### ISSUE TITLE
Feature request: support ALL_PROXY environment variable

### ISSUE THREAD

**Issue by brettdh** [kennethreitz/requests#3183]
As of 2.10.0, I can set `HTTP_PROXY=socks5://example.com:port`, and then requests will use that SOCKS proxy. However, other tools (e.g. Docker) currently require the use of `ALL_PROXY` instead, and get confused if you set `HTTP_PROXY` to a URL that begins with `socks5://`. I think Docker should support the use of `HTTP_PROXY`, but requests should also support the use of `ALL_PROXY`, especially with the recent (thank you thank you thank you) addition of SOCKS support.

I thought that this might need to go through urllib3, but it seems like it would be a relatively simple change to [sessions.py], to look at the `'all'` key before checking the scheme. But, then I read your contributor's guide and thought it best to post an issue before just doing it. :smile:

Please let me know what you think.

[sessions.py]: https://github.com/kennethreitz/requests/blob/master/requests/sessions.py#L212

**Comment by Lukasa** [comment]
Thanks for the suggestion!

I don't think we need to go through urllib3: your analysis is right, sessions.py can DTRT here. I think this is a reasonable enhancment, so we'd welcome a pull request for this.

**Comment by brettdh** [comment]
Great, thanks for the super-quick answer! I'm happy to pick this up and will start looking into it shortly.
