### ISSUE TITLE
GAE and ChunkedEncodingError, working patch.

### ISSUE THREAD

**Issue by cnicodeme** [kennethreitz/requests#3187]
Hey everyone,

sorry for my intervention here, "out of the blue". I tried to understand if this issue was already discussed (but could find them) so I come here with the situation and trying to understand the solution.

The problem is the following (from what I understood) : Google App Engine, replace the implementation of urlfetch by their own, which contains some changes that breaks urllib3 and subsequently Requests.

@agfor [made a fix](https://github.com/agfor/requests/commit/da863cc) that seems to work (I didn't had any ChunkedEncodingError since I place the patch on line) and, from my understanding, doesn't break the others users, those that don't use GAE.

I didn't saw his patch as submitted here (I'm wondering why) and I don't know why this hasn't been taken into consideration here. (Please note those are real question, not critics/remarks, my intentions are good :) ).

Hence my post :)

**Comment by Lukasa** [comment]
@cnicodeme The requests project does not consider GAE formally supported. Put another way, we don't have any special-case code _in requests_ to use GAE properly. The recommended method of using GoogleAppEngine with requests is to use the [requests-toolbelt `AppEngineAdapter`](http://toolbelt.readthedocs.io/en/latest/adapters.html#appengineadapter).

**Comment by cnicodeme** [comment]
Ok that explains all my questions, thank you !

(and wow, you're fast!)

**Comment by Lukasa** [comment]
My pleasure!
