### ISSUE TITLE
Add support for in-memory multipart upload

### ISSUE THREAD

**Issue by wujek-srujek** [kennethreitz/requests#3194]
As far as I can understand from the docs, it is possible to upload files using the 'files' keyword param, but it requires a file object. I have a case where I have the data in memory, and it would require me to store to a temp file, which I would like to prevent if possible.
Would it be possible for requests to support in-memory data upload for multipart?

**Comment by Lukasa** [comment]
It already does. =) Note the description for the files kwarg in [this bit of documentation](http://docs.python-requests.org/en/master/api/#requests.request).

**Comment by Lukasa** [comment]
Also [this section of the narrative documentation](http://docs.python-requests.org/en/master/user/quickstart/#post-a-multipart-encoded-file) mentions it.

**Comment by wujek-srujek** [comment]
But it requires a 'file-like object', doesn't it? What I meant is I have a byte buffer in memory (an instance of the bytes type in Python 3), not a file. For this interface to work I have to write to a temp file and upload this (at least that's what I am doing now).

**Comment by Lukasa** [comment]
> But it requires a 'file-like object', doesn't it?

No. Let me quote [the narrative documentation](http://docs.python-requests.org/en/master/user/quickstart/#post-a-multipart-encoded-file) here:

> If you want, you can send strings to be received as files:
> 
> ```
> >>> url = 'http://httpbin.org/post'
> >>> files = {'file': ('report.csv', 'some,data,to,send\nanother,row,to,send\n')}
> 
> >>> r = requests.post(url, files=files)
> >>> r.text
> {
>   ...
>   "files": {
>     "file": "some,data,to,send\\nanother,row,to,send\\n"
>   },
>   ...
> }
> ```

**Comment by wujek-srujek** [comment]
Right, sorry, I was a bit mislead by the 'string' wording in the example. For me, it didn't seem like an instance of bytes could also be passed. I guess the documentation could be improved on this - the 'files' keyword description should probably say it is not really necessary for it to be a fileobj, and the narrative docs should say it can also be a bytes instance, not only a string. (Although it rings a bell that in Python 2.x things were calles 'byte strings', maybe that's where it comes from?)

But thank you anyways, I tested it and it works, and I prefer this way than mess around with temporary files.

**Comment by Lukasa** [comment]
> (Although it rings a bell that in Python 2.x things were calles 'byte strings', maybe that's where it comes from?)

Yup. In Python 2, strings were by default byte strings, which is very similar to the Python 3 `bytes` type. This convention has stuck around for those of us who write Python 2/3 compatible code.
