### ISSUE TITLE
redirect with odd (but correct) Location url fails via proxy

### ISSUE THREAD

**Issue by mgdelmonte** [kennethreitz/requests#3196]
Using v2.10.0 (but tested and get same behavior with 2.9.1), if we get a 302 redirect with a header like this (note the missing trailing slash after the domain):

Location: http://captrust.netxinvestor.com?custId=....

AND we're using a proxy (proxy in question is tinyproxy, but tested with other proxies and get same behavior)

AND allow_redirects=True

the proxy will fail with "cannot connect" because the domain in the Location url is improperly parsed.

Firefox and Chrome both properly handle the redirect.  To be honest I haven't checked whether the Location URL does or does not violate the spec, but if the browsers handle it and it appears to be unambiguous I'd vote for `requests` handling it also.  Seems like an easy patch, though I must also confess that I've stepped through the code and can't find where to handle it.

Oddly, if that exact URL is passed to requests as a GET, even via a proxy, it works fine -- so my guess is that it happens somewhere in the SessionRedirectMixin object.

Workaround right now is to request with allow_redirects=False and handle the redirect manually.

**Comment by Lukasa** [comment]
Are you sure this is a URL parsing issue? Are you getting an exception or an error from the proxy? If the former, can I see it?

If not, which is what I suspect, I think your proxy may be the one that's struggling. Essentially, the major difference in the two code paths is that requests won't add the `'/'` path to a `Location` header. Now, probably it should, but right now it doesn't. That means that in the case when you pass it in to requests yourself, requests would emit an extra `/` to the proxy. It seems that your _proxy_ is getting confused here, more than requests.

**Comment by mgdelmonte** [comment]
I can't be sure, though I'll give it another test to see if I can watch where it submits to the proxy.  But without question it works to request the Location URL, but it fails with a 500 error if I request a URL that redirects to the Location URL.  Since the proxy is the same both ways, my best guess is that requests is asking something different of the proxy.

**Comment by Lukasa** [comment]
Yeah, that's definitely the case, but I think the two URLs are semantically identical.

Regardless, I _also_ think that we have a question to ask ourselves (we being @sigmavirus24 and I), which is: why does `resolve_redirects` not end up calling `prepare_url`?
