### ISSUE TITLE
Not possible to receive server response before all of request body is sent?

### ISSUE THREAD

**Issue by zachmullen** [kennethreitz/requests#3199]
I'm not sure if this is actually the case, but from looking at the code it appears to be. To motivate my use case, I am using chunked transfer-encoding mode for the request since I want to support streaming from an underlying service, so the content length is unknown and could be very long. It appears that if the server sends a response prior to the request body being completely sent, we wouldn't know about it, which would be quite bad for something like a redirect or an error condition that was detected very early in the stream. In particular, in a redirect case we certainly don't want to re-send the entire stream.

Is there a good way around this?

**Comment by sigmavirus24** [comment]
@zachmullen short of rewriting our HTTP stack to not use httplib, no. And none of us presently have the time to do that. :-(

**Comment by Lukasa** [comment]
Well, we could work around it if we adjusted `send` to always check whether the socket is readable first, but it's a dirty hack and I don't think it's worth it: it'll just be too brittle I suspect. That said, if someone wants to prototype a change to do that in urllib3 it'd be an interested experiment.

Regardless, this would first be a urllib3 enhancement so I'm closing this.

**Comment by zachmullen** [comment]
Ok, thanks

**Comment by sigmavirus24** [comment]
(Closing for @Lukasa since he said he was going to and didn't. ;))
