### ISSUE TITLE
Request's documentation is self-contradictory about whether connections are pooled automatically

### ISSUE THREAD

**Issue by thanatos** [kennethreitz/requests#3201]
The introduction to requests claims,

> Keep-alive and HTTP connection pooling are 100% automatic

The page on sessions contradicts this, and heavily implies that I need to create a `Session` object to get pooling:

> if you're making several requests to the same host, the underlying TCP connection will be reused, which can result in a significant performance increase (see HTTP persistent connection).

If I need to create a Session in order to achieve connection pooling… that doesn't seem "100% automatic" if I must manually ask for it.

Use of the library seems to indicate that `Session` is the way to go, because I'm getting spammed by "Starting new HTTPS connection" logs.

**Comment by Lukasa** [comment]
Thanks for this!

I don't know that I'd call the documentation contradictory. At least when I see "100% automatic" I see a phrase that means "no user intervention is required", which is true. However, you do need an object to put state on to.

Regardless, what wording change would you recommend to clear this up?

**Comment by kennethreitz** [comment]
Ever porcelain-level api call (e.g. `requests.get`) has a session baked into it, which will be used across all requests within that function call.

As documented, if you intend to make multiple calls, you must create a session.

Documentation is correct.
