### ISSUE TITLE
uncaught possible exception in urllib3/connectionpool.py

### ISSUE THREAD

**Issue by sposs** [kennethreitz/requests#3218]
Hi,
I'm seeing the following exception
``` 
File "/opt/virtualenvs/myapp/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 314, in _raise_timeout
    if 'timed out' in str(err) or 'did not complete (read)' in str(err):  # Python 2.6
TypeError: __str__ returned non-string (type SysCallError)
```
I'm using version 2.7.0 of requests. The url I try to access is a https one.
I don't really know how to debug this...

**Comment by Lukasa** [comment]
Please update your version of requests. This was fixed several releases ago.

**Comment by sposs** [comment]
Thanks. Updated now. Will reopen if needed.
