### ISSUE TITLE
did it update doc?

### ISSUE THREAD

**Issue by yangbeom** [kennethreitz/requests#3221]
I  translate Doc into Doc-KR.

in todo.rst

> As of v1.0.0, Requests has now entered a feature freeze.

did this translate or delete?

**Comment by Lukasa** [comment]
That sentence is true, but it's still fine to continue with translations. =)

**Comment by yangbeom** [comment]
@lukasa Thanks :) i think that sentence is unnecessary in v2.10.0, so seek your advice.

**Comment by Lukasa** [comment]
It's still necessary: we're still in a nominal feature freeze. =)

**Comment by yangbeom** [comment]
@Lukasa make sense!! thanks =)
