### ISSUE TITLE
Global verify options

### ISSUE THREAD

**Issue by abelmokadem** [kennethreitz/requests#3224]
I have noticed that it is possible to specify `verify=False` in order to avoid `CERTIFICATE_VERIFY_FAILED`. Is it possible to globally set this option?

**Comment by Lukasa** [comment]
It is not, no.

Setting `verify=False` is an extremely insecure thing to do, and should be avoided if at all possible. Having a hook that enables you to _globally_ disable TLS certificate verification is extremely insecure, and is also where we draw the line.

**Comment by sigmavirus24** [comment]
Further, we request that all questions be asked on [StackOverflow](stackoverflow.com), not on the defect tracker.
