### ISSUE TITLE
Session cookies handled incorrectly on redirect

### ISSUE THREAD

**Issue by Markus-Goetz** [kennethreitz/requests#3237]
Hi everyone,

the session cookies are handled incorrectly when being redirected from an https URL to an http resource.The initial cookies have been acquired via an https request to <domain>. Therefore, the secure attribute of the respective cookie is set to True. In a later request to the same domain via https, I am 307 redirected to the very same URL except via http. When requests tries to resolve the redirect it will not copy the cookie over because the `return_ok_secure` check in the `cookielib.py` will obviously fail (mismatch between request.type == 'http' and checked type 'https'). Is that a wrong implementation by the service provider or python-requests? Below a pseudo example:

```
import request
print requests.__version__
>>> '2.10.0'
s = requests.Session()
s.post('https://domain.com/login', data={'login': login, 'pw': pw})
print s.cookies
>>> <RequestsCookieJar[<Cookie token=... for domain.com/>]>
res = s.get('https://domain/com/resource') # redirects internally with 307
```

Unfortunately, I can not provide a minimal working example since the script would include sensitive information.

**Comment by Lukasa** [comment]
The `secure` attribute of a cookie should only be set to `True` if the service provider sets it manually. If they _do_ set it manually, that is an instruction that the cookie must not be sent over an insecure (e.g. `http`) channel. Requests is correctly refusing to send that cookie: it should only be sent when TLS is used.
