### ISSUE TITLE
Make RequestEncodingMixin._encode_params() public

### ISSUE THREAD

**Issue by arjennienhuis** [kennethreitz/requests#3239]
I need something that does exactly what `RequestEncodingMixin._encode_params()` does. This works in both python2 and 3:

```py
>>> RequestEncodingMixin._encode_params({u'a': b'b'})
'a=b'
```

Can it be made part of the public API? (Or is it already?)

I am aware that I can just use it as is. But that seems "wrong".

**Comment by sigmavirus24** [comment]
I don't have any strong feelings on it. I actually am uncertain why we're using a Mixin there when those are static methods and don't need to be declared on a class.

If we're going to make them public, I'd rather move them to a well documented submodule that does encoding of data and such for requests. That way people can simply do:

``` py
from requests import encodingutils

encodingutils.encode_params(...)
```

**Comment by Lukasa** [comment]
Do we really need to expose them? This is a 16-line function that mostly just translates different inputs to something useful to pass to `urlencode`. Do we need to really expose this, or is it safer just for those who want it to copy the code out?

**Comment by sigmavirus24** [comment]
> Do we really need to expose them?

I don't know. I do have questions about using a Mixin here but that's tangential to this issue. I'm not sure we want to make these publicly available though. I lean towards not doing it because it's not what requests is for, but I'm also not sure if not opening it up means people won't use it anyway.

**Comment by kennethreitz** [comment]
Don't change something just because you can.
