### ISSUE TITLE
docs don't show correct max_redirects

### ISSUE THREAD

**Issue by jvanasco** [kennethreitz/requests#3250]
In the docs, `max_redirects = None` (http://docs.python-requests.org/en/master/api/?highlight=max_redirects#requests.Session.max_redirects)

however it actually is set to `DEFAULT_REDIRECT_LIMIT` from `.models`...

https://github.com/kennethreitz/requests/blob/cd4e6b9aef4b5d3224a1aae1b3a2cef1b09710a4/requests/sessions.py#L330-L332

... which is defined as `30`

https://github.com/kennethreitz/requests/blob/cd4e6b9aef4b5d3224a1aae1b3a2cef1b09710a4/requests/models.py#L47

**Comment by Lukasa** [comment]
Hrm, this seems to be a problem with the RTD docs build. @sigmavirus24, any ideas?

**Comment by sigmavirus24** [comment]
So, sphinx is the source of this bug and I suspect it might be fixable but with something that I'm not entirely certain we want to do.

The following triggers the "bug" (a.k.a., limitation in sphinx-doc):

``` py
class Session(...):
    def __init__(self):
        self.max_redirects = 30
```

And this "fixes" it:

``` py
class Session(...):
    max_redirects = 30
    def __init__(self):
        pass
```

We update our attributes to do this for documentation purposes, but this _can_ have negative effects if we over-do it. Thoughts?

**Comment by Lukasa** [comment]
I'd rather not do it, frankly: I think it'd end up looking gross. =(

**Comment by jvanasco** [comment]
The class (or possibly method) do string can declare it as an instance variable, and then note what package it's imported from.  It's not a perfect solution in that one needs to look at source for the real value, but it stops the wrong info from appearing in the API docs.   (Fwiw, I naively trusted the docs and hit the limit... Making me go crazy for 15 minutes reinstalling requests and trying to figure out why No Limit was triggering an exception)

**Comment by sigmavirus24** [comment]
@Lukasa to be clear we'd still be able to use the constant we import from `requests.models` that also appropriately helps sphinx determine what is happening.

I am not particularly opinionated about this I guess.

**Comment by Lukasa** [comment]
Can we just change the doc string to say "Defaults to `30`"?

**Comment by sigmavirus24** [comment]
@Lukasa that works for me.

**Comment by kennethreitz** [comment]
@Lukasa that was going to be my suggestion. Utilizing class-instance variables just for the doc build is a huge red flag for me.

**Comment by kennethreitz** [comment]
It's important to keep in mind that a _lot_ of people read through the Requests codebase is a way to learn how to write and organize Python code well.

**Comment by sigmavirus24** [comment]
> Utilizing class-instance variables just for the doc build is a huge red flag for me. 

So class variable definitions have a lot of other benefits. One very common one is if someone uses mock to create an autospec'd Session. The mock will reflect the attributes that users expect to be there _only_ if the attributes were defined at the class level. (In other words, we make people's lives easier when they mock out the Session as a collaborator object in their testing.)
