### ISSUE TITLE
Setting Proxy-Authorization Header Manually

### ISSUE THREAD

**Issue by mmedal** [kennethreitz/requests#3252]
I know you guys have addressed a variety of concerns relating to configuring proxies and that proxying is functionally complex, but I'd like to raise one issue I was having today. We have a new proxy in our environment that requires auth with a yubikey rather than a password. We can simply set an environment variable to a token returned from a yubikey auth endpoint that expires every 12 hours and pass it along with the Proxy-Authorization header in tools like curl, wget, etc... However, it gets a little trickier with requests, as the default api seems to only support including the proxy-user:proxy-pass in the proxy-url.

In our case, we can't do this, as a yubikey token is only good once. As a temporary workaround, I've subclassed HTTPAdapter and modified the proxy_headers method:

    class CustomHTTPAdapter(HTTPAdapter):
        def proxy_headers(self, proxy):
            return {
                'Proxy-Authorization': 'Basic ' + environ.get('proxy_token', str())
            }  

and then mount it on a Session:

    import requests

    from mypkgs.adapters import CustomHTTPAdapter
    

    s = requests.Session()
    s.mount('https://', CustomHTTPAdapter())
    s.get('https://someurl')

It would be incredibly useful to simply be able to do something like `requests.get(uri, proxy_headers=proxy_headers)`. Am I barking up the wrong tree here or do you have any ideas or feedback?

**Comment by Lukasa** [comment]
Generally speaking we're disinclined to add a separate `proxy_headers` kwarg. The vast majority of users don't need it, and those that do are relatively well-served by the `proxy_headers` override of the HTTPAdapter.

Requests is extremely reluctant to add new kwargs to the top-level API if it can possibly be avoided, and in this case I think it can.

Sorry! =(

**Comment by mmedal** [comment]
Thanks for the feedback! In that case, is there an easy way to mount a custom HTTPAdapter on the main requests api rather than on a session? I didn't note any in the documentation, but maybe I missed it.

**Comment by Lukasa** [comment]
Nope: the requests API manufactures a new Session on each request to avoid having any implicit global state that can lead to all kinds of weird bugs.
