### ISSUE TITLE
Minor session object documentation issues

### ISSUE THREAD

**Issue by jayvdb** [kennethreitz/requests#3288]
I suspect this is a documentation issue, for expected and desired behaviour, rather than an unintended bug...

http://docs.python-requests.org/en/master/user/advanced/#session-objects states that 

> The Session object ... will use urllib3's connection pooling. So if you're making several requests to the same host, the underlying TCP connection will be reused, which can result in a significant performance increase (see HTTP persistent connection).
> ...
> Note, however, that method-level parameters will not be persisted across requests, even if using a session. This example will only send the cookies with the first request, but not the second: ..."

There is a minor conflict between those, in that exceptions to the rule include the `verify` parameter and likely other connection related parameters (`cert`, `timeout`, ...?), which do in fact persist across the requests.  This is strongly implied by the opening paragraph, which says that the connection is reused.

Also "several requests to the same host" is not quite correct, I believe, as different protocols will result in different connections, naturally.

**Comment by jayvdb** [comment]
Note #3289 shows the `verify` parameter being persistent between requests in the same session.

**Comment by jayvdb** [comment]
What would be interesting to test is whether a connection reset of some sort causes the `verify` parameter in the session to the same protocol/host to be lost.  Maybe there is a test in `urllib3` that already covers that scenario.

**Comment by Lukasa** [comment]
This is a known issue (see #2863) and will be fixed in an upcoming release, having had the underlying urllib3 issue fixed (shazow/urllib3#830).
