### ISSUE TITLE
Content-length not calculated correctly

### ISSUE THREAD

**Issue by therealjb86** [kennethreitz/requests#3290]
PUT request using previous connection .content generates content-length of 1. Please can you help me determine why this is happening?

Code:

r = requests.get('http://192.168.55.5/api/?client=wget&file-name=dummy&type=vmware/vmware/2.0/si/serviceprofile/serviceprofile-1/containerset',
                         data={r1.content}, headers={'content-type':'application/xml'}, verify=False, auth=('admin', 'paloalto'))

Generated request:

PUT /api/?client=wget&file-name=dummy&type=vmware/vmware/2.0/si/serviceprofile/serviceprofile-1/containerset HTTP/1.1
Host: 192.168.55.5
Connection: keep-alive
User-Agent: python-requests/2.10.0
Accept-Encoding: gzip, deflate
Accept: */*
Content-Length: 1
content-type: application/xml
Authorization: Basic YWRtaW46cGFsb2FsdG8=

<?xml version="1.0" encoding="UTF-8"?>
<containerSet><container><id>securitygroup-22</id><name>Ten1SubtA-sec-group</name><description></description><revision>3</revision><type>IP</type><address>192.168.111.89</address><address>192.168.111.88</address></container><container><id>securitygroup-27</id><name>test-sec</name><description></description><revision>7</revision><type>IP</type></container></containerSet>

**Comment by therealjb86** [comment]
You can see the body is clearly more than 1 byte so unless I'm missing something this looks like a bug. Let me know what additional information you would like and I will add it.

**Comment by sigmavirus24** [comment]
It's actually not quite complete. You haven't told us what operating system you're using or shown us how to get `r1` for the post request you make above. The way in which you made that request is actually worth knowing.

You also don't explain where you retrieved this generated request from. Is that from the server or from the request attribute on the response.

There is, in fact, very little information here and at this point belongs on StackOverflow. There's little evidence of any actual bug in requests.

**Comment by therealjb86** [comment]
Python 3.6.0a1 (v3.6.0a1:5896da372fb0, May 16 2016, 15:20:48) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.

> > > import requests
> > > requests.**version**
> > > '2.10.0'

The generated request is a capture (tcpdump) of r on the server, before it was cut off it clearly showed over 400 bytes of content, yet the Content-Length has been calculated as '1' by requests. 

r1 = requests.get('https://10.193.87.73/api/2.0/si/serviceprofile/serviceprofile-16/containerset', verify=False, auth=('root', 'paloalto'))

The response to GET request r1 contains the data I am using in the PUT request r

data:

<?xml version="1.0" encoding="UTF-8"?>
<containerSet><container><id>securitygroup-22</id><name>Ten1SubtA-sec-group</name><description></description><revision>3</revision><type>IP</type><address>192.168.111.89</address><address>192.168.111.88</address></container><container><id>securitygroup-27</id><name>test-sec</name><description></description><revision>7</revision><type>IP</type></container></containerSet>

**Comment by therealjb86** [comment]
data:

<?xml version="1.0" encoding="UTF-8"?>
<containerSet><container><id>securitygroup-22</id><name>Ten1SubtA-sec-group</name><description></description><revision>3</revision><type>IP</type><address>192.168.111.89</address><address>192.168.111.88</address></container><container><id>securitygroup-27</id><name>test-sec</name><description></description><revision>7</revision><type>IP</type></container></containerSet>

**Comment by Lukasa** [comment]
Uh...why is your `data=` argument a set?

**Comment by therealjb86** [comment]
uh... hmm.. maybe I chopped and changed my code too much and ended up with a typo... Thanks for pointing me at my mistake :) I will now go and slap myself in the face for the next 10 minutes :(

**Comment by Lukasa** [comment]
Heh, no need to self-flagellate too much, it happens to all of us. =)

**Comment by sigmavirus24** [comment]
@therealjb86 I should have caught that last night. :) Sorry for not being able to be helpful sooner.
