### ISSUE TITLE
session ignores POST data when caching redirects

### ISSUE THREAD

**Issue by panda-34** [kennethreitz/requests#3291]
I was scraping a site where the search form makes a POST request which is redirected with 301 code. That code being permanent, the redirect is cached in session.redirect_cache by POST URL alone, so for all further searches the session gets the same page. I suggest that redirect_cache should use POST body as a key also, it's quite typical for sites to redirect POSTs to different URLs based on data.

**Comment by sigmavirus24** [comment]
Hey @panda-34,

Thanks for pointing this out. This was something I hadn't seen before (or considered). Tthe redirect cache is meant to very simplistic. The default cache can be disabled like as described [here](https://github.com/kennethreitz/requests/pull/2095#issuecomment-45977320). You can then use a real cache system, like [cachecontrol](/ionrock/cachecontrol) to do this kind of work.

**Comment by panda-34** [comment]
POST requests aren't really supposed to be cacheable, redirects or not. Bypassing the POST and jumping immediately to the result (even with correct URL) might have some very nasty consequences.

**Comment by StewPoll** [comment]
Just on the topic of disabling the cache - Is it possible to disable the
cache for specific calls, or does it need to be done globally?

**Comment by Lukasa** [comment]
Once again, I would vastly prefer that rather than us making the 301 cache increasingly more complex we simply _remove_ it. It frequently behaves incorrectly and leads to subtle confusion. I was in opposition to its merging back when it was proposed and I remain opposed to its function now.

**Comment by sigmavirus24** [comment]
@Lukasa I'm in agreement. Let's do that in 3.0

**Comment by kennethreitz** [comment]
+1, I don't like it.
