### ISSUE TITLE
Scrape  issue 

### ISSUE THREAD

**Issue by itranga** [kennethreitz/requests#3331]
I tried to scrape http://www.nbcnews.com/health/health-news/brain-study-helps-explain-some-veterans-agony-n589916 .Then i got the below issue.

404 Client Error: Not Found for url: http://www.nbcnews.com/health/health-news/brain-study-helps-explain-some-veterans-agony-n589916%20

**Comment by Lukasa** [comment]
You left a space at the end of your URL. You need to remove it: requests will not automatically do that for you.

**Comment by itranga** [comment]
Thanks for your reply. But i did't add any spaces to the url, i also saw that '%20' end of the url. how is it happened?

**Comment by Lukasa** [comment]
That %20 is the urlencoding for a space, which is how I determined what happened. Where did your URL come from?

**Comment by sigmavirus24** [comment]
This discussion belongs on [StackOverflow](https://stackoverflow.com/questions/tagged/python-requests).
