### ISSUE TITLE
Failed to establish a new connection: [Errno 65] No route to host

### ISSUE THREAD

**Issue by ljdawn** [kennethreitz/requests#3354]
hi, I'm trying to
```python
import requests
req = requests.Session()
headers = {'Referer':'https://archive.org/','User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:47.0) Gecko/20100101 Firefox/47.0'}
req.headers.update(headers)
res = req.get('https://archive.org/', headers=headers, timeout=20, proxies={'http': '52.192.0.225:8080'}, verify=False)
```
Then got ---------------------------------------------------------------------------
ConnectionError                           Traceback (most recent call last)
<ipython-input-23-1ddf77e531ff> in <module>()
      3 headers = {'Referer':'https://archive.org/','User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:47.0) Gecko/20100101 Firefox/47.0'}
      4 req.headers.update(headers)
----> 5 res = req.get('https://archive.org/', headers=headers, timeout=20, proxies={'http': '52.192.0.225:8080'}, verify=False)

/Users/test/env/lib/python2.7/site-packages/requests/sessions.pyc in get(self, url, **kwargs)
    485 
    486         kwargs.setdefault('allow_redirects', True)
--> 487         return self.request('GET', url, **kwargs)
    488 
    489     def options(self, url, **kwargs):

/Users/test/env/lib/python2.7/site-packages/requests/sessions.pyc in request(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)
    473         }
    474         send_kwargs.update(settings)
--> 475         resp = self.send(prep, **send_kwargs)
    476 
    477         return resp

/Users/test/env/lib/python2.7/site-packages/requests/sessions.pyc in send(self, request, **kwargs)
    583 
    584         # Send the request
--> 585         r = adapter.send(request, **kwargs)
    586 
    587         # Total elapsed time of the request (approximately)

/Users/test/env/lib/python2.7/site-packages/requests/adapters.pyc in send(self, request, stream, timeout, verify, cert, proxies)
    465                 raise ProxyError(e, request=request)
    466 
--> 467             raise ConnectionError(e, request=request)
    468 
    469         except ClosedPoolError as e:

ConnectionError: HTTPSConnectionPool(host='archive.org', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x105ea5fd0>: Failed to establish a new connection: [Errno 65] No route to host',))

I've tried to use proxies, set down the verify, but that does not work. Thank you

**Comment by Lukasa** [comment]
Your proxy configuration appears to be wrong: you've set up a proxy for only HTTP schemed addresses. Do you want to try changing your `req.get` request to be:

``` python
res = req.get('https://archive.org/', headers=headers, timeout=20, proxies={'http': 'http://52.192.0.225:8080', 'https': 'http://52.192.0.225:8080'})
```

**Comment by ljdawn** [comment]
@Lukasa  OK. thank you .
