### ISSUE TITLE
'True' payload in get cause problem

### ISSUE THREAD

**Issue by lufeihaidao** [kennethreitz/requests#3355]
```python
payload = {'key1': 'value1', 'key2': True}
r = requests.get('http://httpbin.org/get', params=payload)
print(r.url)
# 'http://httpbin.org/get?key1=value1&key2=True'
```

With `key2` I wanna get a boolean param, but requests gives me 'True'. 'True' will be considered as a string in many frameworks.

**Comment by lufeihaidao** [comment]
Is it a bug, or designed to be so?

**Comment by Lukasa** [comment]
@lufeihaidao HTTP query parameters are not typed: they are _all_ strings. There is no such thing as a boolean parameter in a query string. What do you think a boolean parameter is, in this context?

**Comment by lufeihaidao** [comment]
@Lukasa Sorry, in my app, `key2` is supposed to be a boolean field. And many frameworks' boolean validations only check whether the `key2` string is '1' or 'true',rather than 'True'. So when the client assembles params with 'True', it will not pass the server's boolean validator.

**Comment by lufeihaidao** [comment]
In this case, I need to modify the server's boolean validator to support 'True'?

**Comment by Lukasa** [comment]
@lufeihaidao You could do that, or you could just pass the string `true` rather than `True`.

``` python
payload = {'key1': 'value1', 'key2': 'true'}
```

**Comment by lufeihaidao** [comment]
@Lukasa OK, thanks.

**Comment by Lukasa** [comment]
No problem.
