### ISSUE TITLE
Adding DRY-ness in auth.py

### ISSUE THREAD

**Issue by ueg1990** [kennethreitz/requests#3357]
@sigmavirus24 mentioned that in auth.py, the magic method __ne__ is technically not needed since != is implied from definition of __eq__. Would this be considered a useful update?

**Comment by sigmavirus24** [comment]
Have you checked that it's not necessary on Python 2.6? It might be necessary there.

**Comment by ueg1990** [comment]
You are right. It is needed in Python 2.6.
