### ISSUE TITLE
Custom ResponseClass

### ISSUE THREAD

**Issue by jamielennox** [kennethreitz/requests#3360]
A common pattern in webob is allowing applications to define there own request and response class. This makes it easier to work with and expose attributes and methods that you will commonly use in your application. For example you can add properties for headers that are commonly used in your application. 

Theoretically you could do the request side of this today subclassing requests.Request, however the more useful side here would be being able to specify a response class (it can be asserted that custom response class is a subclass of requests.Response).

**Comment by kennethreitz** [comment]
Thank you for the idea, but again, in short brevity: no. :)

**Comment by sigmavirus24** [comment]
> For example you can add properties for headers that are commonly used in your application.

You could also do this with a separate response class (that takes a requests.Response) as a parameter and uses descriptors for that. OpenStack already has a lot of "session" classes that use requests.Session instances under the covers. I don't understand why they couldn't have their own Response object that uses descriptors as intended to achieve a similar goal.
