### ISSUE TITLE
TypeError in iter_slices() when slice_length=None

### ISSUE THREAD

**Issue by nateprewitt** [kennethreitz/requests#3369]
An unintended side effect of using `chunk_size=None` (as referenced in PR #3368) is a failure in `iter_slices()`. The two code snippets below will both trigger [`reused_chunks` being chosen](https://github.com/kennethreitz/requests/blob/master/requests/models.py#L695) as the return value of `iter_content`. The generator is produced by `iter_slices` which currently requires the chunk_size to be an integer, otherwise it raises a TypeError when [trying to add an int and NoneType](https://github.com/kennethreitz/requests/blob/master/requests/utils.py#L388).

Perhaps these are obscure enough edge cases, that it's not an issue. I just wanted to make a quick note of it.

#### Examples ####
```
def test_stream():
    s = requests.Session()
    req = requests.Request('GET', 'https://httpbin.org/get').prepare()
    resp = s.send(req, stream=False)
    next(resp.iter_content(None))

def test_decode():
    r = requests.Response()
    r.raw = io.BytesIO(b'the content')
    all_content = r.content
    decoded_chunk = next(r.iter_content(None, True))
```

**Comment by Lukasa** [comment]
Why does `iter_slices` with `slice_length = None` not trigger a `TypeError`?

**Comment by nateprewitt** [comment]
Sorry, I'm not sure I understand the question. I'm currently seeing the following error returned with both python2.7 and python3.5.

`TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'`

A more direct code snippet for reproduction would be:

`next(requests.utils.iter_slices('my string', None))`

**Comment by Lukasa** [comment]
Ok, that's good, I just didn't read the report clearly enough I guess. =)
