### ISSUE TITLE
4-byte UTF-8 character in package description can break repositories

### ISSUE THREAD

**Issue by wichert** [kennethreitz/requests#3395]
I'm afraid this is a bit of a 'WTF' thing. I was trying to use a hosted package repository, and discovered that trying to upload a wheel for requests failed. Some back and forth revealed an interesting reason: they store package description in MySQL, and MySQL can't normally store 4-byte UTF-8 sequences. And it so happens the cake symbol you are using for the `pip install` example is a 4-byte UTF-8 character.

Considering this is not a bug in requests and the limitation is completely silly I hate to ask this, but still: could you consider using another replacing that cake symbol with something else so we won't hit that limitation?

**Comment by Lukasa** [comment]
Uh...I mean, we could. But it seems like that's just deferring the problem until later in the day. At some point the hosted package repository is going to need to deal with the full breadth of UTF-8. I feel like it'd be for the good of the world to hold Requests hostage behind dealing with this issue!

Seriously though, MySQL's standard utf8 encoding is a joke: your package host really desperately needs to migrate to utf8mb4 or they'll encounter substantial trouble down the road. I recommend either moving to a different package host or threatening to do so unless they fix the issue.

**Comment by sigmavirus24** [comment]
> I recommend either moving to a different package host or threatening to do so unless they fix the issue.

I second that. I doubt Requests is the only package that will cause you this pain. Asking each one as it pops up to "fix" this (instead of the hosted repository fixing it) seems really kind of unreasonable.
