### ISSUE TITLE
JSON decode failed

### ISSUE THREAD

**Issue by cchenship** [kennethreitz/requests#3396]
I want to do the following curl call in python with requests

**curl:**
`curl -b cookies -c cookies -X POST --file @auth 'https://api.a_website.com/auth'`

The above curl commanded worked.

**python**
```
base_url = 'https://api.a_website.com/auth'
result = requests.post(url=base_url, data={'auth': open('auth', 'rb')}, cookies=cookies)
result.content
```
However, I got the following error:

> 
b'{"response":{"error_id":"SYNTAX","error":"JSON decode failed","error_description":null,"service":null,"method":null,"error_code":null,"dbg_info":{"instance":"65.bm-hbapi.prod.nym2","slave_hit":false,"db":"master","awesomesauce_cache_used":false,"count_cache_used":false,"uuid":"c941819d5c860f9a","warnings":[],"time":39.22700881958,"start_microtime":1468334115.9092,"version":"1.16.707","slave_lag":0,"output_term":"not_found"}}}\n'

here is the auth file
`$ cat auth`

> {
>     "auth": {
>         "username" : "a_username",
>         "password" : "a_password"
>     }
> }

**Comment by sigmavirus24** [comment]
You are not sending JSON to the website in either request.

For assistance with using this library, please ask your question on [StackOverflow](https://stackoverflow.com/questions/tagged/python-requests). We do not provide a Q&A forum in the bug tracker.

**Comment by Lukasa** [comment]
Please note as well that, whatever you think that curl command was doing, I don't think it was doing the right thing. I don't think curl takes a `--file` argument...

Assuming you meant `--data` instead, what you want is this:

`result = requests.post(url=base_url, data=open('auth', 'rb'), cookies=cookies)`

**Comment by cchenship** [comment]
Thanks for the quick response, I was indeed using -d in curl, pasted the wrong line
