### ISSUE TITLE
option to not urlencode parameters ?

### ISSUE THREAD

**Issue by pcompassion** [kennethreitz/requests#3398]
The api end point I'm working with won't work correctly when parameters are urlencoded.

There seems to be other servers who don't work well with urlencoded urls... 
(http://stackoverflow.com/a/23497912/433570)

How can I make requests not urlencode ? :(

**Comment by Lukasa** [comment]
The best way to do it is to build your URL yourself, and then use the [PreparedRequest flow](http://docs.python-requests.org/en/master/user/advanced/#prepared-requests) to manually change `PreparedRequest.url` to the complete URL you'd like to use.
