### ISSUE TITLE
"hostname doesn't match" error while requesting IP address directly and setting host header (HTTPS)

### ISSUE THREAD

**Issue by huoneefi** [kennethreitz/requests#3403]
In an application, I can't use DNS resolving. So I request the IP address directly while setting the host header (vhosts). In this case, SSL certificate validation (/SNI) doesn't work properly because it doesn't respect the explicitly set host header:

Python 2.7.11:
```python
>>> import requests
>>> requests.__version__
'2.10.0'
>>> requests.get(url="http://example.org")
<Response [200]>
>>> requests.get(url="https://example.org")
<Response [200]>
>>> requests.get(url="http://93.184.216.34", headers={"Host": "example.org"})
<Response [200]>
>>> requests.get(url="https://93.184.216.34", headers={"Host": "example.org"})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "[...]/requests/api.py", line 71, in get
    return request('get', url, params=params, **kwargs)
  File "[...]/requests/api.py", line 57, in request
    return session.request(method=method, url=url, **kwargs)
  File "[...]/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "[...]/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "[...]/requests/adapters.py", line 477, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: hostname '93.184.216.34' doesn't match either of 'www.example.org', 'example.com', 'example.edu', 'example.net', 'example.org', 'www.example.com', 'www.example.edu', 'www.example.net'
```

**Comment by kennethreitz** [comment]
This is intended and expected behavior, at the moment. 

The host header is simply a semantic of HTTP, not of the connection you are making, and has no effect on the underlying TLS mechanisms. 

Requests could build additional supplemental functionality around this, to support this rare use-case, but has opted not to so far. It's most likely that the end result would be a custom ConnectionAdapter that would need to be utilized to enable this behavior.

**Comment by kennethreitz** [comment]
That being said, you should be able to build this ConnectionAdapter yourself. I think it would make a great addition to the Requests-Toolbelt. 

https://github.com/sigmavirus24/requests-toolbelt

**Comment by huoneefi** [comment]
Thank you for your thoughts about this issue. I implemented an Adapter and created a pull request to requests-toolbelt: https://github.com/sigmavirus24/requests-toolbelt/pull/157
