### ISSUE TITLE
send a lot of http request at same time?

### ISSUE THREAD

**Issue by 1c7** [kennethreitz/requests#3418]
### What I have tried
I already search on Google, 
and tried “grequest”, but grequests document is not enough, I don't know how to use it correctly.

### What I am trying to do
what I am trying to do is send about 1000 http GET request,   
and then use "beautifulsoup"(python module) get content I want.  

### Why I need send multi request once
send them one by one is just too slow  
I want send as much as possible, maybe 30 requests in a batch?
I am crawling a website, so there are really no way to cut down request number..

### Lastly
Thanks for you time on reading this post :dancer: 

oh, I just found out requests and grequest is same author, awesome.

**Comment by Lukasa** [comment]
@1c7 I'm taking this example [straight from the grequests README](https://github.com/kennethreitz/grequests):

``` python
import grequests

urls = [
# Put all the URLs you need to get here.
]

# Create a whole series of unsent requests.
requests = (grequests.get(u) for u in urls)

# Send them
responses = grequests.map(requests)

for response in responses:
    # Do whatever you need to do with the responses.
```
