### ISSUE TITLE
When using Session.send on a prepared request, session hooks aren't dispatched

### ISSUE THREAD

**Issue by 13steinj** [kennethreitz/requests#3424]
https://github.com/kennethreitz/requests/blob/bca205e9bf60adbf578ef15958c872bfedcbdc60/requests/sessions.py#L568

I'm unsure if this is intentional or not, just had a problem given a session level hook didn't run. Hooks are merged when [preparing the request](https://github.com/kennethreitz/requests/blob/bca205e9bf60adbf578ef15958c872bfedcbdc60/requests/sessions.py#L396), but any requests prepared by the user manually and then sent via Session.send don't run session level hooks.

**Comment by Lukasa** [comment]
This is intentional. [Per the documentation](http://docs.python-requests.org/en/master/user/advanced/#prepared-requests), if you want the advantages of a Session you need to use the `Session.prepare_request` method.
