### ISSUE TITLE
Code Consistency Work

### ISSUE THREAD

**Issue by nateprewitt** [kennethreitz/requests#3427]
This is a combination of two passes over the code to help cleanup some of the coding style differences that have creeped in over time. It's mostly cosmetic but I think it'll help reduce inconsistencies going forward by having the code be an example for future contributors. Per @Lukasa's request, I'm going to break this up into two pull requests. One involving docstrings and the other involving pep8 fixes. I don't know that these changes are necessarily "correct", I simply chose what appeared to be the most common occurrence in the code. I'm sure @kennethreitz will have opinions on which choices are best.

**Comment by kennethreitz** [comment]
Is this supposed to be a pull request?

**Comment by Lukasa** [comment]
@kennethreitz, I kinda want you to take the lead on code review for this: just flag changes you don't like and I'm sure @nateprewitt will undo it.

**Comment by Lukasa** [comment]
Nah, it's an umbrella issue that'll cover two PRs.

**Comment by kennethreitz** [comment]
👍
