### ISSUE TITLE
Documentation makes no mention of CookieJar

### ISSUE THREAD

**Issue by roselma** [kennethreitz/requests#3460]
There are only dict-based examples in the documentation of the cookies parameter to the get method.  Making some mention of the use of CookieJar might save some poor sod from re-implementing half of CookieJar and then finally discovering its existence by printing the cookies property in the response.

**Comment by Lukasa** [comment]
Yup, sounds good to me. Would you like to write something? =)

**Comment by nateprewitt** [comment]
It looks like the [`RequestsCookieJar` class](http://docs.python-requests.org/en/master/api/#requests.cookies.RequestsCookieJar) is available on the main page of links in the documentation, under the [Developer Interface docs](http://docs.python-requests.org/en/master/#the-api-documentation-guide).

Were you looking to have a code example added in the Quickstart section @roselma, or would a link to the existing documentation suffice?

**Comment by roselma** [comment]
The quickstart guide is (thankfully) quite thorough, so careless readers may fail to notice that they are not looking at the most detailed documentation available.  I believe that a sentence in the Cookies section of the quickstart guide linking to RequestsCookieJar info would be adequate.

Or, you know... you could just drop this, since technically the documentation _does_ make mention of CookieJar... just not in the quickstart guide.

I created a pull request with a blurb about RequestsCookieJar.  Do with it as you see fit.

**Comment by sigmavirus24** [comment]
Closed by #3469
