### ISSUE TITLE
python -m requests

### ISSUE THREAD

**Issue by glyph** [kennethreitz/requests#3464]
Often when I'm debugging some HTTP thing, I poke at with `curl`.  But of course in many cases when I interact with it for real, I am going to be talking to it with `requests`.  Sometimes - especially in the case of weird SSL debugging - `curl` and `requests` will behave differently.  It would be really handy if `requests` had at least partial emulation of the `curl` command-line options to enable me to just `python -m requests https://example.com/` and see what it's doing independent of my code.

A really cool bonus feature here would be to print out the relevant Python code for making that same request, but I can see how that might be getting a little far out of scope.

**Comment by glyph** [comment]
Sorry if this is a dup - I could swear I've seen it before but after 15 minutes of searching I couldn't find it.

**Comment by kennethreitz** [comment]
I have considered this in the past, but opted against it. Might as well use http://httpie.org, which uses Requests.

**Comment by glyph** [comment]
@kennethreitz Oh - in my defense I did try searching closed issues as well :).

**Comment by kennethreitz** [comment]
I don't think anyone's asked for it before :)

**Comment by kennethreitz** [comment]
Bonus-fact: I used to have a function built-in that would turn your Request object into a curl command. It's been removed (obviously), but I think someone's maintaining a version of it (or perhaps the opposite of it) out there somewhere.

**Comment by glyph** [comment]
Thanks for the pointer to httpie.  I've been using it for testing my latest little creation and it is _rad_.
