### ISSUE TITLE
Replacing HTTP Content-Length header

### ISSUE THREAD

**Issue by noadmin** [kennethreitz/requests#3466]
Good day,

We use your lib for testing S3 protocol, and found minor issue with HTTP headers:
some of header parameters, such as Content-Length, were override by sessions.prepare_request()
is it possible to add logic not to do this (smth like if request.headers['Content-Length']:         p.headers['Content-Length'] = request.headers['Content-Length']) if header value is provided.

Thank You

**Comment by Lukasa** [comment]
You can change these values by using the [`PreparedRequest` flow](http://docs.python-requests.org/en/master/user/advanced/#prepared-requests), which allow you to either skip the Session preparation step or to change the request after it has been prepared by the Session.

_However_, I strongly recommend that you do not change the Content-Length: Requests has almost certainly got it right, and if you change it to a different value you are likely to break the connection.
