### ISSUE TITLE
OverflowError: requested number of bytes is more than a Python string can hold

### ISSUE THREAD

**Issue by mopuru-murali** [kennethreitz/requests#3471]
I'm facing some weird problem.

I'm not able to post ~3GB (more than 2GB) file using requests > 0.7.4 module because of getting following err.

File "/build/toolchain/noarch/requests-2.5.3/lib/python2.6/site-packages/requests/api.py", line 83, in post
  return request('post', url, data=data, **kwargs)
File "/build/toolchain/noarch/requests-2.5.3/lib/python2.6/site-packages/requests/api.py", line 38, in request
  return s.request(method=method, url=url, **kwargs)
File "/build/toolchain/noarch/requests-2.5.3/lib/python2.6/site-packages/requests/sessions.py", line 200, in request
  r.send(prefetch=prefetch)
File "/build/toolchain/noarch/requests-2.5.3/lib/python2.6/site-packages/requests/models.py", line 387, in send
  fields.update({k: (fn, fp.read())})
OverflowError: requested number of bytes is more than a Python string can hold

But, with requests<=0.7.4 its working fine. No problem of OverflowError.

So, I was wondering why it started throwing OverflowError in latest version of requests module (or from requests > 0.7.4)?

I tested this with python2.6 and python2.7.

PS: I know that instead of posting huge file at once, we can post same file via file chunks. But, I do not want chucks way.

**Comment by Lukasa** [comment]
The problem here is that you're sending the file using a multipart file upload. For requests, this causes us to read in the entire file in order to build the body.

You can resolve this by either not using multipart file uploads (if that's possible), or else by using the [streaming multipart data encoder](https://toolbelt.readthedocs.io/en/latest/uploading-data.html#streaming-multipart-data-encoder) from the Requests toolbelt.

**Comment by mopuru-murali** [comment]
Are you saying requests<=0.7.4 handles multipart file uploads well by default?
But, I dont think this below code uses multipart format

1501         res = requests.post(
1502             server_url,
1503             files={
1504                 'package': open(package, 'rb')},
1505             data={
1506                 'md5sum': md5sum,
1507                 'length_in_bytes': packagelen
1508             })

May I know is it save using requests<=0.7.4 for file uploads?

**Comment by sigmavirus24** [comment]
> Are you saying requests<=0.7.4 handles multipart file uploads well by default?

No. That is not what @Lukasa is saying.

>  But, I dont think this below code uses multipart format

You're using the files parameter, so yes, it is sending a multipart message.

If you describe what you want the body to look like, we _might_ be able to help you, but you should be using [StackOverflow](stackoverflow.com) for help with this module, not the defect tracker.

**Comment by Lukasa** [comment]
> May I know is it save using requests<=0.7.4 for file uploads?

It is extremely _unsafe_ to use such an old version of Requests, for any purpose.
