### ISSUE TITLE
post with unicode data and the post body will be truncated!!!

### ISSUE THREAD

**Issue by ifooth** [kennethreitz/requests#3472]
when i use requests post data with unicode, and the content-length will be wrong, and the post data will be truncated, test with requests 2.10.0

test code

---

```
# -*- coding: utf-8 -*
import json
import requests
# use utf-8
import sys
reload(sys)
sys.setdefaultencoding('utf-8')

data = json.dumps({'test': u"测试"}, ensure_ascii=False)
print data
resp = requests.post('https://github.com/kennethreitz/requests/issues', data=data, verify=False)
```

fiddler snapshot

---

![u](https://cloud.githubusercontent.com/assets/1853121/17411410/052ec118-5aab-11e6-9486-ab29fd6a7a9e.png)

reason

---

```
data = json.dumps({'test': u"测试"}, ensure_ascii=False)
the unicode length: len(data) = 14
the utf-8 chars length len(data.encode('utf-8')) = 18
encode with utf-8 but the content-length not change, so, the post body is truncated data
data.encode('utf-8')[:len(data)] = {"test": "测
```

is it a bug? need help

**Comment by Lukasa** [comment]
Why are you passing `ensure_ascii=False`?

**Comment by Lukasa** [comment]
Anyway, that's kind of neither here nor there. There are several solutions to your problem:
1. Don't use `ensure_ascii=False`. There's no requirement to do it: JSON allows unicode escape characters.
2. Alternatively, don't pass Requests a unicode string in `data`. This kind of works in Python 2, but I wish it didn't: it makes no sense. Encode it yourself using `utf-8`.
3. Just defer all of this decision making and use `requests.post(url, json={'test': u"测试"})`.
