### ISSUE TITLE
process is terminated while starting new https protocol

### ISSUE THREAD

**Issue by truyet** [kennethreitz/requests#3473]
I use requests pacakge to call nexmo api with post method: requests.post(url)

It has worked well for a month, but after my service is terminated and I check logging throw lastest row: 
 requests.packages.urllib3.connectionpool - INFO - Starting new HTTPS connection (1): rest.nexmo.com

I catched exception but no errors are written to logging.

**Comment by Lukasa** [comment]
That information is nowhere near detailed enough to tell us what happened. You'll need to provide a traceback or something similar.

**Comment by sigmavirus24** [comment]
We can reopen this if and when we get more information.
