### ISSUE TITLE
requests v2.11 has a syntax error in python3.2

### ISSUE THREAD

**Issue by huseyinyilmaz** [kennethreitz/requests#3479]
First of all thanks for the awesome library. I am really enjoying using requests. This is my favorite library.

In the last version of requests, I started to get an error on my own library and it turned out it was because of my requests dependency. 

In python3.2, requests v2.11 gives following error:
```
  File "/home/travis/build/huseyinyilmaz/placebo/requests/__init__.py", line 64, in <module>
    from .models import Request, Response, PreparedRequest
  File "/home/travis/build/huseyinyilmaz/placebo/requests/models.py", line 856
    http_error_msg = u'%s Client Error: %s for url: %s' % (self.status_code, reason, self.url)
                                                      ^
SyntaxError: invalid syntax
```

Here is the fix
https://github.com/kennethreitz/requests/pull/3478

Again sorry about the crappy way of testing. I could not install python3.2 on my local machine so I could not test it with requests tests.

**Comment by nateprewitt** [comment]
Hey @huseyinyilmaz, I think this may have been discussed in #3385 (particularly [here](https://github.com/kennethreitz/requests/pull/3385#discussion_r69560890)). Removing the `u` designation on the string would revert the unicode support added in #3385.

**Comment by sigmavirus24** [comment]
Ah, I see @nateprewitt already chimed in over here.

**Comment by huseyinyilmaz** [comment]
I see. So, python3.2 is not supported by requests library. Than I will just close the issue and pr.

Thanks for the link @nateprewitt .

**Comment by huseyinyilmaz** [comment]
Hey,
I just wanted to give some extra feedback. I got this error because when I installed requests with following command:

```
pip install requests
```

It installed an unstable version in python 3.2.
Is it possible to not to release unsupported versions in pypi. So python3.2 would not get any updates but it would always load supported version but old version.

**Comment by Lukasa** [comment]
@huseyinyilmaz That is not possible, I'm afraid: you'd need to ask @dstufft to provide tools to do that. It's a nice idea, certainly, although it requires much more formalisation of the trove classifiers system that currently exists.

**Comment by sigmavirus24** [comment]
@huseyinyilmaz I think you're going to have a bad time as more and more projects find it unreasonable to support Python 3.2. There are _very_ few users on that version and it does not even receive security updates.

**Comment by dstufft** [comment]
There are updates being made to PEP 503 that will make it possible. It'll take some time for setuptools/pip/etc to filter out that respects that.
