### ISSUE TITLE
Can't connect to HTTPS URL because the SSL module is not available.

### ISSUE THREAD

**Issue by rohitkhatri** [kennethreitz/requests#3482]
If I try to fetch any https url, It throws an error on the server, but when I try it on the local machine, It works.

Code:

	def test():
	  data = requests.get('https://newsroom.co',verify=False)
	  return data;

**Comment by Lukasa** [comment]
@rohitkhatri This is almost certainly a problem with the OpenSSL shipped on your server. You'll likely need to elaborate for us to help you: for example, _what_ error do you see?

**Comment by rohitkhatri** [comment]
@Lukasa You can check this out here http://52.40.67.18/testing

**Comment by Lukasa** [comment]
Oh that's easy: the Python on your server was compiled without the SSL module. It will be impossible to make HTTPS requests without the SSL module. You'll need to take this up with whomever built your application environment.

**Comment by rohitkhatri** [comment]
So what do I need to do in order to resolve this issue, any suggestion?

**Comment by Lukasa** [comment]
My suggestion is the same as what I said in the last comment: you'll need to contact whomever built your application environment. If you're deploying on something like Google App Engine, you'll need to consult their docs. If you're using something like Docker, you'll need to consider changing your base image.

**Comment by rohitkhatri** [comment]
I'm using amazon ec2 instace with ubuntu 14.04 installed on it.

**Comment by Lukasa** [comment]
Where is your Python coming from? Because the Python shipped with Ubuntu 14.04 definitely has the SSL module installed.

**Comment by softvar** [comment]
@rohitkhatri How did you resolve this? I'm getting the same error?

**Comment by jonwhittlestone** [comment]
and me

**Comment by Lukasa** [comment]
All: you need to contact whomever built your Python install. If it was you, then you need to check the Python documentation because you didn't link against OpenSSL.
