### ISSUE TITLE
requests 2.11.0 raises when header contains leading space

### ISSUE THREAD

**Issue by brantlk** [kennethreitz/requests#3488]
With the release of requests 2.11.0 we're seeing errors where things were working with requests 2.10.0. The exception that's raised is "Invalid return character or leading space in header".

We can work around the problem and make sure we set headers without leading spaces, just making sure that this was the intention to have things that were working with 2.10 stop working with 2.11.

**Comment by Lukasa** [comment]
Thanks for this!

This is deliberate. Headers with leading spaces in them are frequently mis-handled by intermediaries and servers. This can lead to attacks or misbehaviour, where any or all of a server, client, and all involved proxies disagree on what headers are actually present. This is called a smuggling attack, and it's not a good thing.

Given that this misbehaviour exists, and given that it is not really _sensible_ to add extra whitespace to the header field value, Requests has simply decided to forbid it entirely. This was entirely the intention of the change: we're trying to help Requests emit better-formed HTTP data.

**Comment by brantlk** [comment]
ok, thanks for the explanation.

**Comment by clayg** [comment]
> This is deliberate

heh, awesome

https://bugs.launchpad.net/python-swiftclient/+bug/1614280
https://review.openstack.org/#/c/356802/1
