### ISSUE TITLE
Any way to set verify=False on session object?

### ISSUE THREAD

**Issue by JamesTheHacker** [kennethreitz/requests#3495]
Is there any way to set `verify=False` on a session object rather than having to use it on every HTTP request made by the session?

**Comment by Lukasa** [comment]
No. =) If you're going to make yourself unsafe, we'd like you to do it every time. Think of us as like your better angel, sitting on your shoulder saying "are you _sure_ you want to turn off your security?".

**Comment by JamesTheHacker** [comment]
Ah ok. I was debugging HTTP requests with Burp Suite. It's the only time I will be setting `verify=False`. I wanted to do it once for development purposes only.

**Comment by Lukasa** [comment]
Oh sure, there are lots of totally legitimate reasons to turn it off, that's why we have the switch at all. =D But we just never want to make it _too_ comfortable to turn off.
