### ISSUE TITLE
session() got an unexpected keyword argument 'headers'

### ISSUE THREAD

**Issue by breize** [kennethreitz/requests#3509]
When trying the second example of [http://docs.python-requests.org/en/v0.10.6/user/advanced/#session-objects](http://docs.python-requests.org/en/v0.10.6/user/advanced/#session-objects) i get the following error:

`TypeError: session() got an unexpected keyword argument 'auth'`

Did something change there and the documentation didn't get updated?

**Comment by Lukasa** [comment]
@breize You're linking to an ancient version of the documentation. Try this: http://docs.python-requests.org/en/latest/user/advanced/

**Comment by tino** [comment]
@Lukasa this is still in the latest docs version: `http://docs.python-requests.org/en/latest/api/#requests.Session.auth`. I have the same with `headers=`. Are the docs out of date?

Any reason not to accept this as a init kwarg? Seems a bit silly that you have to do:
```
s = requests.Session()
s.headers.update('foo', 'bar')
```
