### ISSUE TITLE
Not raise ProxyError when I use proxy `https://...:8080` 

### ISSUE THREAD

**Issue by eromoe** [kennethreitz/requests#3515]
Code:
```
proxies = {'https': u'https://...:8080'} # or {'HTTP':'http://:80' }
r = requests.head(u'http://example.com', proxies=proxies, timeout=10)
r.status_code
>>> 200
```

The proxy is broken, seems requests do not use this proxy and make request directly,
it should raise `ProxyError('Cannot connect to proxy.'` here.

**Comment by Lukasa** [comment]
That proxy is not broken. We are using the configuration you set. If you set the scheme `{'https': u'https://...:8080'}`, and make a request to a URL beginning with `http://`, you have not set any proxy for us to use: as a result, we don't use it.

The mere presence of a proxy dictionary does not indicate that the user wants _every_ request they issue to be proxied.
