### ISSUE TITLE
It seems that I cannot hide my IP using the proxy?

### ISSUE THREAD

**Issue by eduOS** [kennethreitz/requests#3517]
I want to hide my own IP address but it seems unstable. 
```
import requests
url = "http://httpbin.org/get"
proxy0 = {"http":"http://118.179.220.186:8080"} # just an example, it may have expired
proxy1 = {"http":"http://41.79.60.202:8080"}
r0 = requests.get(url, proxies=proxy0, timeout=5)
r1 = requests.get(url, proxies=proxy1, timeout=5)
r0.json()["origin"] 
r1.json()["origin"] 
```

When I tested it the the origin in r0 contained only one IP while that of r1 contained two including my own IP. 

The same problem was posted on StackOverflow, please refer to [here](http://stackoverflow.com/q/27824055/3552975).

**Comment by Lukasa** [comment]
@eduOS In this instance, it's possible that the proxy is setting X-Forwarded-For header, which will contain the IP address of your source. Alternatively, it's possible that you're getting forwarded to a HTTPS address. Either way, it's likely that the connection is still using the proxy: so longa s the scheme of the two URLs match, we _will_ use it.
