### ISSUE TITLE
connection: keep-alive not working with requests used in pyArango

### ISSUE THREAD

**Issue by dothebart** [kennethreitz/requests#3522]
Hi, 
requests is used in the connection object of pyArango:
https://github.com/tariqdaouda/pyArango/blob/master/pyArango/connection.py
Though I only see one instance of the connection object being created and used through out the life of https://github.com/tariqdaouda/pyArango/blob/master/examples/debiangraph.py (I've added printfs in these cases) the http connection isn't re-used.

I've followed the connection between pyArango and ArangoDB with Wireshark, to find both of them sending `connection: Keep-Alive` thus the client instantly disconnecting the tcp connection after the HTTP-Requests is done. 

I'm a bit out of Ideas howto better debug this, is there a smart way?

**Comment by Lukasa** [comment]
You're saying that wire shark shows the requests-based client sending `Connection: keep-alive`, is that right? If so, what is the server sending?

**Comment by dothebart** [comment]
yes, its sending that. The server does send that too. Then the client closes the connection, just to open a new one in subsequent requests.

**Comment by Lukasa** [comment]
@dothebart It's hard to know exactly what's going on here, but the connection will be left open unless the `Session` is leaked, closed, or otherwise lost. The only other way the connection gets lost is if `Connection: close` is set.

**Comment by dothebart** [comment]
Ok, we found the issue. The bearer object keeping the session object went out of scope and thus closed the connection.
