### ISSUE TITLE
Segfault while using requests in GPIO Callback on Raspberry Pi 3

### ISSUE THREAD

**Issue by momo-aux** [kennethreitz/requests#3533]
I'm getting a segfault sometimes after pressing the Button.
This little script can be used to reproduce the error. (If you don't get a segfault after 20 button presses, restart the script, sooner or later you'll get one).

requests Version is 2.4.3
Python Version is 3.4.2

Perhaps someone could give me a hint what/how to find out what the problem is. 

```
import time
from time import mktime, time, sleep
import RPi.GPIO as GPIO
import requests

def button_press_isr1(channel):
    GPIO.remove_event_detect(18)
    sleep(0.0001)
    cnt = 0
    edge_start1 = time()
    while (time() - edge_start1) <= 0.035 : # 35 mSec max, 15mSec margin
        sleep(0.0015) # 1.5 mSec
        if GPIO.input(18) == 0 : # 0/False for Falling, 1/True for Rising
            cnt += 1
        else: # when we have captured a glitch, start all over again
            cnt = 0
        if cnt == 7 : # 7? lucky number
            break
    if cnt == 7 :
        response = requests.post(url="http://192.168.1.5:8080")
    GPIO.add_event_detect(18, GPIO.FALLING, callback=button_press_isr1)


def init():
  #GPIO.setwarnings(True)
  GPIO.setmode(GPIO.BCM)
  GPIO.setup(18, GPIO.IN)

  GPIO.add_event_detect(18, GPIO.FALLING, callback=button_press_isr1)

def main():
  try:
    while True:
      sleep(0.03)

  except KeyboardInterrupt:
      # exit with CTRL+C
      print("CTRL+C used to end Program")
  finally:
    GPIO.cleanup()


if __name__ == "__main__":
    init()
    main()

```

**Comment by Lukasa** [comment]
Thanks for reporting this!

It's not possible to segfault the interpreter from inside Requests, because Requests is written in pure-Python. That suggests that the issue is inside the GPIO calls. Unfortunately, to be more specific you'll need to use a debugger like GDB to catch the segfault and print the C stack for that call.

Support for that problem is outside the scope of this bugtracker, I'm afraid.

**Comment by momo-aux** [comment]
Ah great to know that there is only one option left :-), thank you
