### ISSUE TITLE
('Connection aborted.', error(105, 'No buffer space available'))

### ISSUE THREAD

**Issue by glennpierce** [kennethreitz/requests#3537]
I have some code that calls like

r = session.get(url, stream=False, timeout=1)
data = r.content

This is called in a loop for 150 urls constantly. Usually this works but after a while I get errors like

('Connection aborted.', error(105, 'No buffer space available'))

This is over an ipsec tunnel so I suspect the bug is with the tunnel but wanted to make sure.

Thanks

**Comment by Lukasa** [comment]
Do you have a more complete traceback for that? This error _generally_ indicates a problem with the socket buffer itself: that is, the buffer is overflowing. It'd be good to see where it's coming from, but _probably_ it's related to the ipsec tunnel: certainly many similar bugs seem to be raised that involve ipsec.

**Comment by glennpierce** [comment]
I solved it in the by doing
echo "65535" > /proc/sys/net/ipv4/xfrm4_gc_thresh

I found the solution https://wiki.strongswan.org/issues/1169

The default on centos 7 was quite low.

Thanks
