### ISSUE TITLE
Header doesn't accept int values already

### ISSUE THREAD

**Issue by anchaj** [kennethreitz/requests#3540]
Hi,
I discovered that new version (2.11.1, build:0x021101) doesn't accept int type in headers.
Before update (2.3.0, build:0x20300) everything was ok. 
```
import requests
headers = {'exampleHeader': 10} # raise InvalidHeader: Header value 10 must be of type str or bytes...
# headers = {'exampleHeader': '10'}  # for new version of library
requests.request("PUT", http://google.com, headers=headers)
```

**Comment by StewPoll** [comment]
This was an intentional change.

You will find many other closed issues discussing this since 11 came out.

You will need to convert to string before using as a header.

**Comment by Lukasa** [comment]
Yup, that's correct. =) Thanks @TetraEtc!
