### ISSUE TITLE
proxies has no effect

### ISSUE THREAD

**Issue by ripples-alive** [kennethreitz/requests#3544]
Suppose my IP is `1.1.1.1` and an anonymous proxy is `2.2.2.2:2222`. I write code like this:

```python
while True:
    proxy = '2.2.2.2:2222'
    session = requests.Session()
    session.headers['User-Agent'] = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0'
    session.proxies = {
        'http': proxy,
        'https': proxy,
    }
    print session.get('http://members.3322.org/dyndns/getip').content
    print session.get('http://members.3322.org/dyndns/getip', proxies=session.proxies).content
```

The output for one loop should be:

```
2.2.2.2
2.2.2.2
```

Firstly, I ran this program, the result was the same as expected.
However, several days later, I suddenly found that the output for one loop became:

```
1.1.1.1
2.2.2.2
```

I killed the process and ran it again, the output was still wrong. (repeated several times)
Then I restart the computer and ran it again. The output became right, again.

In fact, I can hardly reproduce the issue. But it did happened.

```
OS: Windows 10 home (version 1511, os version 10586.545).
Python 2.7.11
requests 2.11.0 (installed by pip)
```

**Comment by Lukasa** [comment]
Without the ability to reproduce this, I don't think we can really take any action on this. =(
