### ISSUE TITLE
Requests Truck Factor

### ISSUE THREAD

**Issue by 2mferreira** [kennethreitz/requests#3547]
Dear Requests contributors,

I am Master's student investigating the importance of the idea of truck factors in Software Engineering.

As you know, [truck factor](https://en.wikipedia.org/wiki/Bus_factor) (aka bus factor) is defined as “the number of people on your team who have to be hit by a truck before the project is in serious trouble”. By "serious trouble", we mean that it will very difficult to maintain the project (e.g., bugs will take more time to be fixed, new features will be delayed etc).

I would appreciate your contribution by answering two questions:

1) According to your experience, what number best represents the truck factor of Requests?

2) Who are the developers responsible for this truck factor estimation?

Mívian Ferreira
Master's Student
Applied Software Engineering Group (ASERG)
UFMG, Brazil
http://aserg.labsoft.dcc.ufmg.br/

**Comment by Lukasa** [comment]
1) 3
2) Me.

**Comment by 2mferreira** [comment]
Thanks a lot for the answer!

Regarding question (2), there is a failure from my part. I was indeed asking about the name of the three developers that are responsible for the Requests TF.

**Comment by Lukasa** [comment]
Myself, @sigmavirus24, and @kennethreitz
