### ISSUE TITLE
requests.get doesn't fail HTTP requests with verify option

### ISSUE THREAD

**Issue by Findeton** [kennethreitz/requests#3549]
When you use the verify parameter on requests.get, the function is supposed to check that the webpage certificate is valid. Obviously, if the webpage is not HTTPS, the webpage has no certificate.

I think it would be nice if in that case the request fails. I mean, imagine we have Google's cert on /srv/google-cert:

```
$ cat /srv/google-cert
-----BEGIN CERTIFICATE-----
MIIDVDCCAjygAwIBAgIDAjRWMA0GCSqGSIb3DQEBBQUAMEIxCzAJBgNVBAYTAlVT
MRYwFAYDVQQKEw1HZW9UcnVzdCBJbmMuMRswGQYDVQQDExJHZW9UcnVzdCBHbG9i
YWwgQ0EwHhcNMDIwNTIxMDQwMDAwWhcNMjIwNTIxMDQwMDAwWjBCMQswCQYDVQQG
EwJVUzEWMBQGA1UEChMNR2VvVHJ1c3QgSW5jLjEbMBkGA1UEAxMSR2VvVHJ1c3Qg
R2xvYmFsIENBMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA2swYYzD9
9BcjGlZ+W988bDjkcbd4kdS8odhM+KhDtgPpTSEHCIjaWC9mOSm9BXiLnTjoBbdq
fnGk5sRgprDvgOSJKA+eJdbtg/OtppHHmMlCGDUUna2YRpIuT8rxh0PBFpVXLVDv
iS2Aelet8u5fa9IAjbkU+BQVNdnARqN7csiRv8lVK83Qlz6cJmTM386DGXHKTubU
1XupGc1V3sjs0l44U+VcT4wt/lAjNvxm5suOpDkZALeVAjmRCw7+OC7RHQWa9k0+
bw8HHa8sHo9gOeL6NlMTOdReJivbPagUvTLrGAMoUgRx5aszPeE4uwc2hGKceeoW
MPRfwCvocWvk+QIDAQABo1MwUTAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBTA
ephojYn7qwVkDBF9qn1luMrMTjAfBgNVHSMEGDAWgBTAephojYn7qwVkDBF9qn1l
uMrMTjANBgkqhkiG9w0BAQUFAAOCAQEANeMpauUvXVSOKVCUn5kaFOSPeCpilKIn
Z57QzxpeR+nBsqTP3UEaBU6bS+5Kb1VSsyShNwrrZHYqLizz/Tt1kL/6cdjHPTfS
tQWVYrmm3ok9Nns4d0iXrKYgjy6myQzCsplFAMfOEVEiIuCl6rYVSAlk6l5PdPcF
PseKUgzbFbS9bZvlxrFUaKnjaZC2mqUPuLk/IH2uSrW4nOQdtqvmlKXBx4Ot2/Un
hw4EbNX/3aBd7YdStysVAq45pmp06drE57xNNB6pXE0zX5IJL4hmXXeXxx12E6nV
5fEWCRE11azbJHFwLJhWC9kXtNHjUStedejV0NxPNO3CBWaAocvmMw==

-----END CERTIFICATE-----
```

Then right now this is what happens:

```
>>> import requests
>>> requests.get('https://www.google.com', verify='/srv/google-cert')
<Response [200]>
>>> requests.get('http://www.ull.es', verify='/srv/google-cert')
<Response [200]>
```

I'm proposing a change: the second get call (which is HTTP) should fail.

I've tested this on requests 2.11.1.

**Comment by Lukasa** [comment]
Thanks for this suggestion! However, I'm afraid I disagree. =) That represents a pretty substantial change in the behaviour of the verify argument, and is well outside what is currently documented. Additionally, it raises some extremely difficult questions. For example, what if the request is redirected from HTTPS to HTTP: should that fail?

But fundamentally it just punishes users too heavily for simple errors. `verify` has a very simply defined behaviour [as shown here](http://docs.python-requests.org/en/master/user/advanced/#ssl-cert-verification): whenever set to a validation mode, requests will validate _HTTPS_ requests, but not others.

You can achieve your desired behaviour (no HTTPS support) by reconfiguring your Session somewhat:

``` python
s = requests.Session()
del s.adapters['https://']
```

This will make Requests entirely unable to make HTTP requests.
