### ISSUE TITLE
Using Python's requests lib throwing ProxyError

### ISSUE THREAD

**Issue by coderfreedom** [kennethreitz/requests#3558]
When I use requests.get('http://www.google.com')
It throws a ```ProxyError```:
```
ProxyError: HTTPConnectionPool(host=My vps's IP , port=80): Max retries exceeded with url: http://www.google.com/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x03EB66F0>: Failed to establish a new connection: [Errno 10061] ',)))
```

When I use the HTTP Protocol request website, the host will turn into my vps's IP.  Although I shutdown the VPN. But userHTTPS Protocol will not  appear this issue.

**Comment by Lukasa** [comment]
@coderfreedom You almost certainly have the `HTTP_PROXY` environment variable set. Why is that set if you don't want HTTP tools to use your VPS?

**Comment by flzq** [comment]
@Lukasa   But I close it in IE settings. 
sometimes I need VPN to climbe the Great Fire Wall    : ) you know, a lot of  websites I can't visit. Sometimes visit github I also need use VPN.

**Comment by Lukasa** [comment]
Hrm. Can you run this for me?

``` python
import requests
print requests.utils.get_environ_proxies('http://www.google.com')
```

**Comment by flzq** [comment]
@Lukasa 

```
{'http': '107.160.9.10'}
```

It was my vps's IP, why????

**Comment by Lukasa** [comment]
I don't know, but it's somewhere in your system: either the HTTP_PROXY environment variable or elsewhere in your system configuration. Either way, we're just doing what your system tells us to do. You can probably override that by setting `proxies={'http': None}`.

**Comment by flzq** [comment]
@Lukasa I use this way before. But sometimes  I need use othre lib which can't set proxies, such as `builtwith.parse('http://example.webscraping.com')`  it also through `Error: <urlopen error [Errno 10061] >`

**Comment by Lukasa** [comment]
@coderfreedom In that case, this is a configuration issue on your machine. I'm afraid I can't really help beyond that. =(

**Comment by sigmavirus24** [comment]
@coderfreedom you can use `trust_env=False` to avoid using any proxies discovered in your environment as a work around until you figure out your system configuration problem.

**Comment by flzq** [comment]
@Lukasa  Anyway, thank you for your help  : )
This problem has troubled me for months, It drives me crazy "_"
I think it's time to use Mac OS.  : )

**Comment by flzq** [comment]
@sigmavirus24  But another lib will still not work.

**Comment by flzq** [comment]
@Lukasa  @sigmavirus24  Does python has a global variable to carvery it???

**Comment by edeuser** [comment]
@coderfreedom : Did you solve this problem? I also met VPN related issue.

**Comment by zengbiao** [comment]
it read your IE's proxy setting, you can try unset proxy setting in inetcpl.cpl.
