### ISSUE TITLE
Same error here " bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)

### ISSUE THREAD

**Issue by CHW2017** [kennethreitz/requests#3562]
import urllib3
import urllib3.contrib.pyopenssl
import certifi

urllib3.contrib.pyopenssl.inject_into_urllib3()

http = urllib3.PoolManager(
    cert_reqs='CERT_REQUIRED', # Force certificate check.
    ca_certs=certifi.where(),  # Path to the Certifi bundle.
)

# You're ready to make verified HTTPS requests.
try:
    r = http.request('GET', 'https://devapi.trustmile.com/static/index.html')
    print r.status
except urllib3.exceptions.SSLError as e:
    print e

**Comment by Lukasa** [comment]
This is a bug report for urllib3, but you have issued it against Requests. =) Please open this bug report on the urllib3 repository.
