### ISSUE TITLE
behavior of encoding

### ISSUE THREAD

**Issue by fredzannarbor** [kennethreitz/requests#3566]
Hello,

I am having a terrible time figuring out what requests is doing here.

  ```  r = requests.get('http://0.0.0.0:5006/buy', params=payload)
   print(r.url) #debug
   print(r.encoding)
   print(r.text)
   print(r.headers)

```
debugging commands in console produce:
```payload from cli is {"key1": "foo", "key2": "bar"}
payload in function is {"key1": "foo", "key2": "bar"}
http://0.0.0.0:5006/buy?%7B%22key1%22:%20%22foo%22,%20%22key2%22:%20%22bar%22%7D
ISO-8859-1```

The URL looks wrong to me, is it somehow being created incorrectly?

**Comment by nateprewitt** [comment]
Hey @fredzannarbor, are you sure that your `payload` variable is of type `dict` and not `str`. The results you're seeing seem to be consistent with url encoding a string rather than passing a dictionary for iteration.

**Comment by Lukasa** [comment]
The URL is right; its urlencoding the string payload you gave it. You cannot just send arbitrary data in a URL: as it is structured, certain bytes have semantic meaning. If you don't want that meaning, you need to encode those bytes using what is called urlencoding. That's what we have done here.
