### ISSUE TITLE
socks5 does not work well 

### ISSUE THREAD

**Issue by ljdawn** [kennethreitz/requests#3570]
Hi. When I'm using proxy = {'http': 'socks5://IP:PORT', 'https': 'socks5://IP:PORT'}, I got "AssertionError: Not supported proxy scheme socks5". I had upgraded my requests( version:2.11.1)  and env is mac osx.

**Comment by PegasusWang** [comment]
```
proxies = {'http': 'socks5://127.0.0.1:9050',
                   'https': 'socks5://127.0.0.1:9050'}
requests.get(url, proxies=proxies)
```

it works for me. I suggest you debug to find error.

**Comment by Lukasa** [comment]
@PegasusWang This suggests that your PySocks isn't working well. `pip install -U pysocks==1.5.6` should resolve your problem.
