### ISSUE TITLE
ValueError encountered

### ISSUE THREAD

**Issue by antlong** [kennethreitz/requests#3571]
https://dpaste.de/t0kx

More info available if needed.

**Comment by Lukasa** [comment]
@antlong Can you provide your code, please? Can you also tell us what version of Requests you're using, and where you got it from?

**Comment by antlong** [comment]
https://dpaste.de/zUtN

Requests 1.2.3 from pip.

Note: The urls in the file contain special characters.

**Comment by Lukasa** [comment]
So Requests 1.2.3 is _ancient_: I'm almost certain that we fixed this in the last two years. Please upgrade your Requests. =)

**Comment by antlong** [comment]
Ahhhh forgot i was on an older centos dev box running this. Thanks!
