### ISSUE TITLE
single request causing connection-pool to repeat multiple times

### ISSUE THREAD

**Issue by jefftune** [kennethreitz/requests#3592]
I posted the same issue on [stackoverflow](http://stackoverflow.com/questions/39594458/python-requests-single-request-causing-connection-pool-to-repeat-multiple-time)

**Question:** **requests** module in the background is repeating "Starting new HTTPS connection" followed by an equal number of method calls, and these repeated background actions increase over runtime of my program to **20 times**. This is concerning to me.

 1. For each "Starting new HTTPS connection" is **requests** module actually starting a new connection?
 2. For each method call "PUT ..." is **requests** module actually calling endpoint?
 3. If either or both of the aforementioned are true, then what should I do to prevent requests module from making repeated connections and calls?

I turned on **DEBUG logging** on requests module.

Initially for the first couple of minutes, the logs generated from **requests** looks fine, single "Starting new HTTPS connection" followed by and single method call, for example, "PUT":

    2016-09-20 05:14:48            INFO    "Starting new HTTPS connection (1): ****.**.**"
    2016-09-20 05:14:49            DEBUG   ""PUT /*/***/***/*** HTTP/1.1" 200 17"

However, then for a single action request, the number of "Starting new HTTPS connection" followed by the number of actions start to increase more and more, from 1 to 2 to 3 and up to 20 repeats.

This is happening regardless of what is the endpoint or action method applied.

These repeated logging appear to be coming from: **requests.packages.urllib3.connectionpool**

Here is an example the **requests** module is repeating 3 times for each request:

    2016-09-20 05:15:08            INFO    "Starting new HTTPS connection (1): ****.**.**"
    2016-09-20 05:15:08            INFO    "Starting new HTTPS connection (1): ****.**.**"
    2016-09-20 05:15:08            INFO    "Starting new HTTPS connection (1): ****.**.**"
    2016-09-20 05:15:08            DEBUG   ""PUT /*/***/***/*** HTTP/1.1" 200 17"
    2016-09-20 05:15:08            DEBUG   ""PUT /*/***/***/*** HTTP/1.1" 200 17"
    2016-09-20 05:15:08            DEBUG   ""PUT /*/***/***/*** HTTP/1.1" 200 17"

**Comment by sigmavirus24** [comment]
We cannot answer your question until you show us the code you've written producing these warnings. Also, since this is a _question_ it should be answered on StackOverflow (where you asked it originally).

**Comment by jefftune** [comment]
@sigmavirus24 

I am not sure why this was **closed**.

I cannot provide the code because it contains proprietary credentials.

So, what would cause requests would make repeated "Starting new HTTPS connection" followed by repeated method calls?

**Comment by Lukasa** [comment]
@jefftune Multithreaded use of Requests is the most likely case. In the absence of any kind of code, we cannot effectively debug your situation: you are asking us to look at two logs and to discern everything you are doing with the code. We know nothing about your environment, the manner in which you're using the code, whether you're running with multiple sessions, or anything else.

If you could _strip_ the credentials from your code (e.g. replace them with `****`), then we can help. But otherwise, what you're asking us to do is to blindfold ourselves, tie both our hands behind our back, sit on a chair in a darkened room, and then work out what item you're holding in your hand based on the sound it makes when you drop it. We can _try_, but our odds are bad.

**Comment by jefftune** [comment]
@Lukasa 

Thanks for the feedback, I will look into **Multithreaded use of Requests**

**Comment by sigmavirus24** [comment]
@jefftune this was **closed** because:
- it's not a defect
- this project answers questions on StackOverflow (although maybe not as quickly as you would like)
- we cannot help you without providing some sample

therefore there's nothing actionable to come out of this issue.

**Comment by jefftune** [comment]
@sigmavirus24 

Understood, thank you

**Comment by tina0430** [comment]
Hi, I am having the same issue.
If I request for the url that starts with “https” using GET/POST method with logger module, then the logger prints repeated logs just like @jefftune’s case.  (in the case of "http", it works really well). 
I can't access your StackOverflow link.  
@sigmavirus24 said that you got the answer on StackOverflow.
Can you give me the link or where I can find the link?

Thank you
