### ISSUE TITLE
when will the requests supports HTTP/2?

### ISSUE THREAD

**Issue by fendouai** [kennethreitz/requests#3601]
Our project need a http/2 client.

**Comment by Lukasa** [comment]
There is no roadmap for this. HTTP/2 is a complex protocol and it is not likely that Requests in its current form will achieve good support for it any time soon. In the meantime, you can [use this](https://hyper.readthedocs.io/en/latest/quickstart.html#requests-integration).

**Comment by StewPoll** [comment]
Read the docs appears to be down. Fyi

**Comment by Lukasa** [comment]
Loading fine for me here.

**Comment by StewPoll** [comment]
All resolved. Must have been a temporary DNS issue.
