### ISSUE TITLE
Link on Documentation web page not working

### ISSUE THREAD

**Issue by iamprakashom** [kennethreitz/requests#3603]
link for *connection pooling* on [this](http://docs.python-requests.org/en/master/user/advanced/#session-objects), line 3 looks broken and shows message

*SORRY
This Page doesn't exist yet.*

**Comment by bbamsch** [comment]
Seems that the old documentation on connection pooling moved around in urllib. The page it references (http://urllib3.readthedocs.io/en/1.5/pools.html) no longer exists after some refactoring was done.

Perhaps a better alternative is:
http://urllib3.readthedocs.io/en/latest/reference/index.html#module-urllib3.connectionpool
or
http://urllib3.readthedocs.io/en/latest/advanced-usage.html#customizing-pool-behavior

**Comment by Lukasa** [comment]
Yup, that looks wrong. I recommend the first link you posted @bbamsch. Would either of you be interested in submitting a pull request to fix that?

**Comment by iamprakashom** [comment]
I am working on it.

**Comment by iamprakashom** [comment]
@Lukasa, If I understand right, first link you are referring to is http://urllib3.readthedocs.io/en/1.5/pools.html ?

**Comment by Lukasa** [comment]
No, sorry, I meant http://urllib3.readthedocs.io/en/latest/reference/index.html#module-urllib3.connectionpool

**Comment by iamprakashom** [comment]
thank you

**Comment by nateprewitt** [comment]
This is resolved with #3604.
