### ISSUE TITLE
MKCOL verb from WebDAV

### ISSUE THREAD

**Issue by paul-hammant** [kennethreitz/requests#3611]
MKCOL would be super useful - make a directory on the remote server.

curl has it:

    curl -u user:pwd -X MKCOL http://yourserver.com/baseurl/newdiruwannacreate

**Comment by StewPoll** [comment]
From what I know the -X flag means you're using a custom metbod, laying
outside normal HTTP requests.

You should be able to achieve this using `requests.request('MKCOL',
**kwargs)`

I may be wrong though.

**Comment by sigmavirus24** [comment]
@TetraEtc is correct. Cheers!

**Comment by paul-hammant** [comment]
Thanks :)
