### ISSUE TITLE
Update streaming request headers

### ISSUE THREAD

**Issue by thisbejim** [kennethreitz/requests#3613]
Is there any way to update headers on a streaming request without restarting the request? 

I am using an Authorization header with tokens that go stale after an hour, so without updating the header to include new tokens a stream can only run for an hour.

**Comment by sigmavirus24** [comment]
Headers are sent at the start of the message. How do you think you would update them without a new request?

The RFC specifies "trailers" but those are for the end of the message, not for the middle of a message and those aren't widely supported (and thus are not supported by requests).
