### ISSUE TITLE
Consider vendoring the IDNA library.

### ISSUE THREAD

**Issue by Lukasa** [kennethreitz/requests#3616]
As has been noted on the [Python Security SIG mailing list](https://mail.python.org/pipermail/security-sig/2016-October/000122.html), Python currently only includes the deprecated IDNA 2003 codec in the standard library. This is problematic, because IDNA 2003 is forbidden for some ccTLDs, such as `.de`: instead, the newer IDNA 2008 standard should be used. That standard is implemented in the PyPI package `idna`.

If we're going to support IDNA 2008, I would like it to not be optional: it leads to a fairly substantial and difficult to debug change, so it should be supported fully. To do that and keep in touch with Kenneth's wishes regarding dependencies, we'd have to vendor it.

I'd like contributors and packagers, particularly @eriol, @ralphbean, and @sigmavirus24 to weigh in with their thoughts here. What are your thoughts here? I'd also, if possible, like to hear from @kjd: while `idna` is licensed under a BSD-like license that should be broadly compatible with our own Apache 2.0 and so should present no legal blockers to vendoring, I'd still rather do it with the original author's permission than without it.

**Comment by kjd** [comment]
It is fine by me. Happy to support widespread use of the modern IDNA standard however I can.

**Comment by sigmavirus24** [comment]
I'm 👍 on it. I think making it non-optional is an excellent idea.

**Comment by eriol** [comment]
+1 for me. I agree with @sigmavirus24 on making it non-optional.

**Comment by jeremycline** [comment]
Hey, @ralphbean has asked me to take over being the point of contact for Fedora packaging interactions.

I'm fine with this and I'm also fine with it being non-optional.

**Comment by Lukasa** [comment]
Thanks for your feedback folks! I've done the work in #3620: please cast your eye over it. This is particularly true for downstream packagers, who will likely want to consider the effect this dependency will have on your packaging ecosystems.
