### ISSUE TITLE
Preparing POST request hook 

### ISSUE THREAD

**Issue by pmart123** [kennethreitz/requests#3623]
First, as countless have said, I'd like to thank all of the contributors for such an excellent package.

I am trying to maintain an auto-incrementing id for a given session and url every time I submit a post request. For example, say I have an authenticated session object.

### Example
```python
ID_KEY = 'id'
counter = 1
data = 'blah'
payload = {ID_KEY: counter, 'other_stuff': data}
resp = session.post(SPECIFIC_URL, json=payload)
counter += 1
payload = {ID_KEY: counter, 'other_stuff': data}
resp2 = session.post(SPECIFIC_URL, json=payload)
```

My easy solution is having an adapter class that wraps the session object with its own post method, but I was wondering if I could use either a prepared request or hook that would achieve the same effect more cleanly?

**Comment by Lukasa** [comment]
A Session wrapper or something similar is the best approach here. We got rid of most of our hooks, and you can't hook into the request factory easily.
