### ISSUE TITLE
Cannot import requests when filename is email.py

### ISSUE THREAD

**Issue by kocsenc** [kennethreitz/requests#3650]
This is a weird error. But if you attempt to import requests from a filename `email.py` importing will fail. 

## Steps to Reproduce

1. `mkdir potato && cd potato`
1. `vim email.py`
1. `echo 'import requests' > email.py`
1. `python email.py`

## Actual Result (bug)

Instead of importing, it will start to ask for specific dependencies.
```bash
$ python email.py
Traceback (most recent call last):
  File "email.py", line 1, in <module>
    import requests
  File "/Library/Python/2.7/site-packages/requests/__init__.py", line 60, in <module>
    from .packages.urllib3.exceptions import DependencyWarning
  File "/Library/Python/2.7/site-packages/requests/packages/__init__.py", line 29, in <module>
    import urllib3
ImportError: No module named urllib3
```

## Machine information
Using macOS default Python `v2.7.10` and default `pip` located at `/Library/Python/2.7/site-packages/requests`

**Comment by sigmavirus24** [comment]
`email` is a standard library package name, you should _never_ shadow those. We, rely on it not being shadowed and use it, which is why you cannot import requests. Please change your file name.
