### ISSUE TITLE
requests can't properly handle 'WWW-Authenticate' response header 

### ISSUE THREAD

**Issue by beruhan** [kennethreitz/requests#3651]
when the http response like this:
`HTTP/1.1 401 Unauthorized\r\n
Server: DNVRS-Webs\r\n
Content-Type: text/html\r\n
WWW-Authenticate: Basic realm="DVRNVRDVS"\r\n
WWW-Authenticate: Digest realm="DVRNVRDVS", domain="::", qop="auth", nonce="2c4158c9159934737e69aa698494ae04", opaque="", algorithm="MD5", stale="FALSE"\r\n`
I have print the response headers ,`{'Server': 'DNVRS-Webs', 'Content-Type': 'text/html', 'WWW-Authenticate': 'Basic realm="DVRNVRDVS", Digest realm="DVRNVRDVS", domain="::", qop="auth", nonce="2c4158c9159934737e69aa698494ae04", opaque="", algorithm="MD5", stale="FALSE"'}`,is this a bug? @nakajima @alex @mkomitee @thedaniel

**Comment by drpoggi** [comment]
This isn't a bug in Requests. You're getting a 401, which means you're using or were provided the wrong credentials for the server you're attempting to authenticate to.

**Comment by sigmavirus24** [comment]
@drpoggi is likely correct. Further, without extra information, it's hard for any of the people you tagged in this bug to help you (let alone the maintainers of this project).

If you have a _question_ please ask it on [StackOverflow](https://stackoverflow.com).

**Comment by Lukasa** [comment]
I presume the _actual_ question is: is it a bug that the two WWW-Authenticate headers got merged into one.

The answer is no. WWW-Authenticate is defined as a list header, and the relevant RFC (RFC 7235 for those keeping track) explicitly points out that the header may contain multiple challenges, each of which is comma-separated, as well as the various comma-separated parameters. What requests did was totally fine here.

**Comment by beruhan** [comment]
here is a example,`import requests
from requests.auth import *
req = requests.get('http://61.91.211.158:81/onvif/snapshot/101',timeout=3)
print req.headers`,but it raise timeout exception,I have used wireshark to capture the packets,It response quikly.`HTTP/1.1 401 Unauthorized
Date: Sat, 29 Oct 2016 19:06:59 GMT
Server: DNVRS-Webs
Cache-Control: no-cache
Content-Type: text/html
Connection: keep-alive
Keep-Alive: timeout=60, max=99
WWW-Authenticate: Basic realm="DVRNVRDVS"
WWW-Authenticate: Digest realm="DVRNVRDVS", domain="::", qop="auth", nonce="71225169d5e6c3e80672d195911b6d23", opaque="", algorithm="MD5", stale="FALSE"`,why requests will raise timeout exception? ,and when I remove timeout param It will get 401 status code,but will wait a long long time.@Lukasa @sigmavirus24 @drpoggi

**Comment by Lukasa** [comment]
I suspect that the issue is that the response is not correctly terminated, which causes Requests to expect more data to show up. Is there any body content? Because having a Content-Type suggests there is.
