### ISSUE TITLE
Requests library becomes broken, forcing reinstallation solves the problem

### ISSUE THREAD

**Issue by ssbarnea** [kennethreitz/requests#3670]
It seems that I am not the only one that discovered that his python-requests library is in a broken state.
```
    import requests
  File "/usr/lib/python2.7/site-packages/requests/__init__.py", line 64, in <module>
    from . import utils
  File "/usr/lib/python2.7/site-packages/requests/utils.py", line 29, in <module>
    from .exceptions import InvalidURL, InvalidHeader, FileModeWarning
ImportError: cannot import name InvalidHeader
```

See https://bugzilla.redhat.com/show_bug.cgi?id=1393979 and http://stackoverflow.com/questions/32986626/python-requests-importerror-cannot-import-name-headerparsingerror which are two unrelated occurences that are fixed by the same workaround:

`pip install --upgrade --force-reinstall requestsexceptions requests requests-toolbelt`

#### pip freeze
I mention that the forced reinstallation did not change the reported versions but fixed the import error.
```
requests==2.11.1
requests-toolbelt==0.7.0
requestsexceptions==1.1.3
urllib3==1.15.1
```

**Comment by Lukasa** [comment]
This is unequivocally not a Requests issue. Requests defines `InvalidHeader` in the `exceptions` module, that import has to work. If it doesn't work, it's the result of something messing with the requests exceptions heirarchy. Given that you have installed a package called `requestsexceptions` you should strongly consider the possibility that _they_ broke your software, not us.

**Comment by sigmavirus24** [comment]
FYI, requestsexceptions looks like it doesn't monkey-patch `requests.exceptions`: https://github.com/openstack-infra/requestsexceptions/blob/master/requestsexceptions/__init__.py.

Either way, force reinstalling indicates that this is emphatically not our problem (as @Lukasa has already pointed out).

**Comment by sigmavirus24** [comment]
Also, @ssbarnea, http://stackoverflow.com/questions/32986626/python-requests-importerror-cannot-import-name-headerparsingerror seems to be a different (although similar) issue. From the StackOverflow issue it looks like you have some left over bits of old versions of requests on your disk.

**Comment by AaronM04** [comment]
For the lazy, the commands that successfully fixed this are:

```
sudo pip uninstall requests
sudo pip install --upgrade requests
```
