### ISSUE TITLE
[Errno -3] Temporary failure in name resolution

### ISSUE THREAD

**Issue by kalyanakannan** [kennethreitz/requests#3677]
While trying to get access token from api I getting the follwoing error,

ConnectionError: HTTPSConnectionPool(host='', port=443): Max retries exceeded with url: /oauth2/access_token/ (Caused by <class 'socket.gaierror'>: [Errno -3] Temporary failure in name resolution)

Is there any way I can resolve this error?

Thanks.

**Comment by Lukasa** [comment]
This error means that a DNS problem occurred and we couldn't resolve the IP address. If you see this problem you should simply retry the request.

**Comment by kalyanakannan** [comment]
Already I have tried that, but it's not working for me. Shall I try with IP address Or is there any other solution for this?

**Comment by Lukasa** [comment]
Can you print the URL you're trying to reach?

**Comment by kalyanakannan** [comment]
I tried the same API URL in postman, its working fine. But  in my request method, it throws the above error.

**Comment by Lukasa** [comment]
So this strongly suggests you have a problem with your OS or Python configuration, or possibly your URL, because it seems like the Python code cannot resolve the domain name.

**Comment by kalyanakannan** [comment]
I am getting the right URL from requests. Following warning error message is displayed while running the script. Is there any issues?

/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning

**Comment by Lukasa** [comment]
Those error messages aren't going to be relevant, no. Can you set `allow_redirects=False` to see if you're being redirected away?

**Comment by kalyanakannan** [comment]
it's working now. problem from dns system. thank you

**Comment by syedn** [comment]
how did u resolve dns problem???

**Comment by ibgithub** [comment]
I face the same problem, and solved by restart computer

**Comment by andre-cavalheiro** [comment]
I fixed this by disabling my VPN

**Comment by netdesign** [comment]
You have issues with your DNS. Check on your system that public interface is configured to use correct DNS servers.

**Comment by georgesamy** [comment]
For me, it was the firewall that was blocking the connection. I'm using ufw .. the following command fixed it for me.
`sudo ufw allow out to any port 53`
don't forget to reload ufw
`sudo ufw reload`
