### ISSUE TITLE
v2.12.0: URL has an invalid label error

### ISSUE THREAD

**Issue by afaicode** [kennethreitz/requests#3686]
When url contains an underscore the request fails with 'URL has an invalid label error'

Seems like a result of updating to urllib3 to 1.19.

While underscores in the hostname would not meet strict RFC requirements it would still work in many scenarios, so I would propose to remove the check

Example:
```
requests.get('http://test_t')
*** InvalidURL: URL has an invalid label.
```

**Comment by nateprewitt** [comment]
Thanks for opening this issue, @afaicode. This is currently being tracked in #3683 which will be the official issue for further discussion. I believe @Lukasa has stated underscores in host names are not behaviour we likely want to support, but you're welcome to raise objections in the appropriate issue.

**Comment by Lukasa** [comment]
Yup, closing in favour of #3683.
