### ISSUE TITLE
A whitespace at the start of Url causes error on request

### ISSUE THREAD

**Issue by hussaintamboli** [kennethreitz/requests#3696]
In [1]: import requests

    In [2]: requests.get("http://stackoverflow.com/")
    Out[2]: <Response [200]>

    In [3]: requests.get(" http://stackoverflow.com/")
    # ... stacktrace skipped ...
    InvalidSchema: No connection adapters were found for ' http://stackoverflow.com/'

Url should have been stripped. But I may be missing something here.

**Comment by Lukasa** [comment]
I'm open to a PR that will cause us to strip URLs, that seems reasonable enough to me.

**Comment by hussaintamboli** [comment]
Sure.

**Comment by hussaintamboli** [comment]
I have created a pull request #3697. Please have a look.

**Comment by hussaintamboli** [comment]
PR is merged. Closing it as it's fixed.
