### ISSUE TITLE
SSLError: [SSL] PEM lib (_ssl.c:2603) when I want to connect to a server with TLS

### ISSUE THREAD

**Issue by darakt** [kennethreitz/requests#3702]
Hi, 
I can't connect myself to an Apple server using requests.
I can connect myself to this same server using openssl directly or using socket directly
For instance, I'm doing that in such way with openssl
`openssl s_client -CAfile GeoTrust_Global_CA.pem -connect api.push.apple.com:443
`
My code is pretty basic:
`s = requests.session()
    s.cert = "GeoTrust_Global_CA.pem"
    s.port = 443
    url = 'https://api.push.apple.com'
    r = s.get(url)`

**Comment by Lukasa** [comment]
@darakt You're using the `cert` argument, but you want to be using the `verify` argument.

**Comment by kevr** [comment]
`requests.get('url', verify=True)` is causing this issue for me.
