### ISSUE TITLE
bug in PreparedRequests without simplejson library (under jython 2.7 only?)

### ISSUE THREAD

**Issue by j-christ** [kennethreitz/requests#3705]
I noticed the following bug when running requests under jython 2.7 where I had not yet installed simplejson:

In requests/models.py, the method PreparedRequest.prepare_body has the following code:

````
        if not data and json is not None:
            # urllib3 requires a bytes-like body. Python 2's json.dumps
            # provides this natively, but Python 3 gives a Unicode string.
            content_type = 'application/json'
            body = complexjson.dumps(json)
            if not isinstance(body, bytes):
                body = body.encode('utf-8')
````

`json` in this case, is defined from the .compat file:

````
try:
    import simplejson as json
except (ImportError, SyntaxError):
    # simplejson does not support Python 3.2, it throws a SyntaxError
    # because of u'...' Unicode literals.
    import json
````

If simplejson is not installed under jython, the code in models.py throws an exception because dumps is not defined in the json module.

**Comment by Lukasa** [comment]
In this instance, I think I'm inclined to suggest that this is a JSON problem, not a Requests problem. json.dumps is not a new interface. And without it, our json parameter cannot possibly work anyway.

**Comment by nateprewitt** [comment]
@j-Christ, Jython 2.7 should support dumps without issue. I'd suggest checking your local directory or python path for another json.py file.

**Comment by j-christ** [comment]
@nateprewitt Thanks!  That was the issue...somewhere in the jython path was a json package by patrickdlogan@[...].com, and requests was finding that one instead.
