### ISSUE TITLE
Allow domains instead urls

### ISSUE THREAD

**Issue by sihaelov** [kennethreitz/requests#3708]
```
requests.get('google.com')
requests.exceptions.MissingSchema: Invalid URL 'google.com': No schema supplied. Perhaps you meant http://google.com?
```

Why does it not allow use domains? It looks as the simple task and I can do it. What do you think? I searched similar issues but did not find.

**Comment by sigmavirus24** [comment]
It's impossible to know whether you wanted us to use HTTP or HTTPs, and in the face of uncertainty (especially when privacy is concerned) it's significantly more correct to not guess.

You can absolutely implement whatever behaviour you're thinking of in a wrapper. There's no need and no desire for it to live in Requests.
