### ISSUE TITLE
Indna causes issues with Jython due to uts46data.py

### ISSUE THREAD

**Issue by johnabooth** [kennethreitz/requests#3711]
Unable to use requests in Jython 2.7 without some patches to Indna.  I've made these at https://github.com/METAVERO/idna and notified main repo owners.

**Comment by Lukasa** [comment]
Thanks for letting us know. You should strongly consider opening a pull request on the idna repository instead of just an issue.

**Comment by johnabooth** [comment]
Hi Lukasa, I did open a pull request on my repository and then closed it.  A little new to Github -- do I need to open another pull request or are you able to review the history in that repo?

**Comment by Lukasa** [comment]
It's harder to review the history. It would be easier if you opened a pull request against the _original_ repository though.

**Comment by johnabooth** [comment]
Please review - https://github.com/METAVERO/idna/pull/1

I re-did the repo via a fork from original since it wasn't setup properly before.  There is now an open pull request to the main Idna project.

**Comment by nateprewitt** [comment]
@johnabooth It doesn't look like you've actually opened a pull requests against the upstream repo [kjd/idna](https://github.com/kjd/idna). You'll need to visit that repo, use the "New Pull Request" button and select your branch `johnabooth-jython27-fix`. The maintainer of that repo should be able to perform a review on your proposed changes.

**Comment by ppolewicz** [comment]
https://github.com/kjd/idna/pull/33 was merged. It splits the large piece of code to smaller ones and should fix the Jython issue.

`idna` released `https://github.com/kjd/idna/releases/tag/v2.2`, so if the dependency is adjusted, #3711 should be resolved. Should the entry in `setupy.py`'s `extras_require['security']` be increased to 2.2?

**Comment by Lukasa** [comment]
I don't think we need to do that, no. Jython users will simply get the newest version as appropriate.

**Comment by johnabooth** [comment]
Thanks all.
