### ISSUE TITLE
Older changelog entries don't specify urllib3 versions

### ISSUE THREAD

**Issue by alexwlchan** [kennethreitz/requests#3712]
Some of the older changelog entries, starting at 2.4.0 and working backward, mention that the urllib3 version was bumped but don't say what version it was bumped to.

This can cause mildly annoying dependency resolution problems, especially if you partake in unsavory activities such as:

* Installing requests from an RPM source that doesn't vendor urllib3
* Running extremely outdated versions of requests/urllib3

It would be useful if the changelog included these details (as newer changelog entries do).

I'm happy to put in the time to do this, but probably not immediately.

**Comment by Lukasa** [comment]
So, uh, this won't work as well as you think.

Prior to v2.6.2 the Requests team didn't necessarily update to specific urllib3 versions but instead updated to the state of the urllib3 master branch. That means there often *is no* urllib3 version that directly matches what Requests was using. So my question is: why does your RPM source not appropriately state this dependency?

**Comment by alexwlchan** [comment]
That’s unfortunate.

I’m not entirely sure where the RPM came from (somebody else put it in the codebase and didn’t update the urllib3 RPM). We’ve managed to resolve the current issue by updating to a newer-ish version, which seems to have resolved the current issues.

Since there isn‘t a nice mapping of requests versions::urllib3 versions, I guess I’ll leave this for now.
