### ISSUE TITLE
Old "cryptography" package causes crash

### ISSUE THREAD

**Issue by aseering** [kennethreitz/requests#3714]
As of `requests==2.12.1`, `requests[security]` depends on `cryptography>=1.3.4`.  That's fine.  However, `requests` (without `[security]`) crashes if `cryptography==1.0.2` is installed.  This is a perfectly valid configuration of packages according to `pip`; as a user, I would expect it to behave as if I had not specified `[security]` (because I didn't specify it).

The specific failure is discussed a bit more here:

http://discuss.flexget.com/t/unhandled-error-in-plugin-configure-series-solved/2900

The crash was resolved, also as described at the above link, by running:

```
pip install --upgrade cryptography
```

Uninstalling `cryptography` would probably have worked fine too.

The crash appears to be caused because `requests` internally tests for `[security]` by importing a thing which imports its bundled `pyopenssl` which imports `cryptography`; if that succeeds, the extra is used.  But with a too-old version of `cryptography`, it imports just fine but it constructs objects that are missing required fields.

I can think of a couple approaches here:

* Catch this failure and print an error message that more-helpfully explains that your `cryptography` package needs updating
* Validate the version/functionality of the `cryptography`package more carefully, and don't enable the `[security]` extra's features if an old version happens to be installed

I'd be happy to post a PR for either approach.  Right now I'm looking for feedback on whether it's worth addressing this (I'd certainly appreciate it) and on what approach you'd prefer.

**Comment by Lukasa** [comment]
Thanks for this!

I think this is actually fundamentally a problem with urllib3: urllib3's contrib module should be more aggressively checking for whether it possesses a suitable cryptography module before injecting itself. If you open an issue on that repository, we can take it forward from there.

Thanks again for the report!

**Comment by aseering** [comment]
Thanks @Lukasa !  Posted an issue in (what I hope is) the main urllib3 repo.

**Comment by aseering** [comment]
Gentle *ping* here -- this has been fixed upstream; is there anything I can/should be doing to pull the fix in here?

**Comment by Lukasa** [comment]
Nope. Updates to urllib3 are brought in as part of our release process. It'll get merged when it gets merged.
