### ISSUE TITLE
CLOSE_WAIT Issue

### ISSUE THREAD

**Issue by venkat2111987** [kennethreitz/requests#3730]
Hi,

We are developing a python application using tornado framework. The application consumes a REST end point exposed by splunk system to get some metrics data. A scheduled background process runs and populates our application local data-store.  While tornado serves data to third party using the local data-store. 

We are using Requests==2.9.1 to communicate with Splunk

Code snippet using which we are communicating to Splunk:
------------------------------------------------------------------
                      try:
                            resp = requests.get(splunkapi,params = params, verify = False, headers = header )
                            if resp.status_code == 200 and (resp.content not in ['""','"None"']) :
                                results = json.loads(resp.json())
                                with open("outfile.json" , 'w') as outfile:
                                    json.dump(results, outfile,indent=4)
                            else:
                                with open("outfile.json" , 'w') as outfile:
                                    json.dump(dict(), outfile,indent=4)
                      except Exception,e:
                            with open("outfile.json" as outfile:
                                json.dump(dict(), outfile,indent=4)

CLOSE_WAIT Issue:
---------------------
Step 1: I bring up Tornado Application.
Step 2: I bring up splunk system.
Everything works fine
Step 3: For some reason, the sys admins have to reboot the machine where tornado application is running.
Lot of connections in CLOSE_WAIT status at splunk side.
Step 4: Restart Splunk.
Everything is cleaned up. The system continues to run smoothly.
Step 5: Reboot the system where tornado application is running.
Again same issue. Lot of CLOSE_WAIT connections at splunk side. 

Are the CLOSE_WAIT connections a result of "Requests" not communicating properly with splunk?

**Comment by Lukasa** [comment]
No. 

CLOSE_WAIT is the TCP state that is entered by the TCP peer that initiates a connection close. It cannot be avoided: it exists to ensure that delayed or retransmitted packets belonging to a TCP connection are not lost.

When the Tornado application is closed down, Requests' pooled sockets all get closed by the Python runtime or the OS. That means your Tornado application initiated the close, and so all those pooled sockets will enter TIME_WAIT. This is not a problem: it is expected behaviour for a TCP client.

**Comment by Lukasa** [comment]
Ah, apologies, I see you're getting the CLOSE_WAIT on the other machine. That seems like Splunk is initiating an idle timeout. What Python interpreter are you using?

**Comment by venkat2111987** [comment]
We are using Python 2.7.5 for our tornado application (dockerized). The splunk version on the other machine is 6.4.0 which is packaged with python 2.7.11.

Thanks!

**Comment by Lukasa** [comment]
Are you familiar with Wireshark? It would be interesting to see Wireshark traffic from the application. In particular, I'm interested to see whether the TCP connections your server sets up to splunk are cleaned up promptly in use or not.
