### ISSUE TITLE
empty username and password no longer generate basicauth authstring

### ISSUE THREAD

**Issue by hummus** [kennethreitz/requests#3736]
Possibly just a previously quirkly behavior that intentionally no longer works.

For `requests<2.12.2` having `None` for username and password still resulted in a BasicAuth authstr being created. Starting in `2.12.2` it will raise an exception.

```Traceback (most recent call last):
  ...
  File "/blah/lib/python2.7/site-packages/requests/auth.py", line 38, in _basic_auth_str
    b64encode(b':'.join((username, password))).strip()
TypeError: sequence item 0: expected string, NoneType found
```

here's the change, (which certainly seems desirable), but caused our upstream (`python-gitlab`) to break.
https://github.com/kennethreitz/requests/commit/329a5cfdd4500fb1ce405a3242ef95f9197d24ba

**Comment by Lukasa** [comment]
Uh...what basic auth string did it generate?

**Comment by hummus** [comment]
```
(Pdb) username is None
True
(Pdb) password is None
True
(Pdb) authstr
'Basic Tm9uZTpOb25l'
```
yea i'm fully aware that this doesn't make much sense and closing wontfix seems entirely reasonable. Just figured I'd call it out in case anyone else was similarly relying on the behavior.

**Comment by Lukasa** [comment]
Heh, yeah, that's the base64 encoded form of `None:None`. I think we can call this wontfix: that should never have worked, and it's quite surprising.

**Comment by floer32** [comment]
@hummus should we file a ticket at [python-gitlab](https://github.com/gpocentek/python-gitlab/issues)'s issue tracker? I would do it myself but I don't know enough about the problem
