### ISSUE TITLE
The new 2.12.2 breaks certain docker-py's build's argument

### ISSUE THREAD

**Issue by huikang** [kennethreitz/requests#3741]
see the issue in https://github.com/docker/docker-py/issues/1325, although I am not sure this is a right place to post.

**Comment by StewPoll** [comment]
As per #3734 this is already getting worked on. The relevant issue to follow in Requests is #3735 

Also - If you had locked in docker/docker-py you'd see that they had already been talking about this over there in [docker/docker-py/#1321](https://github.com/docker/docker-py/issues/1321)

**Comment by Lukasa** [comment]
Yup, this is a duplicate. Closing in favour of #3735.
