### ISSUE TITLE
Proxy socks windows

### ISSUE THREAD

**Issue by kityamoto** [kennethreitz/requests#3768]
`$ pip install requests[socks]`

`>>>import requests`
`>>>proxies = {'http': 'socks5://127.0.0.1:9150','https': 'socks5://127.0.0.1:9150'}`
`>>>r = requests.get('https://api.github.com', proxies=proxies)`
`Traceback (most recent call last):`
`...`
`   raise InvalidSchema("Missing dependencies for SOCKS support.")`
`requests.exceptions.InvalidSchema: Missing dependencies for SOCKS support.`

Package is installed win_inet_pton with pysocks automatically.
`$ pip install win_inet_pton`

**Comment by Lukasa** [comment]
Can you provide the output of `pip freeze`, and confirm that when you type `import socks` that that works?

**Comment by johaven** [comment]
I confirm for him ;)

```
>> pip freeze
future==0.16.0
psutil==5.0.0
PySocks==1.6.5
requests==2.12.4
six==1.10.0
win-inet-pton==1.0.1
```


```
>> python
Python 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import socks
>>>
```

**Comment by sigmavirus24** [comment]
@yoyoprs I believe @Lukasa wanted you two to `import socks` and then check that the version was the same as what `pip` reports.

**Comment by renxt0310** [comment]
Sounds greate.I will get right on it

**Comment by drnextgis** [comment]
Workaround:

```
pip install win-inet-pton
```
