### ISSUE TITLE
Problem running PyInstaller 3.2 compiled executable using requests v2.12.x

### ISSUE THREAD

**Issue by sureshk75** [kennethreitz/requests#3775]
Hi, firstly thank you for the awesome module that you have here. I've been using Python 3.4.4 on an app I created about 2 months ago and recently ran into some issues with requests. The following is the traceback displayed when attempting to run it after compiling it into a windows executable using PyInstaller 3.2 using requests v2.12.x (all patches). I have downgraded to requests v2.11.1 as that version compiles and runs without errors. I thought I'd give you the heads up as I couldn't find a similar issue and solution anywhere.

Thanks

> Traceback (most recent call last):
>   File "site-packages\requests\packages\__init__.py", line 27, in <module>
>   File "C:\Python34\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
>     exec(bytecode, module.__dict__)
>   File "site-packages\requests\packages\urllib3\__init__.py", line 8, in <module>
>   File "C:\Python34\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
>     exec(bytecode, module.__dict__)
>   File "site-packages\requests\packages\urllib3\connectionpool.py", line 28, in <module>
>   File "site-packages\requests\packages\urllib3\packages\six.py", line 203, in load_module
>   File "site-packages\requests\packages\urllib3\packages\six.py", line 115, in _resolve
>   File "site-packages\requests\packages\urllib3\packages\six.py", line 82, in _import_module
> ImportError: No module named 'queue'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "dt3.py", line 13, in <module>
>   File "C:\Python34\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
>     exec(bytecode, module.__dict__)
>   File "site-packages\requests\__init__.py", line 63, in <module>
>   File "C:\Python34\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
>     exec(bytecode, module.__dict__)
>   File "site-packages\requests\utils.py", line 24, in <module>
>   File "C:\Python34\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
>     exec(bytecode, module.__dict__)
>   File "site-packages\requests\_internal_utils.py", line 11, in <module>
>   File "C:\Python34\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
>     exec(bytecode, module.__dict__)
>   File "site-packages\requests\compat.py", line 11, in <module>
>   File "C:\Python34\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
>     exec(bytecode, module.__dict__)
>   File "site-packages\requests\packages\__init__.py", line 29, in <module>
> ImportError: No module named 'urllib3'

**Comment by Lukasa** [comment]
This seems like a pyinstaller problem: our import of the queue module via `six` isn't being detected. You should ensure that your packaging includes that standard library module.

**Comment by mafrosis** [comment]
@Lukasa We hit this problem today. Can you explain what you mean by:
> You should ensure that your packaging includes that standard library module.

Thanks

**Comment by Lukasa** [comment]
The queue module, which is part of the standard library.

**Comment by mafrosis** [comment]
Thanks for the quick reply @Lukasa. Seems the pyinstaller guys think this is a problem with requests due to your bundling of `six` (https://github.com/kennethreitz/requests/issues/3793).

Any thoughts on that? I'd like to try to help get this resolved.

**Comment by Lukasa** [comment]
I'm pretty unimpressed that pyinstaller thinks this is our fault. We are using valid Python code that through a valid import chain imports a stdlib module that they are removing. Our job is not to contort ourselves for the benefit of their tool. Their job is to support valid Python code.
