### ISSUE TITLE
Handle Content in new tab

### ISSUE THREAD

**Issue by arunchandramouli** [kennethreitz/requests#3778]
I tried to scrap report from https://www.theice.com/marketdata/reports/datawarehouse/ConsolidatedDailyVolumeOIReport.shtml?selectionForm=

We can find Report Date, Asset Class and a Submit button
When we hit submit it actually opens in a new Tab as 

https://www.theice.com/marketdata/reports/datawarehouse/ConsolidatedDailyVolumeOIReport.shtm

I tried simulating POST, but it always says Session Time Out.

On Contrast if you could see
https://www.theice.com/marketdata/reports/175.
When you enter dates and hit submit, it opens but not in a new tab, in this case requests is able to get the data.

Is there any solution for this? Please suggest.

**Comment by sigmavirus24** [comment]
Questions belong on [StackOverflow](https://stackoverflow.com) using the [python-requests tag](http://stackoverflow.com/questions/tagged/python-requests) not in the defect/bug tracker.

**Comment by arunchandramouli** [comment]
But it's not working?

**Comment by sigmavirus24** [comment]
@arunchandramouli taking a quick look at those websites, it looks as if they require JavaScript in order for you to successfully scrape their data. Requests does not (and has never) executed JavaScript. You need a different tool. Requests is working exactly as expected. There is no bug here.
