### ISSUE TITLE
SSL context

### ISSUE THREAD

**Issue by AlmightyOatmeal** [kennethreitz/requests#3784]
In some instances, requests is used to access services via SSL that disable TLS v1.0 for security reasons but there is no way to configure what SSL/TLS versions are acceptable nor pass in a SSL context. This is very disappointing.

For example, I *need* to be able to create this context and use it, but I can't...
```
import ssl
context = ssl.SSLContext(ssl.PROTOCOL_SSLv23)
context.options |= ssl.OP_NO_TLSv1
```

**Comment by Lukasa** [comment]
Thanks for this report!

Firstly, services that disable TLSv1 should still be compatible with Requests. Requests advertises support for all TLS versions higher than SSLv3 in the default configuration, so services should simply choose TLSv1.2. Requests will happily do that. 

Secondly, you absolutely can pass an SSL context as of v2.12. See [this comment](https://github.com/kennethreitz/requests/issues/3777#issuecomment-267998174) for an example of how to do it.

I hope that calms your disappointment.

**Comment by Lukasa** [comment]
I should note: *please* do not use the context in your original comment. It's severely insecure. Please always use `create_urllib3_context` and then edit it accordingly: you'll get much higher security that way, and we'll keep moving forward with more secure configurations.

**Comment by AlmightyOatmeal** [comment]
> Firstly, services that disable TLSv1 should still be compatible with Requests. 

In an ideal world, yes. This is the real world which is far from ideal.

> Requests advertises support for all TLS versions higher than SSLv3 in the default 
> configuration, so services should simply choose TLSv1.2. Requests will happily do 
> that.

Obviously not.

> Secondly, you absolutely can pass an SSL context as of v2.12. See this comment 
> for an example of how to do it.

Also not true. I have to create an entire adapter to pass into it instead of simply passing in a context. However, it does work! I was able to successfully modify Zeep to nicely handle that new adapter for the session and it worked like a champ but I still had to construct my own context that was only slightly different than the one urllib3 made. 

> I should note: please do not use the context in your original comment. It's severely 
> insecure. Please always use create_urllib3_context and then edit it accordingly: 
> you'll get much higher security that way, and we'll keep moving forward with more 
> secure configurations.

So far from the truth. What does `create_urllib3_context` do? Literally the same thing I did.

In the end, thank you for the suggestion because that adapter did exactly what I needed it to. Unfortunately Zeep is such a mess that it may be a moot point although I should be able to modify Suds to use requests. I am still a fan, and advocate, of the `requests` module! 

Cheers Lukasa!
