### ISSUE TITLE
Pyinstaller error with requests version > 2.11.1

### ISSUE THREAD

**Issue by Sattar1** [kennethreitz/requests#3793]
Hi
I am developing an application with python, using _requests_ library in it.
I make executable file with _pyinstaller_ library.

My application works with newest version of _requests_ when I run it through python commands or inside IDLE. But when I get EXE output with _pyinstaller_, It doesn't run correctly. Here is the message:

"
... (trace files)
ImportError: No module named 'queue'
During handling of the above exception, another exception occurred:
... (trace files)
ImportError: No module named 'urllib3'
Failed to execute script.
"
So I figured out that there is something wrong with _**urllib3**_ library. Then I downgraded _requests_ to "2.11.1" version (One before updating bundled urllib3 to 1.19) and created another EXE file. Rerun it, and worked!

Now I know that there is something wrong with newer versions of _requests_ (> 2.11.1) and _pyinstaller_. But don't know how to fix it. Could you plz help me?

Thanks.

**Comment by Lukasa** [comment]
This is strictly a PyInstaller issue. Requests works fine, and vendors all of its dependencies. Clearly PyInstaller is having trouble locating the dependent module, even though it is entirely within the Requests package. That problem is PyInstaller's, and you'll need to take it up with them.

**Comment by htgoebel** [comment]
This is caused by requests' bundling it's own copy of `six`.
