### ISSUE TITLE
Use proxy to hide IP

### ISSUE THREAD

**Issue by Djokx** [kennethreitz/requests#3800]
Hi,
I'm trying to use a proxy to hide my IP with my script.

I'm just trying 
`requests.get("https://api.ipify.org?format=json", proxies={"http":proxies[0][:-1]}).json()`

But I get my real IP address, no the proxy's one. It that normal ? How is it possible to hide my IP with requests ?

Thanks

**Comment by Lukasa** [comment]
The proxy dictionary is keyed on the scheme of the URL you are *requesting*. In your example you are requesting a *https* URL with a proxy dictionary that only has a *http* key. This means Requests thinks you don't want to proxy https requests, and so sends them directly. Add *https* to your proxy dictionary as well, using the same proxy, and you should be fine.
