### ISSUE TITLE
Add validation of HTTP URL

### ISSUE THREAD

**Issue by Th30n** [kennethreitz/requests#3815]
I'd like to verify that a URL will be valid for a HTTP request. The main motivation is telling the user in the GUI that the typed URL cannot be used.

Currently, I'm using `requests.models.parse_url`, but this is obviously not enough because `PreparedRequest.prepare_url` performs additional checks (e.g. `host.encode('idna')`). It would be great if the same checks were exposed as a public API.

**Comment by Lukasa** [comment]
The simplest thing to do is to use the [PreparedRequest flow](http://docs.python-requests.org/en/master/user/advanced/#prepared-requests): specifically the second example, which goes via a Session.

You can catch exceptions raised in this process and use those to determine the validity of the URL.

**Comment by sigmavirus24** [comment]
You could also use rfc3986 which has some validation code built-in.

**Comment by Th30n** [comment]
Thanks @Lukasa.
