### ISSUE TITLE
Import error with idna version

### ISSUE THREAD

**Issue by llazzaro** [kennethreitz/requests#3818]
Hello,

I recently upgraded to 2.12 and I started to see this import error:

> (Pdb) request('get', url, params=params, **kwargs)
> *** ImportError: No module named uts46data

Looking in the changes I saw that it was recently added idna. 
My projects are using import hooks and inside of it the hook use requests.

The code of idna is doing an import inside the method uts46_remap, which is breaking my code.
Moving the import uts46_remap outside fixes this issue.

**Comment by Lukasa** [comment]
Closed for reasons discussed in #3819.
