### ISSUE TITLE
Access to the server certificate

### ISSUE THREAD

**Issue by Te-k** [kennethreitz/requests#3826]
Hi,
I checked documentation and the stackoverflow questions (like [this](https://stackoverflow.com/questions/16903528/how-to-get-response-ssl-certificate-from-requests-in-python)) and from what I see, it is not possible to get the server certificate information with requests.

* Is there any hack to get this info?
* Is there any plan to add this info to the answer? If no, consider this as a feature request :+1:

**Comment by Lukasa** [comment]
> Is there any hack to get this info?

Yes. If you stream the response (that is, set `stream=True`), then when you get the response back you can go digging for the socket. Depending on the Python version it'll be in slightly different places: on Python 2 it'll be at `response.raw._fp.fp._sock`, on Python 3 it'll be `response.raw._fp.fp.raw._sock`. At this point, for SSL connections, you can call `getpeercert()`.

> Is there any plan to add this info to the answer?

There is not. =)

Ultimately, this is a feature that's of minimal utility to most people. It comes too late to make doing any kind of security validation worthwhile, and if the goal is simply to determine the certificate for a remote peer it is almost always going to be better to use the ssl and socket modules directly, or even the OpenSSL command line tool.

So the number of people for whom this feature would provide a benefit is ultimately too low to justify adding it. Sorry!

**Comment by Te-k** [comment]
Thanks for your quick answer.

As I could not find any answer to that question, some other people may find this hack interesting. Is there a place where I could add this for documentation? (Like a  "ugly hack that works" in the documentation?)

I noticed that the cert is not available if verify is False, is there any way of still accessing this information even without verifying the certificate?

**Comment by Lukasa** [comment]
I would vastly prefer not to add this hack to the documentation, primarily because we don't promise it'll continue to work.

> I noticed that the cert is not available if verify is False, is there any way of still accessing this information even without verifying the certificate?

I'm afraid not. This is a product of the way OpenSSL works: `verify=False` turns into `CERT_NONE`, which causes OpenSSL to not store the certificate if the remote peer presents it.
