### ISSUE TITLE
Strict-Transport-Security Header not complet submittet

### ISSUE THREAD

**Issue by MrFastDie** [kennethreitz/requests#3834]
I'm trying to get the strict-transport-security header in python3 with requests.
My code looks like the following:
`import requests
r = requests.get("https://%s" % domain")
print (r.headers)`

My problem is that the strict-transport-security header does not contain all data. The real Header looks like ```max-age=31536010; includeSubDomains; preload```, but the header by r.headers['strict-transport-security'] only contains ```max-age=31536010; includeSubDomains```, not the preload which is needed by my application.

Tested on FreeBSD 11.0 and Mint Rosa and Arch 4.8.13

**Comment by Lukasa** [comment]
Requests does not amend the headers in any way, so you get what we received. Are there any proxies or other intermediaries which may be amending headers?
