### ISSUE TITLE
ignoring MTU and MSS in TCP handshake

### ISSUE THREAD

**Issue by boogardgodig** [kennethreitz/requests#3838]
Hi
I was using requests flawlessly till yesterday I realised I cannot send large packets to https server getting following error
`requests/adapters.py", line 473, in send
raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine("''",))
`
Turns out my ISP started filtering ICMP fargmentation needed packets and drops large packets. Otherwise packets would have been fragmented and retransmited. Shouldn't requests fragment packets with respenct to MTU or MSS to prevent this from happening?
Is there a work around to this problem?

**Comment by Lukasa** [comment]
Requests does not control the way packets are emitted. The socket API for TCP does not expose or allow us to control packet boundaries: the TCP layer in the kernel manages all of this. Any problem you're seeing would be encountered by other programs on your system. 

You'll need to investigate your system's configuration.
