### ISSUE TITLE
multipart/form-data not encoding correctly on recent versions

### ISSUE THREAD

**Issue by cmanallen** [kennethreitz/requests#3839]
I have a request that works in older version of the `requests` library but not in more recent versions.  The trouble point is the `model` key in the files dictionary.  In version `2.11.1`, the model key is correctly recognized by the remote endpoint.  In newer versions, the `model` key appears to be omitted or malformed in some way.

I don't believe the API endpoint is the issue.  I can execute a `curl` command and it will work as expected.

A sample (functioning) curl request:

```bash
curl -F data_file=@my_file.mp3 -F model=en-US "https://api.speechmatics.com/v1.0/user/1/jobs/?auth_token=ABC"
```

### Request

```python
import requests


files = {
    'data_file': open(filename, 'rb'),
    'model': ('', 'en-US'),
}
response = requests.post(
    'https://api.speechmatics.com/v1.0/user/1/jobs/?auth_token=ABC',
    files=files)
print(response.content)  # b'{\n  "code": 400, \n  "error": "No language selected"\n}'
```

### Versions tested:
*All versions installed through `pip` and are being used with `python 3.5`.*

`2.11.1` - Works.
`2.12.4` - **Fails.**
`2.13.0` - **Fails.**

**Comment by Lukasa** [comment]
Yeah, this behaviour changed. In particular, the lower-level urllib3 library wanted to allow the possibility of setting an *empty* filename (as opposed to not providing the filename at all). You can get the correct behaviour on all platforms by changing `'model': ('', 'en-US'),` to `'model': (None, 'en-US'),`

**Comment by cmanallen** [comment]
@Lukasa Thanks!
