### ISSUE TITLE
PUT (requests.put) specifying the source file location for zip file error 10054

### ISSUE THREAD

**Issue by Twoflower2** [kennethreitz/requests#3842]
With using trying an zip file I get the following, any clues: (requests-2.13.0)

```
with open('default.zip', 'rb') as data:
    requests.put(url, data=data)

```
Output:

```
C:\svn\libraries\cpp>python req_put.py default.zip

Traceback (most recent call last):
  File "req_put.py", line 102, in <module>
    resp = requests.put(uri,  headers=headers, data=data) # data=data , params=payload)
  File "C:\Python27\lib\site-packages\requests\api.py", line 124, in put
    return request('put', url, data=data, **kwargs)
  File "C:\Python27\lib\site-packages\requests\api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 473, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error(10054, 'An existing connection was forcibly closed by the remote host'))

```

**Comment by Lukasa** [comment]
The server will have sent a 4XX response, which means it doesn't like your upload. Unfortunately Requests can't handle this yet, because httplib doesn't make it easy. We're working on a substantial refactor to fix this, but it'll be a long time coming. In the meantime, I suggest you try to investigate what format the server is actually expecting.

**Comment by Twoflower2** [comment]
@Lukasa Many thanks. Seeing that is really seems you know what is going on here 3 qs:

1. What other Python cURL lib can I use here that you might know of that works?
2. Why would requests.put() work perfectly not specifying the data param, hence not specifying the source location of file?
3. Not being sure how cURL does this, is it not possible to also add the cURL `-T, --upload-file <file>` like option in the requests library?

**Comment by Lukasa** [comment]
1. pycurl
2. HTTP is a very general protocol. PUT does not inherently have anything to do with uploading files. In fact, it's perfectly allowed to send a PUT without any body. This is why Requests allows it.
3. `curl -T` does exactly what you just did. The only difference between Requests and curl is in one case: if you do `curl -T <filename> http://host` (that is, with no path), then curl will send a PUT to `/filename`. To do the same thing with Requests, you'd need to do:

    ```python
    url = "http://example.com/"
    with open('default.zip', 'rb') as data:
        requests.put(url + "default.zip", data=data)
    ```

**Comment by gopal9405** [comment]
what should I do for the tar.gz file in a PUT request using pycurl module @Lukasa

**Comment by gopal9405** [comment]
I figure out the solution.
