### ISSUE TITLE
`except` without exception class specified makes IDNA-encoding non-threadsafe.

### ISSUE THREAD

**Issue by Crazy-Owl** [kennethreitz/requests#3843]
Hello,

We have a python program with resident process running in separate thread. We make requests in said thread and when master thread spots a timeout, a custom exception is dispatched to child thread via OS signal. We use Requests `2.12.4`.

However, that exception is caught not by our handler (in child thread main loop), but by `except:` directive in `alabel` function deep in `packages/idna/core.py`: https://github.com/kennethreitz/requests/blob/master/requests/packages/idna/core.py#L264 because that handler is an unconditional "catch-all" `except:` directive. That leads to very cryptic behaviour like child thread not stopping and trying to access urls with unnecessary IDNA-encoding (all our URLs are in plain ascii).

Expected behaviour for that handler is not to catch everything, but to expect a specific exception class(es) and work just with them.

**Comment by Lukasa** [comment]
Yup, that looks wrong, thanks for reporting it! The `idna` code is vendored, without edits, from [this repo](https://github.com/kjd/idna). I recommend you open an issue there, which when fixed will make its way into Requests.

**Comment by Crazy-Owl** [comment]
The changes to `idna` repo landed about two weeks ago: https://github.com/kjd/idna/pull/39

When can we expect the chages to be reflected in `requests`?

**Comment by Lukasa** [comment]
The changes will land when we prepare our next minor release: those releases are when we update our vendored dependencies.
