### ISSUE TITLE
requests messes up a ZIP stream (?)

### ISSUE THREAD

**Issue by ResidentMario** [kennethreitz/requests#3847]
There's an interesting bug that I've run into involving reading [a zipfile](https://data.cityofnewyork.us/dataset/Broadband-Data-Dig-Datasets/ft4n-yqee) off the web.

The details as in the comments to [this answer on StackOverflow](http://stackoverflow.com/a/42016924/1993206):

This fails with a `BadZipFileError`: 

```
z = zipfile.ZipFile(io.BytesIO(requests.get("https://data.cityofnewyork.us/dataset/Broadband-Data-Dig-Datasets/ft4n-yqee").content))
```

But writing `requests.get("https://data.cityofnewyork.us/dataset/Broadband-Data-Dig-Datasets/ft4n-yqee").content` to a file and *then* opening it with `ZipFile` works fine. So this works:

```
with open("temp.zip", "wb") as fp:
    fp.write(requests.get("https://data.cityofnewyork.us/dataset/Broadband-Data-Dig-Datasets/ft4n-yqee").content)

with open("temp.zip", "rb") as fp:
    zipcontent = zipfile.ZipFile(fp)
    
```

This is on Python 3.5.2 and Requests 2.12.4.

**Comment by Lukasa** [comment]
That doesn't work for me at all. =)

An FYI: the response I get from that website is HTML, always. By my reckoning the download link is `https://data.cityofnewyork.us/download/ft4n-yqee/application%2Fzip`, and that link does appear to work correctly in the code sample. =)

**Comment by ResidentMario** [comment]
Yes, my bad for posting the wrong link! What platform are you on?

**Comment by Lukasa** [comment]
Mac. =) Python 3.5.2.
