### ISSUE TITLE
A little suggestion about 'LookupDict' in 'requests/requests/structures.py' 

### ISSUE THREAD

**Issue by jiazhuamh** [kennethreitz/requests#3848]
Dear Sir,
I like your 'requests' Python library very much and I'm reading the source code these days. I found a problem that is tricky. The 'LookupDict' class definition is:
`
```
class LookupDict(dict):

    def __init__(self, name=None):
        self.name = name
        super(LookupDict, self).__init__()
    def __repr__(self):
        return '<lookup \'%s\'>' % (self.name)

    def __getitem__(self, key):
        # We allow fall-through here, so values default to None

        return self.__dict__.get(key, None)

    def get(self, key, default=None):
        return self.__dict__.get(key, default)
```
`

It inherits the 'dict' object but does not use any of the 'dict' methed. It only use the class's \__dict__ and it is ok to replace the 'dict' with 'object'.

**Comment by Lukasa** [comment]
`LookupDict` absolutely includes all of the dict methods. In particular, it allows the use of `__setitem__` and other things from the dict class. It specifically does only one thing, which is override `__getitem__` to allow returning `None`.

So it's not ok to replace the dict with `object` in this case, even though the requests codebase doesn't use that functionality.

Thanks for reporting this issue though, and I hope you keep reading through the codebase!

**Comment by jiazhuamh** [comment]
Thanks a lot for your reply. I'll read the code with your clue.
