### ISSUE TITLE
Missing response headers when malformed header is part of the response

### ISSUE THREAD

**Issue by gboudreau** [kennethreitz/requests#3852]
Using Python 3.5, requests 2.13.0

```
>>> import requests
>>> r = requests.get('https://online.chasecanada.ca/ChaseCanada_Consumer/Login.do')
>>> print(r)
<Response [200]>
>>> print(r.headers)
{'Date': 'Sat, 04 Feb 2017 19:52:14 GMT'}
>>> 
```

I'm pretty sure the problem is caused by an invalid HTTP header returned by the server:

    HTTP/1.1 200 OK
    Date: Sat, 04 Feb 2017 19:16:34 GMT
    My Param: None
    [...]

It directly follows the `Date` response header, which is returned fine, but since no other response headers is returned, I think this broken header is breaking the HTTP response headers parser.

**Comment by gboudreau** [comment]
Hum. Not sure this is a `requests` issue, since the `headers` dict in the `urllib3.response.HTTPResponse` object also only has the `Date` header...
Maybe there is a workaround somehow..?

**Comment by sigmavirus24** [comment]
As I answered on the urllib3 issue you opened, there is no workaround until urllib3 is no longer reliant on `http.client`. Cheers!
