### ISSUE TITLE
Support urllib3 Retries at Individual Request Level

### ISSUE THREAD

**Issue by TimOrme** [kennethreitz/requests#3854]
Right now, requests supports urllib3 retries at the pool level, allowing retries to occur fairly globally. It seems as if urllib3 supports retries at a more granular level as well, for individual requests:

```
>>> r = http.request(
...     'GET',
...     'http://httpbin.org/redirect/3',
...     retries=urllib3.Retries(
...         redirect=2, raise_on_redirect=False))
>>> r.status
302
```

It would be nice if requests had support for this level of granularity, as some of our cases require retries for only specific endpoints on a single API.

Apologies if this is the wrong place for this, wasn't sure where to place feature requests.

Thanks!
Tim

**Comment by Lukasa** [comment]
Thanks for this request!

Unfortunately, we're unlikely to support this: it's fundamentally an additional complexity that we don't think is justified in the API. At this point our top-level API is largely frozen, and we're very unlikely to widen it or add new features.

However, it's worth noting that the Transport Adapter in use for a given request is chosen on a longest-prefix-match on the *entire* URL. That means that you can register different adapters for different paths, as well as different hosts, which should give you the flexibility you need.

I hope that helps!
