### ISSUE TITLE
why I

### ISSUE THREAD

**Issue by xsren** [kennethreitz/requests#3858]
Hi, execuse me to trouble you!
I want to use requests with gevent to make a concurrent spider. The offical docs says  

> If you are concerned about the use of blocking IO, there are lots of projects out there that combine Requests with one of Python's asynchronicity frameworks. Two excellent examples are grequests and requests-futures.

But after read [this question in stackoverflow](http://stackoverflow.com/questions/9501663/how-enable-requests-async-mode), i am confused. Because I run the code in my machine,  but it seems requests does better than urllib(python 2.7.10,gevent 1.1.2,requests 2.11.1).

the code:
```
import sys

import gevent
from gevent import monkey

monkey.patch_all()

import requests
import urllib2

def worker(url, use_urllib2=False):
    if use_urllib2:
        content = urllib2.urlopen(url).read().lower()
    else:
        content = requests.get(url).content.lower()
    title = content.split('<title>')[1].split('</title>')[0].strip()

urls = ['http://www.baidu.com']*15

def by_requests():
    jobs = [gevent.spawn(worker, url) for url in urls]
    gevent.joinall(jobs)

def by_urllib2():
    jobs = [gevent.spawn(worker, url, True) for url in urls]
    gevent.joinall(jobs)

if __name__=='__main__':
    from timeit import Timer
    t = Timer(stmt="by_requests()", setup="from __main__ import by_requests")  
    print 'by requests: %s seconds'%t.timeit(number=3)
    t = Timer(stmt="by_urllib2()", setup="from __main__ import by_urllib2")  
    print 'by urllib2: %s seconds'%t.timeit(number=3)
    sys.exit(0)
```

the result:
```
➜  test_requests python test04.py
by requests: 0.178946971893 seconds
by urllib2: 1.94786500931 seconds
➜  test_requests python test04.py
by requests: 0.233242034912 seconds
by urllib2: 1.55849504471 seconds
➜  test_requests python test04.py
by requests: 0.52639913559 seconds
by urllib2: 3.95958900452 seconds
➜  test_requests python test04.py
by requests: 0.56934094429 seconds
by urllib2: 4.00116705894 seconds
```

My question:
1. The result seems that now gevent + requests is asynchronous. But many people in the website say I should use grequests. Is that right?
2. Why the result I use requests same to I use grequests?

Hope you can answer my question . Thanks very much.

**Comment by Lukasa** [comment]
Requests can work with gevent directly without any trouble: this is the nature of gevent. grequests provides some specific additional utilities for managing Requests with gevent. It's a nice addition, but not required.

**Comment by xsren** [comment]
OK！Thank you very much！
