### ISSUE TITLE
File names stripped of leading dots

### ISSUE THREAD

**Issue by p3lim** [kennethreitz/requests#3860]
Currently using the following to upload a file to a webserver:
```
files = {'files': ('.png', open(file_path, 'rb'))}
res = requests.post(url, files=files)
```
The reason I rename the file to just ".png" is because with an empty base name the server will randomly give the file a name.
However, and I'm not sure if requests is the one to blame here, the file ends up being uploaded with the name "png" instead, as if the leading "." was stripped from the name.

Is this something requests is intentionally doing or should I look elsewhere for the cause?

**Comment by Lukasa** [comment]
This is not something requests is doing. A quick Wireshark dump of your sample code against `http://httpbin.org/post` shows that the request looks like this:

```
POST /post HTTP/1.1
Host: httpbin.org
Connection: keep-alive
Accept-Encoding: gzip, deflate
Accept: */*
User-Agent: python-requests/2.13.0
Content-Length: 655
Content-Type: multipart/form-data; boundary=746c7fc2a98549969068cf0f6860f3d7

--746c7fc2a98549969068cf0f6860f3d7
Content-Disposition: form-data; name="files"; filename=".png"
<...file data ...>
```

Note that the filename still has the leading dot. =) So this isn't Requests doing something, it has to be elsewhere.

**Comment by p3lim** [comment]
Alright, thanks for checking 👍
