### ISSUE TITLE
Uploading large video files

### ISSUE THREAD

**Issue by dvigneshwer** [kennethreitz/requests#3870]
Hi,

The code snippet below works for uploading a small video file(15MB) to my storage service.

```
url = self.swift_public_url+'/'+self.swift_container+'/'+self.video_name			 
files = {'file': open(self.local_video_loc, 'rb')}
headers = {
	'x-auth-token': self.swift_auth_token,
         'content-type': "application/x-www-form-urlencoded",
}
response = requests.request("PUT",url,files=files,headers=headers)
```

The code crashes my computer(becomes unresponsive) when I am trying to upload a video of say 2+ GB of size.

**_How to perform the following:_**
* Chunk the data to smaller units and upload to the service
* Is it possible to parallel run  

**Attempts:**
* Opened the video file and started reading it in chunks
* Created a generator using the yield keyword
* read_as_gen should send me each chunk one by one 
~~~~
url = self.swift_public_url+'/'+self.swift_container+'/'+self.video_name
				
def read_as_gen(filename, chunksize=-1):
	  with open(filename, mode='rb') as f:
	         while True:
			  chunk = f.read(chunksize)
			  if len(chunk) > 0:
			            yield chunk
			   else:
			             raise StopIteration

files = {'file': read_as_gen(self.local_video_loc, 64*1024)}

# files = {'file': open(self.local_video_loc, 'rb')}
headers = {
	          'x-auth-token': self.swift_auth_token,
	          'content-type': "application/x-www-form-urlencoded",
		}
response = requests.request("PUT",url,files=files,headers=headers)
~~~~

Above attempt did not work for me, only a 70 bytes video file was created in my storage server.  

~~~~
hdfs_client.upload('/'+self.hfds_video_loc+'/'+self.video_name,self.local_video_loc,overwrite=False,n_threads=1, temp_dir=None, chunk_size=65536, progress=None, cleanup=True)
~~~~
Above functionality can be implemented with the hdfs client.
Ref: https://hdfscli.readthedocs.io/en/latest/api.html#hdfs.client.Client.upload

I am basically trying to create the above client using the request module for another storage service.

**Comment by Lukasa** [comment]
By default Requests will read all the files in `files` into memory. Naturally, for multi-gigabyte files this can go all kinds of wrong. You will likely find this works better by using the [Requests' toolbelt's streaming multipart uploader](https://toolbelt.readthedocs.io/en/latest/user.html#multipart-form-data-encoder).
