### ISSUE TITLE
Suggestion: add a new field `method` to `Response` class

### ISSUE THREAD

**Issue by nodakai** [kennethreitz/requests#3881]
If it make sense to include the [`url`][url] field to the `Response` class in order to be human friendly when automatic redirection kicks in, shouldn't there be a `method` field as well, for the case when a `POST` results in 302 with which Requests respond with `GET` ?

Background: I was investigating an issue with a Consul REST API client which was based on Requests, and found out it was related to #2590 . While it's great the v3.0 will be shipped with the fix #3757, my observation was it was tricky to figure out what was going on under the hood. I could see my `PUT` was redirected from `/v1/kv/a//b` to `/v1/kv/a/b` by 301 but at first I had no idea the method was also changed to `GET`, striping the content data away. I gave a try on `curl -v` and hurrah, it displayed "Switch from POST to GET".

Moreover, if my understanding is correct (web isn't my field of specialty,) in a hypothetical situation when Requests is following a looong chain of mixture of 301 and 303, it would be helpful to be able to identify at which point the method changed from, say, `PUT` to `GET`.

Anyways the bottom line is, the `url` isn't complete without an accompanying `method` field, I think.

[url]: http://docs.python-requests.org/en/latest/api/#requests.Response.url

**Comment by sigmavirus24** [comment]
@nodakai that all is available in the response history already. I don't understand how the final response having a method would help you identify that. `response.request.method` already exists and (I thought) is documented.

**Comment by sigmavirus24** [comment]
Also, hi! Welcome! Thanks for opening this and starting the discussion for it. I'm a bit distracted so my responses will be a bit.. short. :)

**Comment by Lukasa** [comment]
Thanks for this request!

So I agree with @sigmavirus24. While the `response.url` field is a handy convenience, in general we make sure that the request that triggered a given response is always available at `response.request`, and can be introspected. 

If you didn't find that obvious, I'd be delighted to merge a pull request with clarifying documentation.
