### ISSUE TITLE
HTTPS proxy with requests

### ISSUE THREAD

**Issue by pn1984** [kennethreitz/requests#3882]
A small (but expanding) set of HTTP clients now offer the ability to connect to proxies over TLS. 'curl' recently added this feature in v7.52.0 (More info. can be found at https://daniel.haxx.se/blog/2016/11/26/https-proxy-with-curl/). Please consider adding support for this feature to 'requests'.

**Comment by Lukasa** [comment]
Hi there, thanks for this request!

Adding support for this feature requires a pretty substantial internal changes to the code logic of our dependencies. This work is ongoing, and when it's done it can be discussed, but for now it's not something we can promise to put on any kind of roadmap.

Sorry! :pray:
