### ISSUE TITLE
Documentation issue: requests.request behavior unclear when 'data' parameter is dictionary

### ISSUE THREAD

**Issue by nmusolino** [kennethreitz/requests#3894]
The [documentation for 'requests.request' ](http://docs.python-requests.org/en/master/api/#requests.request) lists a parameter 'data':

> data -- (optional) Dictionary, bytes, or file-like object to send in the body of the Request.

It is unclear what the behavior will be when a dictionary is passed.  Since an HTTP request's body is a series of bytes, it is unclear how the library will serialize a dictionary to a series of bytes.  For example, will it write the dictionary as JSON, or as XML?

For the other parameter types (bytes or file-like object) I think it is fairly obvious what the behavior will be.

Suggested resolution:  the documentation should add a sentence like:  "Dictionary objects will be serialized as JSON using the 'json' module", along with any restrictions on the content of the dictionary.

I encountered this when reading the [first section](http://docs.python-requests.org/en/master/user/quickstart/#make-a-request) of the Quickstart guide.

**Comment by Lukasa** [comment]
> "Dictionary objects will be serialized as JSON using the 'json' module", along with any restrictions on the content of the dictionary.

Heh, the fact that you wrote this suggests that it might be worthwhile, given that that's exactly *not* what we do. Dictionaries are encoded as application/x-www-form-urlencoded data.

So, in general I'd say that our behaviour is in-line with what most users who have used other libraries would expect, but it also can't hurt to elaborate a bit. This is a good PR for a first-time contributor to pick up, so I'm going to attach some labels and let someone come along to fix it.

**Comment by JordanP** [comment]
I also expected it to be urlencoded. But I had to think 15sec to conclude that urlencoding was what made the most of sense. So +1 for a PR to clarify the doc.

**Comment by ghost** [comment]
In http://docs.python-requests.org/en/master/api/#lower-level-classes, the  form-encoding  is mentioned:

> data -- the body to attach to the request. If a dictionary is provided, form-encoding will take place.
