### ISSUE TITLE
PUT'ing files to Azure blob storage... keeps the whole "body?"

### ISSUE THREAD

**Issue by ckcollab** [kennethreitz/requests#3896]
Heyo! Thanks so much for requests, I use it all the time and appreciate the effort ya'll put into this!

Anyway, I am having a bit of trouble PUT'ing some files to Azure, for some reason Azure receives the files as:

```
--d21a382fd3cb49f085c89cc5c15e180e
Content-Disposition: form-data; name="file"; filename="stdout.txt"
Content-Type: text/plain

<file data>

--d21a382fd3cb49f085c89cc5c15e180e--
```

Instead of just

```
<file data>
```

For the life of me, I can't figure out *why* it's keeping the headers there and such...

```python
def put_blob(url, file_path):
    requests.put(
        url,
        files={'file': open(file_path, 'rb')},
        headers={
            'x-ms-blob-type': 'BlockBlob',
        }
    )
```

**Comment by Lukasa** [comment]
Thanks for this report!

The `files` parameter uploads the data using `multipart/form-encoded` as the data structure. This is the most common interaction with HTML forms, and is therefore how that works.

To upload just the raw file data, pass the file object to the `data` parameter:

```python
    requests.put(
        url,
        data=open(file_path, 'rb'),
        headers={
            'x-ms-blob-type': 'BlockBlob',
        }
    )
```

**Comment by ckcollab** [comment]
You. Are. So. Handsome. Thanks a ton!! That was about an hour spent trying to fix that, agh!

**Comment by adambernier** [comment]
This really helped me, too. Thanks a ton, @Lukasa
