### ISSUE TITLE
Propose additional documentation for post data

### ISSUE THREAD

**Issue by garywu** [kennethreitz/requests#3902]
## Problem statement

Current documentation only specifies the most common case of post data - a dictionary. The code in fact supports other forms of post data which is not documented. Propose to enhance the quick start section that deals with post data to include examples of other uses.

Section of text in the current documentation: [More complicated POST requests](http://docs.python-requests.org/en/master/user/quickstart/#more-complicated-post-requests)

## Questions in the wild indicating the need for more documentation in this regard
On stockoverflow:

* [how to post multiple value with same key in python requests?](http://stackoverflow.com/questions/23384230/how-to-post-multiple-value-with-same-key-in-python-requests)
* [handling duplicate keys in HTTP post in order to specify multiple values](
http://stackoverflow.com/questions/27116424/handling-duplicate-keys-in-http-post-in-order-to-specify-multiple-values)
* [How to send multiple of the same key/parameter via POST?](
http://stackoverflow.com/questions/19004403/how-to-send-multiple-of-the-same-key-parameter-via-post)
* [How to send an array using requests.post (Python)? “Value Error: Too many values to unpack”](
http://stackoverflow.com/questions/31168819/how-to-send-an-array-using-requests-post-python-value-error-too-many-values/35534695)

And there is this issue #1641: Cannot send Single Key, Multiple value data in post because of the use of pythons dict.  

## Proposed modification:

```rst
You can also pass a list of tuples to the ``data`` argument. This is particularly
useful when the form has multiple elements that use the same key::

    >>> payload = (('key1', 'value1'), ('key1', 'value2'))
    >>> r = requests.post('http://httpbin.org/post', data=payload)
    >>> print(r.text)
    {
      ...
      "form": {
        "key1": [
          "value1",
          "value2"
        ]
      },
      ...
    }

Value of each payload element can be a scalar or an iterable::

    >>> payload = (('key1', ('value1', 1, (1, 2))), {'key2', ('value2', 2)})
    >>> r = requests.post('http://httpbin.org/post', data=payload)
    >>> print(r.text)
    {
      ...
      "form": {
        "key1": [
          "value1",
          "1",
          "1",
          "2"
        ],
        "key2": [
          "value2",
          "2"
        ]
      },
      ...
    }

```

**Comment by ghost** [comment]
I am not sure if the use of httpbin is very helpful here. A reader who is not familiar with this service will wonder how the JSON response is produced. It would be more helpful to show the acual *request* body, not how some service interprets it.

**Comment by garywu** [comment]
Thanks for the comment, I'm simply following the existing documentation: [More complicated POST requests](http://docs.python-requests.org/en/master/user/quickstart/#more-complicated-post-requests). My proposed change is right after the first code block.

**Comment by kennethreitz** [comment]
this sounds good to me!

**Comment by kennethreitz** [comment]
go for it @garywu!
