### ISSUE TITLE
requests.get on image url returns 405 (the image url works in browser)

### ISSUE THREAD

**Issue by fabiocaccamo** [kennethreitz/requests#3907]
Unfortunately I cannot provide the image url, maybe this can help: https://github.com/thumbor/thumbor/pull/342/files

**Comment by Lukasa** [comment]
405 means method unsupported. Are you sure you're doing a GET?

**Comment by fabiocaccamo** [comment]
sure :)

**Comment by Lukasa** [comment]
Well in that case, the error is almost certainly not with Requests, and unless you can get us more detail we can't really help you. Sorry! 😟
