### ISSUE TITLE
Streaming uploads for files

### ISSUE THREAD

**Issue by sorenh** [kennethreitz/requests#3925]
It would be really nice if there was a way to do a multipart encoded file uploads without having to load all the files into memory before sending the request so that it could be streamed.

I'm pulling a large file from one place (using `requests.get(stream=True)`) and have to send it somewhere else as part of a multpart post, but I'm running out of memory.

**Comment by Lukasa** [comment]
Thanks for this! Handily, there is exactly such a thing: check out the requests-toolbelt's [`StreamingMultipartEncoder`](https://toolbelt.readthedocs.io/en/latest/uploading-data.html#streaming-multipart-data-encoder).
