### ISSUE TITLE
SSLError raised when path to CA_BUNDLE is not valid could be more meaningful

### ISSUE THREAD

**Issue by bagerard** [kennethreitz/requests#3926]
Hi there,
First of all thanks for the requests library, it's just awesome!
In one of my project I was pulling 'verify' from a config file and passing it along every requests as an argument. Instead of receiving a boolean, it turned out that I was actually passing verify='true' to the requests methods, which makes requests think that I was providing a path to a ca bundle. 
Although I was obviously misusing the api, it took me some time to debug it and I believe that the error message could have been more meaningful.

In fact the following:
```
requests.get('https://github.com/', verify='true')
```
raises
```
/.../requests/requests/adapters.py in send(self, request, stream, timeout, verify, cert, proxies)
    495         except (_SSLError, _HTTPError) as e:
    496             if isinstance(e, _SSLError):
--> 497                 raise SSLError(e, request=request)
    498             elif isinstance(e, ReadTimeoutError):
    499                 raise ReadTimeout(e, request=request)

SSLError: [Errno 2] No such file or directory
```
I'll do a PR and make it raise an IOError (with the path being printed) in case the `verify` param does not point to a valid file/dir. As minor as it is, I hope you'll find it valuable.

**Comment by Lukasa** [comment]
So, before you leap into this (which is a good idea), be aware that you need to be able to distinguish this case from when either of the paths given to the `cert` parameter are bad.

**Comment by bagerard** [comment]
Thanks for the quick feedback, I'll take that into account
