### ISSUE TITLE
"stati" should be "statuses"

### ISSUE THREAD

**Issue by marthjod** [kennethreitz/requests#3930]
"stati" is not a word. Plural of "status" is "statuses" (`REDIRECT_STATI` etc.).

**Comment by Lukasa** [comment]
It's a purely internal name that is not intended to be used by others, so what it's called really doesn't matter. It could be called `MY_FAVOURITE_NUMBERS` and that would be fine. However, if it helps, I'll let you know that the person who wrote the original code knew that "stati" is not a word: it was intended as a joke. 😉
