### ISSUE TITLE
ConnectionError not handled by requests

### ISSUE THREAD

**Issue by fabiocaccamo** [kennethreitz/requests#3932]
**ConnectionError not handled by requests
('Connection aborted.', gaierror(-2, 'Name or service not known'))**

This happened when I tried to load an image from an old tumblr url:

```
url = 'http://41.media.tumblr.com/facde6697dff1c78fcfadbc653a8a295/tumblr_mlc3qpepqL1son6j8o1_1280.jpg'
r = requests.get(url, stream = True)

if r.status_code != requests.codes.ok:
    print('not an exception')
```

I expected that r.status_code == requests.codes.ok returned False instead of throwing the exception.

**Comment by Lukasa** [comment]
Why? There is no response to get there. It doesn't 404, it's returning NXDOMAIN on the DNS lookup. This is entirely expected behaviour.
