### ISSUE TITLE
verify=/path/to/root/certs ignored

### ISSUE THREAD

**Issue by mahescho** [kennethreitz/requests#3934]
I use:
    requests.get(URL,verify=/path/to/root/certs
in /path/to/root/certs are some certificates and hashes:
    lrwxrwxrwx 1 root root   10 Mär 22 14:43 3104f96d.0 -> cert-2.pem
    lrwxrwxrwx 1 root root   10 Mär 22 14:43 33815e15.0 -> cert-1.pem
    lrwxrwxrwx 1 root root   10 Mär 22 14:43 738ed572.0 -> cert-2.pem
    lrwxrwxrwx 1 root root   10 Mär 22 14:43 ae8153b9.0 -> cert-1.pem
    -rw-r--r-- 1 root root 2760 Mär 22 14:43 cert-1.pem
    -rw-r--r-- 1 root root 2151 Mär 22 14:43 cert-2.pem
Certificate verification fails with:
    ERROR [Errno 336265218] _ssl.c:351: error:140B0002:SSL 
    routines:SSL_CTX_use_PrivateKey_file:system lib
When I install the CA certs in the system verification works when "requests" falls back to verify. I try this on Debian 8 with "requests" 2.4.3-6.

**Comment by Lukasa** [comment]
Requests 2.4 does not support openssl certificate directories: only single files. You'd need to cat all those files into a single file and use that. That limitation was lifted in 2.9. Please upgrade Requests. :smile:

**Comment by mahescho** [comment]
Thanks, pip install requests --upgrade solved the Issue.
