### ISSUE TITLE
Prevent unicode escape in json

### ISSUE THREAD

**Issue by hrchu** [kennethreitz/requests#3936]
``` requests.post(url, json=payload)``` always transforms non-ascii chars in the forms of unicode escape , i.e., \uXXXX since the parameter ensure_ascii in```json.dump() ```  is True in default. It is inconvenient for global/non-ascii users, since the receiver have to de-escape it again. It will be better if requests can optionally prevent unicode escape in json. Any ideas?

**Comment by Lukasa** [comment]
JSON with escaped characters is supposed to be identical to JSON without escaped characters. There is no *general* reason to provide an escape hatch to avoid encoding, as it will only bust services that are not properly handling the JSON.

That said, the solution to fixing this is very easy:

```python
import requests
import json

r = requests.post(url, data=json.dumps(your_json, ensure_ascii=False), headers={'Content-Type': 'application/json'})
```
