### ISSUE TITLE
requests takes a half-second to import

### ISSUE THREAD

**Issue by ktdreyer** [kennethreitz/requests#3946]
I noticed it was taking a half-second just to run `--help` for my app, and narrowed it down to requests 2.12.0 taking a long time to load.

I'm on Python 2.7.13, Fedora 25.

Here is the 2.12 series:
```
$ pip install requests==2.12.0
$ time python -c 'import requests'
real	0m0.487s
user	0m0.445s
sys	0m0.040s
$ strace -e open python -c 'import requests' 2>&1 | wc -l
6836
```
0.487 seconds to import, almost 7000 open() calls.

Compared to 2.11.1:
```
$ pip install requests==2.11.1
$ time python -c 'import requests'
real	0m0.085s
user	0m0.066s
sys	0m0.019s
$ strace -e open python -c 'import requests' 2>&1 | wc -l
2321
```
under a tenth of a second to import, and 66% fewer open() calls.

**Comment by Lukasa** [comment]
Can you show us the output of `pip freeze`? Does this happen when the *only* change you make is what Requests version is installed?

**Comment by Lukasa** [comment]
Oh, never mind, I know what this is: this is due to the idna library we vendored in that release. Does this slowness apply up to the current 2.13 release?

**Comment by ktdreyer** [comment]
Thanks for the pointer at 2.13. I tried that one and the same problem occurred. Then I realized that it only happens when I use the `--system-site-packages` argument to `virtualenv`. I'll need to do more digging to find out what's going on here.

**Comment by Lukasa** [comment]
Oh that's very interesting. It's possible that the delay you're seeing is actually to do with PyOpenSSL, which has in some older versions had very long import times.
