### ISSUE TITLE
HTTPS isn't working if proxy is down

### ISSUE THREAD

**Issue by JamesJGoodwin** [kennethreitz/requests#3960]
I'm using requests with proxies and when proxy-server is down for some reason, requests make request without proxy(using the origin IP). Also, this issue appears when making https request with proxy which not support https. Could you please implement functionality, which could allow me to make proxy-only requests?

**Comment by Lukasa** [comment]
Requests should not be making requests without the proxy when the proxy is not working. Can you show us the code you're using please?

**Comment by abriginets** [comment]
I've figured it out, i guess. This happened if making request in `while True` loop.
