### ISSUE TITLE
waiting for a very long time for the reponse

### ISSUE THREAD

**Issue by etiaxie** [kennethreitz/requests#3967]
python version:2.7
requests version:2.11.1

when the response expected to be redirect(301)，after I send out the request.get message, it will take a long time to get response.
however in the wireshark can see the response is immediately returned.it seems like somewhere in code after get the response takes the time out

**Comment by Lukasa** [comment]
Is the response body complete immediately? Can you provide a URL to reproduce this error?

**Comment by sigmavirus24** [comment]
This has been stale for nearly a month. We can reopen this if we get more information and can determine that this is actually a bug in Request.
