### ISSUE TITLE
URLs with Square Brackets []

### ISSUE THREAD

**Issue by apollodatasolutions** [kennethreitz/requests#3968]
We were using Requests with FileStack without issues until we ran into this URL format:

**https://process.filestackapi.com/store=l:S3,p:"/watermarked/"/watermark=f:wUaFDoPfRAiT50LQZWs9,p:[bottom,right],s:63/p2aaZ8pzS8md1vLzY7V2**

the **p:[bottom,right]** part seems to be causing issues (the request doesn't properly make it to their end).  FileStack's documentation suggests using curl with the -g option:

> -g, --globoff
> 
> This option switches off the "URL globbing parser". When you set this option, you can specify URLs that contain the letters {}[] without having them being interpreted by curl itself. Note that these letters are not normal legal URL contents but they should be encoded according to the URI standard.
> https://curl.haxx.se/docs/manpage.html

Is there a similar option for Requests?  I saw that it's not a valid URI, so I am also talking to FileStack to be able to resolve this but I am wondering if there is a temporary solution while I wait for them.

Looking at the response URL, it seems the quotes are encoded but not the brackets?

**https://process.filestackapi.com/store=l:S3,p:%22/watermarked/%22/watermark=f:9shDBUAMSMm58i5r3Ujr,p:[bottom,right],s:17/uj16GiSQa2bzDCVY34vw**

but the same happens in the p:center case which works just fine.

**Comment by Lukasa** [comment]
Are you sure you need it? Requests won't treat them as globs, so that's not a concern. We will encode them, but the snippet of documentation you provided suggested that that is fine. Have you actually tried the request at all?

**Comment by apollodatasolutions** [comment]
Yes, I tried it without the square brackets, no luck.  And yes, I tried the request.  I get a 400 error back from FileStack only when the brackets are present.

The last URL I posted above is from the response.url property after the request is made.  Looks like the quotes are encoded but the brackets are not.  I'll see if FileStack has any news on this.  Not sure if this is a requests or FileStack issue at this point, will update when I know more.  Might be good leaving this issue just in case anyone runs into a similar problem.

**Comment by apollodatasolutions** [comment]
Looks like the solution was simple, just manually encode the bracket characters like this:

**(https://process.filestackapi.com/store=l:S3,p:%22/watermarked/%22/watermark=f:wUaFDoPfRAiT60LQZWs9,p:%5Bbottom,right%5D,s:17/nPh71zWTTCmQXD9ho2ZF)**
