### ISSUE TITLE
requests.exceptions.ConnectionError

### ISSUE THREAD

**Issue by srikanth148** [kennethreitz/requests#3970]
`response = requests.post(url, data=payload ,verify=False, timeout=(3.05, 6.05))`

works fine in python shell but not in python manage.py shell (django)
I am getting below error 
'requests.exceptions.ConnectionError: HTTPConnectionPool(host='ggk-wrl-win1', port=9090): Max retries exceeded with url: /home/trusted/token (Caused by NewConnectionError('<requests.packages.urllib3.connec)'

**Comment by Lukasa** [comment]
You have truncated the exception message so I can't see what it is, do you mind providing the full exception string?

**Comment by srikanth-chandaluri** [comment]
![screenshot from 2017-04-18 17 16 40](https://cloud.githubusercontent.com/assets/26059420/25129293/fcf012f2-245a-11e7-9918-2411e7178104.png)
![image](https://cloud.githubusercontent.com/assets/26059420/25129307/0e63289e-245b-11e7-9e28-43ae74e8cccf.png)

**Comment by Lukasa** [comment]
You're encountering a DNS error for the host name `ggk-wrl-win1`. Can you confirm your network is set up correctly?

**Comment by srikanth-chandaluri** [comment]
yes, setup is good

**Comment by Lukasa** [comment]
From inside `manage.py`, can you run:

```python
import socket
s = socket.create_connection(('ggk-wrl-win1', 80))
```

and tell me what happens please?

**Comment by srikanth-chandaluri** [comment]
![image](https://cloud.githubusercontent.com/assets/26059420/25132475/59037a96-2467-11e7-84ea-62b1e70b010f.png)

**Comment by Lukasa** [comment]
So, as you can see, this is a problem with your environment and not requests. Inside your environment that host name is not resolvable. We cannot help you work out why that is.

**Comment by srikanth-chandaluri** [comment]
but, its works in python shell
![image](https://cloud.githubusercontent.com/assets/26059420/25133783/5b4bb3f0-246b-11e7-8de6-d4273d70ffa6.png)

**Comment by Lukasa** [comment]
Yes, which strongly suggests that your specific environment is at fault. You need to diagnose why the manage.py shell won't make outbound network connections.

**Comment by srikanth-chandaluri** [comment]
I think the issue with my docker setup, thank you

**Comment by kbhingude** [comment]
@srikanth-chandaluri  are you find solution ?

**Comment by kbhingude** [comment]
> I think the issue with my docker setup, thank you

are you find solution
