### ISSUE TITLE
Custom Handler

### ISSUE THREAD

**Issue by achapkowski** [kennethreitz/requests#3972]
How do you extend requests to use a custom handler for a security scheme?
I'm looking for documentation on how to extend the API basically.
Thanks

**Comment by Lukasa** [comment]
What specific kind of API extension do you have in mind? Generally speaking you'd do it by subclassing the Session object.

**Comment by achapkowski** [comment]
I have a site that is token based security, and I want to create a handler to work with this.  So I know the username, password, expiration, and token url, and I want the authentication handler to handle the creation and update of the token based on a given time frame.

**Comment by Lukasa** [comment]
It's token based, but not oauth? You may find Requests-Oauthlib's design instructive of how to handle a complex token based auth system.

**Comment by achapkowski** [comment]
Thanks,  I think I figured it out.  So you inherit from AuthBase, then you write your logic in ```__call__```

My issue now is how do I insert the token parameter into a multi-part request.  For regular POST and GET calls it's easy.  Just append the token to the body or parameters off of the object ```r```.

If I insert the form-data into the r.body of the form request, I a message from server saying it's not valid:

Real quick and dirty method:

```
token = "abc123
item = '--%s\r\nContent-Disposition: form-data; name="token"\r\n\r\n%s\r\n' % \
                    (r.headers['Content-type'].split(';')[1].strip().split('=')[1], token)
r.body = str.encode(item) + r.body
```

It looks right from Fiddler, but apparently it isn't

**Comment by Lukasa** [comment]
There is a body terminating boundary (`--uuid--`) that comes last, after which data will usually be ignored. You'd also need to update the content-length, which you may not have done.

Essentially, you'll want to insert your data *before* the terminating boundary, not after.

**Comment by achapkowski** [comment]
ahh thanks for that! that fixed it. 

Thank you for all the help
