### ISSUE TITLE
ETA on 2.14? + docs request on release schedule

### ISSUE THREAD

**Issue by jvanasco** [kennethreitz/requests#3973]
1. Is there an ETA on 2.14?  I couldn't find any milestone info and there seems to be a few dozen PRs merged since January.

2. There should probably be a line about the release schedule in the contributors guide or elsewhere, so I people like me don't ask annoying questions.

I don't mean to prod for a release, but just get a general idea of when one will likely be made.  I've got a couple of tiny open source projects that rely on a handful of the forthcoming changes and just want to know when I should schedule an afternoon for packaging and updates.

**Comment by Lukasa** [comment]
Heh, there is no schedule. The schedule is "whenever the core devs feel that a release is warranted". In this case, I have an OmniFocus task for this but am currently on holiday, so would expect that we'll release next week. 

Generally speaking I'd say that a schedule doesn't work for a project like this one: we're sufficiently small in scope that it's pretty easy to coordinate the work. However, if you disagree I'd be interested to hear it.

**Comment by jvanasco** [comment]
Well, I'm not talking about an "official" release schedule... just that a lot of projects tend to have something general like "we aim for a release every X months or Y pull requests/core changes".

I had actually looked through the history to try and predict when a release happens, and it tends to be around 3 months (sometimes 2, sometimes 4).  Looking at the commit history though, it seems like there were a lot more PRs merged than usual since 2.13.0... so I expected 2.14 to be on the earlier side.  

2.4  - 2014/08/29
2.5 - 2014/12/01
2.6 - 2015/03/14
2.7 - 2015/05/03
2.8 - 2015/10/08
2.9 - 2015/12/15
2.10 - 2016/04/29
2.11 - 2016/08/06
2.12 - 2016/11/15
2.12 - 2017/01/24

**Comment by Lukasa** [comment]
Heh, frankly it's looking like another 3 month period basically on the nose. 

I have no issue with people doing averages of our release cycle, but I'm nervous about providing that analysis ourselves. It changes the questions from "when is the next release?" to "why is there no release yet?", which isn't really a net improvement.

**Comment by kennethreitz** [comment]
We have no release cadence other than coincidentally.
