### ISSUE TITLE
'headers' field does not allow multiple headers with the same name

### ISSUE THREAD

**Issue by ugultopu** [kennethreitz/requests#3974]
A response returns multiple `Set-Cookie` headers. When I wanted to see these using `response.headers`, only a single `Set-Cookie` header is shown. I have expected all `Set-Cookie` headers to be shown.

Is it intentional to show only one header key-value pair per header key?

**Comment by Lukasa** [comment]
Requests does show multiples, but it joins them into a single header field. This allows users to get a slightly more intuitive behaviour than returning lists, though it does reduce fidelity slightly.
