### ISSUE TITLE
Don't use `urllib.proxy_bypass` on Windows

### ISSUE THREAD

**Issue by schlamar** [kennethreitz/requests#3976]
The `urllib.proxy_bypass` implementation on Windows is using forward and reverse DNS requests. This can result in major performance issues (I guess this depends on the DNS server, right now I have seen delays up to 15 seconds!). Additionally, this behavior is contrary to all major browser implementations.

This could even be a security issue as people might rely on the proxy as a privacy feature and in this case the client shouldn't do any DNS requests as this could leak private information.

I would recommend using a custom implementation which isn't doing any DNS request.

References:

* https://github.com/kennethreitz/requests/issues/2988
* http://bugs.python.org/issue29533

If you are in favor of this proposal I might be able to do a PR.

**Comment by Lukasa** [comment]
In principle we are not attached to the specific implementation of `proxy_bypass`, only the net result. Any change away would be required to reproduce all relevant functionality and to provide complete test coverage. If you're open to doing that work we'll happily consider the PR.

**Comment by schlamar** [comment]
Basically, this would be the copy/pasted Windows versions of [ `urllib.proxy_bypass`](https://github.com/python/cpython/blob/98b1c82/Lib/urllib.py#L1633) and [`urllib.proxy_bypass_registry`](https://github.com/python/cpython/blob/98b1c82/Lib/urllib.py#L1581), the latter without the DNS lookups.

Not quite sure how to test that in a sensible way. Maybe mocking/monkeypatching registry access (`_winreg`)?

**Comment by schlamar** [comment]
Mainly note for myself: `urllib.proxy_bypass_registry` with host `172.16.1.12` and proxyOverride `172.16.1.1` evaluates to True. Not sure if this is a bug or implementation detail (matching start of string).

**Comment by schlamar** [comment]
proxyOverride `192.168.` (without star) and host `192.168.0.1` also evaluates to True. 

In the config dialog it says "do not use proxy server for addresses **beginning with**" (screenshot [here](https://blogs.msdn.microsoft.com/askie/2015/10/12/how-to-configure-proxy-settings-for-ie10-and-ie11-as-iem-is-not-available/)). So I assume the urllib matching behavior is correct and matches the Window behavior.

**Comment by schlamar** [comment]
#3979
