### ISSUE TITLE
Upload data progress

### ISSUE THREAD

**Issue by gladiacxtylish** [kennethreitz/requests#3989]
I saw examples of using `iter_content` to get progress of the download, but I do not see a corresponding API for upload a blob. I am requesting such feature. Thanks.

**Comment by Lukasa** [comment]
If you are uploading a blob of data you can provide either an iterable object (which will be uploaded using chunked encoding) or a file-like object that provides a `read` method (which, if we can determine a length, will be streamed to the server). In either case, we have to call into your code to retrieve the next chunk of data, so you will get notified whenever we've sent the last chunk you gave us. That's the expected way to be notified about uploading data.

Is that sufficient for your needs?

**Comment by gladiacxtylish** [comment]
I am not certain if our server supports chunked encoding, we are not using one of the popular web servers out there. Is there a sample code on this, I could try it out?

**Comment by sigmavirus24** [comment]
@gladiacxtylish you can look at an example in [requests-toolbelt](https://github.com/sigmavirus24/requests-toolbelt/blob/3ac79c3ca358a7d3152a3d06a4f33306f9b6772f/requests_toolbelt/multipart/encoder.py#L316) for this. Cheers!
