### ISSUE TITLE
Deadlocks when retry with pool_block=True

### ISSUE THREAD

**Issue by mattbillenstein** [kennethreitz/requests#3993]
I created a repo with a testcase for this issue:

https://github.com/mattbillenstein/requests-retry-pool-hang

I can repro using gevent and threads.  It seems there are a few other issues exhibiting deadlocks, so hopefully this testcase is helpful in getting to the bottom of this.

**Comment by mattbillenstein** [comment]
Ok, so I have something that fixes this for me -- retries are implemented using recursion and before recursing, the connection isn't released back to the pool, so for every retry, we would grab another connection while still holding onto the old one for no real reason afaict.  See:

https://github.com/mattbillenstein/requests/commit/524b43154553489bf60216acb9030ce5b36f7215

**Comment by Lukasa** [comment]
Connections should be released here: https://github.com/mattbillenstein/requests/commit/524b43154553489bf60216acb9030ce5b36f7215#diff-56e4c9a9f8955a91d87d7da5335a7dddR668.

**Comment by mattbillenstein** [comment]
Yeah, I traced through that, the connection is not put back to the pool there.  If I add a print in there:

        finally:
            if not clean_exit:
                # We hit some kind of exception, handled or otherwise. We need
                # to throw the connection away unless explicitly told not to.
                # Close the connection, set the variable to None, and make sure
                # we put the None back in the pool to avoid leaking it.
                conn = conn and conn.close()
                release_this_conn = True

            print clean_exit, release_this_conn
            if release_this_conn:
                # Put the connection back to be reused. If the connection is
                # expired then it will be None, which will get replaced with a
                # fresh connection during _get_conn.
                self._put_conn(conn)

And reduce my test to just one one request:

    $ time ./retry_pool_hang_gevent.py  --retry
    True False
    True False
    True False
    True False
    True False
    .
    real    0m0.898s
    user    0m0.206s
    sys     0m0.041s

**Comment by Lukasa** [comment]
So it seems like Requests is not asking for that connection to be returned to the pool. This feels like a urllib3 issue; it seems like urllib3 leaks connections with `preload_content=False` and retries set. Mind opening an issue there?
