### ISSUE TITLE
response.apparent encoding throws error after using iter_lines

### ISSUE THREAD

**Issue by eka** [kennethreitz/requests#4005]
When using iter_lines with stream=True, and later trying to get the response.apparent_encoding, I get an exception as follows:

`RuntimeError: The content for this response was already consumed`

So my question is: Is this the proper behavior? I mean, shouldn't I be able to get the apparent_encoding even after consuming the content using stream=True? 
I was thinking on running the chardet on the buffer result of consuming the iteration but I'm thinking that this beats the purpose since the result is already encoded.

Am I missing something?

Thanks.

**Comment by Lukasa** [comment]
Thanks for opening this issue!

> Is this the proper behavior?

Yes. :smile:

> I mean, shouldn't I be able to get the apparent_encoding even after consuming the content using stream=True?

No. :smile: When you set `stream=True`, you are telling Requests that you *do not* want us to buffer the content for any reason. That means we do not store it, which means we cannot hand it off to chardet to process. `apparent_encoding` cannot be used in conjunction with `stream=True`. If you are going to consume all the content into a single buffer, you can just safely use `stream=False`.

**Comment by estebanfeldman** [comment]
Thanks for your answer. Thought would be that.
