### ISSUE TITLE
Install fails 2.14.x

### ISSUE THREAD

**Issue by rhtyd** [kennethreitz/requests#4011]
The pypi page is not loading as well:
https://pypi.python.org/pypi/requests/2.14.1

Logs:
07:58:51 Processing requests-2.14.1.tar.gz
07:58:51 Writing /tmp/easy_install-WACg1D/requests-2.14.1/setup.cfg
07:58:51 Running requests-2.14.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-WACg1D/requests-2.14.1/egg-dist-tmp-MeAs3M
07:58:51 
07:58:51 stderr: no previously-included directories found matching 'docs/_build'
07:58:51 warning: no previously-included files matching '*.py[cdo]' found anywhere in distribution
07:58:51 warning: no previously-included files matching '__pycache__' found anywhere in distribution
07:58:51 warning: no previously-included files matching '*.so' found anywhere in distribution
07:58:51 warning: no previously-included files matching '*.pyd' found anywhere in distribution
07:58:51 zip_safe flag not set; analyzing archive contents...
07:58:51 error: Setup script exited with error in requests setup command: Invalid environment marker: sys_platform == "win32" and python_version<"3.3"

**Comment by Lukasa** [comment]
Thanks, I think this is an issue with your system. What OS are you running, and can you print out the version of pip you have installed please? This is almost certainly related to #4006.

**Comment by yadvr** [comment]
@Lukasa I just checked our Jenkins/Ansible setup, we're running `easy_install cloudmonkey` that depends on requests: https://github.com/apache/cloudstack-cloudmonkey/blob/5.3.3/setup.py#L36
The OS is CentOS7.1.

The pypi page used to render correctly for old versions: 
https://pypi.python.org/pypi/requests/2.13.0

But not for the latest:
https://pypi.python.org/pypi/requests/2.14.1

This looks like broke it for me: https://github.com/kennethreitz/requests/commit/800a074b5d7adbbcaf96a5e6b3754c560f6768ff

**Comment by Lukasa** [comment]
Requests does not support being installed via `easy_install`. Have you tried running `pip install cloudmonkey`?

**Comment by yadvr** [comment]
@Lukasa okay will amend changes, looks like the failure happens when `sys_platform` is not defined,  pip install --upgrade distribute may fix it.

**Comment by yadvr** [comment]
Thanks @Lukasa for your support, using pip fixed the issue for me. Though bear in mind, our scripts used to work well with requests `1.13.0`, so something has changed.
I'll close the ticket now.

**Comment by Lukasa** [comment]
See the discussion in #4006 for an idea of what has changed.
