### ISSUE TITLE
Cookies not passed to redirect

### ISSUE THREAD

**Issue by stuz5000** [kennethreitz/requests#4017]
If I: 
  `requests.post(LOGIN_URL, data=DATA, headers=HEADERS)`

and the initial response is a redirect with with new cookies in the response, it seems the cookies are passed to the redirected request and the above may receive no cookies. :-(

If I do
  `requests.post(LOGIN_URL, data=DATA, headers=HEADERS, allow_redirects=False)`
then I do get back cookies, but then have to extract the cookie, and add them to a new request for the redirected URL.

If the redirect is to the same domain, it would be helpful to have the returned cookies passed to the second request where `allow_redirects=True`, emulating a browser's treatment of cookies.

**Comment by Lukasa** [comment]
Sorry, I need some more information. Requests absolutely *does* persist cookies like a browser does. Where are your cookies coming from? Are you setting them in the headers, or is the server setting them?

**Comment by allComputableThings** [comment]
This is the behavior for 2.14.2

Without redirects:
```
   r = requests.post(LOGIN_URL, data=DATA, headers=HEADERS, allow_redirects=False)
   r.cookies  # is not empty
```

With redirects:
```
   r = requests.post(LOGIN_URL, data=DATA, headers=HEADERS, allow_redirects=False)
   r.cookies  # is empty
```

HEADERS doesn't have any cookies (or any fields that are reserved by http).
I didn't supply the cookies, they are returned from the request.

I think the sequence of events is as follows:

- Request: post LOGIN_URL (with form data, and boring headers, no cookies)
  Response: 
     has a set-cookie
     Is a 302 with location='/'
  
- Request: get with path='/' (and same domain), supply cookie
  Reponse: 200, but no set-cookie is returned from this final response.

Only the final response requests.post is returned -- this doesn't have any cookies from the login response as I'd hoped.

Looking at the implementation of  requests.post I see I can get what I want with:
```
with sessions.Session() as session:
    r = session.request(url=LOGIN_URL,
                        method="post",
                        data=LOGIN_FORMDATA,
                        headers=LOGIN_HEADERS)
  return r, session.cookies
```

I'd would be nice to be able to collect the final response and the collected session cookies in a single command. However, thinking about it, it probably wouldn't help the request API -- is probably better to use the session object to do what I want.
