### ISSUE TITLE
requests.exceptions.SSLError.__str__ returns non-string type

### ISSUE THREAD

**Issue by dev-dull** [kennethreitz/requests#4018]
requests 2.4.3
python 2.7.9
os: Debian Jesse

I looked through the release notes from 2.4.3 to present and didn't see this one as fixed.

Issue:
requests.exceptions.SSLError is raised, but when the error is printed or cast to string, another error is thrown stating that __str__ returned a non-string.

Just to restate: the non-string value is the issue here. I'm not yet sure how to reproduce as we were doing some wacky things. If I'm successful in reproducing this, I'll follow-up with steps.

I was using python/requests to troubleshoot a 'connection reset by peer' error at work and we made the following manipulations:
- changed `/etc/hosts` to point a domain at a test IP.
- added a 'Host' header that referred back at that domain.
- hit an HTTPS/SSL URL on that domain
-- because of previous changes, the cert and domain likely mismatch
-- This URL does a 302 redirect (it's a redirect service)
- requests.exceptions.SSLError is raised and caught as expected
- printing the error and casting the error as `str()` raises an error about __str__ returning a non-string.
- iirc, this issue still existed when I set `verify=False`

**Comment by Lukasa** [comment]
Before reporting this issue to us, can you please report to the Debian maintainers? We are no longer providing support for 2.4.3, so unless it can be reproduced on the current release we're not really able to do much for you. However, the Debian maintainers from whom you installed the package *are* supporting that version of the software, so contacting them is more likely to be useful for you.

I should note, per the [Debian bug reporting notes](https://www.debian.org/Bugs/Reporting), that you should refrain from reporting bugs to the upstream maintainers:

> **Don't file bugs upstream**
>
> If you file a bug in Debian, don't send a copy to the upstream software maintainers yourself, as it is possible that the bug exists only in Debian. If necessary, the maintainer of the package will forward the bug upstream.

Thanks for reaching out!
