### ISSUE TITLE
pypi tarballs are missing tests directory

### ISSUE THREAD

**Issue by floppym** [kennethreitz/requests#4024]
The tests are missing from the pypi tarballs for at least a few releases.

Oddly, when I run `python setup.py sdist` from a git checkout, the resulting tarball does have the tests; I'm not sure how that is working.

**Comment by Lukasa** [comment]
Which releases are affected?

**Comment by nateprewitt** [comment]
@Lukasa, I believe this is related to moving the tests into their own directory starting in 2.10.

#4015 probably should have been to change test_requests.py to 'tests' in MANIFEST.in rather than removing the bad filename.

**Comment by floppym** [comment]
I checked the tarballs for the following releases, they are all missing the tests directory.

2.11.1
2.12.3
2.13.0
2.14.2

**Comment by Lukasa** [comment]
That sounds right @nateprewitt. Want to fix that up with a PR?

**Comment by nateprewitt** [comment]
Yep, I'll throw the PR up when I get back to a computer, unless you have any interest @floppym.

**Comment by floppym** [comment]
> Oddly, when I run python setup.py sdist from a git checkout, the resulting tarball does have the tests; I'm not sure how that is working.

This was working for me because I had the `hgdistver` python package installed. This installs a setuptools plugin that auto-detects any files under version control.
