### ISSUE TITLE
POST header Content-Length with negative value

### ISSUE THREAD

**Issue by msvicky1206** [kennethreitz/requests#4034]
Im new to requests and to http methods.
Im trying to test an server accepting http calls. As part of validation, Im trying to set negative value to 'Content-Length' header and expect 400 'Bad request' but requests.post() returns 200.
I also observed that in POST request headers, content-length is modified to actual value as per the file data being uploaded.

```python
In [75]: headers={'Date': 'Wed, 17 May 2017 08:45:39 GMT', 'Content-Length': '-50'}

In [76]: data = open('/tmp/50').read()

In [77]: out = requests.post(url=url, headers=headers, data=data)

In [78]: out.request.headers
Out[78]: {'Content-Length': '50', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'User-Agent': 'python-requests/2.14.2', 'Connection': 'keep-alive', 'Date': 'Wed, 17 May 2017 08:45:39 GMT'}

In [79]: out.headers
Out[79]: { 'Content-Length': '37', 'Server': '1/1.0/', 'Connection': 'keep-alive',  'Date': 'Wed, 17 May 2017 18:01:08 GMT'}

In [80]: out.status_code
Out[80]: 201
```
Am i missing something here?
I have tested the same with curl, which responds back with 400 response code.

**Comment by Lukasa** [comment]
Requests is not intended as a HTTP testing tool: in particular, it is not intended to allow you to craft malformed HTTP requests. If that's what you're looking for you'll need to find a different tool for that.
