### ISSUE TITLE
Trouble with a specific request

### ISSUE THREAD

**Issue by BobLamarley** [kennethreitz/requests#4053]
Hi,
I have a trouble with my python code.
When i do this cUrl, it work : 
`curl -i -XPOST 'http://51.255.80.74:8086/write?db=testdb' --data-binary 'lps0,host=serverlama,region=us-west value=0.65'`
My value is added in to my database.
I want to do the same in python with this script:

````
import requests
import xml.etree.ElementTree as ET

###
interestingData = ['lps0','wuc0']

###INFLUXDB INFOS
databaseName = 'testdb'
urlPostData = 'http://51.255.80.74:8086/write?db='+databaseName

urlGetData = 'http://192.168.168.110/admin/status.xml'
source = requests.get(urlGetData, stream=True)

tree = ET.parse(source.raw)
root = tree.getroot()

for child in root:
        if child.tag in interestingData:
                data = ''+child.tag+',host=serverlama,region=us-west value='+child.text
                response = requests.post(urlPostData, data=data, headers={'Content-Type': 'application/octet-stream'})
````

But i got this error :

````
Traceback (most recent call last):


 File "script3.py", line 27, in <module>
    response = requests.post(urlPostData, data=data, headers={'Content-Type': 'application/octet-stream'})
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 94, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 49, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 457, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 569, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 407, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error(111, 'Connection refused'))
````

My code seems good to me, i tried a lot of solutions but none works :(
If anyone has an idea, it would be great

**Comment by kennethreitz** [comment]
Let's get discorse setup, for questions like this.

**Comment by Lukasa** [comment]
Your GET is failing. Why are you trying that GET?

**Comment by BobLamarley** [comment]
My get is working, and i make that get for dowload the xml content of the page.
The problem is on the requests.post().

**Comment by Lukasa** [comment]
So all I can tell you then is that the server is refusing our connection attempt.

**Comment by BobLamarley** [comment]
Yes but i had already this information :)
My server doesn't refuse the connection attempt when i make a cUrl, why the connection would be refused with a request in python ?

**Comment by Lukasa** [comment]
Can we confirm you're not getting redirected? That is, can you set `allow_redirects=False`?

**Comment by BobLamarley** [comment]
I'm so sorry, i was testing my curl on my PC, not in my container. 
Thanks for your help ! :)

**Comment by sigmavirus24** [comment]
> Let's get discorse setup, for questions like this.

Why can't we simply use StackOverflow for that? That's something we don't need to host @kennethreitz

**Comment by kennethreitz** [comment]
@sigmavirus24 discourse will give us a free hosted account. I think it'll give our users the opportunity to talk to eachother and self-serve issues potentially.
