### ISSUE TITLE
Easter Egg

### ISSUE THREAD

**Issue by kennethreitz** [kennethreitz/requests#4054]
I'd like to embed an easter egg within requests — something very simple, perhaps just a single dunder variable that says "Kenneth was here". 

OR! 

```
>>> requests.__cake__
✨ 🍰 ✨
```
yes, i love this. 

Any objections will be heard, and likely ignored, but open to thougts if anyone feels strongly against it.

**Comment by kennethreitz** [comment]
Done!

**Comment by kennethreitz** [comment]
Did on my iPad, trusting CI to report if there are any failures caused by this one-line change. Keeping an eye out, as I don't have a dev environment on me at the moment.

**Comment by kennethreitz** [comment]
@Lukasa sorry! :sparkles: :cake: :sparkles:

**Comment by Lukasa** [comment]
:wink: No worries.
