### ISSUE TITLE
move setup.py to use a __version__.py

### ISSUE THREAD

**Issue by kennethreitz** [kennethreitz/requests#4057]
better pattern. death to regex.

**Comment by sethmlarson** [comment]
Would be nice to keep `__version__` exposed at the package level so that `requests.__version__` is still a thing.

**Comment by kennethreitz** [comment]
Absolutely!

**Comment by sethmlarson** [comment]
Only reason I note that is because I know that `pipenv` does not expose `.__version__` at the package level instead opting for `pipenv.__version__.__version__`.

**Comment by kennethreitz** [comment]
@SethMichaelLarson can you open an issue about that?

**Comment by kennethreitz** [comment]
Addressed in #4059
