### ISSUE TITLE
"params" arg of requests.get does not properly encode json

### ISSUE THREAD

**Issue by mxndrwgrdnr** [kennethreitz/requests#4060]
I have an API endpoint that handles json. This request returns a 400 error 
```
requests.get(url, params={"json":json.dumps(myDict)}
``` 
while this works fine 
```
requests.post(url,json=myDict)
```
Is there no proper way to pass json in a GET request?

**Comment by Lukasa** [comment]
This is entirely up to your API endpoint. If the endpoint doesn't want JSON in the request URL, then it will error out: if it does, then it won't. You need to read your endpoint documentation or observe other requests to see how they send the data.

**Comment by mxndrwgrdnr** [comment]
No, the API can handle JSON in the request URL. It's just that when I pass json as a value a-la `params={key:value}` in the GET request, the json gets formatted improperly. The url it returns places a `+` character after every `:` in the json.

**Comment by Lukasa** [comment]
That's not improper, that's the result of `json.dumps`:

```python
>>> json.dumps({'test': 'name'})
'{"test": "name"}'
```

If that's not the way you want your data to look, you need to change the data. We're going to send exactly what you ask us to. :smile:

**Comment by mxndrwgrdnr** [comment]
Ah, yes! So I guess by specifying `separators=(',' , ':')` the json.dumps() call I can get rid of the `+`'s. Thanks!
