### ISSUE TITLE
readthedocs is broken

### ISSUE THREAD

**Issue by kennethreitz** [kennethreitz/requests#4061]
ugh https://readthedocs.org/projects/requests/builds/5472443/

**Comment by kennethreitz** [comment]
very unclear what's going on from the error message. @ericholscher?

**Comment by ericholscher** [comment]
Does it happen locally?

**Comment by ericholscher** [comment]
I seem to have it reproducing locally, so I'm guessing it's a bug in something recent on your side.

**Comment by ericholscher** [comment]
Locally I see your config version being set as `ipdb> version
<module 'requests.__version__' from '/Users/eric/checkouts/requests/requests/__version__.pyc'>` which seems...wrong :)

**Comment by nateprewitt** [comment]
Looks like this is a byproduct of #4059. Something is getting confused about requests.__version__ the module vs requests.__version__ the attr. The import statement in init may need to be more explicit, or the module name needs to change.

**Comment by kennethreitz** [comment]
gah, sorry @ericholscher. I should have checked that before pinging you!
