### ISSUE TITLE
Idea: Response.next() method, for when allow_redirects=False

### ISSUE THREAD

**Issue by kennethreitz** [kennethreitz/requests#4065]

**Comment by sigmavirus24** [comment]
I really don't like this. Responses will only keep a connection when you're streaming and that's it. If you're planning on attaching a session, that seems really ill-considered.

**Comment by kennethreitz** [comment]
I really need to figure out why all my Requests notifications are going to spam

**Comment by ueg1990** [comment]
its possible you once put a previous request notification to spam and your email service may have assumed all subsequent requests notifications to spam
