### ISSUE TITLE
Error on importing Session object

### ISSUE THREAD

**Issue by MahdiZareie** [kennethreitz/requests#4070]
Hi guys
I'm using requests (2.16.0) and I'm seeing an error which wasn't here before : 

```
Python 3.5.2 (default, Jul 17 2016, 00:00:00) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import urllib3
>>> urllib3.__version__
'1.16'
>>> from requests import Session
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jenkins/env/lib/python3.5/site-packages/requests/__init__.py", line 49, in <module>
    major, minor, patch = urllib3.__version__.split('.')[:3]
ValueError: not enough values to unpack (expected 3, got 2)
>>> 
```

**Comment by Lukasa** [comment]
Yup, this looks like another error introduced by #4067, which appears to assume urllib3 uses three part version numbers (it does not always do that). You can resolve this by typing `pip install -U urllib3`, though that may break something else in your environment. 

Please watch #4069, as we may well revert the change in 2.16.

**Comment by Lukasa** [comment]
Incidentally @kennethreitz, this is why I didnt want to do this before pip gets a dependency solver: a whole bunch of people who could use Requests before now cannot.

**Comment by kennethreitz** [comment]
this should now be fixed to provide a proper error on the master branch
