### ISSUE TITLE
test

### ISSUE THREAD

**Issue by kennethreitz** [kennethreitz/requests#4080]
Summary.

## Expected Result

What you expected.

## Actual Result

What happened instead.

## Reproduction Steps

```python
import requests

```

### System Information

    $ python -m requests.help

```
{
  "chardet": "3.0.3",
  "cryptography": {
    "version": ""
  },
  "implementation": {
    "name": "CPython",
    "version": "3.6.0"
  },
  "platform": {
    "release": "16.6.0",
    "system": "Darwin"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.16.4"
  },
  "system_ssl": {
    "version": "100020bf"
  },
  "urllib3": "1.21.1",
  "using_pyopenssl": false
}
```

This command is only available on Requests v2.16.4 and greater. Otherwise,
please provide some basic information about your system (Python version,
operating system, &c).

**Comment by sethmlarson** [comment]
Any reason for the inconsistency with the `urllib3` and `chardet` keys not having `version` sub-keys?

**Comment by nateprewitt** [comment]
@SethMichaelLarson looks like those two were added after the other original definitions. Perhaps `urllib3_info = {'version': urllib3.__version__}` [here](https://github.com/kennethreitz/requests/blob/7ce5ca853db84601fe61209428085bac2b79309b/requests/help.py#L72-L73) would be more consistent, @kennethreitz?

**Comment by sethmlarson** [comment]
Also noticed we're not saying anything about OS information/version here? Might be worthwhile.

**Comment by nateprewitt** [comment]
@SethMichaelLarson I believe that's what the `platform` key is representing. I'm not sure if there's more specific information we can get out of the `platform` package. I haven't looked too hard though.

**Comment by sethmlarson** [comment]
@nateprewitt Disregard me, just didn't see that field.

**Comment by kennethreitz** [comment]
ah, good catch

**Comment by kennethreitz** [comment]
updated :)
