### ISSUE TITLE
The conflict between proxies and TLSv1.2

### ISSUE THREAD

**Issue by ytig** [kennethreitz/requests#4680]
I want to use the HTTPS proxy, the first request is success, but all subsequent requests failed.
the crash log is:

> HTTPSConnectionPool(host='***', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_read_bytes', 'sslv3 alert unexpected message')],)",),))

I used Wireshark to view the raw packets, the first request all packets protocol is TLSv1.2, the subsequent requests failed at **Client Hello** which protocol is TLSv1. (When i using other language never appear TLSv1)
And i aslo set ssl_version to be ssl.PROTOCOL_TLSv1_2 with requests.adapters, but it doesn't work.

 Finally i check up urllib.

> request = urllib.request.Request(url)
    request.set_proxy('host:port', 'https')
    context = ssl.SSLContext(ssl.PROTOCOL_TLSv1_2)
    response = urllib.request.urlopen(request, context=context)
    response.read().decode('utf-8')

when i using TLSv1.2 the crash log is:

> <urlopen error [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:777)>

when i using TLSv1 the crash log is: (not every subsequent requests crash)

> <urlopen error [SSL: SSLV3_ALERT_UNEXPECTED_MESSAGE] sslv3 alert unexpected message (_ssl.c:777)>

Version list:

- python: 3.6.3
- requests: 2.18.4
- openssl: stable 1.0.2o

**Comment by lmiguelvargasf** [comment]
Closed due to inactivity.
