### ISSUE TITLE
Make a seperate repo for requests3.

### ISSUE THREAD

**Issue by kenneth-reitz** [kennethreitz/requests#4877]

**Comment by sigmavirus24** [comment]
Why?

**Comment by kinow** [comment]
Indeed, why? I thought it would be easier to keep things in a single place (at least from a user PoV).

**Comment by hugovk** [comment]
Is it https://github.com/kennethreitz/requests3?

**Comment by kennethreitz** [comment]
it is indeed! It's a different namespace, and a different package.

**Comment by kennethreitz** [comment]
https://github.com/kennethreitz/requests3

**Comment by Russell-Jones-OxPhys** [comment]
It would be better to create requests2, should someone need that, and drop python 2 support. Things that depend on the name requests can pin to an old version.
