### ISSUE TITLE
QUESTION: How does content length of chunked encoded data is decided?

### ISSUE THREAD

**Issue by mzfr** [kennethreitz/requests#4977]
I am trying to use [treq](https://github.com/twisted/treq/) for downloading a file from https://speed.hetzner.de/100MB.bin (this link is just for testing). Now if I use requests to send a get the file like

```python
import requests
url = 'https://speed.hetzner.de/100MB.bin'
r = requests.get(url)
```

I get the content and checking the headers
```python
>>> r.headers
{'Server': 'nginx', 'Date': 'Mon, 11 Feb 2019 13:51:08 GMT', 'Content-Type': 'application/octet-stream', 'Content-Length': '104857600', 'Last-Modified': 'Tue, 08 Oct 2013 11:48:13 GMT', 'Connection': 'keep-alive', 'ETag': '"5253f0fd-6400000"', 'Strict-Transport-Security': 'max-age=15768000; includeSubDomains', 'Accept-Ranges': 'bytes'}
```
We can see the content length i.e 104857600 but If I do the same thing with treq and then try to find the response `Content-Length` then it returns `unknow size`. 

I have talked on treq mailing list and they told me
```
Do you have Chunked encoding
https://en.wikipedia.org/wiki/Chunked_transfer_encoding
In this case, the content length is not advertised in the response headers.
```
So I just wanted to know how does `requests` shows the content length? Is there any special function in requests that finds out the content length of such kind of files?

Thanks

**Comment by sigmavirus24** [comment]
We don't. You seem to be encountering a different path on the server than `treq` for unknown reasons. If the server sent back headers we present them, otherwise we do not magically replace or misrepresent what the server sent.

**Comment by mzfr** [comment]
@sigmavirus24 I apologize if it a dumb question but I tried requests with the following URL: https://heyguys.cc/ and I got the `content-length: 1615` but I don't see any content-length header when I am seeing the request in the raw headers of Firefox developer tool. Do you mind telling me why that could be?

**Comment by sigmavirus24** [comment]
Please use [StackOverflow](https://stackoverflow.com) for general usage questions instead and only report defects here.
