### ISSUE TITLE
Requests returns 200 for a url that is invalid

### ISSUE THREAD

**Issue by ReddyKilowatt** [kennethreitz/requests#4982]
Summary.

## Expected Result
requests should return 404 for an invalid url

What you expected.
status_code should be 404

## Actual Result
status_code was 200

What happened instead.
status_code was 200

## Reproduction Steps

```python
import requests
# this is a VALID url
req = requests.get("https://talkpython.fm/episodes/transcript/96/exploring-awesome-python")
print(req.status_code)
```
200 is displayed

```python
import requests

# this is a BAD url
req = requests.get("https://talkpython.fm/episodes/transcript/this_ur_is_just-WRONG")
print(req.status_code)
```
200 is displayed SHOULD display 404

## System Information
Windows 7, Pro 64-Bit
conda 4.6.2

    $ python -m requests.help

```
(py36sci) C:\>python -m requests.help
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": "2.5"
  },
  "idna": {
    "version": "2.8"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.6.6"
  },
  "platform": {
    "release": "7",
    "system": "Windows"
  },
  "pyOpenSSL": {
    "openssl_version": "1010101f",
    "version": "19.0.0"
  },
  "requests": {
    "version": "2.21.0"
  },
  "system_ssl": {
    "version": "100020ff"
  },
  "urllib3": {
    "version": "1.24.1"
  },
  "using_pyopenssl": true
}
```

This command is only available on Requests v2.16.4 and greater. Otherwise,
please provide some basic information about your system (Python version,
operating system, &c).

(py36sci) C:\>python
Python 3.6.6 | packaged by conda-forge | (default, Jul 26 2018, 11:48:23) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.

**Comment by rHuggler** [comment]
Hi @ReddyKilowatt,

I'm not able to reproduce this bug:  
```
$ try requests==2.21.0
==> Use python python3.6
[*] Downloading packages: requests==2.21.0
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> valid_request = requests.get("https://talkpython.fm/episodes/transcript/96/exploring-awesome-python")
>>> print(valid_request.status_code)
200
>>> invalid_request = requests.get("https://talkpython.fm/episodes/transcript/this_ur_is_just-WRONG")
>>> print(invalid_request.status_code)
404
```

Can you double check it please? Thanks!

**Comment by ReddyKilowatt** [comment]
I've talked to the site maintainer and he confirmed it was a server issue and quickly fixed it.
I'm now seeing the expected 404 value.
