### ISSUE TITLE
How to avoid SSRF when you use requests to parse untrusted URLs?

### ISSUE THREAD

**Issue by marataziat** [kennethreitz/requests#5005]
For an example I have a Flask app, it gets 'url' parameter from GET request. Then it do something like this:
```
requests.get(params['url']).text
```
So how to avoid localhost requests? Should I make a new network interface, which can access only external network and then send requests? I tried to search some answers for that and I found only https://github.com/JordanMilne/Advocate/ but the autor says that we shouldn't use it in production. So how to properly secure from SSRF in case like this? Can requests do requests through specified virtual network interfaces?

**Comment by sethmlarson** [comment]
I'd say this isn't within the realm of requests responsibility. This is an input sanitization issue not an HTTP issue. My recommendation would be parsing the URL and maintaining an "allow list" of hosts and URL constructions that are acceptable to make requests to (scheme, w/o userinfo, etc).

**Comment by ghost** [comment]
I have found a better way: https://stackoverflow.com/questions/691045/how-do-you-determine-if-an-ip-address-is-private-in-python you can just check if IP is blacklisted by this or not. Idk how secure it is but I think it's better than nothing.

**Comment by ghost** [comment]
```
>>> ip = '169.254.169.254'
>>> ipaddress.ip_address(ip).is_global
False
>>>
```
Lol, it's just a default python3 module and it can secure you even against aws metadata ip!! How can I make a module which will "proxy" the default requests module and add url ssrf protection?
