### ISSUE TITLE
Status_Code in Session

### ISSUE THREAD

**Issue by prrvchr** [kennethreitz/requests#5010]
Hi,
it would be really nice to have access to the status code from the Session, such as:

```python
with session.get(url, params=params, timeout=g_timeout) as  r:
    if r.status_code == session.codes.ok: 
        return r.json()
```

Thank you.

**Comment by timofurrer** [comment]
What would be the benefit for you of having those accessible from a `requests.Session` over using the look ups from `requests.codes` ?

**Comment by prrvchr** [comment]
I use Requests under UNO (OpenOffice / LibreOffice), and I provide it with extension  [OAuth2OOo](https://github.com/prrvchr/OAuth2OOo/blob/master/README.md)  to allow OpenOffice which only supports python 2.X for now, to work.

The other extensions that require OAuth2 and Requests use only Session with the import of Request in the function providing the Session. Because UNO use lazy loading, I can only use dynamic import, the Requests module being provided by the extension OAuth2OOo is only available after the extension is loaded.

If the status_code are in Session then I do not need anything else ...(All in one)
In thinking where to put it, that I thought Session was the best.
Besides, I already allowed myself to patch, it's only a line:

`self.codes = codes`

Thank

**Comment by prrvchr** [comment]
Hi,
I confessed I was a little misguided, the good solution is to use Python dynamic typing and assign the status_code to an attribute of my Session variable, but certainly not to modify the source code of Requests ... Forgive me.
I close this issue
