### ISSUE TITLE
Post request not sending with big "data" parameter

### ISSUE THREAD

**Issue by nathan30** [kennethreitz/requests#5029]
Hi,

I'm sending some data formated like this : 

```python
data = {
            'encodedFile'   : base64.b64encode(fileContent),
            'priority'      : Config.cfg['OCForMaarch']['priority'],
            'status'        : Config.cfg['OCForMaarch']['status'],
            'type_id'       : Config.cfg['OCForMaarch']['type_id'],
            'format'        : Config.cfg['OCForMaarch']['format'],
            'category_id'   : Config.cfg['OCForMaarch']['category_id'],
            'subject'       : subject,
            'destination'   : destination,
            'address_id'    : contact['id'],
            'exp_contact_id': contact['contact_id'],
            'doc_date'      : date
}

res = requests.post(self.baseUrl + 'resources', auth=self.auth, data=data)`
```

My encoded file is a 12 pages PDF, pretty heavy. The problem is, the data isn't send at all. When I print what the API server receive, nothing of that array appear. If my 'encodedFile' is something like 'dGVzdA==', the API server receive all the informations.

Is there a limitation I had to check ?

Thanks in davance

**Comment by timofurrer** [comment]
> When I print what the API server receive, nothing of that array appear. If my 'encodedFile' is something like 'dGVzdA==', the API server receive all the informations.

What exactly is received on the API server endpoint when sending the entire file? Just no `body` ? Or no request at all?

> Is there a limitation I had to check ?

I'm not aware of any limitation requests has. However, you might want to check your API server: is it running behind nginx with a limit?

**Comment by nathan30** [comment]
> > When I print what the API server receive, nothing of that array appear. If my 'encodedFile' is something like 'dGVzdA==', the API server receive all the informations.
> 
> What exactly is received on the API server endpoint when sending the entire file? Just no `body` ? Or no request at all?
> 
> > Is there a limitation I had to check ?
> 
> I'm not aware of any limitation requests has. However, you might want to check your API server: is it running behind nginx with a limit?

The API received all the informations about auth etc.. But all the data were not sent. But finally I found the problem : 
The post_max_size parameters on my Apache2 php.ini. So closed the thread :) Thanks for your reply btw
