### ISSUE TITLE
Cannot find reference 'cookies' in '__init__.py'

### ISSUE THREAD

**Issue by hsowan** [kennethreitz/requests#5046]
When I use `jar = requests.cookies.RequestsCookieJar()` in PyCharm, it shows warning `Cannot find reference 'cookies' in '__init__.py'`

**Comment by tonybaloney** [comment]
Please check that PyCharm is using the same virtual environment that has `requests` installed. The bottom bar will tell you, or the interpreters/environments window.

**Comment by hsowan** [comment]
I use mac os but there is no problem while running

![image](https://user-images.githubusercontent.com/26451706/55718984-a3d32f80-5a2f-11e9-965d-d472b3f2b110.png)

**Comment by PrimordialHelios** [comment]
Could it perhaps be related to [this](https://stackoverflow.com/questions/23248017/cannot-find-reference-xxx-in-init-py-python-pycharm)? If so, it's a PyCharm bug.

**Comment by kobayashi** [comment]
This looks like pycharm isseue.
