### ISSUE TITLE
why isn't Requests included natively with python?

### ISSUE THREAD

**Issue by 4evermaat** [kennethreitz/requests#5057]
I was curious with all of the heavy usage of `Requests` module, why isn't it just included as a standard python module?  Why does the user have to install it?

What does python expect the user to use instead?

**Comment by gnahckire** [comment]
[urllib.request](https://docs.python.org/3/library/urllib.request.html#module-urllib.request) is in the stdlib. 

While you *can* use that instead of `requests`, many prefer `requests` interfaces to `urllib`.

**Comment by ghost** [comment]
Kenneth's original reasoning for this is "The stdlib is where things go to die". However, he did propose adding it to the stdlib [here](https://github.com/kennethreitz/requests/issues/2424)

**Comment by 4evermaat** [comment]
> [urllib.request](https://docs.python.org/3/library/urllib.request.html#module-urllib.request) is in the stdlib.
> 
> While you _can_ use that instead of `requests`, many prefer `requests` interfaces to `urllib`.

> Kenneth's original reasoning for this is "The stdlib is where things go to die". However, he did propose adding it to the stdlib [here](https://github.com/kennethreitz/requests/issues/2424)

Ok.  I understand more completely now.  And it does make sense now.  I didn't realize there was so much politics in getting a module included in the `stdlib` and the potential loss of control over updates/features.
