### ISSUE TITLE
How can I use other protocol?

### ISSUE THREAD

**Issue by ka1n4t** [kennethreitz/requests#5060]
How can I use other protocol, such as gopher, dict, file....

**Comment by ghost** [comment]
Since requests is an HTTP library, I don't believe it would be possible to use it with gopher. You might have better luck with [Pituophis](https://github.com/dotcomboom/Pituophis)

**Comment by ka1n4t** [comment]
> 
> 
> Since requests is an HTTP library, I don't believe it would be possible to use it with gopher. You might have better luck with [Pituophis](https://github.com/dotcomboom/Pituophis)

thanks, I'll try
