### ISSUE TITLE
http://python-requests.org is down 

### ISSUE THREAD

**Issue by 0xYasser** [kennethreitz/requests#5079]
Summary.
http://python-requests.org/ redirects to https://docs.python-requests.org/ instead of http://docs.python-requests.org/. 
## Expected Result
docs to be available

## Actual Result

Secure Connection Failed

## Reproduction Steps

```
curl https://docs.python-requests.org/

```

## System Information

```
N/A
```

**Comment by kennethreitz** [comment]
Thanks! This should now be fixed :)

**Comment by ashb** [comment]
Something is broken about this again: `http://docs.python-requests.org/en/master/objects.inv` 301s to `href="https://2.python-requests.org//en/master/objects.inv`, but `2.python-requests.org` is returning a TLS error.

```
http: error: SSLError: HTTPSConnectionPool(host='2.python-requests.org', port=443): Max retries exceeded with url: /en/master/objects.inv (Caused by SSLError(SSLError(1, '[SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1056)'))) while doing GET request to URL: https://2.python-requests.org/en/master/objects.inv
```
