### ISSUE TITLE
请求起点中文网获取的书籍信息不全

### ISSUE THREAD

**Issue by 2293310198** [kennethreitz/requests#5083]
例如https://book.qidian.com/info/1115277
直接浏览器Ctrl+U查看源码内容是          </div>
                
            </div>
            
        </div>
        
        <div class="book-content-wrap cf">
            
            <div class="left-wrap fl">
                <div class="book-info-detail">
                    <cite class="icon-pin"></cite>
                    <div class="book-intro">
                        <p>
                            
                                　　唐门外门弟子唐三，因偷学内门绝学为唐门所不容，跳崖明志时却发现没有死，反而以另外一个身份来到了另一个世界，一个属于武魂的世界，名叫斗罗大陆。这里没有魔法，没有斗气，没有武术，却有神奇的武魂。这里的每个人，在自己六岁的时候，都会在武魂殿中令武魂觉醒。武魂有动物，有植物，有器物，武魂可以辅助人们的日常生活。而其中一些特别出色的武魂却可以用来修炼并进行战斗，这个职业，是斗罗大陆上最为强大也是最荣耀的职业——魂师!<br>　　当唐门暗器来到斗罗大陆，当唐三武魂觉醒，他能否在这片武魂的世界再铸唐门的辉煌？他能否成为这个世界的主宰：神?
                            
                        </p>
                    </div>
                    <div class="book-state" data-l1="4">
                        <ul>
                            
                            
                            <li>
                                <b>作者自定义标签</b>
                                <div class="detail">
                                    <p class="tag-wrap" data-l1="4">
                                        
                                        
                                        <a class="tags" href="//www.qidian.com/all?tag=热血" target="_blank" data-eid="qd_G70">热血</a>
                                        
                                        
                                    </p>
                                </div>
                            </li>
                            
                            
                                
                                <li class="honor" id="honor">
                                    <b>荣誉动态</b>
                                    <div class="detail">
                                    <strong>2014-09-19 累积获得五十万个收藏<em class="iconfont">&#xe623;</em></strong>
    但是requests的请求返回数据是首发时间：2009-12-12 07:00:00 章节字数                        <li data-rid="596"><a href="//vipreader.qidian.com/chapter/1115277/26041662" target="_blank" data-eid="qd_G55" data-cid="//vipreader.qidian.com/chapter/1115277/26041662" title="首发时间：2009-12-13 07:42:37 章节字数                                　　唐门外门弟子唐三，因偷学内门绝学为唐门所不容，跳崖明志时却发现没有死，反而以另外一个身份来到了另一个世界，一个属于武魂的世界，名叫斗罗大陆。这里没有魔法，没有斗气，没有武 术，却有神奇的武魂。这里的每个人，在自己六岁的时候，都会在武魂殿中令武魂觉醒。武魂有动物，有植物，有器物，武魂可以辅助人们的日常生活。而其中一些特别出色的武魂却可以用来修炼并进行战斗，这个 职业，是斗罗大陆上最为强大也是最荣耀的职业——魂师!<br>　　当唐门暗器来到斗罗大陆，当                                        <a class="tags" href="//www.qidian.com/all?tag=热血" target="_blank" data-eid="q                                        <a class="blue collect" href="//book.qidian.com/honor/1115277" target="_blank" d                                            <a class="blue" href="//vipreader.qidian.com/chapter/1115277/26041662" data-eid="qd_G19" data-cid="//vipreader.qidian.com/chapter/1115277/2604
获取的信息是不完全的

**Comment by Thrimbda** [comment]
requests cannot perform followed ajax requests for you.
Please confirm the website you are requesting's loading method.

for example
```bash
curl https://book.qidian.com/info/1115277

# python repl
>>> import requests
>>> print(requests.get('https://book.qidian.com/info/1115277').text)
```
if these two responses are different, then it might be some issue about requests itself.

**Comment by xcjson** [comment]
我试了curl https://book.qidian.com/info/1115277
获取到的也不全，但是view-source:https://book.qidian.com/info/1115277看到的源代码是完整的
这里不支持ajax异步请求啊

**Comment by xcjson** [comment]
使用BeautifulSoup获取这个区块的数据
soup = BeautifulSoup(r.text, "lxml")
soup.find("div",class_="book-intro").p
获取的值是                                　　唐门外门弟子唐三，因偷学内门绝学为唐门所不容，跳崖明志时却发现没有死，反而以另外一个身份来到了另一个世界，一个属于武魂的世界，名叫斗罗大陆。这里没有魔法 ，没有斗气，没有武术，却有神奇的武魂。这里的每个人，在自己六岁的时候，都会在武魂殿中令武魂觉醒。武魂有动物，有植物，有器物，武魂可以辅助人们的日常生活。而其中一些特别出色的武魂却可以用来修 炼并进行战斗，这个职业，是斗罗大陆上最为强大也是最荣耀的职业——魂师!<br/>　　当唐门暗器来到斗罗大陆，当                        </p>魂的世界再铸唐门的辉煌？他能否成为这个世界的主宰：神?
虽然相比原文
唐门外门弟子唐三，因偷学内门绝学为唐门所不容，跳崖明志时却发现没有死，反而以另外一个身份来到了另一个世界，一个属于武魂的世界，名叫斗罗大陆。这里没有魔法，没有斗气，没有武术，却有神奇的武魂。这里的每个人，在自己六岁的时候，都会在武魂殿中令武魂觉醒。武魂有动物，有植物，有器物，武魂可以辅助人们的日常生活。而其中一些特别出色的武魂却可以用来修炼并进行战斗，这个职业，是斗罗大陆上最为强大也是最荣耀的职业——魂师!<br>　　当唐门暗器来到斗罗大陆，当唐三武魂觉醒，他能否在这片武魂的世界再铸唐门的辉煌？他能否成为这个世界的主宰：神?
也缺少了一点但是比requests请求的反而全一些
 <li data-rid="595"><a href="//vipreader.qidian.com/chapter/1115277/26030979" target="_blank" data-eid="qd_G55" data-cid="//vipreader.qidian.com/chapter/1115277/26030979" title="首发时间：2009-12-12 07:00:00 章节字数                        <li data-rid="596"><a href="//vipreader.qidian.com/chapter/1115277/26041662" target="_blank" data-eid="qd_G55" data-cid="//vipreader.qidian.com/chapter/1115277/26041662" title="首发时间：2009-12-13 07:42:37 章节字数                                　　唐门外门弟子唐三，因偷学内门绝学为唐门所不容，跳崖明志时却发现没有死，反而以另外一个身份来到了另一个世界，一个属于武魂的世界，名叫斗罗大陆。这里没有魔法，没有斗气，没有武 术，却有神奇的武魂。这里的每个人，在自己六岁的时候，都会在武魂殿中令武魂觉醒。武魂有动物，有植物，有器物，武魂可以辅助人们的日常生活。而其中一些特别出色的武魂却可以用来修炼并进行战斗，这个 职业，是斗罗大陆上最为强大也是最荣耀的职业——魂师!<br>　　当唐门暗器来到斗罗大陆，当                                        <a class="tags" href="//www.qidian.com/all?tag=热血" target="_blank" data-eid="q                                        <a class="blue collect" href="//book.qidian.com/honor/1115277" target="_blank" d                                            <a class="blue" href="//vipreader.qidian.com/chapter/1115277/260416

**Comment by xcjson** [comment]
直接输出很多标签都没有闭合，就算是异步加载，起点也不至于这样把
<em class="rec"></em><a href="//me.qidian.com/friendIndex.aspx?id=216765        
![image](https://user-images.githubusercontent.com/30544914/57505810-6282b800-732c-11e9-88ed-dcac00ec7102.png)

**Comment by yjqiang** [comment]
This should because there are `\r` in content, and then you use `print` to try to see the content. So it's not a bug in requests. <https://blog.csdn.net/lishenluo/article/details/52642997>
example:
```python
print('ppppp\rooo\r')  # In PyCharm, I got "ooo" as result.
```

**Comment by xcjson** [comment]
。。。感谢大佬解答
同样的代码在python自带的IDLE的都正常∑(O_O；)
这是要我以后都用IDLE的节奏啊

**Comment by yjqiang** [comment]
> 。。。感谢大佬解答
> 同样的代码在python自带的IDLE的都正常∑(O_O；)
> 这是要我以后都用IDLE的节奏啊

找到问题点就close这个issue吧。
According to the reply of @2293310198 , he confirmed that it is not a bug in `requests`. And the reason is https://github.com/kennethreitz/requests/issues/5083#issuecomment-491253735 .
