### ISSUE TITLE
update urllib3 raise proxy error

### ISSUE THREAD

**Issue by returnWOW** [kennethreitz/requests#5129]
Summary.

Set requests on proxies, from urllib3(version 1.25.3) raise urllib3.exceptions.LocationParseError: Failed to parse: http://user:pass@xxx.xxx error

What you expected.

From urllib3 1.24.1 proxy set is work fine. urllib3 version 1.25.3 update url.py raise this error.

What happened instead.

```python
import requests

proxies = {
    'http': 'http://user:pass@127.0.0.1:1080',
    'https': 'http://user:pass@127.0.0.1:1080'
}

requests.get("http://www.bing.com", proxies=proxies)
```

## System Information

```
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": "2.7"
  },
  "idna": {
    "version": "2.8"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.7.2"
  },
  "platform": {
    "release": "7",
    "system": "Windows"
  },
  "pyOpenSSL": {
    "openssl_version": "1010103f",
    "version": "19.0.0"
  },
  "requests": {
    "version": "2.22.0"
  },
  "system_ssl": {
    "version": "101000af"
  },
  "urllib3": {
    "version": "1.25.3"
  },
  "using_pyopenssl": true
}
```

Sorry for my bad English. Now I restore urllib3 to 1.24.1.

**Comment by sethmlarson** [comment]
I'm not receiving your error:

```python
from urllib3.util import parse_url

parse_url("http://user:pass@127.0.0.1:1080")
Url(scheme="http", auth="user:pass", host="127.0.0.1", port=1080, path=None, query=None, fragment=None)
```

Is your `user:pass` example different from what you're actually using? For example do you have an `@` character in your username or password? Please post an example that raises the error you're seeing so I can help resolve it.

**Comment by returnWOW** [comment]
yeah,In my username contain @ character. Thanks for your reply.



发送自我的三星盖乐世智能手机。


-------- 原始信息 --------
发件人： Seth Michael Larson <notifications@github.com>
日期: 2019/7/3 23:40 (GMT+08:00)
收件人： kennethreitz/requests <requests@noreply.github.com>
抄送： wowopo <liukaijiang@outlook.com>, Author <author@noreply.github.com>
主题： Re: [kennethreitz/requests] update urllib3 raise proxy error (#5129)


I'm not receiving your error:

from urllib3.util import parse_url

parse_url("http://user:pass@127.0.0.1:1080")
Url(scheme="http", auth="user:pass", host="127.0.0.1", port=1080, path=None, query=None, fragment=None)

Is your user:pass example different from what you're actually using? For example do you have an @ character in your username or password?

―
