### ISSUE TITLE
python-requests.org looks down

### ISSUE THREAD

**Issue by mhow2** [kennethreitz/requests#5138]
I saw #5079 but to me it is still down, even the domain itself doesn't resolve to an IP address.

**Comment by ksze** [comment]
Seems to be back.

**Comment by mhow2** [comment]
Hi ! Thanks.

http://python-requests.org now redirects to https://2.python-requests.org/en/master/ and the content is ok

However notice that https://python-requests.org/ raise an `SSL_ERROR_INTERNAL_ERROR_ALERT` in my firefox browser.

**Comment by mhow2** [comment]
@kennethreitz  : I don't understand why you close the issue as to me there is still an issue with https
Regards

**Comment by isidentical** [comment]
@mhow2 he is just trolling, dont take his actions serious

**Comment by mhow2** [comment]
@isidentical : maybe he is but in the meantime I still have the error above when accessing https://python-requests.org/
